import type { SeedRow } from './types'

/** A1 seed corpus (381 entries = original 180 + frequency-fill extension), roughly frequency-ordered. */
export const A1_ROWS: SeedRow[] = [
  ['der', 'Tag', 'Tage', 'day', 'Time', 'Der Tag ist lang.', 'The day is long.'],
  ['die', 'Zeit', 'Zeiten', 'time', 'Time', 'Ich habe keine Zeit.', 'I have no time.'],
  ['das', 'Jahr', 'Jahre', 'year', 'Time', 'Das Jahr ist schnell vorbei.', 'The year passed quickly.'],
  ['der', 'Mensch', 'Menschen', 'human, person', 'People', 'Jeder Mensch macht Fehler.', 'Every person makes mistakes.'],
  [null, 'sein', null, 'to be', 'Verbs', 'Ich bin müde.', 'I am tired.'],
  [null, 'haben', null, 'to have', 'Verbs', 'Wir haben ein Auto.', 'We have a car.'],
  [null, 'werden', null, 'to become; will', 'Verbs', 'Es wird spät.', 'It is getting late.'],
  [null, 'können', null, 'can, to be able to', 'Verbs', 'Kannst du schwimmen?', 'Can you swim?'],
  [null, 'müssen', null, 'must, to have to', 'Verbs', 'Ich muss arbeiten.', 'I have to work.'],
  [null, 'sagen', null, 'to say', 'Verbs', 'Was sagst du?', 'What are you saying?'],
  [null, 'machen', null, 'to do, to make', 'Verbs', 'Was machst du?', 'What are you doing?'],
  [null, 'geben', null, 'to give', 'Verbs', 'Gib mir das Buch.', 'Give me the book.'],
  [null, 'kommen', null, 'to come', 'Verbs', 'Woher kommst du?', 'Where do you come from?'],
  [null, 'sollen', null, 'should, to be supposed to', 'Verbs', 'Du sollst schlafen.', 'You should sleep.'],
  [null, 'wissen', null, 'to know (a fact)', 'Verbs', 'Ich weiß es nicht.', 'I do not know it.'],
  [null, 'wollen', null, 'to want', 'Verbs', 'Ich will lernen.', 'I want to learn.'],
  [null, 'gehen', null, 'to go, to walk', 'Verbs', 'Wir gehen nach Hause.', 'We are going home.'],
  [null, 'sehen', null, 'to see', 'Verbs', 'Ich sehe den Mann.', 'I see the man.'],
  [null, 'essen', null, 'to eat', 'Verbs', 'Ich esse einen Apfel.', 'I am eating an apple.'],
  [null, 'trinken', null, 'to drink', 'Verbs', 'Trinkst du Wasser?', 'Are you drinking water?'],
  [null, 'schlafen', null, 'to sleep', 'Verbs', 'Das Kind schläft.', 'The child is sleeping.'],
  [null, 'sprechen', null, 'to speak', 'Verbs', 'Sprechen Sie Deutsch?', 'Do you speak German?'],
  [null, 'lesen', null, 'to read', 'Verbs', 'Ich lese ein Buch.', 'I am reading a book.'],
  [null, 'schreiben', null, 'to write', 'Verbs', 'Sie schreibt einen Brief.', 'She is writing a letter.'],
  [null, 'hören', null, 'to hear, to listen', 'Verbs', 'Ich höre Musik.', 'I am listening to music.'],
  [null, 'verstehen', null, 'to understand', 'Verbs', 'Ich verstehe Sie nicht.', 'I do not understand you.'],
  [null, 'lernen', null, 'to learn', 'Verbs', 'Wir lernen Deutsch.', 'We are learning German.'],
  [null, 'arbeiten', null, 'to work', 'Verbs', 'Er arbeitet im Büro.', 'He works in the office.'],
  [null, 'wohnen', null, 'to live, to reside', 'Verbs', 'Ich wohne in Berlin.', 'I live in Berlin.'],
  [null, 'heißen', null, 'to be called', 'Verbs', 'Wie heißt du?', 'What is your name?'],
  [null, 'fahren', null, 'to drive, to ride', 'Verbs', 'Wir fahren mit dem Bus.', 'We are taking the bus.'],
  [null, 'kaufen', null, 'to buy', 'Verbs', 'Ich kaufe Brot.', 'I am buying bread.'],
  [null, 'spielen', null, 'to play', 'Verbs', 'Die Kinder spielen Fußball.', 'The children are playing soccer.'],
  [null, 'bleiben', null, 'to stay, to remain', 'Verbs', 'Bleib hier!', 'Stay here!'],
  [null, 'helfen', null, 'to help', 'Verbs', 'Kannst du mir helfen?', 'Can you help me?'],
  [null, 'fragen', null, 'to ask', 'Verbs', 'Ich frage den Lehrer.', 'I am asking the teacher.'],
  [null, 'antworten', null, 'to answer', 'Verbs', 'Bitte antworte schnell.', 'Please answer quickly.'],
  [null, 'warten', null, 'to wait', 'Verbs', 'Ich warte auf den Bus.', 'I am waiting for the bus.'],
  [null, 'suchen', null, 'to search, to look for', 'Verbs', 'Ich suche meine Schlüssel.', 'I am looking for my keys.'],
  [null, 'finden', null, 'to find', 'Verbs', 'Ich finde das Buch gut.', 'I think the book is good.'],
  [null, 'nehmen', null, 'to take', 'Verbs', 'Nimm den Stift.', 'Take the pen.'],
  [null, 'denken', null, 'to think', 'Verbs', 'Was denkst du?', 'What do you think?'],
  [null, 'glauben', null, 'to believe', 'Verbs', 'Ich glaube dir.', 'I believe you.'],
  [null, 'lieben', null, 'to love', 'Verbs', 'Ich liebe dich.', 'I love you.'],
  [null, 'leben', null, 'to live, to be alive', 'Verbs', 'Sie leben in Wien.', 'They live in Vienna.'],
  [null, 'öffnen', null, 'to open', 'Verbs', 'Öffne das Fenster.', 'Open the window.'],
  [null, 'schließen', null, 'to close', 'Verbs', 'Schließ die Tür.', 'Close the door.'],
  [null, 'sitzen', null, 'to sit', 'Verbs', 'Er sitzt auf dem Stuhl.', 'He is sitting on the chair.'],
  [null, 'stehen', null, 'to stand', 'Verbs', 'Das Buch steht dort.', 'The book is over there.'],
  [null, 'laufen', null, 'to run, to walk', 'Verbs', 'Ich laufe jeden Morgen.', 'I run every morning.'],
  ['der', 'Mann', 'Männer', 'man', 'People', 'Der Mann liest die Zeitung.', 'The man is reading the newspaper.'],
  ['die', 'Frau', 'Frauen', 'woman, wife', 'People', 'Die Frau kauft ein.', 'The woman is shopping.'],
  ['das', 'Kind', 'Kinder', 'child', 'People', 'Das Kind spielt im Park.', 'The child is playing in the park.'],
  ['der', 'Junge', 'Jungen', 'boy', 'People', 'Der Junge ist klein.', 'The boy is small.'],
  ['das', 'Mädchen', 'Mädchen', 'girl', 'People', 'Das Mädchen singt schön.', 'The girl sings beautifully.'],
  ['die', 'Familie', 'Familien', 'family', 'People', 'Meine Familie ist groß.', 'My family is big.'],
  ['der', 'Vater', 'Väter', 'father', 'People', 'Mein Vater arbeitet viel.', 'My father works a lot.'],
  ['die', 'Mutter', 'Mütter', 'mother', 'People', 'Meine Mutter kocht gut.', 'My mother cooks well.'],
  ['die', 'Eltern', null, 'parents', 'People', 'Meine Eltern wohnen hier.', 'My parents live here.'],
  ['der', 'Bruder', 'Brüder', 'brother', 'People', 'Mein Bruder heißt Max.', 'My brother is called Max.'],
  ['die', 'Schwester', 'Schwestern', 'sister', 'People', 'Meine Schwester ist Studentin.', 'My sister is a student.'],
  ['der', 'Freund', 'Freunde', 'friend, boyfriend', 'People', 'Er ist mein bester Freund.', 'He is my best friend.'],
  ['die', 'Freundin', 'Freundinnen', 'friend, girlfriend', 'People', 'Sie ist meine Freundin.', 'She is my friend.'],
  ['der', 'Name', 'Namen', 'name', 'People', 'Mein Name ist Anna.', 'My name is Anna.'],
  [null, 'gut', null, 'good', 'Adjectives', 'Das Essen ist gut.', 'The food is good.'],
  [null, 'schlecht', null, 'bad', 'Adjectives', 'Das Wetter ist schlecht.', 'The weather is bad.'],
  [null, 'neu', null, 'new', 'Adjectives', 'Mein Auto ist neu.', 'My car is new.'],
  [null, 'alt', null, 'old', 'Adjectives', 'Das Haus ist alt.', 'The house is old.'],
  [null, 'groß', null, 'big, tall', 'Adjectives', 'Die Stadt ist groß.', 'The city is big.'],
  [null, 'klein', null, 'small', 'Adjectives', 'Das Zimmer ist klein.', 'The room is small.'],
  [null, 'schön', null, 'beautiful, nice', 'Adjectives', 'Der Park ist schön.', 'The park is beautiful.'],
  [null, 'schnell', null, 'fast', 'Adjectives', 'Der Zug ist schnell.', 'The train is fast.'],
  [null, 'langsam', null, 'slow', 'Adjectives', 'Bitte langsam sprechen.', 'Please speak slowly.'],
  [null, 'teuer', null, 'expensive', 'Adjectives', 'Das Handy ist teuer.', 'The phone is expensive.'],
  [null, 'billig', null, 'cheap', 'Adjectives', 'Die Jacke ist billig.', 'The jacket is cheap.'],
  [null, 'richtig', null, 'correct, right', 'Adjectives', 'Die Antwort ist richtig.', 'The answer is correct.'],
  [null, 'falsch', null, 'wrong, false', 'Adjectives', 'Das ist falsch.', 'That is wrong.'],
  [null, 'glücklich', null, 'happy', 'Emotions', 'Ich bin glücklich.', 'I am happy.'],
  [null, 'traurig', null, 'sad', 'Emotions', 'Warum bist du traurig?', 'Why are you sad?'],
  [null, 'müde', null, 'tired', 'Emotions', 'Ich bin müde.', 'I am tired.'],
  [null, 'ja', null, 'yes', 'Basics', 'Ja, gerne.', 'Yes, with pleasure.'],
  [null, 'nein', null, 'no', 'Basics', 'Nein, danke.', 'No, thank you.'],
  [null, 'bitte', null, 'please, you are welcome', 'Basics', 'Ein Kaffee, bitte.', 'A coffee, please.'],
  [null, 'danke', null, 'thank you', 'Basics', 'Danke schön!', 'Thank you very much!'],
  [null, 'hallo', null, 'hello', 'Basics', 'Hallo, wie geht es dir?', 'Hello, how are you?'],
  [null, 'tschüss', null, 'bye', 'Basics', 'Tschüss, bis morgen!', 'Bye, see you tomorrow!'],
  [null, 'wer', null, 'who', 'Question Words', 'Wer ist das?', 'Who is that?'],
  [null, 'was', null, 'what', 'Question Words', 'Was ist das?', 'What is that?'],
  [null, 'wo', null, 'where', 'Question Words', 'Wo wohnst du?', 'Where do you live?'],
  [null, 'wann', null, 'when', 'Question Words', 'Wann kommst du?', 'When are you coming?'],
  [null, 'warum', null, 'why', 'Question Words', 'Warum lernst du Deutsch?', 'Why are you learning German?'],
  [null, 'wie', null, 'how', 'Question Words', 'Wie geht es dir?', 'How are you?'],
  [null, 'wie viel', null, 'how much', 'Question Words', 'Wie viel kostet das?', 'How much does that cost?'],
  [null, 'wie viele', null, 'how many', 'Question Words', 'Wie viele Kinder haben Sie?', 'How many children do you have?'],
  [null, 'auch', null, 'also, too', 'Basics', 'Ich komme auch mit.', 'I am coming too.'],
  [null, 'nicht', null, 'not', 'Basics', 'Das ist nicht mein Buch.', 'That is not my book.'],
  [null, 'kein', null, 'no, not a', 'Basics', 'Ich habe kein Auto.', 'I do not have a car.'],
  [null, 'sehr', null, 'very', 'Basics', 'Das ist sehr gut.', 'That is very good.'],
  [null, 'schon', null, 'already', 'Basics', 'Ich bin schon fertig.', 'I am already done.'],
  [null, 'noch', null, 'still, yet', 'Basics', 'Ich habe noch Hunger.', 'I am still hungry.'],
  [null, 'jetzt', null, 'now', 'Time', 'Jetzt gehe ich.', 'Now I am leaving.'],
  [null, 'heute', null, 'today', 'Time', 'Heute ist Montag.', 'Today is Monday.'],
  [null, 'morgen', null, 'tomorrow', 'Time', 'Morgen habe ich Zeit.', 'Tomorrow I have time.'],
  [null, 'gestern', null, 'yesterday', 'Time', 'Gestern hat es geregnet.', 'Yesterday it rained.'],
  [null, 'immer', null, 'always', 'Time', 'Er kommt immer zu spät.', 'He is always late.'],
  [null, 'oft', null, 'often', 'Time', 'Wir gehen oft ins Kino.', 'We often go to the cinema.'],
  [null, 'manchmal', null, 'sometimes', 'Time', 'Manchmal lese ich.', 'Sometimes I read.'],
  [null, 'nie', null, 'never', 'Time', 'Ich rauche nie.', 'I never smoke.'],
  ['die', 'Stunde', 'Stunden', 'hour', 'Time', 'Ich warte eine Stunde.', 'I am waiting an hour.'],
  ['die', 'Minute', 'Minuten', 'minute', 'Time', 'Noch fünf Minuten!', 'Five more minutes!'],
  ['die', 'Woche', 'Wochen', 'week', 'Time', 'Bis nächste Woche!', 'Until next week!'],
  ['der', 'Monat', 'Monate', 'month', 'Time', 'Im nächsten Monat reise ich.', 'Next month I am traveling.'],
  ['der', 'Morgen', 'Morgen', 'morning', 'Time', 'Guten Morgen!', 'Good morning!'],
  ['der', 'Abend', 'Abende', 'evening', 'Time', 'Guten Abend!', 'Good evening!'],
  ['die', 'Nacht', 'Nächte', 'night', 'Time', 'Gute Nacht!', 'Good night!'],
  ['das', 'Essen', 'Essen', 'food, meal', 'Food', 'Das Essen schmeckt gut.', 'The food tastes good.'],
  ['das', 'Frühstück', 'Frühstücke', 'breakfast', 'Food', 'Das Frühstück ist um acht.', 'Breakfast is at eight.'],
  ['das', 'Brot', 'Brote', 'bread', 'Food', 'Ich kaufe frisches Brot.', 'I am buying fresh bread.'],
  ['das', 'Brötchen', 'Brötchen', 'bread roll', 'Food', 'Ein Brötchen mit Käse, bitte.', 'A roll with cheese, please.'],
  ['die', 'Butter', null, 'butter', 'Food', 'Butter auf das Brot, bitte.', 'Butter on the bread, please.'],
  ['der', 'Käse', 'Käse', 'cheese', 'Food', 'Ich esse gern Käse.', 'I like eating cheese.'],
  ['das', 'Ei', 'Eier', 'egg', 'Food', 'Ich möchte zwei Eier.', 'I would like two eggs.'],
  ['die', 'Milch', null, 'milk', 'Food', 'Trinkst du Milch?', 'Do you drink milk?'],
  ['der', 'Kaffee', 'Kaffees', 'coffee', 'Drinks', 'Ein Kaffee, bitte.', 'A coffee, please.'],
  ['der', 'Tee', 'Tees', 'tea', 'Drinks', 'Ich trinke Tee mit Zucker.', 'I drink tea with sugar.'],
  ['das', 'Wasser', 'Wässer', 'water', 'Drinks', 'Ein Glas Wasser, bitte.', 'A glass of water, please.'],
  ['der', 'Saft', 'Säfte', 'juice', 'Drinks', 'Orangensaft schmeckt gut.', 'Orange juice tastes good.'],
  ['das', 'Bier', 'Biere', 'beer', 'Drinks', 'Ein Bier, bitte.', 'A beer, please.'],
  ['der', 'Wein', 'Weine', 'wine', 'Drinks', 'Rotwein oder Weißwein?', 'Red wine or white wine?'],
  ['das', 'Fleisch', null, 'meat', 'Food', 'Ich esse kein Fleisch.', 'I do not eat meat.'],
  ['der', 'Fisch', 'Fische', 'fish', 'Food', 'Der Fisch ist frisch.', 'The fish is fresh.'],
  ['der', 'Reis', null, 'rice', 'Food', 'Reis mit Gemüse, bitte.', 'Rice with vegetables, please.'],
  ['die', 'Kartoffel', 'Kartoffeln', 'potato', 'Food', 'Ich mag Kartoffeln.', 'I like potatoes.'],
  ['das', 'Gemüse', null, 'vegetables', 'Food', 'Gemüse ist gesund.', 'Vegetables are healthy.'],
  ['der', 'Apfel', 'Äpfel', 'apple', 'Food', 'Der Apfel ist rot.', 'The apple is red.'],
  ['die', 'Banane', 'Bananen', 'banana', 'Food', 'Die Banane ist gelb.', 'The banana is yellow.'],
  ['der', 'Zucker', null, 'sugar', 'Food', 'Zucker im Kaffee?', 'Sugar in the coffee?'],
  ['das', 'Salz', null, 'salt', 'Food', 'Das Salz ist in der Küche.', 'The salt is in the kitchen.'],
  ['der', 'Hunger', null, 'hunger', 'Food', 'Ich habe Hunger.', 'I am hungry.'],
  ['der', 'Durst', null, 'thirst', 'Food', 'Ich habe Durst.', 'I am thirsty.'],
  ['das', 'Haus', 'Häuser', 'house', 'Home', 'Das Haus ist weiß.', 'The house is white.'],
  ['die', 'Wohnung', 'Wohnungen', 'apartment', 'Home', 'Meine Wohnung ist klein.', 'My apartment is small.'],
  ['das', 'Zimmer', 'Zimmer', 'room', 'Home', 'Das Zimmer ist hell.', 'The room is bright.'],
  ['die', 'Küche', 'Küchen', 'kitchen', 'Home', 'Die Küche ist neu.', 'The kitchen is new.'],
  ['das', 'Bad', 'Bäder', 'bathroom', 'Home', 'Wo ist das Bad?', 'Where is the bathroom?'],
  ['die', 'Tür', 'Türen', 'door', 'Home', 'Die Tür ist offen.', 'The door is open.'],
  ['das', 'Fenster', 'Fenster', 'window', 'Home', 'Das Fenster ist zu.', 'The window is closed.'],
  ['der', 'Tisch', 'Tische', 'table', 'Home', 'Das Buch liegt auf dem Tisch.', 'The book is on the table.'],
  ['der', 'Stuhl', 'Stühle', 'chair', 'Home', 'Der Stuhl ist bequem.', 'The chair is comfortable.'],
  ['das', 'Bett', 'Betten', 'bed', 'Home', 'Das Bett ist weich.', 'The bed is soft.'],
  ['der', 'Schlüssel', 'Schlüssel', 'key', 'Home', 'Wo ist mein Schlüssel?', 'Where is my key?'],
  ['die', 'Stadt', 'Städte', 'city', 'City', 'Berlin ist eine große Stadt.', 'Berlin is a big city.'],
  ['die', 'Straße', 'Straßen', 'street', 'City', 'Die Straße ist lang.', 'The street is long.'],
  ['der', 'Bahnhof', 'Bahnhöfe', 'train station', 'Travel', 'Der Zug kommt am Bahnhof an.', 'The train arrives at the station.'],
  ['das', 'Auto', 'Autos', 'car', 'Travel', 'Mein Auto ist rot.', 'My car is red.'],
  ['der', 'Bus', 'Busse', 'bus', 'Travel', 'Der Bus kommt um acht.', 'The bus comes at eight.'],
  ['der', 'Zug', 'Züge', 'train', 'Travel', 'Der Zug ist pünktlich.', 'The train is on time.'],
  ['das', 'Fahrrad', 'Fahrräder', 'bicycle', 'Travel', 'Ich fahre mit dem Fahrrad.', 'I am riding my bicycle.'],
  ['die', 'Fahrkarte', 'Fahrkarten', 'ticket', 'Travel', 'Eine Fahrkarte nach Bonn, bitte.', 'A ticket to Bonn, please.'],
  ['das', 'Geld', 'Gelder', 'money', 'Shopping', 'Ich habe kein Geld dabei.', 'I have no money with me.'],
  ['das', 'Wetter', null, 'weather', 'Weather', 'Wie ist das Wetter?', 'How is the weather?'],
  ['die', 'Sonne', null, 'sun', 'Weather', 'Die Sonne scheint.', 'The sun is shining.'],
  ['der', 'Regen', null, 'rain', 'Weather', 'Der Regen ist kalt.', 'The rain is cold.'],
  [null, 'kalt', null, 'cold', 'Weather', 'Das Wasser ist kalt.', 'The water is cold.'],
  [null, 'warm', null, 'warm', 'Weather', 'Der Tee ist warm.', 'The tea is warm.'],
  ['der', 'Kopf', 'Köpfe', 'head', 'Body', 'Mein Kopf tut weh.', 'My head hurts.'],
  ['die', 'Hand', 'Hände', 'hand', 'Body', 'Meine Hand ist kalt.', 'My hand is cold.'],
  ['der', 'Arzt', 'Ärzte', 'doctor', 'Health', 'Ich gehe zum Arzt.', 'I am going to the doctor.'],
  [null, 'krank', null, 'sick, ill', 'Health', 'Das Kind ist krank.', 'The child is sick.'],
  [null, 'gesund', null, 'healthy', 'Health', 'Sport macht gesund.', 'Exercise keeps you healthy.'],
  ['die', 'Schule', 'Schulen', 'school', 'School', 'Die Schule beginnt um acht.', 'School starts at eight.'],
  ['der', 'Lehrer', 'Lehrer', 'teacher', 'School', 'Der Lehrer ist nett.', 'The teacher is nice.'],
  ['das', 'Buch', 'Bücher', 'book', 'School', 'Ich lese ein Buch.', 'I am reading a book.'],
  ['der', 'Stift', 'Stifte', 'pen', 'School', 'Mein Stift ist blau.', 'My pen is blue.'],
  ['die', 'Arbeit', 'Arbeiten', 'work, job', 'Work', 'Die Arbeit ist schwer.', 'The work is hard.'],
  ['das', 'Büro', 'Büros', 'office', 'Work', 'Er ist im Büro.', 'He is at the office.'],
  ['der', 'Sport', null, 'sport, exercise', 'Fitness', 'Ich mache Sport.', 'I exercise.'],
  ['das', 'Fitnessstudio', 'Fitnessstudios', 'gym', 'Fitness', 'Das Fitnessstudio ist neu.', 'The gym is new.'],
  ['das', 'Training', 'Trainings', 'workout, training', 'Fitness', 'Das Training beginnt um sieben.', 'The workout starts at seven.'],
  ['die', 'Übung', 'Übungen', 'exercise', 'Fitness', 'Diese Übung ist schwer.', 'This exercise is hard.'],
  // ── A1 extension: numbers, pronouns, core function words ──
  [null, 'eins', null, 'one', 'Numbers', 'Eins, zwei, drei!', 'One, two, three!'],
  [null, 'zwei', null, 'two', 'Numbers', 'Ich habe zwei Geschwister.', 'I have two siblings.'],
  [null, 'drei', null, 'three', 'Numbers', 'Wir sind drei Freunde.', 'We are three friends.'],
  [null, 'vier', null, 'four', 'Numbers', 'Das Auto hat vier Türen.', 'The car has four doors.'],
  [null, 'fünf', null, 'five', 'Numbers', 'Ich lerne fünf Wörter.', 'I am learning five words.'],
  [null, 'sechs', null, 'six', 'Numbers', 'Es ist sechs Uhr.', 'It is six oclock.'],
  [null, 'sieben', null, 'seven', 'Numbers', 'Sieben Tage sind eine Woche.', 'Seven days are one week.'],
  [null, 'acht', null, 'eight', 'Numbers', 'Die Schule beginnt um acht Uhr.', 'School starts at eight.'],
  [null, 'neun', null, 'nine', 'Numbers', 'Mein Sohn ist neun Jahre alt.', 'My son is nine years old.'],
  [null, 'zehn', null, 'ten', 'Numbers', 'Ich habe zehn Euro.', 'I have ten euros.'],
  [null, 'elf', null, 'eleven', 'Numbers', 'Das Kind ist elf Jahre alt.', 'The child is eleven years old.'],
  [null, 'zwölf', null, 'twelve', 'Numbers', 'Es ist zwölf Uhr.', 'It is twelve oclock.'],
  [null, 'zwanzig', null, 'twenty', 'Numbers', 'Ich habe zwanzig Minuten gewartet.', 'I waited twenty minutes.'],
  [null, 'hundert', null, 'hundred', 'Numbers', 'Das kostet hundert Euro.', 'That costs one hundred euros.'],
  [null, 'tausend', null, 'thousand', 'Numbers', 'Tausend Dank!', 'A thousand thanks!'],
  ['die', 'Zahl', 'Zahlen', 'number', 'Numbers', 'Die Zahl ist zu groß.', 'The number is too big.'],
  [null, 'ich', null, 'I, me', 'Basics', 'Ich wohne in Berlin.', 'I live in Berlin.'],
  [null, 'du', null, 'you (informal)', 'Basics', 'Du bist mein Freund.', 'You are my friend.'],
  [null, 'er', null, 'he', 'Basics', 'Er ist Lehrer.', 'He is a teacher.'],
  [null, 'es', null, 'it', 'Basics', 'Es ist kalt heute.', 'It is cold today.'],
  [null, 'man', null, 'one, you, people (generic)', 'Basics', 'Man kann hier gut essen.', 'You can eat well here.'],
  [null, 'sie', null, 'she', 'Basics', 'Sie ist Studentin.', 'She is a student.'],
  [null, 'wir', null, 'we', 'Basics', 'Wir lernen Deutsch.', 'We are learning German.'],
  [null, 'ihr', null, 'you (plural, informal)', 'Basics', 'Ihr seid spät.', 'You are late.'],
  [null, 'alle', null, 'all, everyone', 'Basics', 'Alle Kinder spielen.', 'All children are playing.'],
  [null, 'etwas', null, 'something', 'Basics', 'Ich möchte etwas trinken.', 'I would like something to drink.'],
  [null, 'nichts', null, 'nothing', 'Basics', 'Ich habe nichts gesagt.', 'I said nothing.'],
  [null, 'alles', null, 'everything', 'Basics', 'Alles ist gut.', 'Everything is fine.'],
  [null, 'und', null, 'and', 'Basics', 'Ich mag Kaffee und Tee.', 'I like coffee and tea.'],
  [null, 'oder', null, 'or', 'Basics', 'Tee oder Kaffee?', 'Tea or coffee?'],
  [null, 'aber', null, 'but', 'Basics', 'Ich will, aber ich kann nicht.', 'I want to, but I cannot.'],
  [null, 'dann', null, 'then, after that', 'Basics', 'Wir essen, dann gehen wir.', 'We eat, then we go.'],
  [null, 'hier', null, 'here', 'Basics', 'Ich wohne hier.', 'I live here.'],
  [null, 'da', null, 'there', 'Basics', 'Da ist der Bus!', 'There is the bus!'],
  [null, 'dort', null, 'over there', 'Basics', 'Dort ist der Bahnhof.', 'Over there is the train station.'],
  [null, 'so', null, 'so, like this', 'Basics', 'So ist es richtig.', 'That is how it is right.'],
  [null, 'doch', null, 'but, yet (contradiction)', 'Basics', 'Doch, ich habe Zeit!', 'Yes I do, I have time!'],
  [null, 'wieder', null, 'again', 'Basics', 'Wir sehen uns wieder.', 'We will see each other again.'],
  // ── A1 extension: prepositions, time, common verbs ──
  [null, 'mit', null, 'with', 'Basics', 'Ich fahre mit dem Bus.', 'I am taking the bus.'],
  [null, 'für', null, 'for', 'Basics', 'Das ist für dich.', 'That is for you.'],
  [null, 'von', null, 'from, of', 'Basics', 'Das ist ein Geschenk von Anna.', 'That is a present from Anna.'],
  [null, 'bei', null, 'at, near', 'Basics', 'Ich bleibe bei meinem Vater.', 'I am staying with my father.'],
  [null, 'nach', null, 'after; to (places)', 'Basics', 'Wir fahren nach Berlin.', 'We are driving to Berlin.'],
  [null, 'aus', null, 'out of, from', 'Basics', 'Ich komme aus Spanien.', 'I come from Spain.'],
  [null, 'zu', null, 'to, at', 'Basics', 'Ich gehe zur Schule.', 'I am going to school.'],
  [null, 'an', null, 'at, on (vertical)', 'Basics', 'Das Bild ist an der Wand.', 'The picture is on the wall.'],
  [null, 'auf', null, 'on, onto', 'Basics', 'Das Buch ist auf dem Tisch.', 'The book is on the table.'],
  [null, 'in', null, 'in, into', 'Basics', 'Die Milch ist in der Tasche.', 'The milk is in the bag.'],
  [null, 'um', null, 'at (time); around', 'Basics', 'Wir treffen uns um acht.', 'We are meeting at eight.'],
  ['die', 'Sekunde', 'Sekunden', 'second', 'Time', 'Warte eine Sekunde!', 'Wait a second!'],
  ['das', 'Wochenende', 'Wochenenden', 'weekend', 'Time', 'Am Wochenende schlafe ich lange.', 'On the weekend I sleep in.'],
  ['der', 'Geburtstag', 'Geburtstage', 'birthday', 'Time', 'Mein Geburtstag ist im Mai.', 'My birthday is in May.'],
  ['die', 'Uhr', 'Uhren', 'clock, watch', 'Time', 'Die Uhr zeigt drei.', 'The clock shows three.'],
  [null, 'früh', null, 'early', 'Time', 'Ich stehe früh auf.', 'I get up early.'],
  [null, 'spät', null, 'late', 'Time', 'Es ist schon spät.', 'It is already late.'],
  [null, 'zuerst', null, 'first (of all)', 'Time', 'Zuerst frühstücke ich.', 'First I have breakfast.'],
  [null, 'danach', null, 'after that', 'Time', 'Danach gehe ich arbeiten.', 'After that I go to work.'],
  [null, 'tragen', null, 'to carry, to wear', 'Verbs', 'Er trägt eine Jacke.', 'He is wearing a jacket.'],
  [null, 'schneiden', null, 'to cut', 'Verbs', 'Ich schneide das Brot.', 'I am cutting the bread.'],
  [null, 'backen', null, 'to bake', 'Verbs', 'Wir backen einen Kuchen.', 'We are baking a cake.'],
  [null, 'singen', null, 'to sing', 'Verbs', 'Die Kinder singen laut.', 'The children are singing loudly.'],
  [null, 'tanzen', null, 'to dance', 'Verbs', 'Wir tanzen gern.', 'We like to dance.'],
  [null, 'schwimmen', null, 'to swim', 'Verbs', 'Ich kann gut schwimmen.', 'I can swim well.'],
  [null, 'lachen', null, 'to laugh', 'Emotions', 'Die Kinder lachen.', 'The children are laughing.'],
  [null, 'weinen', null, 'to cry', 'Emotions', 'Warum weinst du?', 'Why are you crying?'],
  [null, 'rufen', null, 'to call, to shout', 'Verbs', 'Er ruft meinen Namen.', 'He is calling my name.'],
  [null, 'holen', null, 'to get, to fetch', 'Verbs', 'Ich hole Milch aus dem Laden.', 'I am getting milk from the shop.'],
  [null, 'bringen', null, 'to bring', 'Verbs', 'Ich bringe das Buch mit.', 'I am bringing the book.'],
  [null, 'legen', null, 'to lay, to put', 'Verbs', 'Ich lege den Stift auf den Tisch.', 'I am putting the pen on the table.'],
  [null, 'ziehen', null, 'to pull', 'Verbs', 'Wir ziehen die Tür auf.', 'We are pulling the door open.'],
  [null, 'schieben', null, 'to push', 'Verbs', 'Wir schieben das Auto.', 'We are pushing the car.'],
  [null, 'werfen', null, 'to throw', 'Verbs', 'Wirf den Ball!', 'Throw the ball!'],
  [null, 'fangen', null, 'to catch', 'Verbs', 'Der Hund fängt den Ball.', 'The dog catches the ball.'],
  [null, 'bauen', null, 'to build', 'Verbs', 'Wir bauen ein Haus.', 'We are building a house.'],
  [null, 'verkaufen', null, 'to sell', 'Verbs', 'Er verkauft sein Fahrrad.', 'He is selling his bicycle.'],
  [null, 'zahlen', null, 'to pay', 'Shopping', 'Ich zahle jetzt.', 'I am paying now.'],
  [null, 'probieren', null, 'to try, to taste', 'Verbs', 'Probier mal die Suppe!', 'Try the soup!'],
  [null, 'rechnen', null, 'to calculate', 'Verbs', 'Sie rechnet schnell.', 'She calculates quickly.'],
  [null, 'zählen', null, 'to count', 'Numbers', 'Ich zähle bis zehn.', 'I am counting to ten.'],
  // ── A1 extension: separable & everyday verbs ──
  [null, 'malen', null, 'to paint', 'Verbs', 'Das Kind malt ein Bild.', 'The child is painting a picture.'],
  [null, 'sammeln', null, 'to collect', 'Verbs', 'Er sammelt Briefmarken.', 'He collects stamps.'],
  [null, 'springen', null, 'to jump', 'Fitness', 'Der Hund springt ins Wasser.', 'The dog jumps into the water.'],
  [null, 'reiten', null, 'to ride (a horse)', 'Free Time', 'Sie reitet ein Pferd.', 'She is riding a horse.'],
  [null, 'folgen', null, 'to follow', 'Verbs', 'Folgen Sie mir, bitte.', 'Follow me, please.'],
  [null, 'führen', null, 'to lead, to guide', 'Verbs', 'Die Straße führt zum Bahnhof.', 'The street leads to the station.'],
  [null, 'passieren', null, 'to happen', 'Verbs', 'Was ist passiert?', 'What happened?'],
  [null, 'dauern', null, 'to take (time), to last', 'Time', 'Wie lange dauert der Film?', 'How long does the movie take?'],
  [null, 'fühlen', null, 'to feel', 'Emotions', 'Ich fühle mich gut.', 'I feel good.'],
  [null, 'schicken', null, 'to send', 'Communication', 'Ich schicke dir eine Nachricht.', 'I am sending you a message.'],
  [null, 'aufstehen', null, 'to get up', 'Verbs', 'Ich stehe um sieben auf.', 'I get up at seven.'],
  [null, 'anziehen', null, 'to put on, to dress', 'Clothing', 'Ich ziehe mich warm an.', 'I am dressing warmly.'],
  [null, 'duschen', null, 'to shower', 'Body', 'Er duscht nach dem Sport.', 'He showers after sports.'],
  [null, 'aufmachen', null, 'to open up', 'Home', 'Mach das Fenster auf!', 'Open the window!'],
  [null, 'zumachen', null, 'to close, to shut', 'Home', 'Mach die Tür zu!', 'Close the door!'],
  [null, 'fernsehen', null, 'to watch TV', 'Free Time', 'Abends sehe ich fern.', 'In the evenings I watch TV.'],
  [null, 'aufwachen', null, 'to wake up', 'Verbs', 'Ich wache um sechs auf.', 'I wake up at six.'],
  [null, 'einschlafen', null, 'to fall asleep', 'Verbs', 'Das Kind schläft schnell ein.', 'The child falls asleep quickly.'],
  [null, 'mitnehmen', null, 'to take along', 'Travel', 'Nimm eine Flasche Wasser mit!', 'Take a bottle of water along!'],
  // ── A1 extension: people & home nouns ──
  ['der', 'Herr', 'Herren', 'gentleman, mister', 'People', 'Der Herr wartet dort.', 'The gentleman is waiting there.'],
  ['die', 'Dame', 'Damen', 'lady', 'People', 'Die Dame ist freundlich.', 'The lady is friendly.'],
  ['das', 'Baby', 'Babys', 'baby', 'People', 'Das Baby schläft.', 'The baby is sleeping.'],
  ['der', 'Gast', 'Gäste', 'guest', 'People', 'Der Gast kommt um acht.', 'The guest comes at eight.'],
  ['die', 'Geschwister', null, 'siblings', 'People', 'Wir sind zwei Geschwister.', 'We are two siblings.'],
  ['der', 'Sohn', 'Söhne', 'son', 'People', 'Mein Sohn ist sechs.', 'My son is six.'],
  ['die', 'Tochter', 'Töchter', 'daughter', 'People', 'Ihre Tochter lernt Spanisch.', 'Her daughter is learning Spanish.'],
  ['der', 'Großvater', 'Großväter', 'grandfather', 'People', 'Mein Großvater wohnt bei uns.', 'My grandfather lives with us.'],
  ['die', 'Großmutter', 'Großmütter', 'grandmother', 'People', 'Meine Großmutter kocht Suppe.', 'My grandmother is cooking soup.'],
  ['der', 'Garten', 'Gärten', 'garden', 'Home', 'Der Garten ist klein.', 'The garden is small.'],
  ['die', 'Wand', 'Wände', 'wall', 'Home', 'Die Wand ist weiß.', 'The wall is white.'],
  ['der', 'Boden', 'Böden', 'floor, ground', 'Home', 'Der Boden ist nass.', 'The floor is wet.'],
  ['das', 'Licht', 'Lichter', 'light', 'Home', 'Das Licht ist an.', 'The light is on.'],
  ['die', 'Lampe', 'Lampen', 'lamp', 'Home', 'Die Lampe ist neu.', 'The lamp is new.'],
  ['der', 'Spiegel', 'Spiegel', 'mirror', 'Home', 'Der Spiegel hängt im Bad.', 'The mirror hangs in the bathroom.'],
  ['die', 'Dusche', 'Duschen', 'shower', 'Home', 'Die Dusche ist warm.', 'The shower is warm.'],
  ['die', 'Toilette', 'Toiletten', 'toilet', 'Home', 'Wo ist die Toilette?', 'Where is the toilet?'],
  ['der', 'Kühlschrank', 'Kühlschränke', 'refrigerator', 'Home', 'Die Milch ist im Kühlschrank.', 'The milk is in the refrigerator.'],
  ['das', 'Regal', 'Regale', 'shelf', 'Home', 'Die Bücher stehen im Regal.', 'The books are on the shelf.'],
  ['der', 'Platz', 'Plätze', 'place, square, seat', 'City', 'Der Platz ist voll.', 'The square is full.'],
  ['der', 'Park', 'Parks', 'park', 'City', 'Der Park ist schön.', 'The park is beautiful.'],
  ['das', 'Dorf', 'Dörfer', 'village', 'City', 'Das Dorf ist klein.', 'The village is small.'],
  // ── A1 extension: city, food, body, clothing, school, nature nouns ──
  ['das', 'Land', 'Länder', 'country, land', 'City', 'Das Land ist grün.', 'The country is green.'],
  ['die', 'Ecke', 'Ecken', 'corner', 'City', 'Warte an der Ecke!', 'Wait at the corner!'],
  ['die', 'Brücke', 'Brücken', 'bridge', 'City', 'Die Brücke ist alt.', 'The bridge is old.'],
  ['das', 'Geschäft', 'Geschäfte', 'shop, business', 'City', 'Das Geschäft öffnet um neun.', 'The shop opens at nine.'],
  ['die', 'Bank', 'Bänke', 'bench; bank', 'City', 'Wir sitzen auf der Bank.', 'We are sitting on the bench.'],
  ['die', 'Kirche', 'Kirchen', 'church', 'City', 'Die Kirche ist alt.', 'The church is old.'],
  ['die', 'Post', null, 'post office, mail', 'City', 'Die Post ist um die Ecke.', 'The post office is around the corner.'],
  ['die', 'Wurst', 'Würste', 'sausage', 'Food', 'Die Wurst schmeckt gut.', 'The sausage tastes good.'],
  ['der', 'Joghurt', 'Joghurts', 'yogurt', 'Food', 'Ich esse einen Joghurt.', 'I am eating a yogurt.'],
  ['das', 'Stück', 'Stücke', 'piece', 'Food', 'Ein Stück Kuchen, bitte.', 'One piece of cake, please.'],
  ['die', 'Tasse', 'Tassen', 'cup', 'Food', 'Eine Tasse Kaffee, bitte.', 'A cup of coffee, please.'],
  ['das', 'Glas', 'Gläser', 'glass', 'Food', 'Das Glas ist voll.', 'The glass is full.'],
  ['die', 'Flasche', 'Flaschen', 'bottle', 'Food', 'Ich kaufe eine Flasche Wasser.', 'I am buying a bottle of water.'],
  ['der', 'Teller', 'Teller', 'plate', 'Food', 'Der Teller ist weiß.', 'The plate is white.'],
  ['der', 'Löffel', 'Löffel', 'spoon', 'Food', 'Nimm den Löffel!', 'Take the spoon!'],
  ['die', 'Gabel', 'Gabeln', 'fork', 'Food', 'Ich brauche eine Gabel.', 'I need a fork.'],
  ['das', 'Messer', 'Messer', 'knife', 'Food', 'Das Messer ist scharf.', 'The knife is sharp.'],
  ['der', 'Hals', 'Hälse', 'neck, throat', 'Body', 'Mein Hals tut weh.', 'My throat hurts.'],
  ['die', 'Schulter', 'Schultern', 'shoulder', 'Body', 'Meine Schulter tut weh.', 'My shoulder hurts.'],
  ['der', 'Finger', 'Finger', 'finger', 'Body', 'Mein Finger tut weh.', 'My finger hurts.'],
  ['das', 'Knie', 'Knie', 'knee', 'Body', 'Mein Knie ist rot.', 'My knee is red.'],
  ['die', 'Mütze', 'Mützen', 'cap, hat', 'Clothing', 'Die Mütze ist warm.', 'The cap is warm.'],
  ['der', 'Hut', 'Hüte', 'hat', 'Clothing', 'Der Hut ist schwarz.', 'The hat is black.'],
  ['die', 'Socke', 'Socken', 'sock', 'Clothing', 'Wo ist meine Socke?', 'Where is my sock?'],
  ['der', 'Schal', 'Schals', 'scarf', 'Clothing', 'Nimm den Schal mit!', 'Take the scarf along!'],
  ['die', 'Tasche', 'Taschen', 'bag, pocket', 'Clothing', 'Meine Tasche ist schwer.', 'My bag is heavy.'],
  ['der', 'Knopf', 'Knöpfe', 'button', 'Clothing', 'Der Knopf ist klein.', 'The button is small.'],
  ['der', 'Student', 'Studenten', 'student (m)', 'School', 'Der Student lernt viel.', 'The student studies a lot.'],
  ['die', 'Studentin', 'Studentinnen', 'student (f)', 'School', 'Die Studentin wohnt hier.', 'The student lives here.'],
  ['der', 'Schüler', 'Schüler', 'pupil, school student', 'School', 'Der Schüler hat eine Frage.', 'The pupil has a question.'],
  ['die', 'Klasse', 'Klassen', 'class', 'School', 'Die Klasse ist groß.', 'The class is big.'],
  ['das', 'Heft', 'Hefte', 'notebook', 'School', 'Mein Heft ist neu.', 'My notebook is new.'],
  ['der', 'Bleistift', 'Bleistifte', 'pencil', 'School', 'Ich schreibe mit dem Bleistift.', 'I am writing with the pencil.'],
  ['die', 'Tafel', 'Tafeln', 'board, blackboard', 'School', 'Der Lehrer schreibt an die Tafel.', 'The teacher writes on the board.'],
  ['der', 'Wind', null, 'wind', 'Weather', 'Der Wind ist kalt.', 'The wind is cold.'],
  ['der', 'Schnee', null, 'snow', 'Weather', 'Der Schnee ist weiß.', 'The snow is white.'],
  ['die', 'Wolke', 'Wolken', 'cloud', 'Weather', 'Die Wolke ist groß.', 'The cloud is big.'],
  ['das', 'Eis', null, 'ice; ice cream', 'Food', 'Das Eis ist kalt.', 'The ice cream is cold.'],
  ['der', 'Himmel', null, 'sky, heaven', 'Nature', 'Der Himmel ist blau.', 'The sky is blue.'],
  ['der', 'Stern', 'Sterne', 'star', 'Nature', 'Ich sehe einen Stern.', 'I see a star.'],
  // ── A1 extension: nature, misc nouns, adjectives, adverbs ──
  ['der', 'Mond', null, 'moon', 'Nature', 'Der Mond ist hell.', 'The moon is bright.'],
  ['das', 'Meer', 'Meere', 'sea, ocean', 'Nature', 'Wir fahren ans Meer.', 'We are going to the sea.'],
  ['der', 'Fluss', 'Flüsse', 'river', 'Nature', 'Der Fluss ist lang.', 'The river is long.'],
  ['der', 'Baum', 'Bäume', 'tree', 'Nature', 'Der Baum ist alt.', 'The tree is old.'],
  ['die', 'Blume', 'Blumen', 'flower', 'Nature', 'Ich schenke ihr eine Blume.', 'I am giving her a flower.'],
  ['das', 'Gras', null, 'grass', 'Nature', 'Das Gras ist grün.', 'The grass is green.'],
  ['das', 'Ding', 'Dinge', 'thing', 'Basics', 'Was ist das für ein Ding?', 'What kind of thing is that?'],
  ['die', 'Sache', 'Sachen', 'thing, matter', 'Basics', 'Das ist eine gute Sache.', 'That is a good thing.'],
  ['der', 'Weg', 'Wege', 'way, path', 'Travel', 'Ich kenne den Weg.', 'I know the way.'],
  ['die', 'Hilfe', null, 'help', 'Basics', 'Danke für die Hilfe!', 'Thanks for the help!'],
  [null, 'lang', null, 'long', 'Adjectives', 'Der Film ist lang.', 'The movie is long.'],
  [null, 'kurz', null, 'short', 'Adjectives', 'Die Pause ist kurz.', 'The break is short.'],
  [null, 'hell', null, 'bright, light', 'Adjectives', 'Das Zimmer ist hell.', 'The room is bright.'],
  [null, 'dunkel', null, 'dark', 'Adjectives', 'Der Keller ist dunkel.', 'The basement is dark.'],
  [null, 'laut', null, 'loud', 'Adjectives', 'Die Musik ist laut.', 'The music is loud.'],
  [null, 'leise', null, 'quiet', 'Adjectives', 'Sprich leise!', 'Speak quietly!'],
  [null, 'stark', null, 'strong', 'Adjectives', 'Der Kaffee ist stark.', 'The coffee is strong.'],
  [null, 'voll', null, 'full', 'Adjectives', 'Der Bus ist voll.', 'The bus is full.'],
  [null, 'leer', null, 'empty', 'Adjectives', 'Die Straße ist leer.', 'The street is empty.'],
  [null, 'sauber', null, 'clean', 'Adjectives', 'Die Küche ist sauber.', 'The kitchen is clean.'],
  [null, 'schmutzig', null, 'dirty', 'Adjectives', 'Die Schuhe sind schmutzig.', 'The shoes are dirty.'],
  [null, 'nass', null, 'wet', 'Adjectives', 'Das Gras ist nass.', 'The grass is wet.'],
  [null, 'trocken', null, 'dry', 'Adjectives', 'Der Boden ist trocken.', 'The ground is dry.'],
  [null, 'weich', null, 'soft', 'Adjectives', 'Das Bett ist weich.', 'The bed is soft.'],
  [null, 'hart', null, 'hard', 'Adjectives', 'Das Brot ist hart.', 'The bread is hard.'],
  [null, 'leicht', null, 'light, easy', 'Adjectives', 'Die Tasche ist leicht.', 'The bag is light.'],
  [null, 'schwer', null, 'heavy, difficult', 'Adjectives', 'Der Koffer ist schwer.', 'The suitcase is heavy.'],
  [null, 'jung', null, 'young', 'Adjectives', 'Sie ist noch jung.', 'She is still young.'],
  [null, 'nett', null, 'nice', 'Adjectives', 'Sie ist sehr nett.', 'She is very nice.'],
  [null, 'freundlich', null, 'friendly', 'Adjectives', 'Der Mann ist freundlich.', 'The man is friendly.'],
  [null, 'fertig', null, 'finished, ready', 'Adjectives', 'Ich bin fertig!', 'I am done!'],
  [null, 'frei', null, 'free, available', 'Adjectives', 'Morgen bin ich frei.', 'Tomorrow I am free.'],
  [null, 'kaputt', null, 'broken', 'Adjectives', 'Mein Handy ist kaputt.', 'My phone is broken.'],
  [null, 'genau', null, 'exactly, precise', 'Basics', 'Das ist genau richtig.', 'That is exactly right.'],
  [null, 'klar', null, 'clear, of course', 'Basics', 'Klar, ich helfe dir!', 'Of course, I will help you!'],
  [null, 'gern', null, 'gladly, with pleasure', 'Basics', 'Ich lese gern.', 'I like reading.'],
  [null, 'ungefähr', null, 'approximately', 'Numbers', 'Es dauert ungefähr eine Stunde.', 'It takes about an hour.'],
  [null, 'meistens', null, 'most of the time', 'Time', 'Meistens fahre ich mit dem Bus.', 'Most of the time I take the bus.'],
  [null, 'selten', null, 'rarely', 'Time', 'Ich bin selten krank.', 'I am rarely sick.'],
  [null, 'sofort', null, 'immediately', 'Time', 'Komm sofort!', 'Come immediately!'],
  [null, 'bald', null, 'soon', 'Time', 'Wir sehen uns bald.', 'We will see each other soon.'],
]
