import type { SeedRow } from './types'

/** A1 seed corpus (~180 entries), roughly frequency-ordered within the level. */
export const A1_ROWS: SeedRow[] = [
  ['der', 'Tag', 'Tage', 'day', 'Time', 'Der Tag ist lang.', 'The day is long.'],
  ['die', 'Zeit', 'Zeiten', 'time', 'Time', 'Ich habe keine Zeit.', 'I have no time.'],
  ['das', 'Jahr', 'Jahre', 'year', 'Time', 'Das Jahr ist schnell vorbei.', 'The year passed quickly.'],
  ['der', 'Mensch', 'Menschen', 'human, person', 'People', 'Jeder Mensch macht Fehler.', 'Every person makes mistakes.'],
  [null, 'sein', null, 'to be', 'Verbs', 'Ich bin müde.', 'I am tired.'],
  [null, 'haben', null, 'to have', 'Verbs', 'Wir haben ein Auto.', 'We have a car.'],
  [null, 'werden', null, 'to become; will', 'Verbs', 'Es wird spät.', 'It is getting late.'],
  [null, 'können', null, 'can, to be able to', 'Verbs', 'Kannst du schwimmen?', 'Can you swim?'],
  [null, 'müssen', null, 'must, to have to', 'Verbs', 'Ich muss arbeiten.', 'I have to work.'],
  [null, 'sagen', null, 'to say', 'Verbs', 'Was sagst du?', 'What are you saying?'],
  [null, 'machen', null, 'to do, to make', 'Verbs', 'Was machst du?', 'What are you doing?'],
  [null, 'geben', null, 'to give', 'Verbs', 'Gib mir das Buch.', 'Give me the book.'],
  [null, 'kommen', null, 'to come', 'Verbs', 'Woher kommst du?', 'Where do you come from?'],
  [null, 'sollen', null, 'should, to be supposed to', 'Verbs', 'Du sollst schlafen.', 'You should sleep.'],
  [null, 'wissen', null, 'to know (a fact)', 'Verbs', 'Ich weiß es nicht.', 'I do not know it.'],
  [null, 'wollen', null, 'to want', 'Verbs', 'Ich will lernen.', 'I want to learn.'],
  [null, 'gehen', null, 'to go, to walk', 'Verbs', 'Wir gehen nach Hause.', 'We are going home.'],
  [null, 'sehen', null, 'to see', 'Verbs', 'Ich sehe den Mann.', 'I see the man.'],
  [null, 'essen', null, 'to eat', 'Verbs', 'Ich esse einen Apfel.', 'I am eating an apple.'],
  [null, 'trinken', null, 'to drink', 'Verbs', 'Trinkst du Wasser?', 'Are you drinking water?'],
  [null, 'schlafen', null, 'to sleep', 'Verbs', 'Das Kind schläft.', 'The child is sleeping.'],
  [null, 'sprechen', null, 'to speak', 'Verbs', 'Sprechen Sie Deutsch?', 'Do you speak German?'],
  [null, 'lesen', null, 'to read', 'Verbs', 'Ich lese ein Buch.', 'I am reading a book.'],
  [null, 'schreiben', null, 'to write', 'Verbs', 'Sie schreibt einen Brief.', 'She is writing a letter.'],
  [null, 'hören', null, 'to hear, to listen', 'Verbs', 'Ich höre Musik.', 'I am listening to music.'],
  [null, 'verstehen', null, 'to understand', 'Verbs', 'Ich verstehe Sie nicht.', 'I do not understand you.'],
  [null, 'lernen', null, 'to learn', 'Verbs', 'Wir lernen Deutsch.', 'We are learning German.'],
  [null, 'arbeiten', null, 'to work', 'Verbs', 'Er arbeitet im Büro.', 'He works in the office.'],
  [null, 'wohnen', null, 'to live, to reside', 'Verbs', 'Ich wohne in Berlin.', 'I live in Berlin.'],
  [null, 'heißen', null, 'to be called', 'Verbs', 'Wie heißt du?', 'What is your name?'],
  [null, 'fahren', null, 'to drive, to ride', 'Verbs', 'Wir fahren mit dem Bus.', 'We are taking the bus.'],
  [null, 'kaufen', null, 'to buy', 'Verbs', 'Ich kaufe Brot.', 'I am buying bread.'],
  [null, 'spielen', null, 'to play', 'Verbs', 'Die Kinder spielen Fußball.', 'The children are playing soccer.'],
  [null, 'bleiben', null, 'to stay, to remain', 'Verbs', 'Bleib hier!', 'Stay here!'],
  [null, 'helfen', null, 'to help', 'Verbs', 'Kannst du mir helfen?', 'Can you help me?'],
  [null, 'fragen', null, 'to ask', 'Verbs', 'Ich frage den Lehrer.', 'I am asking the teacher.'],
  [null, 'antworten', null, 'to answer', 'Verbs', 'Bitte antworte schnell.', 'Please answer quickly.'],
  [null, 'warten', null, 'to wait', 'Verbs', 'Ich warte auf den Bus.', 'I am waiting for the bus.'],
  [null, 'suchen', null, 'to search, to look for', 'Verbs', 'Ich suche meine Schlüssel.', 'I am looking for my keys.'],
  [null, 'finden', null, 'to find', 'Verbs', 'Ich finde das Buch gut.', 'I think the book is good.'],
  [null, 'nehmen', null, 'to take', 'Verbs', 'Nimm den Stift.', 'Take the pen.'],
  [null, 'denken', null, 'to think', 'Verbs', 'Was denkst du?', 'What do you think?'],
  [null, 'glauben', null, 'to believe', 'Verbs', 'Ich glaube dir.', 'I believe you.'],
  [null, 'lieben', null, 'to love', 'Verbs', 'Ich liebe dich.', 'I love you.'],
  [null, 'leben', null, 'to live, to be alive', 'Verbs', 'Sie leben in Wien.', 'They live in Vienna.'],
  [null, 'öffnen', null, 'to open', 'Verbs', 'Öffne das Fenster.', 'Open the window.'],
  [null, 'schließen', null, 'to close', 'Verbs', 'Schließ die Tür.', 'Close the door.'],
  [null, 'sitzen', null, 'to sit', 'Verbs', 'Er sitzt auf dem Stuhl.', 'He is sitting on the chair.'],
  [null, 'stehen', null, 'to stand', 'Verbs', 'Das Buch steht dort.', 'The book is over there.'],
  [null, 'laufen', null, 'to run, to walk', 'Verbs', 'Ich laufe jeden Morgen.', 'I run every morning.'],
  ['der', 'Mann', 'Männer', 'man', 'People', 'Der Mann liest die Zeitung.', 'The man is reading the newspaper.'],
  ['die', 'Frau', 'Frauen', 'woman, wife', 'People', 'Die Frau kauft ein.', 'The woman is shopping.'],
  ['das', 'Kind', 'Kinder', 'child', 'People', 'Das Kind spielt im Park.', 'The child is playing in the park.'],
  ['der', 'Junge', 'Jungen', 'boy', 'People', 'Der Junge ist klein.', 'The boy is small.'],
  ['das', 'Mädchen', 'Mädchen', 'girl', 'People', 'Das Mädchen singt schön.', 'The girl sings beautifully.'],
  ['die', 'Familie', 'Familien', 'family', 'People', 'Meine Familie ist groß.', 'My family is big.'],
  ['der', 'Vater', 'Väter', 'father', 'People', 'Mein Vater arbeitet viel.', 'My father works a lot.'],
  ['die', 'Mutter', 'Mütter', 'mother', 'People', 'Meine Mutter kocht gut.', 'My mother cooks well.'],
  ['die', 'Eltern', null, 'parents', 'People', 'Meine Eltern wohnen hier.', 'My parents live here.'],
  ['der', 'Bruder', 'Brüder', 'brother', 'People', 'Mein Bruder heißt Max.', 'My brother is called Max.'],
  ['die', 'Schwester', 'Schwestern', 'sister', 'People', 'Meine Schwester ist Studentin.', 'My sister is a student.'],
  ['der', 'Freund', 'Freunde', 'friend, boyfriend', 'People', 'Er ist mein bester Freund.', 'He is my best friend.'],
  ['die', 'Freundin', 'Freundinnen', 'friend, girlfriend', 'People', 'Sie ist meine Freundin.', 'She is my friend.'],
  ['der', 'Name', 'Namen', 'name', 'People', 'Mein Name ist Anna.', 'My name is Anna.'],
  [null, 'gut', null, 'good', 'Adjectives', 'Das Essen ist gut.', 'The food is good.'],
  [null, 'schlecht', null, 'bad', 'Adjectives', 'Das Wetter ist schlecht.', 'The weather is bad.'],
  [null, 'neu', null, 'new', 'Adjectives', 'Mein Auto ist neu.', 'My car is new.'],
  [null, 'alt', null, 'old', 'Adjectives', 'Das Haus ist alt.', 'The house is old.'],
  [null, 'groß', null, 'big, tall', 'Adjectives', 'Die Stadt ist groß.', 'The city is big.'],
  [null, 'klein', null, 'small', 'Adjectives', 'Das Zimmer ist klein.', 'The room is small.'],
  [null, 'schön', null, 'beautiful, nice', 'Adjectives', 'Der Park ist schön.', 'The park is beautiful.'],
  [null, 'schnell', null, 'fast', 'Adjectives', 'Der Zug ist schnell.', 'The train is fast.'],
  [null, 'langsam', null, 'slow', 'Adjectives', 'Bitte langsam sprechen.', 'Please speak slowly.'],
  [null, 'teuer', null, 'expensive', 'Adjectives', 'Das Handy ist teuer.', 'The phone is expensive.'],
  [null, 'billig', null, 'cheap', 'Adjectives', 'Die Jacke ist billig.', 'The jacket is cheap.'],
  [null, 'richtig', null, 'correct, right', 'Adjectives', 'Die Antwort ist richtig.', 'The answer is correct.'],
  [null, 'falsch', null, 'wrong, false', 'Adjectives', 'Das ist falsch.', 'That is wrong.'],
  [null, 'glücklich', null, 'happy', 'Emotions', 'Ich bin glücklich.', 'I am happy.'],
  [null, 'traurig', null, 'sad', 'Emotions', 'Warum bist du traurig?', 'Why are you sad?'],
  [null, 'müde', null, 'tired', 'Emotions', 'Ich bin müde.', 'I am tired.'],
  [null, 'ja', null, 'yes', 'Basics', 'Ja, gerne.', 'Yes, with pleasure.'],
  [null, 'nein', null, 'no', 'Basics', 'Nein, danke.', 'No, thank you.'],
  [null, 'bitte', null, 'please, you are welcome', 'Basics', 'Ein Kaffee, bitte.', 'A coffee, please.'],
  [null, 'danke', null, 'thank you', 'Basics', 'Danke schön!', 'Thank you very much!'],
  [null, 'hallo', null, 'hello', 'Basics', 'Hallo, wie geht es dir?', 'Hello, how are you?'],
  [null, 'tschüss', null, 'bye', 'Basics', 'Tschüss, bis morgen!', 'Bye, see you tomorrow!'],
  [null, 'wer', null, 'who', 'Question Words', 'Wer ist das?', 'Who is that?'],
  [null, 'was', null, 'what', 'Question Words', 'Was ist das?', 'What is that?'],
  [null, 'wo', null, 'where', 'Question Words', 'Wo wohnst du?', 'Where do you live?'],
  [null, 'wann', null, 'when', 'Question Words', 'Wann kommst du?', 'When are you coming?'],
  [null, 'warum', null, 'why', 'Question Words', 'Warum lernst du Deutsch?', 'Why are you learning German?'],
  [null, 'wie', null, 'how', 'Question Words', 'Wie geht es dir?', 'How are you?'],
  [null, 'wie viel', null, 'how much', 'Question Words', 'Wie viel kostet das?', 'How much does that cost?'],
  [null, 'wie viele', null, 'how many', 'Question Words', 'Wie viele Kinder haben Sie?', 'How many children do you have?'],
  [null, 'auch', null, 'also, too', 'Basics', 'Ich komme auch mit.', 'I am coming too.'],
  [null, 'nicht', null, 'not', 'Basics', 'Das ist nicht mein Buch.', 'That is not my book.'],
  [null, 'kein', null, 'no, not a', 'Basics', 'Ich habe kein Auto.', 'I do not have a car.'],
  [null, 'sehr', null, 'very', 'Basics', 'Das ist sehr gut.', 'That is very good.'],
  [null, 'schon', null, 'already', 'Basics', 'Ich bin schon fertig.', 'I am already done.'],
  [null, 'noch', null, 'still, yet', 'Basics', 'Ich habe noch Hunger.', 'I am still hungry.'],
  [null, 'jetzt', null, 'now', 'Time', 'Jetzt gehe ich.', 'Now I am leaving.'],
  [null, 'heute', null, 'today', 'Time', 'Heute ist Montag.', 'Today is Monday.'],
  [null, 'morgen', null, 'tomorrow', 'Time', 'Morgen habe ich Zeit.', 'Tomorrow I have time.'],
  [null, 'gestern', null, 'yesterday', 'Time', 'Gestern hat es geregnet.', 'Yesterday it rained.'],
  [null, 'immer', null, 'always', 'Time', 'Er kommt immer zu spät.', 'He is always late.'],
  [null, 'oft', null, 'often', 'Time', 'Wir gehen oft ins Kino.', 'We often go to the cinema.'],
  [null, 'manchmal', null, 'sometimes', 'Time', 'Manchmal lese ich.', 'Sometimes I read.'],
  [null, 'nie', null, 'never', 'Time', 'Ich rauche nie.', 'I never smoke.'],
  ['die', 'Stunde', 'Stunden', 'hour', 'Time', 'Ich warte eine Stunde.', 'I am waiting an hour.'],
  ['die', 'Minute', 'Minuten', 'minute', 'Time', 'Noch fünf Minuten!', 'Five more minutes!'],
  ['die', 'Woche', 'Wochen', 'week', 'Time', 'Bis nächste Woche!', 'Until next week!'],
  ['der', 'Monat', 'Monate', 'month', 'Time', 'Im nächsten Monat reise ich.', 'Next month I am traveling.'],
  ['der', 'Morgen', 'Morgen', 'morning', 'Time', 'Guten Morgen!', 'Good morning!'],
  ['der', 'Abend', 'Abende', 'evening', 'Time', 'Guten Abend!', 'Good evening!'],
  ['die', 'Nacht', 'Nächte', 'night', 'Time', 'Gute Nacht!', 'Good night!'],
  ['das', 'Essen', 'Essen', 'food, meal', 'Food', 'Das Essen schmeckt gut.', 'The food tastes good.'],
  ['das', 'Frühstück', 'Frühstücke', 'breakfast', 'Food', 'Das Frühstück ist um acht.', 'Breakfast is at eight.'],
  ['das', 'Brot', 'Brote', 'bread', 'Food', 'Ich kaufe frisches Brot.', 'I am buying fresh bread.'],
  ['das', 'Brötchen', 'Brötchen', 'bread roll', 'Food', 'Ein Brötchen mit Käse, bitte.', 'A roll with cheese, please.'],
  ['die', 'Butter', null, 'butter', 'Food', 'Butter auf das Brot, bitte.', 'Butter on the bread, please.'],
  ['der', 'Käse', 'Käse', 'cheese', 'Food', 'Ich esse gern Käse.', 'I like eating cheese.'],
  ['das', 'Ei', 'Eier', 'egg', 'Food', 'Ich möchte zwei Eier.', 'I would like two eggs.'],
  ['die', 'Milch', null, 'milk', 'Food', 'Trinkst du Milch?', 'Do you drink milk?'],
  ['der', 'Kaffee', 'Kaffees', 'coffee', 'Drinks', 'Ein Kaffee, bitte.', 'A coffee, please.'],
  ['der', 'Tee', 'Tees', 'tea', 'Drinks', 'Ich trinke Tee mit Zucker.', 'I drink tea with sugar.'],
  ['das', 'Wasser', 'Wässer', 'water', 'Drinks', 'Ein Glas Wasser, bitte.', 'A glass of water, please.'],
  ['der', 'Saft', 'Säfte', 'juice', 'Drinks', 'Orangensaft schmeckt gut.', 'Orange juice tastes good.'],
  ['das', 'Bier', 'Biere', 'beer', 'Drinks', 'Ein Bier, bitte.', 'A beer, please.'],
  ['der', 'Wein', 'Weine', 'wine', 'Drinks', 'Rotwein oder Weißwein?', 'Red wine or white wine?'],
  ['das', 'Fleisch', null, 'meat', 'Food', 'Ich esse kein Fleisch.', 'I do not eat meat.'],
  ['der', 'Fisch', 'Fische', 'fish', 'Food', 'Der Fisch ist frisch.', 'The fish is fresh.'],
  ['der', 'Reis', null, 'rice', 'Food', 'Reis mit Gemüse, bitte.', 'Rice with vegetables, please.'],
  ['die', 'Kartoffel', 'Kartoffeln', 'potato', 'Food', 'Ich mag Kartoffeln.', 'I like potatoes.'],
  ['das', 'Gemüse', null, 'vegetables', 'Food', 'Gemüse ist gesund.', 'Vegetables are healthy.'],
  ['der', 'Apfel', 'Äpfel', 'apple', 'Food', 'Der Apfel ist rot.', 'The apple is red.'],
  ['die', 'Banane', 'Bananen', 'banana', 'Food', 'Die Banane ist gelb.', 'The banana is yellow.'],
  ['der', 'Zucker', null, 'sugar', 'Food', 'Zucker im Kaffee?', 'Sugar in the coffee?'],
  ['das', 'Salz', null, 'salt', 'Food', 'Das Salz ist in der Küche.', 'The salt is in the kitchen.'],
  ['der', 'Hunger', null, 'hunger', 'Food', 'Ich habe Hunger.', 'I am hungry.'],
  ['der', 'Durst', null, 'thirst', 'Food', 'Ich habe Durst.', 'I am thirsty.'],
  ['das', 'Haus', 'Häuser', 'house', 'Home', 'Das Haus ist weiß.', 'The house is white.'],
  ['die', 'Wohnung', 'Wohnungen', 'apartment', 'Home', 'Meine Wohnung ist klein.', 'My apartment is small.'],
  ['das', 'Zimmer', 'Zimmer', 'room', 'Home', 'Das Zimmer ist hell.', 'The room is bright.'],
  ['die', 'Küche', 'Küchen', 'kitchen', 'Home', 'Die Küche ist neu.', 'The kitchen is new.'],
  ['das', 'Bad', 'Bäder', 'bathroom', 'Home', 'Wo ist das Bad?', 'Where is the bathroom?'],
  ['die', 'Tür', 'Türen', 'door', 'Home', 'Die Tür ist offen.', 'The door is open.'],
  ['das', 'Fenster', 'Fenster', 'window', 'Home', 'Das Fenster ist zu.', 'The window is closed.'],
  ['der', 'Tisch', 'Tische', 'table', 'Home', 'Das Buch liegt auf dem Tisch.', 'The book is on the table.'],
  ['der', 'Stuhl', 'Stühle', 'chair', 'Home', 'Der Stuhl ist bequem.', 'The chair is comfortable.'],
  ['das', 'Bett', 'Betten', 'bed', 'Home', 'Das Bett ist weich.', 'The bed is soft.'],
  ['der', 'Schlüssel', 'Schlüssel', 'key', 'Home', 'Wo ist mein Schlüssel?', 'Where is my key?'],
  ['die', 'Stadt', 'Städte', 'city', 'City', 'Berlin ist eine große Stadt.', 'Berlin is a big city.'],
  ['die', 'Straße', 'Straßen', 'street', 'City', 'Die Straße ist lang.', 'The street is long.'],
  ['der', 'Bahnhof', 'Bahnhöfe', 'train station', 'Travel', 'Der Zug kommt am Bahnhof an.', 'The train arrives at the station.'],
  ['das', 'Auto', 'Autos', 'car', 'Travel', 'Mein Auto ist rot.', 'My car is red.'],
  ['der', 'Bus', 'Busse', 'bus', 'Travel', 'Der Bus kommt um acht.', 'The bus comes at eight.'],
  ['der', 'Zug', 'Züge', 'train', 'Travel', 'Der Zug ist pünktlich.', 'The train is on time.'],
  ['das', 'Fahrrad', 'Fahrräder', 'bicycle', 'Travel', 'Ich fahre mit dem Fahrrad.', 'I am riding my bicycle.'],
  ['die', 'Fahrkarte', 'Fahrkarten', 'ticket', 'Travel', 'Eine Fahrkarte nach Bonn, bitte.', 'A ticket to Bonn, please.'],
  ['das', 'Geld', 'Gelder', 'money', 'Shopping', 'Ich habe kein Geld dabei.', 'I have no money with me.'],
  ['das', 'Wetter', null, 'weather', 'Weather', 'Wie ist das Wetter?', 'How is the weather?'],
  ['die', 'Sonne', null, 'sun', 'Weather', 'Die Sonne scheint.', 'The sun is shining.'],
  ['der', 'Regen', null, 'rain', 'Weather', 'Der Regen ist kalt.', 'The rain is cold.'],
  [null, 'kalt', null, 'cold', 'Weather', 'Das Wasser ist kalt.', 'The water is cold.'],
  [null, 'warm', null, 'warm', 'Weather', 'Der Tee ist warm.', 'The tea is warm.'],
  ['der', 'Kopf', 'Köpfe', 'head', 'Body', 'Mein Kopf tut weh.', 'My head hurts.'],
  ['die', 'Hand', 'Hände', 'hand', 'Body', 'Meine Hand ist kalt.', 'My hand is cold.'],
  ['der', 'Arzt', 'Ärzte', 'doctor', 'Health', 'Ich gehe zum Arzt.', 'I am going to the doctor.'],
  [null, 'krank', null, 'sick, ill', 'Health', 'Das Kind ist krank.', 'The child is sick.'],
  [null, 'gesund', null, 'healthy', 'Health', 'Sport macht gesund.', 'Exercise keeps you healthy.'],
  ['die', 'Schule', 'Schulen', 'school', 'School', 'Die Schule beginnt um acht.', 'School starts at eight.'],
  ['der', 'Lehrer', 'Lehrer', 'teacher', 'School', 'Der Lehrer ist nett.', 'The teacher is nice.'],
  ['das', 'Buch', 'Bücher', 'book', 'School', 'Ich lese ein Buch.', 'I am reading a book.'],
  ['der', 'Stift', 'Stifte', 'pen', 'School', 'Mein Stift ist blau.', 'My pen is blue.'],
  ['die', 'Arbeit', 'Arbeiten', 'work, job', 'Work', 'Die Arbeit ist schwer.', 'The work is hard.'],
  ['das', 'Büro', 'Büros', 'office', 'Work', 'Er ist im Büro.', 'He is at the office.'],
  ['der', 'Sport', null, 'sport, exercise', 'Fitness', 'Ich mache Sport.', 'I exercise.'],
  ['das', 'Fitnessstudio', 'Fitnessstudios', 'gym', 'Fitness', 'Das Fitnessstudio ist neu.', 'The gym is new.'],
  ['das', 'Training', 'Trainings', 'workout, training', 'Fitness', 'Das Training beginnt um sieben.', 'The workout starts at seven.'],
  ['die', 'Übung', 'Übungen', 'exercise', 'Fitness', 'Diese Übung ist schwer.', 'This exercise is hard.'],
]
