import type { SeedRow } from './types'

/** A2 seed corpus (~150 entries): health, authorities, travel, communication, feelings. */
export const A2_ROWS: SeedRow[] = [
  ['der', 'Termin', 'Termine', 'appointment', 'Health', 'Ich habe einen Termin beim Arzt.', 'I have a doctor appointment.'],
  ['die', 'Apotheke', 'Apotheken', 'pharmacy', 'Health', 'Die Apotheke ist geschlossen.', 'The pharmacy is closed.'],
  ['die', 'Tablette', 'Tabletten', 'pill', 'Health', 'Nimm eine Tablette.', 'Take a pill.'],
  ['der', 'Schmerz', 'Schmerzen', 'pain', 'Health', 'Ich habe Schmerzen.', 'I am in pain.'],
  ['das', 'Krankenhaus', 'Krankenhäuser', 'hospital', 'Health', 'Das Krankenhaus ist dort.', 'The hospital is there.'],
  ['der', 'Zahn', 'Zähne', 'tooth', 'Body', 'Mein Zahn tut weh.', 'My tooth hurts.'],
  ['der', 'Bauch', 'Bäuche', 'belly, stomach', 'Body', 'Mein Bauch tut weh.', 'My stomach hurts.'],
  ['der', 'Rücken', 'Rücken', 'back', 'Body', 'Mein Rücken tut weh.', 'My back hurts.'],
  ['das', 'Auge', 'Augen', 'eye', 'Body', 'Ihre Augen sind braun.', 'Her eyes are brown.'],
  ['das', 'Ohr', 'Ohren', 'ear', 'Body', 'Das Kind hat Ohrenschmerzen.', 'The child has ear pain.'],
  ['die', 'Nase', 'Nasen', 'nose', 'Body', 'Meine Nase ist rot.', 'My nose is red.'],
  ['der', 'Mund', 'Münder', 'mouth', 'Body', 'Öffne den Mund.', 'Open your mouth.'],
  ['das', 'Haar', 'Haare', 'hair', 'Body', 'Sie hat lange Haare.', 'She has long hair.'],
  ['das', 'Bein', 'Beine', 'leg', 'Body', 'Mein Bein tut weh.', 'My leg hurts.'],
  ['der', 'Fuß', 'Füße', 'foot', 'Body', 'Der Fuß ist groß.', 'The foot is big.'],
  ['der', 'Arm', 'Arme', 'arm', 'Body', 'Mein Arm ist verletzt.', 'My arm is injured.'],
  ['die', 'Haut', 'Häute', 'skin', 'Body', 'Die Haut ist trocken.', 'The skin is dry.'],
  ['das', 'Herz', 'Herzen', 'heart', 'Body', 'Mein Herz schlägt schnell.', 'My heart is beating fast.'],
  ['die', 'Kleidung', null, 'clothes', 'Clothing', 'Die Kleidung ist teuer.', 'The clothes are expensive.'],
  ['das', 'Hemd', 'Hemden', 'shirt', 'Clothing', 'Das Hemd ist weiß.', 'The shirt is white.'],
  ['die', 'Hose', 'Hosen', 'pants, trousers', 'Clothing', 'Die Hose ist blau.', 'The pants are blue.'],
  ['das', 'Kleid', 'Kleider', 'dress', 'Clothing', 'Das Kleid ist schön.', 'The dress is beautiful.'],
  ['die', 'Jacke', 'Jacken', 'jacket', 'Clothing', 'Nimm eine Jacke mit.', 'Take a jacket with you.'],
  ['der', 'Mantel', 'Mäntel', 'coat', 'Clothing', 'Der Mantel ist warm.', 'The coat is warm.'],
  ['der', 'Schuh', 'Schuhe', 'shoe', 'Clothing', 'Die Schuhe sind neu.', 'The shoes are new.'],
  ['die', 'Größe', 'Größen', 'size', 'Shopping', 'Welche Größe brauchen Sie?', 'What size do you need?'],
  ['die', 'Farbe', 'Farben', 'color', 'Shopping', 'Meine Lieblingsfarbe ist Blau.', 'My favorite color is blue.'],
  [null, 'rot', null, 'red', 'Colors', 'Das Auto ist rot.', 'The car is red.'],
  [null, 'blau', null, 'blue', 'Colors', 'Der Himmel ist blau.', 'The sky is blue.'],
  [null, 'grün', null, 'green', 'Colors', 'Der Salat ist grün.', 'The salad is green.'],
  [null, 'gelb', null, 'yellow', 'Colors', 'Die Sonne ist gelb.', 'The sun is yellow.'],
  [null, 'schwarz', null, 'black', 'Colors', 'Der Kater ist schwarz.', 'The black cat.'],
  [null, 'weiß', null, 'white', 'Colors', 'Die Wand ist weiß.', 'The wall is white.'],
  [null, 'braun', null, 'brown', 'Colors', 'Der Hund ist braun.', 'The dog is brown.'],
  ['die', 'Anmeldung', 'Anmeldungen', 'registration', 'Authorities', 'Die Anmeldung ist im Bürgeramt.', 'Registration is at the citizens office.'],
  ['das', 'Bürgeramt', 'Bürgerämter', 'citizens registration office', 'Authorities', 'Ich gehe zum Bürgeramt.', 'I am going to the citizens office.'],
  ['das', 'Formular', 'Formulare', 'form', 'Authorities', 'Füllen Sie das Formular aus.', 'Fill out the form.'],
  ['der', 'Ausweis', 'Ausweise', 'ID card', 'Authorities', 'Zeigen Sie Ihren Ausweis.', 'Show your ID.'],
  ['der', 'Pass', 'Pässe', 'passport', 'Authorities', 'Mein Pass ist neu.', 'My passport is new.'],
  ['die', 'Adresse', 'Adressen', 'address', 'Authorities', 'Wie ist Ihre Adresse?', 'What is your address?'],
  ['die', 'Versicherung', 'Versicherungen', 'insurance', 'Authorities', 'Ich brauche eine Versicherung.', 'I need an insurance.'],
  ['die', 'Wohnungssuche', null, 'apartment search', 'Home', 'Die Wohnungssuche ist schwer.', 'The apartment search is hard.'],
  ['die', 'Miete', 'Mieten', 'rent', 'Home', 'Die Miete ist hoch.', 'The rent is high.'],
  ['der', 'Vermieter', 'Vermieter', 'landlord', 'Home', 'Der Vermieter ist freundlich.', 'The landlord is friendly.'],
  ['der', 'Nachbar', 'Nachbarn', 'neighbor', 'People', 'Mein Nachbar ist leise.', 'My neighbor is quiet.'],
  ['die', 'Nachbarin', 'Nachbarinnen', 'neighbor (female)', 'People', 'Die Nachbarin hilft mir.', 'The neighbor helps me.'],
  ['die', 'Reise', 'Reisen', 'trip, journey', 'Travel', 'Die Reise war schön.', 'The trip was nice.'],
  ['der', 'Flughafen', 'Flughäfen', 'airport', 'Travel', 'Der Flughafen ist groß.', 'The airport is big.'],
  ['das', 'Flugzeug', 'Flugzeuge', 'airplane', 'Travel', 'Das Flugzeug fliegt nach Berlin.', 'The plane flies to Berlin.'],
  ['der', 'Koffer', 'Koffer', 'suitcase', 'Travel', 'Mein Koffer ist schwer.', 'My suitcase is heavy.'],
  ['die', 'Landschaft', 'Landschaften', 'landscape', 'Nature', 'Die Landschaft ist schön.', 'The landscape is beautiful.'],
  ['der', 'Wald', 'Wälder', 'forest', 'Nature', 'Der Wald ist dunkel.', 'The forest is dark.'],
  ['der', 'See', 'Seen', 'lake', 'Nature', 'Der See ist kalt.', 'The lake is cold.'],
  ['der', 'Berg', 'Berge', 'mountain', 'Nature', 'Der Berg ist hoch.', 'The mountain is high.'],
  ['das', 'Tier', 'Tiere', 'animal', 'Nature', 'Das Tier ist klein.', 'The animal is small.'],
  ['der', 'Vogel', 'Vögel', 'bird', 'Nature', 'Der Vogel singt.', 'The bird sings.'],
  ['der', 'Hund', 'Hunde', 'dog', 'Animals', 'Der Hund ist freundlich.', 'The dog is friendly.'],
  ['die', 'Katze', 'Katzen', 'cat', 'Animals', 'Die Katze schläft.', 'The cat is sleeping.'],
  ['die', 'U-Bahn', null, 'subway, metro', 'Transport', 'Ich nehme die U-Bahn.', 'I take the subway.'],
  ['die', 'S-Bahn', null, 'suburban train', 'Transport', 'Die S-Bahn kommt spät.', 'The suburban train is late.'],
  ['die', 'Haltestelle', 'Haltestellen', 'stop (bus or tram)', 'Transport', 'Die Haltestelle ist dort.', 'The stop is there.'],
  [null, 'umsteigen', null, 'to change (trains)', 'Verbs', 'Ich muss umsteigen.', 'I have to change trains.'],
  [null, 'einsteigen', null, 'to get on', 'Verbs', 'Steigen Sie bitte ein!', 'Please get on!'],
  [null, 'aussteigen', null, 'to get off', 'Verbs', 'Ich steige hier aus.', 'I am getting off here.'],
  [null, 'mitkommen', null, 'to come along', 'Verbs', 'Kommst du mit?', 'Are you coming along?'],
  [null, 'einkaufen', null, 'to shop', 'Verbs', 'Wir kaufen im Supermarkt ein.', 'We shop at the supermarket.'],
  [null, 'kochen', null, 'to cook', 'Verbs', 'Ich koche Abendessen.', 'I am cooking dinner.'],
  [null, 'aufräumen', null, 'to tidy up', 'Verbs', 'Räum bitte dein Zimmer auf!', 'Please tidy your room!'],
  [null, 'putzen', null, 'to clean', 'Verbs', 'Ich putze die Küche.', 'I am cleaning the kitchen.'],
  [null, 'waschen', null, 'to wash', 'Verbs', 'Ich wasche die Wäsche.', 'I am washing the laundry.'],
  [null, 'anrufen', null, 'to call (phone)', 'Communication', 'Ich rufe dich an.', 'I will call you.'],
  [null, 'anfangen', null, 'to start', 'Verbs', 'Der Film fängt an.', 'The movie is starting.'],
  [null, 'aufhören', null, 'to stop', 'Verbs', 'Hör bitte auf!', 'Please stop!'],
  [null, 'erzählen', null, 'to tell, to narrate', 'Verbs', 'Erzähl mir die Geschichte!', 'Tell me the story!'],
  [null, 'erklären', null, 'to explain', 'Verbs', 'Können Sie das erklären?', 'Can you explain that?'],
  [null, 'zeigen', null, 'to show', 'Verbs', 'Zeig mir das Bild.', 'Show me the picture.'],
  [null, 'brauchen', null, 'to need', 'Verbs', 'Ich brauche Hilfe.', 'I need help.'],
  [null, 'bekommen', null, 'to receive, to get', 'Verbs', 'Ich bekomme einen Brief.', 'I am receiving a letter.'],
  [null, 'besuchen', null, 'to visit', 'Verbs', 'Ich besuche meine Oma.', 'I am visiting my grandma.'],
  [null, 'treffen', null, 'to meet', 'Verbs', 'Wir treffen uns um acht.', 'We are meeting at eight.'],
  [null, 'vergessen', null, 'to forget', 'Verbs', 'Ich habe es vergessen.', 'I forgot it.'],
  [null, 'erinnern', null, 'to remember', 'Verbs', 'Ich erinnere mich.', 'I remember.'],
  [null, 'wünschen', null, 'to wish', 'Verbs', 'Was wünschst du dir?', 'What do you wish for?'],
  [null, 'gefallen', null, 'to please, to like', 'Verbs', 'Das gefällt mir.', 'I like that.'],
  [null, 'schmecken', null, 'to taste', 'Verbs', 'Das schmeckt lecker.', 'That tastes delicious.'],
  ['die', 'Nachricht', 'Nachrichten', 'message', 'Communication', 'Ich schicke eine Nachricht.', 'I am sending a message.'],
  ['das', 'Handy', 'Handys', 'cell phone', 'Technology', 'Mein Handy ist kaputt.', 'My phone is broken.'],
  ['der', 'Computer', 'Computer', 'computer', 'Technology', 'Der Computer ist langsam.', 'The computer is slow.'],
  ['die', 'E-Mail', 'E-Mails', 'email', 'Communication', 'Ich schreibe eine E-Mail.', 'I am writing an email.'],
  ['die', 'Nummer', 'Nummern', 'number', 'Communication', 'Wie ist deine Nummer?', 'What is your number?'],
  ['die', 'Freude', null, 'joy', 'Emotions', 'Das macht mir Freude.', 'That brings me joy.'],
  ['die', 'Angst', 'Ängste', 'fear', 'Emotions', 'Ich habe Angst vor Hunden.', 'I am afraid of dogs.'],
  ['die', 'Liebe', null, 'love', 'Emotions', 'Liebe ist wichtig.', 'Love is important.'],
  ['die', 'Hoffnung', null, 'hope', 'Emotions', 'Ich habe Hoffnung.', 'I have hope.'],
  [null, 'wütend', null, 'angry', 'Emotions', 'Warum bist du wütend?', 'Why are you angry?'],
  [null, 'aufgeregt', null, 'excited', 'Emotions', 'Ich bin aufgeregt.', 'I am excited.'],
  [null, 'ruhig', null, 'calm, quiet', 'Emotions', 'Bleib ruhig.', 'Stay calm.'],
  [null, 'stolz', null, 'proud', 'Emotions', 'Ich bin stolz auf dich.', 'I am proud of you.'],
  [null, 'nervös', null, 'nervous', 'Emotions', 'Ich bin nervös.', 'I am nervous.'],
  ['der', 'Feiertag', 'Feiertage', 'public holiday', 'Time', 'Montag ist ein Feiertag.', 'Monday is a holiday.'],
  ['der', 'Urlaub', 'Urlaube', 'vacation', 'Travel', 'Ich habe Urlaub im Juli.', 'I have vacation in July.'],
  ['die', 'Party', 'Partys', 'party', 'Free Time', 'Die Party beginnt um acht.', 'The party starts at eight.'],
  ['das', 'Konzert', 'Konzerte', 'concert', 'Free Time', 'Das Konzert war toll.', 'The concert was great.'],
  ['der', 'Film', 'Filme', 'movie', 'Free Time', 'Der Film ist spannend.', 'The movie is exciting.'],
  ['die', 'Musik', null, 'music', 'Free Time', 'Ich höre gern Musik.', 'I like listening to music.'],
  ['das', 'Lied', 'Lieder', 'song', 'Free Time', 'Das Lied ist schön.', 'The song is beautiful.'],
  ['der', 'Witz', 'Witze', 'joke', 'Free Time', 'Er erzählt einen Witz.', 'He is telling a joke.'],
  ['die', 'Bibliothek', 'Bibliotheken', 'library', 'School', 'Die Bibliothek ist still.', 'The library is quiet.'],
  ['die', 'Prüfung', 'Prüfungen', 'exam', 'School', 'Die Prüfung ist schwer.', 'The exam is hard.'],
  ['die', 'Note', 'Noten', 'grade, mark', 'School', 'Ich habe eine gute Note.', 'I have a good grade.'],
  ['die', 'Hausaufgaben', null, 'homework', 'School', 'Die Hausaufgaben sind fertig.', 'The homework is done.'],
  ['die', 'Meinung', 'Meinungen', 'opinion', 'Communication', 'Meine Meinung ist anders.', 'My opinion is different.'],
  [null, 'vielleicht', null, 'maybe', 'Basics', 'Vielleicht kommt er später.', 'Maybe he will come later.'],
  [null, 'wahrscheinlich', null, 'probably', 'Basics', 'Es regnet wahrscheinlich.', 'It is probably raining.'],
  [null, 'natürlich', null, 'of course', 'Basics', 'Natürlich helfe ich.', 'Of course I will help.'],
  [null, 'zum Beispiel', null, 'for example', 'Basics', 'Zum Beispiel: Montag.', 'For example: Monday.'],
  [null, 'zusammen', null, 'together', 'Basics', 'Wir gehen zusammen.', 'We are going together.'],
  [null, 'allein', null, 'alone', 'Basics', 'Ich wohne allein.', 'I live alone.'],
  [null, 'wirklich', null, 'really', 'Basics', 'Das ist wirklich teuer.', 'That is really expensive.'],
  [null, 'leider', null, 'unfortunately', 'Basics', 'Leider habe ich keine Zeit.', 'Unfortunately I have no time.'],
  [null, 'endlich', null, 'finally', 'Basics', 'Endlich ist Wochenende!', 'Finally it is the weekend!'],
  [null, 'fast', null, 'almost', 'Basics', 'Ich bin fast fertig.', 'I am almost done.'],
  [null, 'gar nicht', null, 'not at all', 'Basics', 'Das gefällt mir gar nicht.', 'I do not like that at all.'],
  ['der', 'Grund', 'Gründe', 'reason', 'Communication', 'Der Grund ist einfach.', 'The reason is simple.'],
  ['die', 'Frage', 'Fragen', 'question', 'Communication', 'Hast du eine Frage?', 'Do you have a question?'],
  ['die', 'Antwort', 'Antworten', 'answer', 'Communication', 'Die Antwort ist richtig.', 'The answer is correct.'],
  ['das', 'Problem', 'Probleme', 'problem', 'Communication', 'Das Problem ist groß.', 'The problem is big.'],
  ['die', 'Lösung', 'Lösungen', 'solution', 'Communication', 'Wir finden eine Lösung.', 'We will find a solution.'],
  ['das', 'Beispiel', 'Beispiele', 'example', 'Communication', 'Ein Beispiel, bitte.', 'An example, please.'],
  ['die', 'Wahrheit', 'Wahrheiten', 'truth', 'Communication', 'Sag die Wahrheit!', 'Tell the truth!'],
  ['der', 'Laden', 'Läden', 'shop', 'Shopping', 'Der Laden ist offen.', 'The shop is open.'],
  ['der', 'Markt', 'Märkte', 'market', 'Shopping', 'Der Markt ist am Sonntag zu.', 'The market is closed on Sundays.'],
  ['die', 'Kasse', 'Kassen', 'checkout, cash desk', 'Shopping', 'Bitte zahlen Sie an der Kasse.', 'Please pay at the checkout.'],
  ['der', 'Preis', 'Preise', 'price', 'Shopping', 'Der Preis ist hoch.', 'The price is high.'],
  ['das', 'Angebot', 'Angebote', 'offer, special', 'Shopping', 'Das Angebot gilt heute.', 'The offer is valid today.'],
  ['die', 'Rechnung', 'Rechnungen', 'bill, invoice', 'Shopping', 'Die Rechnung, bitte.', 'The bill, please.'],
  ['der', 'Euro', null, 'euro', 'Shopping', 'Das kostet zehn Euro.', 'That costs ten euros.'],
  [null, 'kosten', null, 'to cost', 'Verbs', 'Wie viel kostet das?', 'How much does that cost?'],
  [null, 'bezahlen', null, 'to pay', 'Verbs', 'Ich bezahle mit Karte.', 'I am paying by card.'],
  ['die', 'Karte', 'Karten', 'card, map', 'Shopping', 'Ich zahle mit der Karte.', 'I pay with the card.'],
  [null, 'gefährlich', null, 'dangerous', 'Adjectives', 'Die Straße ist gefährlich.', 'The street is dangerous.'],
  [null, 'wichtig', null, 'important', 'Adjectives', 'Das ist wichtig.', 'That is important.'],
  [null, 'interessant', null, 'interesting', 'Adjectives', 'Der Film ist interessant.', 'The movie is interesting.'],
  [null, 'langweilig', null, 'boring', 'Adjectives', 'Das Buch ist langweilig.', 'The book is boring.'],
  [null, 'spannend', null, 'exciting', 'Adjectives', 'Die Geschichte ist spannend.', 'The story is exciting.'],
  [null, 'schwierig', null, 'difficult', 'Adjectives', 'Die Prüfung ist schwierig.', 'The exam is difficult.'],
  [null, 'einfach', null, 'simple, easy', 'Adjectives', 'Das ist einfach.', 'That is easy.'],
  [null, 'anders', null, 'different', 'Adjectives', 'Ich denke anders.', 'I think differently.'],
  [null, 'gleich', null, 'same, equal', 'Adjectives', 'Wir haben das gleiche Auto.', 'We have the same car.'],
  [null, 'möglich', null, 'possible', 'Adjectives', 'Ist das möglich?', 'Is that possible?'],
]
