import type { SeedRow } from './types'

/** A2 seed corpus (345 entries = original 150 + extension): health, authorities, travel, communication, feelings, seasons, family. */
export const A2_ROWS: SeedRow[] = [
  ['der', 'Termin', 'Termine', 'appointment', 'Health', 'Ich habe einen Termin beim Arzt.', 'I have a doctor appointment.'],
  ['die', 'Apotheke', 'Apotheken', 'pharmacy', 'Health', 'Die Apotheke ist geschlossen.', 'The pharmacy is closed.'],
  ['die', 'Tablette', 'Tabletten', 'pill', 'Health', 'Nimm eine Tablette.', 'Take a pill.'],
  ['der', 'Schmerz', 'Schmerzen', 'pain', 'Health', 'Ich habe Schmerzen.', 'I am in pain.'],
  ['das', 'Krankenhaus', 'Krankenhäuser', 'hospital', 'Health', 'Das Krankenhaus ist dort.', 'The hospital is there.'],
  ['der', 'Zahn', 'Zähne', 'tooth', 'Body', 'Mein Zahn tut weh.', 'My tooth hurts.'],
  ['der', 'Bauch', 'Bäuche', 'belly, stomach', 'Body', 'Mein Bauch tut weh.', 'My stomach hurts.'],
  ['der', 'Rücken', 'Rücken', 'back', 'Body', 'Mein Rücken tut weh.', 'My back hurts.'],
  ['das', 'Auge', 'Augen', 'eye', 'Body', 'Ihre Augen sind braun.', 'Her eyes are brown.'],
  ['das', 'Ohr', 'Ohren', 'ear', 'Body', 'Das Kind hat Ohrenschmerzen.', 'The child has ear pain.'],
  ['die', 'Nase', 'Nasen', 'nose', 'Body', 'Meine Nase ist rot.', 'My nose is red.'],
  ['der', 'Mund', 'Münder', 'mouth', 'Body', 'Öffne den Mund.', 'Open your mouth.'],
  ['das', 'Haar', 'Haare', 'hair', 'Body', 'Sie hat lange Haare.', 'She has long hair.'],
  ['das', 'Bein', 'Beine', 'leg', 'Body', 'Mein Bein tut weh.', 'My leg hurts.'],
  ['der', 'Fuß', 'Füße', 'foot', 'Body', 'Der Fuß ist groß.', 'The foot is big.'],
  ['der', 'Arm', 'Arme', 'arm', 'Body', 'Mein Arm ist verletzt.', 'My arm is injured.'],
  ['die', 'Haut', 'Häute', 'skin', 'Body', 'Die Haut ist trocken.', 'The skin is dry.'],
  ['das', 'Herz', 'Herzen', 'heart', 'Body', 'Mein Herz schlägt schnell.', 'My heart is beating fast.'],
  ['die', 'Kleidung', null, 'clothes', 'Clothing', 'Die Kleidung ist teuer.', 'The clothes are expensive.'],
  ['das', 'Hemd', 'Hemden', 'shirt', 'Clothing', 'Das Hemd ist weiß.', 'The shirt is white.'],
  ['die', 'Hose', 'Hosen', 'pants, trousers', 'Clothing', 'Die Hose ist blau.', 'The pants are blue.'],
  ['das', 'Kleid', 'Kleider', 'dress', 'Clothing', 'Das Kleid ist schön.', 'The dress is beautiful.'],
  ['die', 'Jacke', 'Jacken', 'jacket', 'Clothing', 'Nimm eine Jacke mit.', 'Take a jacket with you.'],
  ['der', 'Mantel', 'Mäntel', 'coat', 'Clothing', 'Der Mantel ist warm.', 'The coat is warm.'],
  ['der', 'Schuh', 'Schuhe', 'shoe', 'Clothing', 'Die Schuhe sind neu.', 'The shoes are new.'],
  ['die', 'Größe', 'Größen', 'size', 'Shopping', 'Welche Größe brauchen Sie?', 'What size do you need?'],
  ['die', 'Farbe', 'Farben', 'color', 'Shopping', 'Meine Lieblingsfarbe ist Blau.', 'My favorite color is blue.'],
  [null, 'rot', null, 'red', 'Colors', 'Das Auto ist rot.', 'The car is red.'],
  [null, 'blau', null, 'blue', 'Colors', 'Der Himmel ist blau.', 'The sky is blue.'],
  [null, 'grün', null, 'green', 'Colors', 'Der Salat ist grün.', 'The salad is green.'],
  [null, 'gelb', null, 'yellow', 'Colors', 'Die Sonne ist gelb.', 'The sun is yellow.'],
  [null, 'schwarz', null, 'black', 'Colors', 'Der Kater ist schwarz.', 'The black cat.'],
  [null, 'weiß', null, 'white', 'Colors', 'Die Wand ist weiß.', 'The wall is white.'],
  [null, 'braun', null, 'brown', 'Colors', 'Der Hund ist braun.', 'The dog is brown.'],
  ['die', 'Anmeldung', 'Anmeldungen', 'registration', 'Authorities', 'Die Anmeldung ist im Bürgeramt.', 'Registration is at the citizens office.'],
  ['das', 'Bürgeramt', 'Bürgerämter', 'citizens registration office', 'Authorities', 'Ich gehe zum Bürgeramt.', 'I am going to the citizens office.'],
  ['das', 'Formular', 'Formulare', 'form', 'Authorities', 'Füllen Sie das Formular aus.', 'Fill out the form.'],
  ['der', 'Ausweis', 'Ausweise', 'ID card', 'Authorities', 'Zeigen Sie Ihren Ausweis.', 'Show your ID.'],
  ['der', 'Pass', 'Pässe', 'passport', 'Authorities', 'Mein Pass ist neu.', 'My passport is new.'],
  ['die', 'Adresse', 'Adressen', 'address', 'Authorities', 'Wie ist Ihre Adresse?', 'What is your address?'],
  ['die', 'Versicherung', 'Versicherungen', 'insurance', 'Authorities', 'Ich brauche eine Versicherung.', 'I need an insurance.'],
  ['die', 'Wohnungssuche', null, 'apartment search', 'Home', 'Die Wohnungssuche ist schwer.', 'The apartment search is hard.'],
  ['die', 'Miete', 'Mieten', 'rent', 'Home', 'Die Miete ist hoch.', 'The rent is high.'],
  ['der', 'Vermieter', 'Vermieter', 'landlord', 'Home', 'Der Vermieter ist freundlich.', 'The landlord is friendly.'],
  ['der', 'Nachbar', 'Nachbarn', 'neighbor', 'People', 'Mein Nachbar ist leise.', 'My neighbor is quiet.'],
  ['die', 'Nachbarin', 'Nachbarinnen', 'neighbor (female)', 'People', 'Die Nachbarin hilft mir.', 'The neighbor helps me.'],
  ['die', 'Reise', 'Reisen', 'trip, journey', 'Travel', 'Die Reise war schön.', 'The trip was nice.'],
  ['der', 'Flughafen', 'Flughäfen', 'airport', 'Travel', 'Der Flughafen ist groß.', 'The airport is big.'],
  ['das', 'Flugzeug', 'Flugzeuge', 'airplane', 'Travel', 'Das Flugzeug fliegt nach Berlin.', 'The plane flies to Berlin.'],
  ['der', 'Koffer', 'Koffer', 'suitcase', 'Travel', 'Mein Koffer ist schwer.', 'My suitcase is heavy.'],
  ['die', 'Landschaft', 'Landschaften', 'landscape', 'Nature', 'Die Landschaft ist schön.', 'The landscape is beautiful.'],
  ['der', 'Wald', 'Wälder', 'forest', 'Nature', 'Der Wald ist dunkel.', 'The forest is dark.'],
  ['der', 'See', 'Seen', 'lake', 'Nature', 'Der See ist kalt.', 'The lake is cold.'],
  ['der', 'Berg', 'Berge', 'mountain', 'Nature', 'Der Berg ist hoch.', 'The mountain is high.'],
  ['das', 'Tier', 'Tiere', 'animal', 'Nature', 'Das Tier ist klein.', 'The animal is small.'],
  ['der', 'Vogel', 'Vögel', 'bird', 'Nature', 'Der Vogel singt.', 'The bird sings.'],
  ['der', 'Hund', 'Hunde', 'dog', 'Animals', 'Der Hund ist freundlich.', 'The dog is friendly.'],
  ['die', 'Katze', 'Katzen', 'cat', 'Animals', 'Die Katze schläft.', 'The cat is sleeping.'],
  ['die', 'U-Bahn', null, 'subway, metro', 'Transport', 'Ich nehme die U-Bahn.', 'I take the subway.'],
  ['die', 'S-Bahn', null, 'suburban train', 'Transport', 'Die S-Bahn kommt spät.', 'The suburban train is late.'],
  ['die', 'Haltestelle', 'Haltestellen', 'stop (bus or tram)', 'Transport', 'Die Haltestelle ist dort.', 'The stop is there.'],
  [null, 'umsteigen', null, 'to change (trains)', 'Verbs', 'Ich muss umsteigen.', 'I have to change trains.'],
  [null, 'einsteigen', null, 'to get on', 'Verbs', 'Steigen Sie bitte ein!', 'Please get on!'],
  [null, 'aussteigen', null, 'to get off', 'Verbs', 'Ich steige hier aus.', 'I am getting off here.'],
  [null, 'mitkommen', null, 'to come along', 'Verbs', 'Kommst du mit?', 'Are you coming along?'],
  [null, 'einkaufen', null, 'to shop', 'Verbs', 'Wir kaufen im Supermarkt ein.', 'We shop at the supermarket.'],
  [null, 'kochen', null, 'to cook', 'Verbs', 'Ich koche Abendessen.', 'I am cooking dinner.'],
  [null, 'aufräumen', null, 'to tidy up', 'Verbs', 'Räum bitte dein Zimmer auf!', 'Please tidy your room!'],
  [null, 'putzen', null, 'to clean', 'Verbs', 'Ich putze die Küche.', 'I am cleaning the kitchen.'],
  [null, 'waschen', null, 'to wash', 'Verbs', 'Ich wasche die Wäsche.', 'I am washing the laundry.'],
  [null, 'anrufen', null, 'to call (phone)', 'Communication', 'Ich rufe dich an.', 'I will call you.'],
  [null, 'anfangen', null, 'to start', 'Verbs', 'Der Film fängt an.', 'The movie is starting.'],
  [null, 'aufhören', null, 'to stop', 'Verbs', 'Hör bitte auf!', 'Please stop!'],
  [null, 'erzählen', null, 'to tell, to narrate', 'Verbs', 'Erzähl mir die Geschichte!', 'Tell me the story!'],
  [null, 'erklären', null, 'to explain', 'Verbs', 'Können Sie das erklären?', 'Can you explain that?'],
  [null, 'zeigen', null, 'to show', 'Verbs', 'Zeig mir das Bild.', 'Show me the picture.'],
  [null, 'brauchen', null, 'to need', 'Verbs', 'Ich brauche Hilfe.', 'I need help.'],
  [null, 'bekommen', null, 'to receive, to get', 'Verbs', 'Ich bekomme einen Brief.', 'I am receiving a letter.'],
  [null, 'besuchen', null, 'to visit', 'Verbs', 'Ich besuche meine Oma.', 'I am visiting my grandma.'],
  [null, 'treffen', null, 'to meet', 'Verbs', 'Wir treffen uns um acht.', 'We are meeting at eight.'],
  [null, 'vergessen', null, 'to forget', 'Verbs', 'Ich habe es vergessen.', 'I forgot it.'],
  [null, 'erinnern', null, 'to remember', 'Verbs', 'Ich erinnere mich.', 'I remember.'],
  [null, 'wünschen', null, 'to wish', 'Verbs', 'Was wünschst du dir?', 'What do you wish for?'],
  [null, 'gefallen', null, 'to please, to like', 'Verbs', 'Das gefällt mir.', 'I like that.'],
  [null, 'schmecken', null, 'to taste', 'Verbs', 'Das schmeckt lecker.', 'That tastes delicious.'],
  ['die', 'Nachricht', 'Nachrichten', 'message', 'Communication', 'Ich schicke eine Nachricht.', 'I am sending a message.'],
  ['das', 'Handy', 'Handys', 'cell phone', 'Technology', 'Mein Handy ist kaputt.', 'My phone is broken.'],
  ['der', 'Computer', 'Computer', 'computer', 'Technology', 'Der Computer ist langsam.', 'The computer is slow.'],
  ['die', 'E-Mail', 'E-Mails', 'email', 'Communication', 'Ich schreibe eine E-Mail.', 'I am writing an email.'],
  ['die', 'Nummer', 'Nummern', 'number', 'Communication', 'Wie ist deine Nummer?', 'What is your number?'],
  ['die', 'Freude', null, 'joy', 'Emotions', 'Das macht mir Freude.', 'That brings me joy.'],
  ['die', 'Angst', 'Ängste', 'fear', 'Emotions', 'Ich habe Angst vor Hunden.', 'I am afraid of dogs.'],
  ['die', 'Liebe', null, 'love', 'Emotions', 'Liebe ist wichtig.', 'Love is important.'],
  ['die', 'Hoffnung', null, 'hope', 'Emotions', 'Ich habe Hoffnung.', 'I have hope.'],
  [null, 'wütend', null, 'angry', 'Emotions', 'Warum bist du wütend?', 'Why are you angry?'],
  [null, 'aufgeregt', null, 'excited', 'Emotions', 'Ich bin aufgeregt.', 'I am excited.'],
  [null, 'ruhig', null, 'calm, quiet', 'Emotions', 'Bleib ruhig.', 'Stay calm.'],
  [null, 'stolz', null, 'proud', 'Emotions', 'Ich bin stolz auf dich.', 'I am proud of you.'],
  [null, 'nervös', null, 'nervous', 'Emotions', 'Ich bin nervös.', 'I am nervous.'],
  ['der', 'Feiertag', 'Feiertage', 'public holiday', 'Time', 'Montag ist ein Feiertag.', 'Monday is a holiday.'],
  ['der', 'Urlaub', 'Urlaube', 'vacation', 'Travel', 'Ich habe Urlaub im Juli.', 'I have vacation in July.'],
  ['die', 'Party', 'Partys', 'party', 'Free Time', 'Die Party beginnt um acht.', 'The party starts at eight.'],
  ['das', 'Konzert', 'Konzerte', 'concert', 'Free Time', 'Das Konzert war toll.', 'The concert was great.'],
  ['der', 'Film', 'Filme', 'movie', 'Free Time', 'Der Film ist spannend.', 'The movie is exciting.'],
  ['die', 'Musik', null, 'music', 'Free Time', 'Ich höre gern Musik.', 'I like listening to music.'],
  ['das', 'Lied', 'Lieder', 'song', 'Free Time', 'Das Lied ist schön.', 'The song is beautiful.'],
  ['der', 'Witz', 'Witze', 'joke', 'Free Time', 'Er erzählt einen Witz.', 'He is telling a joke.'],
  ['die', 'Bibliothek', 'Bibliotheken', 'library', 'School', 'Die Bibliothek ist still.', 'The library is quiet.'],
  ['die', 'Prüfung', 'Prüfungen', 'exam', 'School', 'Die Prüfung ist schwer.', 'The exam is hard.'],
  ['die', 'Note', 'Noten', 'grade, mark', 'School', 'Ich habe eine gute Note.', 'I have a good grade.'],
  ['die', 'Hausaufgaben', null, 'homework', 'School', 'Die Hausaufgaben sind fertig.', 'The homework is done.'],
  ['die', 'Meinung', 'Meinungen', 'opinion', 'Communication', 'Meine Meinung ist anders.', 'My opinion is different.'],
  [null, 'vielleicht', null, 'maybe', 'Basics', 'Vielleicht kommt er später.', 'Maybe he will come later.'],
  [null, 'wahrscheinlich', null, 'probably', 'Basics', 'Es regnet wahrscheinlich.', 'It is probably raining.'],
  [null, 'natürlich', null, 'of course', 'Basics', 'Natürlich helfe ich.', 'Of course I will help.'],
  [null, 'zum Beispiel', null, 'for example', 'Basics', 'Zum Beispiel: Montag.', 'For example: Monday.'],
  [null, 'zusammen', null, 'together', 'Basics', 'Wir gehen zusammen.', 'We are going together.'],
  [null, 'allein', null, 'alone', 'Basics', 'Ich wohne allein.', 'I live alone.'],
  [null, 'wirklich', null, 'really', 'Basics', 'Das ist wirklich teuer.', 'That is really expensive.'],
  [null, 'leider', null, 'unfortunately', 'Basics', 'Leider habe ich keine Zeit.', 'Unfortunately I have no time.'],
  [null, 'endlich', null, 'finally', 'Basics', 'Endlich ist Wochenende!', 'Finally it is the weekend!'],
  [null, 'fast', null, 'almost', 'Basics', 'Ich bin fast fertig.', 'I am almost done.'],
  [null, 'gar nicht', null, 'not at all', 'Basics', 'Das gefällt mir gar nicht.', 'I do not like that at all.'],
  ['der', 'Grund', 'Gründe', 'reason', 'Communication', 'Der Grund ist einfach.', 'The reason is simple.'],
  ['die', 'Frage', 'Fragen', 'question', 'Communication', 'Hast du eine Frage?', 'Do you have a question?'],
  ['die', 'Antwort', 'Antworten', 'answer', 'Communication', 'Die Antwort ist richtig.', 'The answer is correct.'],
  ['das', 'Problem', 'Probleme', 'problem', 'Communication', 'Das Problem ist groß.', 'The problem is big.'],
  ['die', 'Lösung', 'Lösungen', 'solution', 'Communication', 'Wir finden eine Lösung.', 'We will find a solution.'],
  ['das', 'Beispiel', 'Beispiele', 'example', 'Communication', 'Ein Beispiel, bitte.', 'An example, please.'],
  ['die', 'Wahrheit', 'Wahrheiten', 'truth', 'Communication', 'Sag die Wahrheit!', 'Tell the truth!'],
  ['der', 'Laden', 'Läden', 'shop', 'Shopping', 'Der Laden ist offen.', 'The shop is open.'],
  ['der', 'Markt', 'Märkte', 'market', 'Shopping', 'Der Markt ist am Sonntag zu.', 'The market is closed on Sundays.'],
  ['die', 'Kasse', 'Kassen', 'checkout, cash desk', 'Shopping', 'Bitte zahlen Sie an der Kasse.', 'Please pay at the checkout.'],
  ['der', 'Preis', 'Preise', 'price', 'Shopping', 'Der Preis ist hoch.', 'The price is high.'],
  ['das', 'Angebot', 'Angebote', 'offer, special', 'Shopping', 'Das Angebot gilt heute.', 'The offer is valid today.'],
  ['die', 'Rechnung', 'Rechnungen', 'bill, invoice', 'Shopping', 'Die Rechnung, bitte.', 'The bill, please.'],
  ['der', 'Euro', null, 'euro', 'Shopping', 'Das kostet zehn Euro.', 'That costs ten euros.'],
  [null, 'kosten', null, 'to cost', 'Verbs', 'Wie viel kostet das?', 'How much does that cost?'],
  [null, 'bezahlen', null, 'to pay', 'Verbs', 'Ich bezahle mit Karte.', 'I am paying by card.'],
  ['die', 'Karte', 'Karten', 'card, map', 'Shopping', 'Ich zahle mit der Karte.', 'I pay with the card.'],
  [null, 'gefährlich', null, 'dangerous', 'Adjectives', 'Die Straße ist gefährlich.', 'The street is dangerous.'],
  [null, 'wichtig', null, 'important', 'Adjectives', 'Das ist wichtig.', 'That is important.'],
  [null, 'interessant', null, 'interesting', 'Adjectives', 'Der Film ist interessant.', 'The movie is interesting.'],
  [null, 'langweilig', null, 'boring', 'Adjectives', 'Das Buch ist langweilig.', 'The book is boring.'],
  [null, 'spannend', null, 'exciting', 'Adjectives', 'Die Geschichte ist spannend.', 'The story is exciting.'],
  [null, 'schwierig', null, 'difficult', 'Adjectives', 'Die Prüfung ist schwierig.', 'The exam is difficult.'],
  [null, 'einfach', null, 'simple, easy', 'Adjectives', 'Das ist einfach.', 'That is easy.'],
  [null, 'anders', null, 'different', 'Adjectives', 'Ich denke anders.', 'I think differently.'],
  [null, 'gleich', null, 'same, equal', 'Adjectives', 'Wir haben das gleiche Auto.', 'We have the same car.'],
  [null, 'möglich', null, 'possible', 'Adjectives', 'Ist das möglich?', 'Is that possible?'],
  // ── A2 extension: health, body & treatment ──
  ['das', 'Medikament', 'Medikamente', 'medicine, medication', 'Health', 'Das Medikament hilft schnell.', 'The medicine helps quickly.'],
  ['die', 'Krankheit', 'Krankheiten', 'illness, disease', 'Health', 'Die Krankheit ist nicht schlimm.', 'The illness is not serious.'],
  ['der', 'Unfall', 'Unfälle', 'accident', 'Health', 'Der Unfall war gestern.', 'The accident was yesterday.'],
  ['die', 'Erkältung', 'Erkältungen', 'cold (illness)', 'Health', 'Ich habe eine Erkältung.', 'I have a cold.'],
  ['das', 'Fieber', null, 'fever', 'Health', 'Das Kind hat Fieber.', 'The child has a fever.'],
  ['die', 'Untersuchung', 'Untersuchungen', 'examination, check-up', 'Health', 'Die Untersuchung dauert kurz.', 'The examination is quick.'],
  ['die', 'Krankenkasse', 'Krankenkassen', 'health insurance fund', 'Health', 'Meine Krankenkasse zahlt das.', 'My health insurance pays for that.'],
  ['der', 'Notfall', 'Notfälle', 'emergency', 'Health', 'Im Notfall ruf die 112.', 'In an emergency call 112.'],
  ['die', 'Verletzung', 'Verletzungen', 'injury', 'Health', 'Die Verletzung ist klein.', 'The injury is small.'],
  [null, 'heilen', null, 'to heal', 'Health', 'Die Wunde heilt schnell.', 'The wound heals quickly.'],
  [null, 'bluten', null, 'to bleed', 'Health', 'Der Finger blutet.', 'The finger is bleeding.'],
  [null, 'husten', null, 'to cough', 'Health', 'Der Patient hustet viel.', 'The patient coughs a lot.'],
  ['das', 'Pflaster', 'Pflaster', 'band-aid, plaster', 'Health', 'Ich brauche ein Pflaster.', 'I need a band-aid.'],
  ['die', 'Salbe', 'Salben', 'ointment', 'Health', 'Die Salbe hilft der Haut.', 'The ointment helps the skin.'],
  ['die', 'Creme', 'Cremes', 'cream', 'Health', 'Die Creme riecht gut.', 'The cream smells good.'],
  // ── authorities & paperwork ──
  ['das', 'Amt', 'Ämter', 'office, authority', 'Authorities', 'Das Amt öffnet um acht.', 'The office opens at eight.'],
  ['die', 'Behörde', 'Behörden', 'authority, agency', 'Authorities', 'Die Behörde ist zuständig.', 'The authority is responsible.'],
  ['der', 'Antrag', 'Anträge', 'application, request', 'Authorities', 'Der Antrag ist fast fertig.', 'The application is almost done.'],
  ['die', 'Unterschrift', 'Unterschriften', 'signature', 'Authorities', 'Ihre Unterschrift fehlt hier.', 'Your signature is missing here.'],
  ['die', 'Bescheinigung', 'Bescheinigungen', 'certificate, proof', 'Authorities', 'Die Bescheinigung ist wichtig.', 'The certificate is important.'],
  ['die', 'Steuer', 'Steuern', 'tax', 'Authorities', 'Die Steuer ist hoch.', 'The tax is high.'],
  ['der', 'Briefkasten', 'Briefkästen', 'mailbox', 'Authorities', 'Der Briefkasten ist leer.', 'The mailbox is empty.'],
  ['das', 'Paket', 'Pakete', 'package', 'Authorities', 'Das Paket kommt morgen.', 'The package arrives tomorrow.'],
  ['die', 'Gebühr', 'Gebühren', 'fee', 'Authorities', 'Die Gebühr ist klein.', 'The fee is small.'],
  ['der', 'Führerschein', 'Führerscheine', "driver's license", 'Authorities', 'Mein Führerschein ist neu.', "My driver's license is new."],
  ['die', 'Öffnungszeiten', null, 'opening hours', 'Authorities', 'Die Öffnungszeiten stehen online.', 'The opening hours are online.'],
  ['die', 'Verlängerung', 'Verlängerungen', 'extension, renewal', 'Authorities', 'Die Verlängerung dauert zwei Wochen.', 'The renewal takes two weeks.'],
  // ── work ──
  ['der', 'Chef', 'Chefs', 'boss', 'Work', 'Mein Chef ist freundlich.', 'My boss is friendly.'],
  ['die', 'Chefin', 'Chefinnen', 'boss (female)', 'Work', 'Die Chefin hilft mir.', 'The boss helps me.'],
  ['der', 'Mitarbeiter', 'Mitarbeiter', 'employee, coworker', 'Work', 'Der Mitarbeiter arbeitet viel.', 'The employee works a lot.'],
  ['der', 'Kunde', 'Kunden', 'customer', 'Work', 'Der Kunde wartet.', 'The customer is waiting.'],
  ['die', 'Kundin', 'Kundinnen', 'customer (female)', 'Work', 'Die Kundin ist zufrieden.', 'The customer is satisfied.'],
  ['der', 'Vertrag', 'Verträge', 'contract', 'Work', 'Der Vertrag ist unterschrieben.', 'The contract is signed.'],
  ['die', 'Pause', 'Pausen', 'break', 'Work', 'Die Pause ist um zehn.', 'The break is at ten.'],
  ['der', 'Feierabend', null, 'end of the workday', 'Work', 'Um fünf ist Feierabend.', 'At five the workday is over.'],
  ['die', 'Arbeitszeit', 'Arbeitszeiten', 'working hours', 'Work', 'Meine Arbeitszeit ist kurz.', 'My working hours are short.'],
  // ── travel & transport ──
  ['die', 'Fahrt', 'Fahrten', 'ride, trip', 'Travel', 'Die Fahrt dauert zwei Stunden.', 'The trip takes two hours.'],
  ['der', 'Flug', 'Flüge', 'flight', 'Travel', 'Der Flug hat Verspätung.', 'The flight is delayed.'],
  ['die', 'Grenze', 'Grenzen', 'border', 'Travel', 'Die Grenze ist jetzt offen.', 'The border is now open.'],
  ['der', 'Ausflug', 'Ausflüge', 'excursion, outing', 'Travel', 'Der Ausflug war schön.', 'The outing was nice.'],
  ['das', 'Hotel', 'Hotels', 'hotel', 'Travel', 'Das Hotel ist zentral.', 'The hotel is central.'],
  ['die', 'Reservierung', 'Reservierungen', 'reservation', 'Travel', 'Die Reservierung gilt bis sechs.', 'The reservation holds until six.'],
  ['die', 'Verspätung', 'Verspätungen', 'delay', 'Travel', 'Der Zug hat zehn Minuten Verspätung.', 'The train is ten minutes late.'],
  ['der', 'Anschluss', 'Anschlüsse', 'connection', 'Transport', 'Der Anschluss fährt um drei.', 'The connection leaves at three.'],
  ['die', 'Richtung', 'Richtungen', 'direction', 'Transport', 'Die Richtung ist falsch.', 'The direction is wrong.'],
  ['die', 'Abfahrt', 'Abfahrten', 'departure', 'Transport', 'Die Abfahrt ist um acht.', 'The departure is at eight.'],
  ['die', 'Ankunft', 'Ankünfte', 'arrival', 'Transport', 'Die Ankunft ist pünktlich.', 'The arrival is on time.'],
  ['das', 'Taxi', 'Taxis', 'taxi', 'Transport', 'Das Taxi wartet vorne.', 'The taxi is waiting out front.'],
  // ── communication & technology ──
  ['der', 'Anruf', 'Anrufe', 'call', 'Communication', 'Der Anruf kam um zehn.', 'The call came at ten.'],
  ['das', 'Gespräch', 'Gespräche', 'conversation, call', 'Communication', 'Das Gespräch war kurz.', 'The conversation was short.'],
  ['der', 'Brief', 'Briefe', 'letter', 'Communication', 'Der Brief kommt morgen.', 'The letter arrives tomorrow.'],
  ['die', 'Postkarte', 'Postkarten', 'postcard', 'Communication', 'Die Postkarte ist aus Rom.', 'The postcard is from Rome.'],
  ['der', 'Kontakt', 'Kontakte', 'contact', 'Communication', 'Der Kontakt bleibt bestehen.', 'The contact remains.'],
  ['der', 'Bildschirm', 'Bildschirme', 'screen', 'Communication', 'Der Bildschirm ist kaputt.', 'The screen is broken.'],
  ['die', 'Tastatur', 'Tastaturen', 'keyboard', 'Communication', 'Die Tastatur ist leise.', 'The keyboard is quiet.'],
  ['der', 'Drucker', 'Drucker', 'printer', 'Communication', 'Der Drucker druckt langsam.', 'The printer prints slowly.'],
  ['das', 'Passwort', 'Passwörter', 'password', 'Communication', 'Das Passwort ist geheim.', 'The password is secret.'],
  ['die', 'Datei', 'Dateien', 'file', 'Communication', 'Die Datei ist groß.', 'The file is big.'],
  ['der', 'Ordner', 'Ordner', 'folder', 'Communication', 'Der Ordner ist neu.', 'The folder is new.'],
  [null, 'speichern', null, 'to save', 'Communication', 'Speichere das Dokument!', 'Save the document!'],
  [null, 'laden', null, 'to load, to charge', 'Communication', 'Ich lade mein Handy auf.', 'I am charging my phone.'],
  // ── feelings & character ──
  ['das', 'Gefühl', 'Gefühle', 'feeling', 'Emotions', 'Das Gefühl ist stark.', 'The feeling is strong.'],
  ['die', 'Sorge', 'Sorgen', 'worry, concern', 'Emotions', 'Die Sorge ist groß.', 'The worry is big.'],
  ['die', 'Überraschung', 'Überraschungen', 'surprise', 'Emotions', 'Die Überraschung war toll.', 'The surprise was great.'],
  ['die', 'Wut', null, 'rage, anger', 'Emotions', 'Seine Wut war groß.', 'His rage was big.'],
  ['die', 'Langeweile', null, 'boredom', 'Emotions', 'Die Langeweile war schlimm.', 'The boredom was awful.'],
  [null, 'sicher', null, 'sure, safe', 'Emotions', 'Ich bin sicher.', 'I am sure.'],
  [null, 'unsicher', null, 'unsure, insecure', 'Emotions', 'Sie wirkt unsicher.', 'She seems unsure.'],
  [null, 'zufrieden', null, 'satisfied', 'Emotions', 'Der Kunde ist zufrieden.', 'The customer is satisfied.'],
  [null, 'unzufrieden', null, 'dissatisfied', 'Emotions', 'Warum bist du unzufrieden?', 'Why are you dissatisfied?'],
  [null, 'enttäuscht', null, 'disappointed', 'Emotions', 'Ich bin enttäuscht.', 'I am disappointed.'],
  [null, 'begeistert', null, 'enthusiastic', 'Emotions', 'Die Kinder sind begeistert.', 'The children are thrilled.'],
  [null, 'verliebt', null, 'in love', 'Emotions', 'Er ist verliebt.', 'He is in love.'],
  // ── free time ──
  ['die', 'Freizeit', null, 'free time', 'Free Time', 'Die Freizeit ist knapp.', 'Free time is scarce.'],
  ['das', 'Hobby', 'Hobbys', 'hobby', 'Free Time', 'Mein Hobby ist Lesen.', 'My hobby is reading.'],
  ['der', 'Verein', 'Vereine', 'club, association', 'Free Time', 'Der Verein trifft sich donnerstags.', 'The club meets on Thursdays.'],
  ['das', 'Spiel', 'Spiele', 'game', 'Free Time', 'Das Spiel macht Spaß.', 'The game is fun.'],
  // ── free time (continued), home & shopping ──
  [null, 'fotografieren', null, 'to photograph', 'Free Time', 'Ich fotografiere die Stadt.', 'I am photographing the city.'],
  ['die', 'Einladung', 'Einladungen', 'invitation', 'Free Time', 'Die Einladung kam per Post.', 'The invitation came by mail.'],
  [null, 'feiern', null, 'to celebrate', 'Free Time', 'Wir feiern heute Abend.', 'We are celebrating tonight.'],
  ['die', 'Hochzeit', 'Hochzeiten', 'wedding', 'Free Time', 'Die Hochzeit war wunderschön.', 'The wedding was wonderful.'],
  ['das', 'Museum', 'Museen', 'museum', 'Free Time', 'Das Museum ist montags zu.', 'The museum is closed on Mondays.'],
  ['der', 'Zoo', 'Zoos', 'zoo', 'Free Time', 'Der Zoo hat neue Pandas.', 'The zoo has new pandas.'],
  ['das', 'Schwimmbad', 'Schwimmbäder', 'swimming pool', 'Free Time', 'Das Schwimmbad ist offen.', 'The swimming pool is open.'],
  ['der', 'Mieter', 'Mieter', 'tenant', 'Home', 'Der Mieter zahlt pünktlich.', 'The tenant pays on time.'],
  ['die', 'Kaution', 'Kautionen', 'deposit', 'Home', 'Die Kaution beträgt drei Monatsmieten.', 'The deposit is three months rent.'],
  ['der', 'Hausmeister', 'Hausmeister', 'caretaker, janitor', 'Home', 'Der Hausmeister repariert die Tür.', 'The caretaker is fixing the door.'],
  ['der', 'Aufzug', 'Aufzüge', 'elevator', 'Home', 'Der Aufzug ist kaputt.', 'The elevator is broken.'],
  ['die', 'Etage', 'Etagen', 'floor, story', 'Home', 'Wir wohnen in der dritten Etage.', 'We live on the third floor.'],
  ['der', 'Balkon', 'Balkone', 'balcony', 'Home', 'Der Balkon ist sonnig.', 'The balcony is sunny.'],
  ['der', 'Keller', 'Keller', 'basement', 'Home', 'Im Keller ist es kalt.', 'It is cold in the basement.'],
  [null, 'umziehen', null, 'to move (house)', 'Home', 'Wir ziehen im Juli um.', 'We are moving in July.'],
  ['der', 'Cent', null, 'cent', 'Shopping', 'Der Cent fehlt noch.', 'The cent is still missing.'],
  ['das', 'Kleingeld', null, 'small change', 'Shopping', 'Ich habe kein Kleingeld dabei.', 'I have no small change on me.'],
  ['der', 'Beleg', 'Belege', 'receipt', 'Shopping', 'Der Beleg liegt in der Tasche.', 'The receipt is in the bag.'],
  ['die', 'Quittung', 'Quittungen', 'receipt', 'Shopping', 'Die Quittung brauche ich für die Steuer.', 'I need the receipt for the taxes.'],
  ['der', 'Rabatt', 'Rabatte', 'discount', 'Shopping', 'Der Rabatt gilt nur heute.', 'The discount is only valid today.'],
  ['die', 'Garantie', 'Garantien', 'guarantee, warranty', 'Shopping', 'Die Garantie läuft zwei Jahre.', 'The warranty lasts two years.'],
  [null, 'umtauschen', null, 'to exchange (a purchase)', 'Shopping', 'Kann ich die Hose umtauschen?', 'Can I exchange the pants?'],
  ['der', 'Kauf', 'Käufe', 'purchase', 'Shopping', 'Der Kauf war ein Fehler.', 'The purchase was a mistake.'],
  // ── A2 extension: everyday verbs ──
  [null, 'anbieten', null, 'to offer', 'Verbs', 'Das Restaurant bietet Salat an.', 'The restaurant offers salad.'],
  [null, 'ausfüllen', null, 'to fill out', 'Authorities', 'Füllen Sie das Formular aus.', 'Fill out the form.'],
  [null, 'abholen', null, 'to pick up', 'Verbs', 'Ich hole die Kinder ab.', 'I am picking up the children.'],
  [null, 'mitbringen', null, 'to bring along', 'Verbs', 'Bring einen Kuchen mit!', 'Bring a cake along!'],
  [null, 'ärgern', null, 'to annoy, to be annoyed', 'Emotions', 'Der Lärm ärgert mich.', 'The noise annoys me.'],
  [null, 'beruhigen', null, 'to calm down', 'Emotions', 'Beruhige dich bitte!', 'Please calm down!'],
  [null, 'klappen', null, 'to work out, to succeed', 'Basics', ' Hoffentlich klappt es morgen.', 'Hopefully it works out tomorrow.'],
  [null, 'funktionieren', null, 'to work, to function', 'Basics', 'Der Drucker funktioniert nicht.', 'The printer is not working.'],
  [null, 'kaputtgehen', null, 'to break', 'Basics', 'Mein Handy ist kaputtgegangen.', 'My phone broke.'],
  [null, 'reparieren', null, 'to repair', 'Verbs', 'Er repariert das Fahrrad.', 'He is repairing the bicycle.'],
  [null, 'einladen', null, 'to invite', 'Free Time', 'Ich lade dich zum Essen ein.', 'I am inviting you to dinner.'],
  [null, 'abgeben', null, 'to hand in', 'School', 'Gib die Hausaufgaben morgen ab.', 'Hand in the homework tomorrow.'],
  [null, 'ausgehen', null, 'to go out', 'Free Time', 'Am Freitag gehen wir aus.', 'On Friday we are going out.'],
  [null, 'zurückkommen', null, 'to come back', 'Verbs', 'Er kommt im Herbst zurück.', 'He is coming back in the fall.'],
  [null, 'sich beeilen', null, 'to hurry', 'Verbs', 'Wir müssen uns beeilen.', 'We have to hurry.'],
  [null, 'bestellen', null, 'to order', 'Shopping', 'Ich bestelle eine Pizza.', 'I am ordering a pizza.'],
  [null, 'buchen', null, 'to book', 'Travel', 'Ich buche das Hotel online.', 'I am booking the hotel online.'],
  // ── A2 extension: adjectives & connectors ──
  [null, 'bequem', null, 'comfortable', 'Adjectives', 'Der Stuhl ist bequem.', 'The chair is comfortable.'],
  [null, 'unbequem', null, 'uncomfortable', 'Adjectives', 'Die Schuhe sind unbequem.', 'The shoes are uncomfortable.'],
  [null, 'praktisch', null, 'practical', 'Adjectives', 'Die Tasche ist praktisch.', 'The bag is practical.'],
  [null, 'passend', null, 'fitting, matching', 'Clothing', 'Die Jacke ist passend.', 'The jacket fits well.'],
  [null, 'eng', null, 'tight, narrow', 'Adjectives', 'Die Hose ist zu eng.', 'The pants are too tight.'],
  [null, 'breit', null, 'wide', 'Adjectives', 'Die Straße ist breit.', 'The street is wide.'],
  [null, 'schmal', null, 'narrow', 'Adjectives', 'Der Weg ist schmal.', 'The path is narrow.'],
  [null, 'flach', null, 'flat', 'Adjectives', 'Das Feld ist flach.', 'The field is flat.'],
  [null, 'steil', null, 'steep', 'Adjectives', 'Der Berg ist steil.', 'The mountain is steep.'],
  [null, 'nötig', null, 'necessary', 'Adjectives', 'Eine Pause ist nötig.', 'A break is necessary.'],
  [null, 'egal', null, 'equal, does not matter', 'Basics', 'Das ist mir egal.', 'That does not matter to me.'],
  [null, 'komisch', null, 'funny, strange', 'Adjectives', 'Der Film ist komisch.', 'The movie is funny.'],
  [null, 'seltsam', null, 'strange, odd', 'Adjectives', 'Das Geräusch ist seltsam.', 'The noise is strange.'],
  [null, 'ernst', null, 'serious', 'Adjectives', 'Die Lage ist ernst.', 'The situation is serious.'],
  [null, 'denn', null, 'because (conjunction)', 'Basics', 'Ich bleibe, denn es regnet.', 'I am staying because it is raining.'],
  [null, 'trotz', null, 'despite', 'Basics', 'Trotz des Regens gehen wir.', 'Despite the rain we are going.'],
  [null, 'wegen', null, 'because of', 'Basics', 'Wegen der Arbeit komme ich später.', 'Because of work I am coming later.'],
  [null, 'also', null, 'so, therefore', 'Basics', 'Also, fangen wir an!', 'So, let us start!'],
  [null, 'sonst', null, 'otherwise', 'Basics', 'Beeil dich, sonst kommen wir zu spät.', 'Hurry, otherwise we will be late.'],
  [null, 'damals', null, 'back then', 'Time', 'Damals war alles anders.', 'Back then everything was different.'],
  [null, 'früher', null, 'earlier, in the past', 'Time', 'Früher wohnten wir in Bonn.', 'Earlier we lived in Bonn.'],
  // ── seasons & education ──
  ['die', 'Jahreszeit', 'Jahreszeiten', 'season', 'Weather', 'Die Jahreszeit liebe ich am meisten.', 'This is the season I love most.'],
  ['der', 'Frühling', 'Frühlinge', 'spring', 'Weather', 'Der Frühling beginnt im März.', 'Spring begins in March.'],
  ['der', 'Sommer', 'Sommer', 'summer', 'Weather', 'Der Sommer ist heiß.', 'The summer is hot.'],
  ['der', 'Herbst', 'Herbste', 'fall, autumn', 'Weather', 'Der Herbst ist golden.', 'The fall is golden.'],
  ['der', 'Winter', 'Winter', 'winter', 'Weather', 'Der Winter ist kalt.', 'The winter is cold.'],
  ['das', 'Gewitter', 'Gewitter', 'thunderstorm', 'Weather', 'Das Gewitter kommt auf.', 'The thunderstorm is coming.'],
  ['der', 'Sturm', 'Stürme', 'storm', 'Weather', 'Der Sturm war stark.', 'The storm was strong.'],
  ['die', 'Universität', 'Universitäten', 'university', 'Education', 'Die Universität ist alt.', 'The university is old.'],
  ['das', 'Studium', 'Studien', 'studies, degree', 'Education', 'Das Studium dauert drei Jahre.', 'The degree takes three years.'],
  ['der', 'Abschluss', 'Abschlüsse', 'degree, graduation', 'Education', 'Der Abschluss ist im Juni.', 'The graduation is in June.'],
  ['das', 'Zeugnis', 'Zeugnisse', 'report card, certificate', 'Education', 'Das Zeugnis ist gut.', 'The report card is good.'],
  ['der', 'Unterricht', null, 'class, instruction', 'Education', 'Der Unterricht beginnt um acht.', 'Class begins at eight.'],
  ['das', 'Fach', 'Fächer', 'subject', 'Education', 'Mathematik ist mein Fach.', 'Math is my subject.'],
  ['der', 'Kurs', 'Kurse', 'course', 'Education', 'Der Kurs startet im September.', 'The course starts in September.'],
  // ── household verbs ──
  [null, 'bügeln', null, 'to iron', 'Home', 'Ich bügle das Hemd.', 'I am ironing the shirt.'],
  [null, 'staubsaugen', null, 'to vacuum', 'Home', 'Er staubsaugt das Wohnzimmer.', 'He is vacuuming the living room.'],
  [null, 'spülen', null, 'to wash dishes', 'Home', 'Ich spüle das Geschirr.', 'I am washing the dishes.'],
  [null, 'abtrocknen', null, 'to dry (dishes)', 'Home', 'Sie trocknet das Geschirr ab.', 'She is drying the dishes.'],
  [null, 'aufhängen', null, 'to hang up', 'Home', 'Häng die Wäsche auf!', 'Hang up the laundry!'],
  // ── A2 extension: family, household, everyday extras ──
  [null, 'falten', null, 'to fold', 'Home', 'Ich falte die Wäsche.', 'I am folding the laundry.'],
  [null, 'abwaschen', null, 'to wash up', 'Home', 'Ich wasche die Tassen ab.', 'I am washing up the cups.'],
  ['der', 'Onkel', 'Onkel', 'uncle', 'People', 'Mein Onkel wohnt in Köln.', 'My uncle lives in Cologne.'],
  ['die', 'Tante', 'Tanten', 'aunt', 'People', 'Die Tante besucht uns.', 'The aunt is visiting us.'],
  ['der', 'Cousin', 'Cousins', 'cousin (m)', 'People', 'Mein Cousin heißt Jan.', 'My cousin is called Jan.'],
  ['die', 'Cousine', 'Cousinen', 'cousin (f)', 'People', 'Die Cousine ist zwölf.', 'The cousin is twelve.'],
  ['der', 'Neffe', 'Neffen', 'nephew', 'People', 'Der Neffe lernt Radfahren.', 'The nephew is learning to ride a bike.'],
  ['die', 'Nichte', 'Nichten', 'niece', 'People', 'Die Nichte malt gern.', 'The niece likes to paint.'],
  ['der', 'Enkel', 'Enkel', 'grandson', 'People', 'Der Enkel besucht die Großeltern.', 'The grandson visits the grandparents.'],
  ['die', 'Enkelin', 'Enkelinnen', 'granddaughter', 'People', 'Die Enkelin hilft im Garten.', 'The granddaughter helps in the garden.'],
  ['der', 'Moment', 'Momente', 'moment', 'Time', 'Einen Moment, bitte!', 'One moment, please!'],
  ['die', 'Frist', 'Fristen', 'deadline', 'Time', 'Die Frist endet am Freitag.', 'The deadline ends on Friday.'],
  ['die', 'Verabredung', 'Verabredungen', 'arrangement to meet', 'Time', 'Die Verabredung steht um sieben.', 'The arrangement is at seven.'],
  [null, 'klingeln', null, 'to ring (a bell)', 'Home', 'Es klingelt an der Tür.', 'The doorbell is ringing.'],
  [null, 'klopfen', null, 'to knock', 'Home', 'Jemand klopft.', 'Someone is knocking.'],
  [null, 'wecken', null, 'to wake (someone)', 'Home', 'Der Wecker weckt mich um sechs.', 'The alarm wakes me at six.'],
  [null, 'gießen', null, 'to water, to pour', 'Home', 'Ich gieße die Blumen.', 'I am watering the flowers.'],
  [null, 'pflanzen', null, 'to plant', 'Nature', 'Wir pflanzen einen Baum.', 'We are planting a tree.'],
  [null, 'parken', null, 'to park', 'Transport', 'Ich parke vor dem Haus.', 'I am parking in front of the house.'],
  [null, 'tanken', null, 'to fill up, to refuel', 'Transport', 'Ich tanke an der nächsten Tankstelle.', 'I am filling up at the next gas station.'],
  [null, 'durstig', null, 'thirsty', 'Body', 'Ich bin durstig.', 'I am thirsty.'],
  [null, 'hungrig', null, 'hungry', 'Body', 'Das Kind ist hungrig.', 'The child is hungry.'],
  [null, 'pünktlich', null, 'on time, punctual', 'Time', 'Der Zug ist pünktlich.', 'The train is on time.'],
  [null, 'ehrlich', null, 'honest', 'Adjectives', 'Sei ehrlich zu mir!', 'Be honest with me!'],
  [null, 'höflich', null, 'polite', 'Adjectives', 'Der Junge ist höflich.', 'The boy is polite.'],
  [null, 'vorsichtig', null, 'careful', 'Adjectives', 'Sei vorsichtig!', 'Be careful!'],
  ['die', 'Ampel', 'Ampeln', 'traffic light', 'City', 'Die Ampel ist rot.', 'The traffic light is red.'],
  ['die', 'Kreuzung', 'Kreuzungen', 'intersection', 'City', 'An der Kreuzung links.', 'Left at the intersection.'],
  ['der', 'Stau', 'Staus', 'traffic jam', 'Transport', 'Der Stau ist zehn Kilometer lang.', 'The traffic jam is ten kilometers long.'],
  ['die', 'Sonnenbrille', 'Sonnenbrillen', 'sunglasses', 'Clothing', 'Die Sonnenbrille liegt im Auto.', 'The sunglasses are in the car.'],
  ['der', 'Regenschirm', 'Regenschirme', 'umbrella', 'Clothing', 'Nimm den Regenschirm mit!', 'Take the umbrella along!'],
  ['der', 'Nachweis', 'Nachweise', 'proof, evidence', 'Authorities', 'Der Nachweis fehlt noch.', 'The proof is still missing.'],
  ['die', 'Erstattung', 'Erstattungen', 'refund', 'Shopping', 'Die Erstattung dauert zwei Wochen.', 'The refund takes two weeks.'],
  ['der', 'Umtausch', null, 'exchange (of goods)', 'Shopping', 'Der Umtausch ist kostenlos.', 'The exchange is free.'],
  ['die', 'Reklamation', 'Reklamationen', 'complaint (about a product)', 'Shopping', 'Die Reklamation war berechtigt.', 'The complaint was justified.'],
  ['der', 'Lieferdienst', 'Lieferdienste', 'delivery service', 'Shopping', 'Der Lieferdienst kommt um acht.', 'The delivery service comes at eight.'],
  ['die', 'Bestellung', 'Bestellungen', 'order', 'Shopping', 'Die Bestellung kommt morgen.', 'The order arrives tomorrow.'],
  ['die', 'Krankmeldung', 'Krankmeldungen', 'sick note', 'Health', 'Die Krankmeldung geht an den Chef.', 'The sick note goes to the boss.'],
]
