import type { SeedRow } from './types'

/** B1 seed corpus (302 entries = original 119 + extension): work, society, opinions, abstract verbs, connectors. */
export const B1_ROWS: SeedRow[] = [
  ['die', 'Besprechung', 'Besprechungen', 'meeting', 'Work', 'Die Besprechung dauert eine Stunde.', 'The meeting lasts an hour.'],
  ['die', 'Firma', 'Firmen', 'company', 'Work', 'Die Firma ist international.', 'The company is international.'],
  ['der', 'Kollege', 'Kollegen', 'colleague', 'Work', 'Mein Kollege hilft mir.', 'My colleague helps me.'],
  ['die', 'Stelle', 'Stellen', 'job, position', 'Work', 'Ich suche eine neue Stelle.', 'I am looking for a new job.'],
  ['die', 'Bewerbung', 'Bewerbungen', 'job application', 'Work', 'Meine Bewerbung ist fertig.', 'My application is ready.'],
  ['der', 'Lebenslauf', 'Lebensläufe', 'resume, CV', 'Work', 'Ich schicke meinen Lebenslauf.', 'I am sending my resume.'],
  ['die', 'Erfahrung', 'Erfahrungen', 'experience', 'Work', 'Sie hat viel Erfahrung.', 'She has a lot of experience.'],
  ['die', 'Ausbildung', 'Ausbildungen', 'training, apprenticeship', 'Work', 'Die Ausbildung dauert drei Jahre.', 'The training takes three years.'],
  ['das', 'Gehalt', 'Gehälter', 'salary', 'Work', 'Das Gehalt ist gut.', 'The salary is good.'],
  ['die', 'Überstunden', null, 'overtime', 'Work', 'Heute mache ich Überstunden.', 'Today I am working overtime.'],
  ['die', 'Entscheidung', 'Entscheidungen', 'decision', 'Society', 'Das ist eine wichtige Entscheidung.', 'That is an important decision.'],
  ['die', 'Entwicklung', 'Entwicklungen', 'development', 'Society', 'Die Entwicklung ist positiv.', 'The development is positive.'],
  ['die', 'Umwelt', null, 'environment', 'Society', 'Wir schützen die Umwelt.', 'We protect the environment.'],
  ['die', 'Gesellschaft', 'Gesellschaften', 'society', 'Society', 'Die Gesellschaft verändert sich.', 'Society is changing.'],
  ['die', 'Wirtschaft', null, 'economy', 'Society', 'Die Wirtschaft wächst.', 'The economy is growing.'],
  ['die', 'Politik', null, 'politics', 'Society', 'Ich interessiere mich für Politik.', 'I am interested in politics.'],
  ['die', 'Regierung', 'Regierungen', 'government', 'Society', 'Die Regierung entscheidet.', 'The government decides.'],
  ['das', 'Gesetz', 'Gesetze', 'law', 'Society', 'Das Gesetz ist neu.', 'The law is new.'],
  ['das', 'Recht', 'Rechte', 'right, law', 'Society', 'Jeder Mensch hat Rechte.', 'Every person has rights.'],
  ['die', 'Verantwortung', null, 'responsibility', 'Society', 'Ich übernehme Verantwortung.', 'I am taking responsibility.'],
  ['der', 'Eindruck', 'Eindrücke', 'impression', 'Communication', 'Der erste Eindruck zählt.', 'The first impression counts.'],
  ['der', 'Streit', 'Streitereien', 'quarrel, dispute', 'Emotions', 'Der Streit ist vorbei.', 'The quarrel is over.'],
  ['der', 'Kompromiss', 'Kompromisse', 'compromise', 'Communication', 'Wir finden einen Kompromiss.', 'We will find a compromise.'],
  ['die', 'Diskussion', 'Diskussionen', 'discussion', 'Communication', 'Die Diskussion war spannend.', 'The discussion was exciting.'],
  ['die', 'Kritik', null, 'criticism', 'Communication', 'Ich nehme Kritik an.', 'I accept criticism.'],
  ['das', 'Argument', 'Argumente', 'argument', 'Communication', 'Das Argument ist überzeugend.', 'The argument is convincing.'],
  ['der', 'Vorteil', 'Vorteile', 'advantage', 'Society', 'Der Vorteil ist klar.', 'The advantage is clear.'],
  ['der', 'Nachteil', 'Nachteile', 'disadvantage', 'Society', 'Jeder Vorteil hat Nachteile.', 'Every advantage has disadvantages.'],
  ['die', 'Folge', 'Folgen', 'consequence', 'Society', 'Das hat Folgen.', 'That has consequences.'],
  ['die', 'Ursache', 'Ursachen', 'cause', 'Society', 'Die Ursache ist unbekannt.', 'The cause is unknown.'],
  ['der', 'Zweck', 'Zwecke', 'purpose', 'Society', 'Der Zweck der Reise ist klar.', 'The purpose of the trip is clear.'],
  ['der', 'Zusammenhang', 'Zusammenhänge', 'connection, context', 'Society', 'Ich verstehe den Zusammenhang.', 'I understand the connection.'],
  ['die', 'Beziehung', 'Beziehungen', 'relationship', 'People', 'Unsere Beziehung ist gut.', 'Our relationship is good.'],
  ['die', 'Ehe', 'Ehen', 'marriage', 'People', 'Die Ehe dauert zehn Jahre.', 'The marriage has lasted ten years.'],
  ['der', 'Partner', 'Partner', 'partner', 'People', 'Mein Partner arbeitet viel.', 'My partner works a lot.'],
  ['die', 'Gemeinschaft', 'Gemeinschaften', 'community', 'Society', 'Die Gemeinschaft hilft.', 'The community helps.'],
  ['die', 'Nachbarschaft', null, 'neighborhood', 'Society', 'Die Nachbarschaft ist freundlich.', 'The neighborhood is friendly.'],
  ['die', 'Sprache', 'Sprachen', 'language', 'Education', 'Deutsch ist eine schöne Sprache.', 'German is a beautiful language.'],
  ['der', 'Wortschatz', null, 'vocabulary', 'Education', 'Mein Wortschatz wächst.', 'My vocabulary is growing.'],
  ['der', 'Fehler', 'Fehler', 'mistake, error', 'Education', 'Aus Fehlern lernt man.', 'One learns from mistakes.'],
  ['der', 'Fortschritt', 'Fortschritte', 'progress', 'Education', 'Ich mache Fortschritte.', 'I am making progress.'],
  ['die', 'Kenntnis', 'Kenntnisse', 'knowledge', 'Education', 'Sie hat gute Kenntnisse.', 'She has good knowledge.'],
  ['die', 'Fähigkeit', 'Fähigkeiten', 'ability, skill', 'Education', 'Das ist eine wichtige Fähigkeit.', 'That is an important skill.'],
  ['das', 'Ziel', 'Ziele', 'goal', 'Education', 'Mein Ziel ist flüssiges Sprechen.', 'My goal is to speak fluently.'],
  ['der', 'Erfolg', 'Erfolge', 'success', 'Work', 'Der Erfolg kam schnell.', 'Success came quickly.'],
  ['das', 'Pech', null, 'bad luck', 'Emotions', 'Das war Pech!', 'That was bad luck!'],
  ['die', 'Geduld', null, 'patience', 'Emotions', 'Man braucht Geduld.', 'One needs patience.'],
  ['der', 'Mut', null, 'courage', 'Emotions', 'Sie hat viel Mut.', 'She has a lot of courage.'],
  ['die', 'Ruhe', null, 'peace, quiet', 'Emotions', 'Ich brauche Ruhe.', 'I need quiet.'],
  [null, 'beschreiben', null, 'to describe', 'Verbs', 'Beschreiben Sie das Bild.', 'Describe the picture.'],
  [null, 'empfehlen', null, 'to recommend', 'Verbs', 'Was empfehlen Sie?', 'What do you recommend?'],
  [null, 'entscheiden', null, 'to decide', 'Verbs', 'Ich muss schnell entscheiden.', 'I must decide quickly.'],
  [null, 'erlauben', null, 'to allow, to permit', 'Verbs', 'Rauchen ist nicht erlaubt.', 'Smoking is not allowed.'],
  [null, 'verbieten', null, 'to forbid', 'Verbs', 'Handys sind verboten.', 'Phones are forbidden.'],
  [null, 'verbessern', null, 'to improve', 'Verbs', 'Ich will mein Deutsch verbessern.', 'I want to improve my German.'],
  [null, 'verschlechtern', null, 'to worsen', 'Verbs', 'Das Wetter verschlechtert sich.', 'The weather is getting worse.'],
  [null, 'erledigen', null, 'to complete, to take care of', 'Verbs', 'Ich erledige die Aufgabe.', 'I will take care of the task.'],
  [null, 'organisieren', null, 'to organize', 'Verbs', 'Sie organisiert die Party.', 'She is organizing the party.'],
  [null, 'planen', null, 'to plan', 'Verbs', 'Wir planen die Reise.', 'We are planning the trip.'],
  [null, 'vorbereiten', null, 'to prepare', 'Verbs', 'Ich bereite die Prüfung vor.', 'I am preparing for the exam.'],
  [null, 'beenden', null, 'to end, to finish', 'Verbs', 'Ich beende die Arbeit.', 'I am finishing the work.'],
  [null, 'fortsetzen', null, 'to continue', 'Verbs', 'Setzen Sie den Text fort.', 'Continue the text.'],
  [null, 'unterbrechen', null, 'to interrupt', 'Verbs', 'Bitte unterbrich mich nicht.', 'Please do not interrupt me.'],
  [null, 'wiederholen', null, 'to repeat', 'Verbs', 'Können Sie das wiederholen?', 'Can you repeat that?'],
  [null, 'üben', null, 'to practice', 'Verbs', 'Ich übe jeden Tag.', 'I practice every day.'],
  [null, 'versuchen', null, 'to try, to attempt', 'Verbs', 'Ich versuche es noch einmal.', 'I will try again.'],
  [null, 'schaffen', null, 'to manage, to accomplish', 'Verbs', 'Ich schaffe das!', 'I can do it!'],
  [null, 'gelten', null, 'to be valid, to apply', 'Verbs', 'Das Angebot gilt nur heute.', 'The offer is only valid today.'],
  [null, 'betreffen', null, 'to concern, to affect', 'Verbs', 'Das betrifft mich nicht.', 'That does not concern me.'],
  [null, 'abhängen', null, 'to depend', 'Verbs', 'Das hängt vom Wetter ab.', 'That depends on the weather.'],
  [null, 'zweifeln', null, 'to doubt', 'Verbs', 'Ich zweifle daran.', 'I doubt it.'],
  [null, 'behaupten', null, 'to claim, to assert', 'Verbs', 'Sie behauptet, dass sie krank war.', 'She claimed that she was sick.'],
  [null, 'bemerken', null, 'to notice', 'Verbs', 'Ich habe den Fehler bemerkt.', 'I noticed the mistake.'],
  [null, 'beobachten', null, 'to observe, to watch', 'Verbs', 'Wir beobachten die Vögel.', 'We are watching the birds.'],
  [null, 'entwickeln', null, 'to develop', 'Verbs', 'Die Firma entwickelt neue Software.', 'The company is developing new software.'],
  [null, 'gründen', null, 'to found, to establish', 'Verbs', 'Er gründet eine Firma.', 'He is founding a company.'],
  [null, 'investieren', null, 'to invest', 'Verbs', 'Wir investieren in Bildung.', 'We are investing in education.'],
  [null, 'sparen', null, 'to save (money)', 'Verbs', 'Ich spare für den Urlaub.', 'I am saving for vacation.'],
  [null, 'ausgeben', null, 'to spend (money)', 'Verbs', 'Ich gebe zu viel aus.', 'I am spending too much.'],
  [null, 'verdienen', null, 'to earn', 'Verbs', 'Sie verdient gut.', 'She earns well.'],
  [null, 'wechseln', null, 'to change, to exchange', 'Verbs', 'Ich möchte Geld wechseln.', 'I would like to exchange money.'],
  [null, 'teilen', null, 'to share, to divide', 'Verbs', 'Wir teilen die Rechnung.', 'We are splitting the bill.'],
  [null, 'interessieren', null, 'to interest', 'Verbs', 'Ich interessiere mich für Kunst.', 'I am interested in art.'],
  [null, 'stören', null, 'to disturb, to bother', 'Verbs', 'Stört es dich?', 'Does it bother you?'],
  [null, 'aufpassen', null, 'to pay attention', 'Verbs', 'Pass gut auf!', 'Pay close attention!'],
  [null, 'nachdenken', null, 'to think about, to reflect', 'Verbs', 'Ich denke darüber nach.', 'I am thinking about it.'],
  [null, 'vorhaben', null, 'to plan, to intend', 'Verbs', 'Was hast du morgen vor?', 'What are you planning for tomorrow?'],
  [null, 'teilnehmen', null, 'to participate', 'Verbs', 'Ich nehme am Kurs teil.', 'I am taking part in the course.'],
  [null, 'beitragen', null, 'to contribute', 'Verbs', 'Jeder kann beitragen.', 'Everyone can contribute.'],
  [null, 'verlieren', null, 'to lose', 'Verbs', 'Ich habe meine Brille verloren.', 'I lost my glasses.'],
  [null, 'gewinnen', null, 'to win', 'Verbs', 'Wir haben das Spiel gewonnen.', 'We won the game.'],
  [null, 'erreichen', null, 'to reach, to achieve', 'Verbs', 'Wir erreichen das Ziel.', 'We are reaching the goal.'],
  [null, 'verpassen', null, 'to miss', 'Verbs', 'Ich habe den Zug verpasst.', 'I missed the train.'],
  [null, 'ausruhen', null, 'to rest', 'Verbs', 'Ich ruhe mich aus.', 'I am resting.'],
  [null, 'trennen', null, 'to separate, to split', 'Verbs', 'Wir trennen den Müll.', 'We separate the trash.'],
  [null, 'verbinden', null, 'to connect', 'Verbs', 'Das verbindet uns.', 'That connects us.'],
  [null, 'unterscheiden', null, 'to differ, to distinguish', 'Verbs', 'Die Zwillinge unterscheiden sich.', 'The twins are different.'],
  [null, 'übereinstimmen', null, 'to agree, to match', 'Verbs', 'Wir stimmen überein.', 'We agree.'],
  [null, 'zusammenarbeiten', null, 'to work together', 'Verbs', 'Wir arbeiten gern zusammen.', 'We like working together.'],
  [null, 'entschuldigen', null, 'to excuse, to forgive', 'Verbs', 'Entschuldigen Sie die Störung.', 'Excuse the interruption.'],
  [null, 'loben', null, 'to praise', 'Verbs', 'Der Chef lobt das Team.', 'The boss praises the team.'],
  ['die', 'Brille', 'Brillen', 'glasses', 'Health', 'Ich brauche eine Brille.', 'I need glasses.'],
  ['das', 'Rezept', 'Rezepte', 'recipe, prescription', 'Food', 'Das Rezept ist einfach.', 'The recipe is simple.'],
  ['die', 'Zutat', 'Zutaten', 'ingredient', 'Food', 'Alle Zutaten sind frisch.', 'All the ingredients are fresh.'],
  [null, 'lecker', null, 'tasty, delicious', 'Food', 'Die Suppe schmeckt lecker.', 'The soup tastes delicious.'],
  [null, 'vegetarisch', null, 'vegetarian', 'Food', 'Ich koche vegetarisch.', 'I cook vegetarian.'],
  ['die', 'Gewohnheit', 'Gewohnheiten', 'habit', 'Emotions', 'Das ist eine alte Gewohnheit.', 'That is an old habit.'],
  ['die', 'Entspannung', null, 'relaxation', 'Health', 'Yoga bringt Entspannung.', 'Yoga brings relaxation.'],
  ['das', 'Gleichgewicht', null, 'balance', 'Health', 'Ich suche das Gleichgewicht.', 'I am looking for balance.'],
  [null, 'eigentlich', null, 'actually', 'Basics', 'Eigentlich wollte ich schlafen.', 'Actually I wanted to sleep.'],
  [null, 'schließlich', null, 'finally, after all', 'Basics', 'Schließlich hat es geklappt.', 'In the end it worked out.'],
  [null, 'trotzdem', null, 'nevertheless', 'Basics', 'Es regnet, trotzdem gehen wir.', 'It is raining, nevertheless we are going.'],
  [null, 'deshalb', null, 'therefore', 'Basics', 'Ich bin müde, deshalb schlafe ich.', 'I am tired, therefore I am sleeping.'],
  [null, 'außerdem', null, 'besides, moreover', 'Basics', 'Außerdem ist es teuer.', 'Besides, it is expensive.'],
  [null, 'jedoch', null, 'however', 'Basics', 'Er ist klein, jedoch stark.', 'He is small, however strong.'],
  [null, 'bestimmt', null, 'certainly, definitely', 'Basics', 'Das schaffe ich bestimmt.', 'I will definitely manage that.'],
  [null, 'möglicherweise', null, 'possibly', 'Basics', 'Möglicherweise regnet es.', 'Possibly it will rain.'],
  [null, 'ziemlich', null, 'quite, fairly', 'Basics', 'Der Film war ziemlich gut.', 'The movie was quite good.'],
  [null, 'absolut', null, 'absolutely', 'Basics', 'Das ist absolut richtig.', 'That is absolutely right.'],
  // ── B1 extension: work & economy ──
  ['die', 'Industrie', 'Industrien', 'industry', 'Work', 'Die Industrie wächst langsam.', 'The industry is growing slowly.'],
  ['der', 'Konzern', 'Konzerne', 'corporation', 'Work', 'Der Konzern hat viele Mitarbeiter.', 'The corporation has many employees.'],
  ['das', 'Einkommen', null, 'income', 'Work', 'Mein Einkommen ist stabil.', 'My income is stable.'],
  ['die', 'Rente', 'Renten', 'pension, retirement', 'Work', 'Die Rente reicht nicht.', 'The pension is not enough.'],
  ['die', 'Karriere', 'Karrieren', 'career', 'Work', 'Ihre Karriere beginnt hier.', 'Her career starts here.'],
  ['die', 'Arbeitslosigkeit', null, 'unemployment', 'Work', 'Die Arbeitslosigkeit sinkt.', 'Unemployment is falling.'],
  ['die', 'Kündigung', 'Kündigungen', 'termination, notice', 'Work', 'Die Kündigung kam per Brief.', 'The termination came by letter.'],
  [null, 'kündigen', null, 'to quit, to terminate', 'Work', 'Ich kündige zum Monatsende.', 'I am quitting at the end of the month.'],
  [null, 'einstellen', null, 'to hire', 'Work', 'Die Firma stellt neue Leute ein.', 'The company is hiring new people.'],
  [null, 'entlassen', null, 'to dismiss, to lay off', 'Work', 'Zwanzig Mitarbeiter werden entlassen.', 'Twenty employees are being laid off.'],
  ['die', 'Abteilung', 'Abteilungen', 'department', 'Work', 'Die Abteilung ist groß.', 'The department is big.'],
  ['die', 'Leitung', 'Leitungen', 'management, line', 'Work', 'Die Leitung entscheidet morgen.', 'Management decides tomorrow.'],
  ['das', 'Projekt', 'Projekte', 'project', 'Work', 'Das Projekt startet im Mai.', 'The project starts in May.'],
  ['die', 'Konferenz', 'Konferenzen', 'conference', 'Work', 'Die Konferenz findet online statt.', 'The conference takes place online.'],
  ['der', 'Umsatz', 'Umsätze', 'revenue, sales', 'Work', 'Der Umsatz steigt.', 'Revenue is rising.'],
  ['der', 'Gewinn', 'Gewinne', 'profit', 'Work', 'Der Gewinn ist höher als letztes Jahr.', 'The profit is higher than last year.'],
  ['der', 'Verlust', 'Verluste', 'loss', 'Work', 'Der Verlust ist groß.', 'The loss is big.'],
  ['die', 'Investition', 'Investitionen', 'investment', 'Work', 'Die Investition lohnt sich.', 'The investment is worthwhile.'],
  ['das', 'Arbeitsamt', 'Arbeitsämter', 'employment office', 'Work', 'Das Arbeitsamt hilft bei der Suche.', 'The employment office helps with the search.'],
  ['die', 'Vollzeit', null, 'full time', 'Work', 'Sie arbeitet in Vollzeit.', 'She works full time.'],
  ['die', 'Teilzeit', null, 'part time', 'Work', 'Ich arbeite in Teilzeit.', 'I work part time.'],
  ['der', 'Beruf', 'Berufe', 'profession', 'Work', 'Mein Beruf ist Lehrer.', 'My profession is teacher.'],
  ['die', 'Qualifikation', 'Qualifikationen', 'qualification', 'Work', 'Die Qualifikation passt zur Stelle.', 'The qualification fits the position.'],
  ['die', 'Weiterbildung', 'Weiterbildungen', 'further training', 'Work', 'Die Weiterbildung kostet wenig.', 'The further training costs little.'],
  // ── society & politics ──
  ['die', 'Wahl', 'Wahlen', 'election, choice', 'Society', 'Die Wahl ist im Herbst.', 'The election is in the fall.'],
  [null, 'wählen', null, 'to vote, to choose', 'Society', 'Wir wählen am Sonntag.', 'We are voting on Sunday.'],
  ['der', 'Bürger', 'Bürger', 'citizen', 'Society', 'Jeder Bürger hat eine Stimme.', 'Every citizen has one vote.'],
  ['die', 'Freiheit', 'Freiheiten', 'freedom', 'Society', 'Die Freiheit ist wichtig.', 'Freedom is important.'],
  ['die', 'Gerechtigkeit', null, 'justice, fairness', 'Society', 'Gerechtigkeit kostet Mühe.', 'Justice takes effort.'],
  ['das', 'Verbrechen', 'Verbrechen', 'crime', 'Society', 'Das Verbrechen wurde aufgeklärt.', 'The crime was solved.'],
  ['die', 'Strafe', 'Strafen', 'punishment, penalty, fine', 'Society', 'Die Strafe ist hoch.', 'The fine is high.'],
  ['der', 'Richter', 'Richter', 'judge', 'Society', 'Der Richter spricht das Urteil.', 'The judge delivers the verdict.'],
  ['das', 'Gericht', 'Gerichte', 'court; dish', 'Society', 'Das Gericht entscheidet heute.', 'The court decides today.'],
  ['der', 'Anwalt', 'Anwälte', 'lawyer', 'Society', 'Der Anwalt hilft im Prozess.', 'The lawyer helps in the trial.'],
  ['die', 'Polizei', null, 'police', 'Society', 'Die Polizei kommt sofort.', 'The police are coming immediately.'],
  ['die', 'Demonstration', 'Demonstrationen', 'demonstration', 'Society', 'Die Demonstration war friedlich.', 'The demonstration was peaceful.'],
  ['die', 'Presse', null, 'press', 'Society', 'Die Presse berichtet heute darüber.', 'The press is reporting on it today.'],
  ['die', 'Medien', null, 'media', 'Society', 'Die Medien diskutieren viel.', 'The media discuss a lot.'],
  ['die', 'Öffentlichkeit', null, 'the public', 'Society', 'Die Öffentlichkeit weiß es schon.', 'The public already knows.'],
  ['der', 'Staat', 'Staaten', 'state, country', 'Society', 'Der Staat zahlt den Zuschuss.', 'The state pays the subsidy.'],
  ['die', 'Einwanderung', null, 'immigration', 'Society', 'Die Einwanderung steigt.', 'Immigration is rising.'],
  ['der', 'Flüchtling', 'Flüchtlinge', 'refugee', 'Society', 'Der Flüchtling erzählt seine Geschichte.', 'The refugee tells his story.'],
  [null, 'integrieren', null, 'to integrate', 'Society', 'Der Kurs hilft, uns zu integrieren.', 'The course helps us integrate.'],
  ['die', 'Mehrheit', 'Mehrheiten', 'majority', 'Society', 'Die Mehrheit ist dafür.', 'The majority is in favor.'],
  // ── opinions & communication ──
  ['die', 'Auseinandersetzung', 'Auseinandersetzungen', 'argument, conflict', 'Communication', 'Die Auseinandersetzung war heftig.', 'The argument was heated.'],
  ['die', 'Absicht', 'Absichten', 'intention', 'Communication', 'Die Absicht war gut.', 'The intention was good.'],
  ['die', 'Vermutung', 'Vermutungen', 'assumption, guess', 'Communication', 'Meine Vermutung war richtig.', 'My guess was right.'],
  ['die', 'Forderung', 'Forderungen', 'demand, claim', 'Communication', 'Die Forderung ist klar.', 'The demand is clear.'],
  ['der', 'Vorschlag', 'Vorschläge', 'suggestion, proposal', 'Communication', 'Der Vorschlag klingt gut.', 'The proposal sounds good.'],
  [null, 'vorschlagen', null, 'to suggest', 'Communication', 'Ich schlage einen Kompromiss vor.', 'I am suggesting a compromise.'],
  ['der', 'Einwand', 'Einwände', 'objection', 'Communication', 'Der Einwand ist berechtigt.', 'The objection is justified.'],
  [null, 'widersprechen', null, 'to contradict', 'Communication', 'Ich muss dir widersprechen.', 'I have to contradict you.'],
  [null, 'zustimmen', null, 'to agree', 'Communication', 'Ich stimme dir zu.', 'I agree with you.'],
  [null, 'ablehnen', null, 'to reject', 'Communication', 'Sie lehnt das Angebot ab.', 'She is rejecting the offer.'],
  [null, 'einverstanden', null, 'in agreement', 'Communication', 'Ich bin einverstanden.', 'I agree.'],
  ['die', 'Ansicht', 'Ansichten', 'view, opinion', 'Communication', 'Das ist meine Ansicht.', 'That is my view.'],
  ['die', 'Einstellung', 'Einstellungen', 'attitude, setting', 'Communication', 'Seine Einstellung hat sich geändert.', 'His attitude has changed.'],
  ['der', 'Ausdruck', 'Ausdrücke', 'expression', 'Communication', 'Der Ausdruck passt hier.', 'The expression fits here.'],
  [null, 'ausdrücken', null, 'to express', 'Communication', 'Ich möchte mich klar ausdrücken.', 'I want to express myself clearly.'],
  ['die', 'Bedeutung', 'Bedeutungen', 'meaning, significance', 'Communication', 'Die Bedeutung ist unklar.', 'The meaning is unclear.'],
  [null, 'bedeuten', null, 'to mean', 'Communication', 'Was bedeutet dieses Wort?', 'What does this word mean?'],
  ['der', 'Sinn', 'Sinne', 'sense, meaning', 'Communication', 'Der Sinn ist einfach.', 'The meaning is simple.'],
  [null, 'erwähnen', null, 'to mention', 'Communication', 'Er erwähnt den Termin.', 'He mentions the appointment.'],
  [null, 'betonen', null, 'to emphasize', 'Communication', 'Sie betont die Regel.', 'She emphasizes the rule.'],
  [null, 'zusammenfassen', null, 'to summarize', 'Communication', 'Fasse den Text kurz zusammen.', 'Summarize the text briefly.'],
  [null, 'vereinfachen', null, 'to simplify', 'Communication', 'Das lässt sich vereinfachen.', 'That can be simplified.'],
  // ── everyday abstractions ──
  ['die', 'Regel', 'Regeln', 'rule', 'Society', 'Die Regel gilt für alle.', 'The rule applies to everyone.'],
  ['die', 'Ausnahme', 'Ausnahmen', 'exception', 'Society', 'Die Ausnahme bestätigt die Regel.', 'The exception confirms the rule.'],
  ['das', 'Erlebnis', 'Erlebnisse', 'experience, event', 'Emotions', 'Das Erlebnis war unvergesslich.', 'The experience was unforgettable.'],
  ['die', 'Erinnerung', 'Erinnerungen', 'memory', 'Emotions', 'Die Erinnerung macht mich glücklich.', 'The memory makes me happy.'],
  ['die', 'Nachfrage', 'Nachfragen', 'demand', 'Work', 'Die Nachfrage ist groß.', 'The demand is high.'],
  ['der', 'Bedarf', null, 'need, requirement', 'Society', 'Der Bedarf wächst jedes Jahr.', 'The need grows every year.'],
  [null, 'benötigen', null, 'to need, to require', 'Verbs', 'Wir benötigen mehr Zeit.', 'We need more time.'],
  ['der', 'Ersatz', null, 'replacement', 'Shopping', 'Der Ersatz kommt nächste Woche.', 'The replacement comes next week.'],
  [null, 'ersetzen', null, 'to replace', 'Verbs', 'Nichts ersetzt Erfahrung.', 'Nothing replaces experience.'],
  ['die', 'Reparatur', 'Reparaturen', 'repair', 'Shopping', 'Die Reparatur kostet wenig.', 'The repair costs little.'],
  ['der', 'Schutz', null, 'protection', 'Society', 'Der Schutz der Daten ist wichtig.', 'The protection of data is important.'],
  [null, 'schützen', null, 'to protect', 'Verbs', 'Wir schützen die Umwelt.', 'We protect the environment.'],
  ['die', 'Gefahr', 'Gefahren', 'danger', 'Society', 'Die Gefahr ist gering.', 'The danger is low.'],
  [null, 'gefährden', null, 'to endanger', 'Verbs', 'Speed gefährdet Leben.', 'Speed endangers lives.'],
  ['die', 'Sicherheit', null, 'safety, security', 'Society', 'Die Sicherheit hat Priorität.', 'Safety has priority.'],
  ['die', 'Auswirkung', 'Auswirkungen', 'effect, impact', 'Society', 'Die Auswirkung ist spürbar.', 'The impact is noticeable.'],
  ['die', 'Veränderung', 'Veränderungen', 'change', 'Society', 'Die Veränderung tut gut.', 'The change does good.'],
  [null, 'verändern', null, 'to change, to alter', 'Verbs', 'Die Stadt verändert sich schnell.', 'The city is changing fast.'],
  [null, 'lohnen', null, 'to be worth it', 'Work', 'Der Aufwand lohnt sich.', 'The effort is worth it.'],
  ['der', 'Aufwand', null, 'effort, expense', 'Work', 'Der Aufwand war groß.', 'The effort was big.'],
  ['die', 'Mühe', null, 'effort, trouble', 'Work', 'Die Mühe hat sich gelohnt.', 'The effort paid off.'],
  // ── character traits ──
  [null, 'zuverlässig', null, 'reliable', 'Adjectives', 'Sie ist sehr zuverlässig.', 'She is very reliable.'],
  [null, 'selbstbewusst', null, 'confident, self-assured', 'Adjectives', 'Er tritt selbstbewusst auf.', 'He appears confident.'],
  [null, 'schüchtern', null, 'shy', 'Adjectives', 'Das Mädchen ist schüchtern.', 'The girl is shy.'],
  [null, 'ehrgeizig', null, 'ambitious', 'Adjectives', 'Der neue Kollege ist ehrgeizig.', 'The new colleague is ambitious.'],
  [null, 'fleißig', null, 'hard-working', 'Adjectives', 'Die Studentin ist fleißig.', 'The student is hard-working.'],
  [null, 'faul', null, 'lazy', 'Adjectives', 'Der Hund ist faul.', 'The dog is lazy.'],
  [null, 'ordentlich', null, 'tidy, orderly', 'Adjectives', 'Ihr Schreibtisch ist ordentlich.', 'Her desk is tidy.'],
  [null, 'chaotisch', null, 'chaotic', 'Adjectives', 'Der Morgen war chaotisch.', 'The morning was chaotic.'],
  [null, 'geduldig', null, 'patient', 'Adjectives', 'Sei bitte geduldig!', 'Please be patient!'],
  [null, 'hilfsbereit', null, 'helpful', 'Adjectives', 'Unsere Nachbarn sind hilfsbereit.', 'Our neighbors are helpful.'],
  [null, 'egoistisch', null, 'selfish', 'Adjectives', 'Das war egoistisch.', 'That was selfish.'],
  [null, 'großzügig', null, 'generous', 'Adjectives', 'Sie ist großzügig.', 'She is generous.'],
  [null, 'streng', null, 'strict', 'Adjectives', 'Der Lehrer ist streng.', 'The teacher is strict.'],
  [null, 'sympathisch', null, 'likeable, pleasant', 'Adjectives', 'Ich finde ihn sympathisch.', 'I find him likeable.'],
  [null, 'unsympathisch', null, 'unlikeable', 'Adjectives', 'Der Film ist mir unsympathisch.', 'I do not like the movie.'],
  // ── B1 extension: verbs ──
  [null, 'beantragen', null, 'to apply for', 'Authorities', 'Ich beantrage einen neuen Pass.', 'I am applying for a new passport.'],
  [null, 'auffallen', null, 'to stand out, to notice', 'Verbs', 'Ihr mutiges Auftreten fällt auf.', 'Her brave manner stands out.'],
  [null, 'zurückgeben', null, 'to give back, to return', 'Verbs', 'Ich gebe das Buch morgen zurück.', 'I am returning the book tomorrow.'],
  [null, 'unterstützen', null, 'to support', 'Verbs', 'Die Familie unterstützt uns.', 'The family supports us.'],
  [null, 'beteiligen', null, 'to participate, to involve', 'Verbs', 'Alle beteiligen sich an der Diskussion.', 'Everyone takes part in the discussion.'],
  [null, 'bewerben', null, 'to apply', 'Work', 'Ich bewerbe mich um die Stelle.', 'I am applying for the position.'],
  [null, 'abschließen', null, 'to conclude, to lock', 'Verbs', 'Wir schließen den Vertrag ab.', 'We are concluding the contract.'],
  [null, 'zunehmen', null, 'to increase; to gain weight', 'Verbs', 'Die Zahl nimmt zu.', 'The number is increasing.'],
  [null, 'abnehmen', null, 'to decrease; to lose weight', 'Verbs', 'Der Druck nimmt ab.', 'The pressure is decreasing.'],
  [null, 'aussehen', null, 'to look, to appear', 'Verbs', 'Du siehst müde aus.', 'You look tired.'],
  [null, 'vorstellen', null, 'to introduce; to imagine', 'Verbs', 'Darf ich mich vorstellen?', 'May I introduce myself?'],
  [null, 'austauschen', null, 'to exchange', 'Verbs', 'Wir tauschen Ideen aus.', 'We are exchanging ideas.'],
  [null, 'wegwerfen', null, 'to throw away', 'Verbs', 'Wirf den Müll nicht einfach weg!', 'Do not just throw the trash away!'],
  [null, 'aufheben', null, 'to keep, to pick up', 'Verbs', 'Hebe den Beleg auf!', 'Keep the receipt!'],
  [null, 'verwenden', null, 'to use', 'Verbs', 'Wir verwenden frische Zutaten.', 'We use fresh ingredients.'],
  [null, 'benutzen', null, 'to use', 'Verbs', 'Benutze den Aufzug!', 'Use the elevator!'],
  [null, 'gebrauchen', null, 'to use, to need', 'Verbs', 'Ich kann das Handy noch gebrauchen.', 'I can still use the phone.'],
  [null, 'handeln', null, 'to act; to deal', 'Verbs', 'Wir müssen schnell handeln.', 'We have to act quickly.'],
  [null, 'verhandeln', null, 'to negotiate', 'Work', 'Die Firma verhandelt mit der Gewerkschaft.', 'The company negotiates with the union.'],
  [null, 'durchsetzen', null, 'to push through, to assert', 'Work', 'Sie setzt ihre Ideen durch.', 'She pushes her ideas through.'],
  [null, 'hinterfragen', null, 'to question, to challenge', 'Verbs', 'Hinterfrage die Quelle!', 'Question the source!'],
  [null, 'umsetzen', null, 'to implement', 'Work', 'Das Team setzt den Plan um.', 'The team implements the plan.'],
  [null, 'klagen', null, 'to complain; to sue', 'Society', 'Die Nachbarn klagen über den Lärm.', 'The neighbors complain about the noise.'],
  [null, 'verzeihen', null, 'to forgive', 'Emotions', 'Ich verzeihe dir.', 'I forgive you.'],
  // ── health & consumer ──
  ['die', 'Behandlung', 'Behandlungen', 'treatment', 'Health', 'Die Behandlung beginnt sofort.', 'The treatment starts immediately.'],
  [null, 'behandeln', null, 'to treat', 'Health', 'Die Ärztin behandelt den Patienten.', 'The doctor treats the patient.'],
  ['die', 'Diagnose', 'Diagnosen', 'diagnosis', 'Health', 'Die Diagnose ist klar.', 'The diagnosis is clear.'],
  ['die', 'Überweisung', 'Überweisungen', 'referral; bank transfer', 'Health', 'Die Überweisung zum Facharzt kam schnell.', 'The referral to the specialist came quickly.'],
  ['die', 'Nebenwirkung', 'Nebenwirkungen', 'side effect', 'Health', 'Die Nebenwirkung ist selten.', 'The side effect is rare.'],
  ['die', 'Vorsorge', null, 'prevention, precaution', 'Health', 'Vorsorge ist besser als Heilen.', 'Prevention is better than healing.'],
  [null, 'impfen', null, 'to vaccinate', 'Health', 'Der Arzt impft das Kind.', 'The doctor vaccinates the child.'],
  ['die', 'Impfung', 'Impfungen', 'vaccination', 'Health', 'Die Impfung ist kostenlos.', 'The vaccination is free.'],
  // ── housing, digital & consumer ──
  ['die', 'Nebenkosten', null, 'additional rental costs', 'Home', 'Die Nebenkosten steigen jedes Jahr.', 'The additional costs rise every year.'],
  ['die', 'Renovierung', 'Renovierungen', 'renovation', 'Home', 'Die Renovierung dauert einen Monat.', 'The renovation takes a month.'],
  [null, 'renovieren', null, 'to renovate', 'Home', 'Wir renovieren das Bad.', 'We are renovating the bathroom.'],
  ['der', 'Dachboden', 'Dachböden', 'attic', 'Home', 'Der Dachboden ist voll.', 'The attic is full.'],
  ['die', 'Baustelle', 'Baustellen', 'construction site', 'City', 'Die Baustelle blockiert die Straße.', 'The construction site blocks the street.'],
  ['die', 'Stadtverwaltung', null, 'city administration', 'Authorities', 'Die Stadtverwaltung antwortet schriftlich.', 'The city administration replies in writing.'],
  ['das', 'Rathaus', 'Rathäuser', 'city hall', 'City', 'Das Rathaus liegt am Marktplatz.', 'The city hall is at the market square.'],
  ['der', 'Datenschutz', null, 'data protection', 'Communication', 'Der Datenschutz ist uns wichtig.', 'Data protection is important to us.'],
  ['das', 'Konto', 'Konten', 'account', 'Shopping', 'Das Konto ist überzogen.', 'The account is overdrawn.'],
  ['die', 'App', 'Apps', 'app', 'Communication', 'Die App ist neu.', 'The app is new.'],
  [null, 'aktualisieren', null, 'to update', 'Communication', 'Aktualisiere die App!', 'Update the app!'],
  ['die', 'Benachrichtigung', 'Benachrichtigungen', 'notification', 'Communication', 'Die Benachrichtigung kam sofort.', 'The notification came immediately.'],
  [null, 'benachrichtigen', null, 'to notify', 'Communication', 'Wir benachrichtigen Sie per E-Mail.', 'We will notify you by email.'],
  // ── B1 extension: adjectives ──
  [null, 'anspruchsvoll', null, 'demanding, sophisticated', 'Adjectives', 'Der Kurs ist anspruchsvoll.', 'The course is demanding.'],
  [null, 'wirksam', null, 'effective', 'Adjectives', 'Die Methode ist wirksam.', 'The method is effective.'],
  [null, 'effektiv', null, 'efficient, effective', 'Adjectives', 'Das Training ist effektiv.', 'The training is efficient.'],
  [null, 'zahlreich', null, 'numerous', 'Adjectives', 'Die Beschwerden waren zahlreich.', 'The complaints were numerous.'],
  [null, 'erheblich', null, 'considerable, substantial', 'Adjectives', 'Der Unterschied ist erheblich.', 'The difference is considerable.'],
  [null, 'deutlich', null, 'clear, distinct', 'Adjectives', 'Der Gewinn ist deutlich gestiegen.', 'The profit rose clearly.'],
  [null, 'auffällig', null, 'striking, noticeable', 'Adjectives', 'Das Muster ist auffällig.', 'The pattern is striking.'],
  [null, 'ungewöhnlich', null, 'unusual', 'Adjectives', 'Die Antwort ist ungewöhnlich.', 'The answer is unusual.'],
  [null, 'außergewöhnlich', null, 'exceptional', 'Adjectives', 'Das Angebot ist außergewöhnlich.', 'The offer is exceptional.'],
  [null, 'bedeutend', null, 'significant, important', 'Adjectives', 'Sie ist eine bedeutende Künstlerin.', 'She is a significant artist.'],
  [null, 'wesentlich', null, 'essential, considerably', 'Adjectives', 'Der Preis ist wesentlich gesunken.', 'The price fell considerably.'],
  [null, 'vorteilhaft', null, 'advantageous', 'Adjectives', 'Der Vertrag ist vorteilhaft.', 'The contract is advantageous.'],
  [null, 'erforderlich', null, 'required, necessary', 'Adjectives', 'Eine Anmeldung ist erforderlich.', 'A registration is required.'],
  [null, 'umstritten', null, 'controversial', 'Adjectives', 'Die Regel ist umstritten.', 'The rule is controversial.'],
  [null, 'fraglich', null, 'questionable, doubtful', 'Adjectives', 'Ob das hilft, ist fraglich.', 'Whether that helps is questionable.'],
  // ── B1 extension: connectors ──
  [null, 'allerdings', null, 'however, though', 'Basics', 'Das stimmt allerdings.', 'That is true though.'],
  [null, 'einerseits', null, 'on the one hand', 'Basics', 'Einerseits ist es günstig.', 'On the one hand it is cheap.'],
  [null, 'andererseits', null, 'on the other hand', 'Basics', 'Andererseits ist es klein.', 'On the other hand it is small.'],
  [null, 'somit', null, 'thus, therefore', 'Basics', 'Somit ist die Frage geklärt.', 'Thus the question is settled.'],
  [null, 'folglich', null, 'consequently', 'Basics', 'Folglich müssen wir handeln.', 'Consequently we have to act.'],
  [null, 'dennoch', null, 'nevertheless', 'Basics', 'Es regnet, dennoch gehen wir.', 'It is raining, nevertheless we are going.'],
  [null, 'hingegen', null, 'in contrast, however', 'Basics', 'Sie ist ruhig, er hingegen laut.', 'She is quiet, he however loud.'],
  [null, 'insbesondere', null, 'in particular', 'Basics', 'Insbesondere die Preise steigen.', 'In particular the prices are rising.'],
  [null, 'bevor', null, 'before (conjunction)', 'Basics', 'Wasche die Hände, bevor du isst.', 'Wash your hands before you eat.'],
  [null, 'nachdem', null, 'after (conjunction)', 'Basics', 'Nachdem er kam, begann das Essen.', 'After he arrived, the meal started.'],
  [null, 'obwohl', null, 'although', 'Basics', 'Wir gehen, obwohl es regnet.', 'We are going although it is raining.'],
  [null, 'während', null, 'during, while', 'Basics', 'Während des Films war es still.', 'During the movie it was quiet.'],
  [null, 'seitdem', null, 'since then', 'Time', 'Seitdem wohne ich hier.', 'Since then I have lived here.'],
  [null, 'sobald', null, 'as soon as', 'Basics', 'Sobald es klingelt, öffne ich.', 'As soon as it rings, I open.'],
  [null, 'falls', null, 'if, in case', 'Basics', 'Falls es regnet, bleiben wir.', 'If it rains, we are staying.'],
  // ── B1 extension: abstract nouns ──
  ['die', 'Selbstständigkeit', null, 'self-employment, independence', 'Work', 'Die Selbstständigkeit birgt Risiken.', 'Self-employment involves risks.'],
  [null, 'selbstständig', null, 'self-employed, independent', 'Adjectives', 'Sie arbeitet selbstständig.', 'She works independently.'],
  ['die', 'Herausforderung', 'Herausforderungen', 'challenge', 'Work', 'Die Herausforderung ist groß.', 'The challenge is big.'],
  ['die', 'Schwierigkeit', 'Schwierigkeiten', 'difficulty', 'Society', 'Die Schwierigkeit liegt im Detail.', 'The difficulty lies in the detail.'],
  ['das', 'Verständnis', null, 'understanding', 'Communication', 'Das Verständnis wächst mit der Zeit.', 'Understanding grows with time.'],
  ['die', 'Erkenntnis', 'Erkenntnisse', 'insight, finding', 'Education', 'Die Erkenntnis ist neu.', 'The finding is new.'],
]
