import type { SeedRow } from './types'

/** B1 seed corpus (757 entries = original 119 + extension + M12.3 household/food/health/work batch + M12.4 travel/authorities batch): work, society, opinions, abstract verbs, connectors. */
export const B1_ROWS: SeedRow[] = [
  ['die', 'Besprechung', 'Besprechungen', 'meeting', 'Work', 'Die Besprechung dauert eine Stunde.', 'The meeting lasts an hour.'],
  ['die', 'Firma', 'Firmen', 'company', 'Work', 'Die Firma ist international.', 'The company is international.'],
  ['der', 'Kollege', 'Kollegen', 'colleague', 'Work', 'Mein Kollege hilft mir.', 'My colleague helps me.'],
  ['die', 'Stelle', 'Stellen', 'job, position', 'Work', 'Ich suche eine neue Stelle.', 'I am looking for a new job.'],
  ['die', 'Bewerbung', 'Bewerbungen', 'job application', 'Work', 'Meine Bewerbung ist fertig.', 'My application is ready.'],
  ['der', 'Lebenslauf', 'Lebensläufe', 'resume, CV', 'Work', 'Ich schicke meinen Lebenslauf.', 'I am sending my resume.'],
  ['die', 'Erfahrung', 'Erfahrungen', 'experience', 'Work', 'Sie hat viel Erfahrung.', 'She has a lot of experience.'],
  ['die', 'Ausbildung', 'Ausbildungen', 'training, apprenticeship', 'Work', 'Die Ausbildung dauert drei Jahre.', 'The training takes three years.'],
  ['das', 'Gehalt', 'Gehälter', 'salary', 'Work', 'Das Gehalt ist gut.', 'The salary is good.'],
  ['die', 'Überstunden', null, 'overtime', 'Work', 'Heute mache ich Überstunden.', 'Today I am working overtime.'],
  ['die', 'Entscheidung', 'Entscheidungen', 'decision', 'Society', 'Das ist eine wichtige Entscheidung.', 'That is an important decision.'],
  ['die', 'Entwicklung', 'Entwicklungen', 'development', 'Society', 'Die Entwicklung ist positiv.', 'The development is positive.'],
  ['die', 'Umwelt', null, 'environment', 'Society', 'Wir schützen die Umwelt.', 'We protect the environment.'],
  ['die', 'Gesellschaft', 'Gesellschaften', 'society', 'Society', 'Die Gesellschaft verändert sich.', 'Society is changing.'],
  ['die', 'Wirtschaft', null, 'economy', 'Society', 'Die Wirtschaft wächst.', 'The economy is growing.'],
  ['die', 'Politik', null, 'politics', 'Society', 'Ich interessiere mich für Politik.', 'I am interested in politics.'],
  ['die', 'Regierung', 'Regierungen', 'government', 'Society', 'Die Regierung entscheidet.', 'The government decides.'],
  ['das', 'Gesetz', 'Gesetze', 'law', 'Society', 'Das Gesetz ist neu.', 'The law is new.'],
  ['das', 'Recht', 'Rechte', 'right, law', 'Society', 'Jeder Mensch hat Rechte.', 'Every person has rights.'],
  ['die', 'Verantwortung', null, 'responsibility', 'Society', 'Ich übernehme Verantwortung.', 'I am taking responsibility.'],
  ['der', 'Eindruck', 'Eindrücke', 'impression', 'Communication', 'Der erste Eindruck zählt.', 'The first impression counts.'],
  ['der', 'Streit', 'Streitereien', 'quarrel, dispute', 'Emotions', 'Der Streit ist vorbei.', 'The quarrel is over.'],
  ['der', 'Kompromiss', 'Kompromisse', 'compromise', 'Communication', 'Wir finden einen Kompromiss.', 'We will find a compromise.'],
  ['die', 'Diskussion', 'Diskussionen', 'discussion', 'Communication', 'Die Diskussion war spannend.', 'The discussion was exciting.'],
  ['die', 'Kritik', null, 'criticism', 'Communication', 'Ich nehme Kritik an.', 'I accept criticism.'],
  ['das', 'Argument', 'Argumente', 'argument', 'Communication', 'Das Argument ist überzeugend.', 'The argument is convincing.'],
  ['der', 'Vorteil', 'Vorteile', 'advantage', 'Society', 'Der Vorteil ist klar.', 'The advantage is clear.'],
  ['der', 'Nachteil', 'Nachteile', 'disadvantage', 'Society', 'Jeder Vorteil hat Nachteile.', 'Every advantage has disadvantages.'],
  ['die', 'Folge', 'Folgen', 'consequence', 'Society', 'Das hat Folgen.', 'That has consequences.'],
  ['die', 'Ursache', 'Ursachen', 'cause', 'Society', 'Die Ursache ist unbekannt.', 'The cause is unknown.'],
  ['der', 'Zweck', 'Zwecke', 'purpose', 'Society', 'Der Zweck der Reise ist klar.', 'The purpose of the trip is clear.'],
  ['der', 'Zusammenhang', 'Zusammenhänge', 'connection, context', 'Society', 'Ich verstehe den Zusammenhang.', 'I understand the connection.'],
  ['die', 'Beziehung', 'Beziehungen', 'relationship', 'People', 'Unsere Beziehung ist gut.', 'Our relationship is good.'],
  ['die', 'Ehe', 'Ehen', 'marriage', 'People', 'Die Ehe dauert zehn Jahre.', 'The marriage has lasted ten years.'],
  ['der', 'Partner', 'Partner', 'partner', 'People', 'Mein Partner arbeitet viel.', 'My partner works a lot.'],
  ['die', 'Gemeinschaft', 'Gemeinschaften', 'community', 'Society', 'Die Gemeinschaft hilft.', 'The community helps.'],
  ['die', 'Nachbarschaft', null, 'neighborhood', 'Society', 'Die Nachbarschaft ist freundlich.', 'The neighborhood is friendly.'],
  ['die', 'Sprache', 'Sprachen', 'language', 'Education', 'Deutsch ist eine schöne Sprache.', 'German is a beautiful language.'],
  ['der', 'Wortschatz', null, 'vocabulary', 'Education', 'Mein Wortschatz wächst.', 'My vocabulary is growing.'],
  ['der', 'Fehler', 'Fehler', 'mistake, error', 'Education', 'Aus Fehlern lernt man.', 'One learns from mistakes.'],
  ['der', 'Fortschritt', 'Fortschritte', 'progress', 'Education', 'Ich mache Fortschritte.', 'I am making progress.'],
  ['die', 'Kenntnis', 'Kenntnisse', 'knowledge', 'Education', 'Sie hat gute Kenntnisse.', 'She has good knowledge.'],
  ['die', 'Fähigkeit', 'Fähigkeiten', 'ability, skill', 'Education', 'Das ist eine wichtige Fähigkeit.', 'That is an important skill.'],
  ['das', 'Ziel', 'Ziele', 'goal', 'Education', 'Mein Ziel ist flüssiges Sprechen.', 'My goal is to speak fluently.'],
  ['der', 'Erfolg', 'Erfolge', 'success', 'Work', 'Der Erfolg kam schnell.', 'Success came quickly.'],
  ['das', 'Pech', null, 'bad luck', 'Emotions', 'Das war Pech!', 'That was bad luck!'],
  ['die', 'Geduld', null, 'patience', 'Emotions', 'Man braucht Geduld.', 'One needs patience.'],
  ['der', 'Mut', null, 'courage', 'Emotions', 'Sie hat viel Mut.', 'She has a lot of courage.'],
  ['die', 'Ruhe', null, 'peace, quiet', 'Emotions', 'Ich brauche Ruhe.', 'I need quiet.'],
  [null, 'beschreiben', null, 'to describe', 'Verbs', 'Beschreiben Sie das Bild.', 'Describe the picture.'],
  [null, 'empfehlen', null, 'to recommend', 'Verbs', 'Was empfehlen Sie?', 'What do you recommend?'],
  [null, 'entscheiden', null, 'to decide', 'Verbs', 'Ich muss schnell entscheiden.', 'I must decide quickly.'],
  [null, 'erlauben', null, 'to allow, to permit', 'Verbs', 'Rauchen ist nicht erlaubt.', 'Smoking is not allowed.'],
  [null, 'verbieten', null, 'to forbid', 'Verbs', 'Handys sind verboten.', 'Phones are forbidden.'],
  [null, 'verbessern', null, 'to improve', 'Verbs', 'Ich will mein Deutsch verbessern.', 'I want to improve my German.'],
  [null, 'verschlechtern', null, 'to worsen', 'Verbs', 'Das Wetter verschlechtert sich.', 'The weather is getting worse.'],
  [null, 'erledigen', null, 'to complete, to take care of', 'Verbs', 'Ich erledige die Aufgabe.', 'I will take care of the task.'],
  [null, 'organisieren', null, 'to organize', 'Verbs', 'Sie organisiert die Party.', 'She is organizing the party.'],
  [null, 'planen', null, 'to plan', 'Verbs', 'Wir planen die Reise.', 'We are planning the trip.'],
  [null, 'vorbereiten', null, 'to prepare', 'Verbs', 'Ich bereite die Prüfung vor.', 'I am preparing for the exam.'],
  [null, 'beenden', null, 'to end, to finish', 'Verbs', 'Ich beende die Arbeit.', 'I am finishing the work.'],
  [null, 'fortsetzen', null, 'to continue', 'Verbs', 'Setzen Sie den Text fort.', 'Continue the text.'],
  [null, 'unterbrechen', null, 'to interrupt', 'Verbs', 'Bitte unterbrich mich nicht.', 'Please do not interrupt me.'],
  [null, 'wiederholen', null, 'to repeat', 'Verbs', 'Können Sie das wiederholen?', 'Can you repeat that?'],
  [null, 'üben', null, 'to practice', 'Verbs', 'Ich übe jeden Tag.', 'I practice every day.'],
  [null, 'versuchen', null, 'to try, to attempt', 'Verbs', 'Ich versuche es noch einmal.', 'I will try again.'],
  [null, 'schaffen', null, 'to manage, to accomplish', 'Verbs', 'Ich schaffe das!', 'I can do it!'],
  [null, 'gelten', null, 'to be valid, to apply', 'Verbs', 'Das Angebot gilt nur heute.', 'The offer is only valid today.'],
  [null, 'betreffen', null, 'to concern, to affect', 'Verbs', 'Das betrifft mich nicht.', 'That does not concern me.'],
  [null, 'abhängen', null, 'to depend', 'Verbs', 'Das hängt vom Wetter ab.', 'That depends on the weather.'],
  [null, 'zweifeln', null, 'to doubt', 'Verbs', 'Ich zweifle daran.', 'I doubt it.'],
  [null, 'behaupten', null, 'to claim, to assert', 'Verbs', 'Sie behauptet, dass sie krank war.', 'She claimed that she was sick.'],
  [null, 'bemerken', null, 'to notice', 'Verbs', 'Ich habe den Fehler bemerkt.', 'I noticed the mistake.'],
  [null, 'beobachten', null, 'to observe, to watch', 'Verbs', 'Wir beobachten die Vögel.', 'We are watching the birds.'],
  [null, 'entwickeln', null, 'to develop', 'Verbs', 'Die Firma entwickelt neue Software.', 'The company is developing new software.'],
  [null, 'gründen', null, 'to found, to establish', 'Verbs', 'Er gründet eine Firma.', 'He is founding a company.'],
  [null, 'investieren', null, 'to invest', 'Verbs', 'Wir investieren in Bildung.', 'We are investing in education.'],
  [null, 'sparen', null, 'to save (money)', 'Verbs', 'Ich spare für den Urlaub.', 'I am saving for vacation.'],
  [null, 'ausgeben', null, 'to spend (money)', 'Verbs', 'Ich gebe zu viel aus.', 'I am spending too much.'],
  [null, 'verdienen', null, 'to earn', 'Verbs', 'Sie verdient gut.', 'She earns well.'],
  [null, 'wechseln', null, 'to change, to exchange', 'Verbs', 'Ich möchte Geld wechseln.', 'I would like to exchange money.'],
  [null, 'teilen', null, 'to share, to divide', 'Verbs', 'Wir teilen die Rechnung.', 'We are splitting the bill.'],
  [null, 'interessieren', null, 'to interest', 'Verbs', 'Ich interessiere mich für Kunst.', 'I am interested in art.'],
  [null, 'stören', null, 'to disturb, to bother', 'Verbs', 'Stört es dich?', 'Does it bother you?'],
  [null, 'aufpassen', null, 'to pay attention', 'Verbs', 'Pass gut auf!', 'Pay close attention!'],
  [null, 'nachdenken', null, 'to think about, to reflect', 'Verbs', 'Ich denke darüber nach.', 'I am thinking about it.'],
  [null, 'vorhaben', null, 'to plan, to intend', 'Verbs', 'Was hast du morgen vor?', 'What are you planning for tomorrow?'],
  [null, 'teilnehmen', null, 'to participate', 'Verbs', 'Ich nehme am Kurs teil.', 'I am taking part in the course.'],
  [null, 'beitragen', null, 'to contribute', 'Verbs', 'Jeder kann beitragen.', 'Everyone can contribute.'],
  [null, 'verlieren', null, 'to lose', 'Verbs', 'Ich habe meine Brille verloren.', 'I lost my glasses.'],
  [null, 'gewinnen', null, 'to win', 'Verbs', 'Wir haben das Spiel gewonnen.', 'We won the game.'],
  [null, 'erreichen', null, 'to reach, to achieve', 'Verbs', 'Wir erreichen das Ziel.', 'We are reaching the goal.'],
  [null, 'verpassen', null, 'to miss', 'Verbs', 'Ich habe den Zug verpasst.', 'I missed the train.'],
  [null, 'ausruhen', null, 'to rest', 'Verbs', 'Ich ruhe mich aus.', 'I am resting.'],
  [null, 'trennen', null, 'to separate, to split', 'Verbs', 'Wir trennen den Müll.', 'We separate the trash.'],
  [null, 'verbinden', null, 'to connect', 'Verbs', 'Das verbindet uns.', 'That connects us.'],
  [null, 'unterscheiden', null, 'to differ, to distinguish', 'Verbs', 'Die Zwillinge unterscheiden sich.', 'The twins are different.'],
  [null, 'übereinstimmen', null, 'to agree, to match', 'Verbs', 'Wir stimmen überein.', 'We agree.'],
  [null, 'zusammenarbeiten', null, 'to work together', 'Verbs', 'Wir arbeiten gern zusammen.', 'We like working together.'],
  [null, 'entschuldigen', null, 'to excuse, to forgive', 'Verbs', 'Entschuldigen Sie die Störung.', 'Excuse the interruption.'],
  [null, 'loben', null, 'to praise', 'Verbs', 'Der Chef lobt das Team.', 'The boss praises the team.'],
  ['die', 'Brille', 'Brillen', 'glasses', 'Health', 'Ich brauche eine Brille.', 'I need glasses.'],
  ['das', 'Rezept', 'Rezepte', 'recipe, prescription', 'Food', 'Das Rezept ist einfach.', 'The recipe is simple.'],
  ['die', 'Zutat', 'Zutaten', 'ingredient', 'Food', 'Alle Zutaten sind frisch.', 'All the ingredients are fresh.'],
  [null, 'lecker', null, 'tasty, delicious', 'Food', 'Die Suppe schmeckt lecker.', 'The soup tastes delicious.'],
  [null, 'vegetarisch', null, 'vegetarian', 'Food', 'Ich koche vegetarisch.', 'I cook vegetarian.'],
  ['die', 'Gewohnheit', 'Gewohnheiten', 'habit', 'Emotions', 'Das ist eine alte Gewohnheit.', 'That is an old habit.'],
  ['die', 'Entspannung', null, 'relaxation', 'Health', 'Yoga bringt Entspannung.', 'Yoga brings relaxation.'],
  ['das', 'Gleichgewicht', null, 'balance', 'Health', 'Ich suche das Gleichgewicht.', 'I am looking for balance.'],
  [null, 'eigentlich', null, 'actually', 'Basics', 'Eigentlich wollte ich schlafen.', 'Actually I wanted to sleep.'],
  [null, 'schließlich', null, 'finally, after all', 'Basics', 'Schließlich hat es geklappt.', 'In the end it worked out.'],
  [null, 'trotzdem', null, 'nevertheless', 'Basics', 'Es regnet, trotzdem gehen wir.', 'It is raining, nevertheless we are going.'],
  [null, 'deshalb', null, 'therefore', 'Basics', 'Ich bin müde, deshalb schlafe ich.', 'I am tired, therefore I am sleeping.'],
  [null, 'außerdem', null, 'besides, moreover', 'Basics', 'Außerdem ist es teuer.', 'Besides, it is expensive.'],
  [null, 'jedoch', null, 'however', 'Basics', 'Er ist klein, jedoch stark.', 'He is small, however strong.'],
  [null, 'bestimmt', null, 'certainly, definitely', 'Basics', 'Das schaffe ich bestimmt.', 'I will definitely manage that.'],
  [null, 'möglicherweise', null, 'possibly', 'Basics', 'Möglicherweise regnet es.', 'Possibly it will rain.'],
  [null, 'ziemlich', null, 'quite, fairly', 'Basics', 'Der Film war ziemlich gut.', 'The movie was quite good.'],
  [null, 'absolut', null, 'absolutely', 'Basics', 'Das ist absolut richtig.', 'That is absolutely right.'],
  // ── B1 extension: work & economy ──
  ['die', 'Industrie', 'Industrien', 'industry', 'Work', 'Die Industrie wächst langsam.', 'The industry is growing slowly.'],
  ['der', 'Konzern', 'Konzerne', 'corporation', 'Work', 'Der Konzern hat viele Mitarbeiter.', 'The corporation has many employees.'],
  ['das', 'Einkommen', null, 'income', 'Work', 'Mein Einkommen ist stabil.', 'My income is stable.'],
  ['die', 'Rente', 'Renten', 'pension, retirement', 'Work', 'Die Rente reicht nicht.', 'The pension is not enough.'],
  ['die', 'Karriere', 'Karrieren', 'career', 'Work', 'Ihre Karriere beginnt hier.', 'Her career starts here.'],
  ['die', 'Arbeitslosigkeit', null, 'unemployment', 'Work', 'Die Arbeitslosigkeit sinkt.', 'Unemployment is falling.'],
  ['die', 'Kündigung', 'Kündigungen', 'termination, notice', 'Work', 'Die Kündigung kam per Brief.', 'The termination came by letter.'],
  [null, 'kündigen', null, 'to quit, to terminate', 'Work', 'Ich kündige zum Monatsende.', 'I am quitting at the end of the month.'],
  [null, 'einstellen', null, 'to hire', 'Work', 'Die Firma stellt neue Leute ein.', 'The company is hiring new people.'],
  [null, 'entlassen', null, 'to dismiss, to lay off', 'Work', 'Zwanzig Mitarbeiter werden entlassen.', 'Twenty employees are being laid off.'],
  ['die', 'Abteilung', 'Abteilungen', 'department', 'Work', 'Die Abteilung ist groß.', 'The department is big.'],
  ['die', 'Leitung', 'Leitungen', 'management, line', 'Work', 'Die Leitung entscheidet morgen.', 'Management decides tomorrow.'],
  ['das', 'Projekt', 'Projekte', 'project', 'Work', 'Das Projekt startet im Mai.', 'The project starts in May.'],
  ['die', 'Konferenz', 'Konferenzen', 'conference', 'Work', 'Die Konferenz findet online statt.', 'The conference takes place online.'],
  ['der', 'Umsatz', 'Umsätze', 'revenue, sales', 'Work', 'Der Umsatz steigt.', 'Revenue is rising.'],
  ['der', 'Gewinn', 'Gewinne', 'profit', 'Work', 'Der Gewinn ist höher als letztes Jahr.', 'The profit is higher than last year.'],
  ['der', 'Verlust', 'Verluste', 'loss', 'Work', 'Der Verlust ist groß.', 'The loss is big.'],
  ['die', 'Investition', 'Investitionen', 'investment', 'Work', 'Die Investition lohnt sich.', 'The investment is worthwhile.'],
  ['das', 'Arbeitsamt', 'Arbeitsämter', 'employment office', 'Work', 'Das Arbeitsamt hilft bei der Suche.', 'The employment office helps with the search.'],
  ['die', 'Vollzeit', null, 'full time', 'Work', 'Sie arbeitet in Vollzeit.', 'She works full time.'],
  ['die', 'Teilzeit', null, 'part time', 'Work', 'Ich arbeite in Teilzeit.', 'I work part time.'],
  ['der', 'Beruf', 'Berufe', 'profession', 'Work', 'Mein Beruf ist Lehrer.', 'My profession is teacher.'],
  ['die', 'Qualifikation', 'Qualifikationen', 'qualification', 'Work', 'Die Qualifikation passt zur Stelle.', 'The qualification fits the position.'],
  ['die', 'Weiterbildung', 'Weiterbildungen', 'further training', 'Work', 'Die Weiterbildung kostet wenig.', 'The further training costs little.'],
  // ── society & politics ──
  ['die', 'Wahl', 'Wahlen', 'election, choice', 'Society', 'Die Wahl ist im Herbst.', 'The election is in the fall.'],
  [null, 'wählen', null, 'to vote, to choose', 'Society', 'Wir wählen am Sonntag.', 'We are voting on Sunday.'],
  ['der', 'Bürger', 'Bürger', 'citizen', 'Society', 'Jeder Bürger hat eine Stimme.', 'Every citizen has one vote.'],
  ['die', 'Freiheit', 'Freiheiten', 'freedom', 'Society', 'Die Freiheit ist wichtig.', 'Freedom is important.'],
  ['die', 'Gerechtigkeit', null, 'justice, fairness', 'Society', 'Gerechtigkeit kostet Mühe.', 'Justice takes effort.'],
  ['das', 'Verbrechen', 'Verbrechen', 'crime', 'Society', 'Das Verbrechen wurde aufgeklärt.', 'The crime was solved.'],
  ['die', 'Strafe', 'Strafen', 'punishment, penalty, fine', 'Society', 'Die Strafe ist hoch.', 'The fine is high.'],
  ['der', 'Richter', 'Richter', 'judge', 'Society', 'Der Richter spricht das Urteil.', 'The judge delivers the verdict.'],
  ['das', 'Gericht', 'Gerichte', 'court; dish', 'Society', 'Das Gericht entscheidet heute.', 'The court decides today.'],
  ['der', 'Anwalt', 'Anwälte', 'lawyer', 'Society', 'Der Anwalt hilft im Prozess.', 'The lawyer helps in the trial.'],
  ['die', 'Polizei', null, 'police', 'Society', 'Die Polizei kommt sofort.', 'The police are coming immediately.'],
  ['die', 'Demonstration', 'Demonstrationen', 'demonstration', 'Society', 'Die Demonstration war friedlich.', 'The demonstration was peaceful.'],
  ['die', 'Presse', null, 'press', 'Society', 'Die Presse berichtet heute darüber.', 'The press is reporting on it today.'],
  ['die', 'Medien', null, 'media', 'Society', 'Die Medien diskutieren viel.', 'The media discuss a lot.'],
  ['die', 'Öffentlichkeit', null, 'the public', 'Society', 'Die Öffentlichkeit weiß es schon.', 'The public already knows.'],
  ['der', 'Staat', 'Staaten', 'state, country', 'Society', 'Der Staat zahlt den Zuschuss.', 'The state pays the subsidy.'],
  ['die', 'Einwanderung', null, 'immigration', 'Society', 'Die Einwanderung steigt.', 'Immigration is rising.'],
  ['der', 'Flüchtling', 'Flüchtlinge', 'refugee', 'Society', 'Der Flüchtling erzählt seine Geschichte.', 'The refugee tells his story.'],
  [null, 'integrieren', null, 'to integrate', 'Society', 'Der Kurs hilft, uns zu integrieren.', 'The course helps us integrate.'],
  ['die', 'Mehrheit', 'Mehrheiten', 'majority', 'Society', 'Die Mehrheit ist dafür.', 'The majority is in favor.'],
  // ── opinions & communication ──
  ['die', 'Auseinandersetzung', 'Auseinandersetzungen', 'argument, conflict', 'Communication', 'Die Auseinandersetzung war heftig.', 'The argument was heated.'],
  ['die', 'Absicht', 'Absichten', 'intention', 'Communication', 'Die Absicht war gut.', 'The intention was good.'],
  ['die', 'Vermutung', 'Vermutungen', 'assumption, guess', 'Communication', 'Meine Vermutung war richtig.', 'My guess was right.'],
  ['die', 'Forderung', 'Forderungen', 'demand, claim', 'Communication', 'Die Forderung ist klar.', 'The demand is clear.'],
  ['der', 'Vorschlag', 'Vorschläge', 'suggestion, proposal', 'Communication', 'Der Vorschlag klingt gut.', 'The proposal sounds good.'],
  [null, 'vorschlagen', null, 'to suggest', 'Communication', 'Ich schlage einen Kompromiss vor.', 'I am suggesting a compromise.'],
  ['der', 'Einwand', 'Einwände', 'objection', 'Communication', 'Der Einwand ist berechtigt.', 'The objection is justified.'],
  [null, 'widersprechen', null, 'to contradict', 'Communication', 'Ich muss dir widersprechen.', 'I have to contradict you.'],
  [null, 'zustimmen', null, 'to agree', 'Communication', 'Ich stimme dir zu.', 'I agree with you.'],
  [null, 'ablehnen', null, 'to reject', 'Communication', 'Sie lehnt das Angebot ab.', 'She is rejecting the offer.'],
  [null, 'einverstanden', null, 'in agreement', 'Communication', 'Ich bin einverstanden.', 'I agree.'],
  ['die', 'Ansicht', 'Ansichten', 'view, opinion', 'Communication', 'Das ist meine Ansicht.', 'That is my view.'],
  ['die', 'Einstellung', 'Einstellungen', 'attitude, setting', 'Communication', 'Seine Einstellung hat sich geändert.', 'His attitude has changed.'],
  ['der', 'Ausdruck', 'Ausdrücke', 'expression', 'Communication', 'Der Ausdruck passt hier.', 'The expression fits here.'],
  [null, 'ausdrücken', null, 'to express', 'Communication', 'Ich möchte mich klar ausdrücken.', 'I want to express myself clearly.'],
  ['die', 'Bedeutung', 'Bedeutungen', 'meaning, significance', 'Communication', 'Die Bedeutung ist unklar.', 'The meaning is unclear.'],
  [null, 'bedeuten', null, 'to mean', 'Communication', 'Was bedeutet dieses Wort?', 'What does this word mean?'],
  ['der', 'Sinn', 'Sinne', 'sense, meaning', 'Communication', 'Der Sinn ist einfach.', 'The meaning is simple.'],
  [null, 'erwähnen', null, 'to mention', 'Communication', 'Er erwähnt den Termin.', 'He mentions the appointment.'],
  [null, 'betonen', null, 'to emphasize', 'Communication', 'Sie betont die Regel.', 'She emphasizes the rule.'],
  [null, 'zusammenfassen', null, 'to summarize', 'Communication', 'Fasse den Text kurz zusammen.', 'Summarize the text briefly.'],
  [null, 'vereinfachen', null, 'to simplify', 'Communication', 'Das lässt sich vereinfachen.', 'That can be simplified.'],
  // ── everyday abstractions ──
  ['die', 'Regel', 'Regeln', 'rule', 'Society', 'Die Regel gilt für alle.', 'The rule applies to everyone.'],
  ['die', 'Ausnahme', 'Ausnahmen', 'exception', 'Society', 'Die Ausnahme bestätigt die Regel.', 'The exception confirms the rule.'],
  ['das', 'Erlebnis', 'Erlebnisse', 'experience, event', 'Emotions', 'Das Erlebnis war unvergesslich.', 'The experience was unforgettable.'],
  ['die', 'Erinnerung', 'Erinnerungen', 'memory', 'Emotions', 'Die Erinnerung macht mich glücklich.', 'The memory makes me happy.'],
  ['die', 'Nachfrage', 'Nachfragen', 'demand', 'Work', 'Die Nachfrage ist groß.', 'The demand is high.'],
  ['der', 'Bedarf', null, 'need, requirement', 'Society', 'Der Bedarf wächst jedes Jahr.', 'The need grows every year.'],
  [null, 'benötigen', null, 'to need, to require', 'Verbs', 'Wir benötigen mehr Zeit.', 'We need more time.'],
  ['der', 'Ersatz', null, 'replacement', 'Shopping', 'Der Ersatz kommt nächste Woche.', 'The replacement comes next week.'],
  [null, 'ersetzen', null, 'to replace', 'Verbs', 'Nichts ersetzt Erfahrung.', 'Nothing replaces experience.'],
  ['die', 'Reparatur', 'Reparaturen', 'repair', 'Shopping', 'Die Reparatur kostet wenig.', 'The repair costs little.'],
  ['der', 'Schutz', null, 'protection', 'Society', 'Der Schutz der Daten ist wichtig.', 'The protection of data is important.'],
  [null, 'schützen', null, 'to protect', 'Verbs', 'Wir schützen die Umwelt.', 'We protect the environment.'],
  ['die', 'Gefahr', 'Gefahren', 'danger', 'Society', 'Die Gefahr ist gering.', 'The danger is low.'],
  [null, 'gefährden', null, 'to endanger', 'Verbs', 'Speed gefährdet Leben.', 'Speed endangers lives.'],
  ['die', 'Sicherheit', null, 'safety, security', 'Society', 'Die Sicherheit hat Priorität.', 'Safety has priority.'],
  ['die', 'Auswirkung', 'Auswirkungen', 'effect, impact', 'Society', 'Die Auswirkung ist spürbar.', 'The impact is noticeable.'],
  ['die', 'Veränderung', 'Veränderungen', 'change', 'Society', 'Die Veränderung tut gut.', 'The change does good.'],
  [null, 'verändern', null, 'to change, to alter', 'Verbs', 'Die Stadt verändert sich schnell.', 'The city is changing fast.'],
  [null, 'lohnen', null, 'to be worth it', 'Work', 'Der Aufwand lohnt sich.', 'The effort is worth it.'],
  ['der', 'Aufwand', null, 'effort, expense', 'Work', 'Der Aufwand war groß.', 'The effort was big.'],
  ['die', 'Mühe', null, 'effort, trouble', 'Work', 'Die Mühe hat sich gelohnt.', 'The effort paid off.'],
  // ── character traits ──
  [null, 'zuverlässig', null, 'reliable', 'Adjectives', 'Sie ist sehr zuverlässig.', 'She is very reliable.'],
  [null, 'selbstbewusst', null, 'confident, self-assured', 'Adjectives', 'Er tritt selbstbewusst auf.', 'He appears confident.'],
  [null, 'schüchtern', null, 'shy', 'Adjectives', 'Das Mädchen ist schüchtern.', 'The girl is shy.'],
  [null, 'ehrgeizig', null, 'ambitious', 'Adjectives', 'Der neue Kollege ist ehrgeizig.', 'The new colleague is ambitious.'],
  [null, 'fleißig', null, 'hard-working', 'Adjectives', 'Die Studentin ist fleißig.', 'The student is hard-working.'],
  [null, 'faul', null, 'lazy', 'Adjectives', 'Der Hund ist faul.', 'The dog is lazy.'],
  [null, 'ordentlich', null, 'tidy, orderly', 'Adjectives', 'Ihr Schreibtisch ist ordentlich.', 'Her desk is tidy.'],
  [null, 'chaotisch', null, 'chaotic', 'Adjectives', 'Der Morgen war chaotisch.', 'The morning was chaotic.'],
  [null, 'geduldig', null, 'patient', 'Adjectives', 'Sei bitte geduldig!', 'Please be patient!'],
  [null, 'hilfsbereit', null, 'helpful', 'Adjectives', 'Unsere Nachbarn sind hilfsbereit.', 'Our neighbors are helpful.'],
  [null, 'egoistisch', null, 'selfish', 'Adjectives', 'Das war egoistisch.', 'That was selfish.'],
  [null, 'großzügig', null, 'generous', 'Adjectives', 'Sie ist großzügig.', 'She is generous.'],
  [null, 'streng', null, 'strict', 'Adjectives', 'Der Lehrer ist streng.', 'The teacher is strict.'],
  [null, 'sympathisch', null, 'likeable, pleasant', 'Adjectives', 'Ich finde ihn sympathisch.', 'I find him likeable.'],
  [null, 'unsympathisch', null, 'unlikeable', 'Adjectives', 'Der Film ist mir unsympathisch.', 'I do not like the movie.'],
  // ── B1 extension: verbs ──
  [null, 'beantragen', null, 'to apply for', 'Authorities', 'Ich beantrage einen neuen Pass.', 'I am applying for a new passport.'],
  [null, 'auffallen', null, 'to stand out, to notice', 'Verbs', 'Ihr mutiges Auftreten fällt auf.', 'Her brave manner stands out.'],
  [null, 'zurückgeben', null, 'to give back, to return', 'Verbs', 'Ich gebe das Buch morgen zurück.', 'I am returning the book tomorrow.'],
  [null, 'unterstützen', null, 'to support', 'Verbs', 'Die Familie unterstützt uns.', 'The family supports us.'],
  [null, 'beteiligen', null, 'to participate, to involve', 'Verbs', 'Alle beteiligen sich an der Diskussion.', 'Everyone takes part in the discussion.'],
  [null, 'bewerben', null, 'to apply', 'Work', 'Ich bewerbe mich um die Stelle.', 'I am applying for the position.'],
  [null, 'abschließen', null, 'to conclude, to lock', 'Verbs', 'Wir schließen den Vertrag ab.', 'We are concluding the contract.'],
  [null, 'zunehmen', null, 'to increase; to gain weight', 'Verbs', 'Die Zahl nimmt zu.', 'The number is increasing.'],
  [null, 'abnehmen', null, 'to decrease; to lose weight', 'Verbs', 'Der Druck nimmt ab.', 'The pressure is decreasing.'],
  [null, 'aussehen', null, 'to look, to appear', 'Verbs', 'Du siehst müde aus.', 'You look tired.'],
  [null, 'vorstellen', null, 'to introduce; to imagine', 'Verbs', 'Darf ich mich vorstellen?', 'May I introduce myself?'],
  [null, 'austauschen', null, 'to exchange', 'Verbs', 'Wir tauschen Ideen aus.', 'We are exchanging ideas.'],
  [null, 'wegwerfen', null, 'to throw away', 'Verbs', 'Wirf den Müll nicht einfach weg!', 'Do not just throw the trash away!'],
  [null, 'aufheben', null, 'to keep, to pick up', 'Verbs', 'Hebe den Beleg auf!', 'Keep the receipt!'],
  [null, 'verwenden', null, 'to use', 'Verbs', 'Wir verwenden frische Zutaten.', 'We use fresh ingredients.'],
  [null, 'benutzen', null, 'to use', 'Verbs', 'Benutze den Aufzug!', 'Use the elevator!'],
  [null, 'gebrauchen', null, 'to use, to need', 'Verbs', 'Ich kann das Handy noch gebrauchen.', 'I can still use the phone.'],
  [null, 'handeln', null, 'to act; to deal', 'Verbs', 'Wir müssen schnell handeln.', 'We have to act quickly.'],
  [null, 'verhandeln', null, 'to negotiate', 'Work', 'Die Firma verhandelt mit der Gewerkschaft.', 'The company negotiates with the union.'],
  [null, 'durchsetzen', null, 'to push through, to assert', 'Work', 'Sie setzt ihre Ideen durch.', 'She pushes her ideas through.'],
  [null, 'hinterfragen', null, 'to question, to challenge', 'Verbs', 'Hinterfrage die Quelle!', 'Question the source!'],
  [null, 'umsetzen', null, 'to implement', 'Work', 'Das Team setzt den Plan um.', 'The team implements the plan.'],
  [null, 'klagen', null, 'to complain; to sue', 'Society', 'Die Nachbarn klagen über den Lärm.', 'The neighbors complain about the noise.'],
  [null, 'verzeihen', null, 'to forgive', 'Emotions', 'Ich verzeihe dir.', 'I forgive you.'],
  // ── health & consumer ──
  ['die', 'Behandlung', 'Behandlungen', 'treatment', 'Health', 'Die Behandlung beginnt sofort.', 'The treatment starts immediately.'],
  [null, 'behandeln', null, 'to treat', 'Health', 'Die Ärztin behandelt den Patienten.', 'The doctor treats the patient.'],
  ['die', 'Diagnose', 'Diagnosen', 'diagnosis', 'Health', 'Die Diagnose ist klar.', 'The diagnosis is clear.'],
  ['die', 'Überweisung', 'Überweisungen', 'referral; bank transfer', 'Health', 'Die Überweisung zum Facharzt kam schnell.', 'The referral to the specialist came quickly.'],
  ['die', 'Nebenwirkung', 'Nebenwirkungen', 'side effect', 'Health', 'Die Nebenwirkung ist selten.', 'The side effect is rare.'],
  ['die', 'Vorsorge', null, 'prevention, precaution', 'Health', 'Vorsorge ist besser als Heilen.', 'Prevention is better than healing.'],
  [null, 'impfen', null, 'to vaccinate', 'Health', 'Der Arzt impft das Kind.', 'The doctor vaccinates the child.'],
  ['die', 'Impfung', 'Impfungen', 'vaccination', 'Health', 'Die Impfung ist kostenlos.', 'The vaccination is free.'],
  // ── housing, digital & consumer ──
  ['die', 'Nebenkosten', null, 'additional rental costs', 'Home', 'Die Nebenkosten steigen jedes Jahr.', 'The additional costs rise every year.'],
  ['die', 'Renovierung', 'Renovierungen', 'renovation', 'Home', 'Die Renovierung dauert einen Monat.', 'The renovation takes a month.'],
  [null, 'renovieren', null, 'to renovate', 'Home', 'Wir renovieren das Bad.', 'We are renovating the bathroom.'],
  ['der', 'Dachboden', 'Dachböden', 'attic', 'Home', 'Der Dachboden ist voll.', 'The attic is full.'],
  ['die', 'Baustelle', 'Baustellen', 'construction site', 'City', 'Die Baustelle blockiert die Straße.', 'The construction site blocks the street.'],
  ['die', 'Stadtverwaltung', null, 'city administration', 'Authorities', 'Die Stadtverwaltung antwortet schriftlich.', 'The city administration replies in writing.'],
  ['das', 'Rathaus', 'Rathäuser', 'city hall', 'City', 'Das Rathaus liegt am Marktplatz.', 'The city hall is at the market square.'],
  ['der', 'Datenschutz', null, 'data protection', 'Communication', 'Der Datenschutz ist uns wichtig.', 'Data protection is important to us.'],
  ['das', 'Konto', 'Konten', 'account', 'Shopping', 'Das Konto ist überzogen.', 'The account is overdrawn.'],
  ['die', 'App', 'Apps', 'app', 'Communication', 'Die App ist neu.', 'The app is new.'],
  [null, 'aktualisieren', null, 'to update', 'Communication', 'Aktualisiere die App!', 'Update the app!'],
  ['die', 'Benachrichtigung', 'Benachrichtigungen', 'notification', 'Communication', 'Die Benachrichtigung kam sofort.', 'The notification came immediately.'],
  [null, 'benachrichtigen', null, 'to notify', 'Communication', 'Wir benachrichtigen Sie per E-Mail.', 'We will notify you by email.'],
  // ── B1 extension: adjectives ──
  [null, 'anspruchsvoll', null, 'demanding, sophisticated', 'Adjectives', 'Der Kurs ist anspruchsvoll.', 'The course is demanding.'],
  [null, 'wirksam', null, 'effective', 'Adjectives', 'Die Methode ist wirksam.', 'The method is effective.'],
  [null, 'effektiv', null, 'efficient, effective', 'Adjectives', 'Das Training ist effektiv.', 'The training is efficient.'],
  [null, 'zahlreich', null, 'numerous', 'Adjectives', 'Die Beschwerden waren zahlreich.', 'The complaints were numerous.'],
  [null, 'erheblich', null, 'considerable, substantial', 'Adjectives', 'Der Unterschied ist erheblich.', 'The difference is considerable.'],
  [null, 'deutlich', null, 'clear, distinct', 'Adjectives', 'Der Gewinn ist deutlich gestiegen.', 'The profit rose clearly.'],
  [null, 'auffällig', null, 'striking, noticeable', 'Adjectives', 'Das Muster ist auffällig.', 'The pattern is striking.'],
  [null, 'ungewöhnlich', null, 'unusual', 'Adjectives', 'Die Antwort ist ungewöhnlich.', 'The answer is unusual.'],
  [null, 'außergewöhnlich', null, 'exceptional', 'Adjectives', 'Das Angebot ist außergewöhnlich.', 'The offer is exceptional.'],
  [null, 'bedeutend', null, 'significant, important', 'Adjectives', 'Sie ist eine bedeutende Künstlerin.', 'She is a significant artist.'],
  [null, 'wesentlich', null, 'essential, considerably', 'Adjectives', 'Der Preis ist wesentlich gesunken.', 'The price fell considerably.'],
  [null, 'vorteilhaft', null, 'advantageous', 'Adjectives', 'Der Vertrag ist vorteilhaft.', 'The contract is advantageous.'],
  [null, 'erforderlich', null, 'required, necessary', 'Adjectives', 'Eine Anmeldung ist erforderlich.', 'A registration is required.'],
  [null, 'umstritten', null, 'controversial', 'Adjectives', 'Die Regel ist umstritten.', 'The rule is controversial.'],
  [null, 'fraglich', null, 'questionable, doubtful', 'Adjectives', 'Ob das hilft, ist fraglich.', 'Whether that helps is questionable.'],
  // ── B1 extension: connectors ──
  [null, 'allerdings', null, 'however, though', 'Basics', 'Das stimmt allerdings.', 'That is true though.'],
  [null, 'einerseits', null, 'on the one hand', 'Basics', 'Einerseits ist es günstig.', 'On the one hand it is cheap.'],
  [null, 'andererseits', null, 'on the other hand', 'Basics', 'Andererseits ist es klein.', 'On the other hand it is small.'],
  [null, 'somit', null, 'thus, therefore', 'Basics', 'Somit ist die Frage geklärt.', 'Thus the question is settled.'],
  [null, 'folglich', null, 'consequently', 'Basics', 'Folglich müssen wir handeln.', 'Consequently we have to act.'],
  [null, 'dennoch', null, 'nevertheless', 'Basics', 'Es regnet, dennoch gehen wir.', 'It is raining, nevertheless we are going.'],
  [null, 'hingegen', null, 'in contrast, however', 'Basics', 'Sie ist ruhig, er hingegen laut.', 'She is quiet, he however loud.'],
  [null, 'insbesondere', null, 'in particular', 'Basics', 'Insbesondere die Preise steigen.', 'In particular the prices are rising.'],
  [null, 'bevor', null, 'before (conjunction)', 'Basics', 'Wasche die Hände, bevor du isst.', 'Wash your hands before you eat.'],
  [null, 'nachdem', null, 'after (conjunction)', 'Basics', 'Nachdem er kam, begann das Essen.', 'After he arrived, the meal started.'],
  [null, 'obwohl', null, 'although', 'Basics', 'Wir gehen, obwohl es regnet.', 'We are going although it is raining.'],
  [null, 'während', null, 'during, while', 'Basics', 'Während des Films war es still.', 'During the movie it was quiet.'],
  [null, 'seitdem', null, 'since then', 'Time', 'Seitdem wohne ich hier.', 'Since then I have lived here.'],
  [null, 'sobald', null, 'as soon as', 'Basics', 'Sobald es klingelt, öffne ich.', 'As soon as it rings, I open.'],
  [null, 'falls', null, 'if, in case', 'Basics', 'Falls es regnet, bleiben wir.', 'If it rains, we are staying.'],
  // ── B1 extension: abstract nouns ──
  ['die', 'Selbstständigkeit', null, 'self-employment, independence', 'Work', 'Die Selbstständigkeit birgt Risiken.', 'Self-employment involves risks.'],
  [null, 'selbstständig', null, 'self-employed, independent', 'Adjectives', 'Sie arbeitet selbstständig.', 'She works independently.'],
  ['die', 'Herausforderung', 'Herausforderungen', 'challenge', 'Work', 'Die Herausforderung ist groß.', 'The challenge is big.'],
  ['die', 'Schwierigkeit', 'Schwierigkeiten', 'difficulty', 'Society', 'Die Schwierigkeit liegt im Detail.', 'The difficulty lies in the detail.'],
  ['das', 'Verständnis', null, 'understanding', 'Communication', 'Das Verständnis wächst mit der Zeit.', 'Understanding grows with time.'],
  ['die', 'Erkenntnis', 'Erkenntnisse', 'insight, finding', 'Education', 'Die Erkenntnis ist neu.', 'The finding is new.'],
  // M12.3 vocab batch (household, eating out, health, work) — appended 2026-09-29.
  ['das', 'Geschirrtuch', 'Geschirrtücher', 'dish towel', 'Home', 'Das Geschirrtuch hängt am Haken.', 'The dish towel hangs on the hook.'],
  ['der', 'Kochlöffel', 'Kochlöffel', 'wooden spoon', 'Home', 'Der Kochlöffel liegt neben dem Herd.', 'The wooden spoon lies next to the stove.'],
  ['die', 'Schürze', 'Schürzen', 'apron', 'Home', 'Die Schürze hängt in der Küche.', 'The apron hangs in the kitchen.'],
  ['das', 'Waschbecken', 'Waschbecken', 'washbasin, sink', 'Home', 'Das Waschbecken ist verstopft.', 'The washbasin is clogged.'],
  ['der', 'Wäscheständer', 'Wäscheständer', 'drying rack', 'Home', 'Der Wäscheständer steht auf dem Balkon.', 'The drying rack stands on the balcony.'],
  ['die', 'Wäscheklammer', 'Wäscheklammern', 'clothespin', 'Home', 'Die Wäscheklammer hält die Hose.', 'The clothespin holds the pants.'],
  ['der', 'Kleiderbügel', 'Kleiderbügel', 'clothes hanger', 'Home', 'Der Kleiderbügel ist aus Metall.', 'The clothes hanger is made of metal.'],
  ['das', 'Putzmittel', 'Putzmittel', 'cleaning product', 'Home', 'Das Putzmittel steht unter der Spüle.', 'The cleaning product is under the sink.'],
  ['der', 'Gartenschlauch', 'Gartenschläuche', 'garden hose', 'Home', 'Der Gartenschlauch liegt im Garten.', 'The garden hose lies in the garden.'],
  ['die', 'Gartenschere', 'Gartenscheren', 'pruning shears', 'Home', 'Die Gartenschere ist scharf.', 'The pruning shears are sharp.'],
  ['der', 'Lichtschalter', 'Lichtschalter', 'light switch', 'Home', 'Der Lichtschalter ist neben der Tür.', 'The light switch is next to the door.'],
  ['der', 'Türgriff', 'Türgriffe', 'door handle', 'Home', 'Der Türgriff ist aus Messing.', 'The door handle is made of brass.'],
  ['der', 'Schlüsselbund', 'Schlüsselbünde', 'bunch of keys', 'Home', 'Der Schlüsselbund liegt auf dem Tisch.', 'The bunch of keys is on the table.'],
  ['die', 'Alarmanlage', 'Alarmanlagen', 'alarm system', 'Home', 'Die Alarmanlage ist scharf geschaltet.', 'The alarm system is armed.'],
  ['der', 'Hauseingang', 'Hauseingänge', 'building entrance', 'Home', 'Der Hauseingang ist frisch gestrichen.', 'The building entrance is freshly painted.'],
  ['der', 'Fahrstuhl', 'Fahrstühle', 'elevator, lift', 'Home', 'Der Fahrstuhl ist wieder in Ordnung.', 'The elevator is working again.'],
  ['der', 'Umzugskarton', 'Umzugskartons', 'moving box', 'Home', 'Der Umzugskarton ist schwer.', 'The moving box is heavy.'],
  ['der', 'Umzug', 'Umzüge', 'move, relocation', 'Home', 'Der Umzug ist am Samstag.', 'The move is on Saturday.'],
  ['die', 'Tiefgarage', 'Tiefgaragen', 'underground garage', 'Home', 'Die Tiefgarage hat vierzig Plätze.', 'The underground garage has forty spaces.'],
  ['der', 'Rasenmäher', 'Rasenmäher', 'lawnmower', 'Home', 'Der Rasenmäher ist elektrisch.', 'The lawnmower is electric.'],
  ['die', 'Hecke', 'Hecken', 'hedge', 'Home', 'Die Hecke wächst schnell.', 'The hedge grows quickly.'],
  ['die', 'Mülltonne', 'Mülltonnen', 'garbage bin', 'Home', 'Die Mülltonne steht an der Straße.', 'The garbage bin stands by the street.'],
  ['die', 'Fernbedienung', 'Fernbedienungen', 'remote control', 'Home', 'Die Fernbedienung liegt auf dem Sofa.', 'The remote control is on the sofa.'],
  ['die', 'Taschenlampe', 'Taschenlampen', 'flashlight', 'Home', 'Die Taschenlampe braucht eine neue Batterie.', 'The flashlight needs a new battery.'],
  ['das', 'Streichholz', 'Streichhölzer', 'match', 'Home', 'Das Streichholz ist angezündet.', 'The match is lit.'],
  ['die', 'Backform', 'Backformen', 'baking tin', 'Home', 'Die Backform ist aus Silikon.', 'The baking tin is made of silicone.'],
  ['der', 'Toaster', 'Toaster', 'toaster', 'Home', 'Der Toaster wird heiß.', 'The toaster is getting hot.'],
  ['die', 'Kehrschaufel', 'Kehrschaufeln', 'dustpan', 'Home', 'Die Kehrschaufel gehört zum Besen.', 'The dustpan belongs with the broom.'],
  ['der', 'Abwasch', null, 'washing-up', 'Home', 'Der Abwasch wartet im Spülbecken.', 'The washing-up is waiting in the sink.'],
  ['der', 'Föhn', 'Föhne', 'hairdryer', 'Home', 'Der Föhn ist zu laut.', 'The hairdryer is too loud.'],
  ['die', 'Bettwäsche', null, 'bed linen', 'Home', 'Die Bettwäsche ist frisch bezogen.', 'The bed linen is freshly put on.'],
  ['das', 'Kopfkissen', 'Kopfkissen', 'pillow', 'Home', 'Das Kopfkissen ist aus Daunen.', 'The pillow is made of down.'],
  ['das', 'Duschgel', null, 'shower gel', 'Home', 'Das Duschgel ist leer.', 'The shower gel is empty.'],
  ['die', 'Zahnbürste', 'Zahnbürsten', 'toothbrush', 'Home', 'Die Zahnbürste ist neu.', 'The toothbrush is new.'],
  ['die', 'Zahnpasta', null, 'toothpaste', 'Home', 'Die Zahnpasta schmeckt nach Minze.', 'The toothpaste tastes of mint.'],
  ['der', 'Rasierer', 'Rasierer', 'razor, shaver', 'Home', 'Der Rasierer liegt im Bad.', 'The shaver is in the bathroom.'],
  [null, 'rasieren', null, 'to shave', 'Home', 'Er rasiert sich vor dem Spiegel.', 'He is shaving in front of the mirror.'],
  ['die', 'Waage', 'Waagen', 'scales', 'Home', 'Die Waage zeigt zwei Kilo mehr.', 'The scales show two kilos more.'],
  ['der', 'Müllbeutel', 'Müllbeutel', 'garbage bag', 'Home', 'Der Müllbeutel passt in die Tonne.', 'The garbage bag fits in the bin.'],
  ['die', 'Gießkanne', 'Gießkannen', 'watering can', 'Home', 'Die Gießkanne steht neben der Tür.', 'The watering can stands next to the door.'],
  ['die', 'Zimmerpflanze', 'Zimmerpflanzen', 'houseplant', 'Home', 'Die Zimmerpflanze braucht Wasser.', 'The houseplant needs water.'],
  ['die', 'Fensterbank', 'Fensterbänke', 'windowsill', 'Home', 'Die Fensterbank ist breit.', 'The windowsill is wide.'],
  ['der', 'Kamin', 'Kamine', 'fireplace, chimney', 'Home', 'Der Kamin wärmt das Zimmer.', 'The fireplace warms the room.'],
  ['der', 'Ofen', 'Öfen', 'oven, stove, furnace', 'Home', 'Der Ofen macht die Wohnung warm.', 'The stove makes the apartment warm.'],
  ['der', 'Filter', 'Filter', 'filter', 'Home', 'Der Filter der Kaffeemaschine ist neu.', 'The coffee machine filter is new.'],
  ['der', 'Grill', 'Grills', 'grill, barbecue', 'Home', 'Der Grill steht im Garten.', 'The barbecue stands in the garden.'],
  [null, 'grillen', null, 'to grill, to barbecue', 'Home', 'Wir grillen im Sommer oft.', 'We often barbecue in summer.'],
  ['der', 'Schraubenzieher', 'Schraubenzieher', 'screwdriver', 'Home', 'Der Schraubenzieher liegt im Werkzeugkasten.', 'The screwdriver is in the toolbox.'],
  ['die', 'Zange', 'Zangen', 'pliers', 'Home', 'Die Zange ist rostig.', 'The pliers are rusty.'],
  ['die', 'Säge', 'Sägen', 'saw', 'Home', 'Die Säge ist scharf.', 'The saw is sharp.'],
  ['der', 'Pinsel', 'Pinsel', 'paintbrush', 'Home', 'Der Pinsel ist noch nass.', 'The paintbrush is still wet.'],
  ['die', 'Tapete', 'Tapeten', 'wallpaper', 'Home', 'Die Tapete ist gestreift.', 'The wallpaper is striped.'],
  ['der', 'Dübel', 'Dübel', 'wall plug, dowel', 'Home', 'Der Dübel hält die Schraube.', 'The wall plug holds the screw.'],
  ['der', 'Zähler', 'Zähler', 'meter, counter', 'Home', 'Der Zähler steht im Flur.', 'The meter is in the hallway.'],
  [null, 'ablesen', null, 'to read off (a meter)', 'Home', 'Er liest den Stromzähler ab.', 'He is reading the electricity meter.'],
  [null, 'tapezieren', null, 'to wallpaper', 'Home', 'Wir tapezieren das Schlafzimmer neu.', 'We are wallpapering the bedroom.'],
  [null, 'montieren', null, 'to assemble, to mount', 'Home', 'Er montiert das Regal an die Wand.', 'He is mounting the shelf on the wall.'],
  ['der', 'Riss', 'Risse', 'crack', 'Home', 'Der Riss in der Wand ist neu.', 'The crack in the wall is new.'],
  [null, 'undicht', null, 'leaky', 'Home', 'Das Dach ist undicht.', 'The roof is leaky.'],
  [null, 'tropfen', null, 'to drip', 'Home', 'Der Wasserhahn tropft.', 'The faucet is dripping.'],
  ['der', 'Tropfen', 'Tropfen', 'drop', 'Home', 'Ein Tropfen fällt auf den Boden.', 'A drop falls on the floor.'],
  ['der', 'Kleber', null, 'glue', 'Home', 'Der Kleber hält gut.', 'The glue holds well.'],
  [null, 'kleben', null, 'to glue, to stick', 'Home', 'Ich klebe das Poster an die Wand.', 'I am sticking the poster to the wall.'],
  ['das', 'Klebeband', 'Klebebänder', 'adhesive tape', 'Home', 'Das Klebeband ist in der Schublade.', 'The adhesive tape is in the drawer.'],
  ['das', 'Möbel', 'Möbel', 'piece of furniture', 'Home', 'Das Möbel ist aus Massivholz.', 'The piece of furniture is solid wood.'],
  ['die', 'Einrichtung', 'Einrichtungen', 'furnishings', 'Home', 'Die Einrichtung ist modern.', 'The furnishings are modern.'],
  [null, 'einrichten', null, 'to furnish, to set up', 'Home', 'Wir richten die neue Wohnung ein.', 'We are furnishing the new apartment.'],
  ['der', 'Vorhang', 'Vorhänge', 'curtain, drapes', 'Home', 'Der Vorhang ist dunkelrot.', 'The curtain is dark red.'],
  ['die', 'Fliese', 'Fliesen', 'tile', 'Home', 'Die Fliese im Bad ist gesprungen.', 'The tile in the bathroom is cracked.'],
  ['die', 'Beleuchtung', null, 'lighting', 'Home', 'Die Beleuchtung ist zu dunkel.', 'The lighting is too dark.'],
  ['der', 'Stecker', 'Stecker', 'plug', 'Home', 'Der Stecker ist defekt.', 'The plug is defective.'],
  ['das', 'Backblech', 'Backbleche', 'baking sheet', 'Home', 'Das Backblech ist eingefettet.', 'The baking sheet is greased.'],
  ['das', 'Bügeleisen', 'Bügeleisen', 'iron', 'Home', 'Das Bügeleisen ist noch heiß.', 'The iron is still hot.'],
  ['das', 'Bügelbrett', 'Bügelbretter', 'ironing board', 'Home', 'Das Bügelbrett steht im Schlafzimmer.', 'The ironing board stands in the bedroom.'],
  ['der', 'Wäschekorb', 'Wäschekörbe', 'laundry basket', 'Home', 'Der Wäschekorb ist voll.', 'The laundry basket is full.'],
  ['der', 'Dosenöffner', 'Dosenöffner', 'can opener', 'Home', 'Der Dosenöffner ist in der Schublade.', 'The can opener is in the drawer.'],
  ['der', 'Korkenzieher', 'Korkenzieher', 'corkscrew', 'Home', 'Der Korkenzieher öffnet die Flasche.', 'The corkscrew opens the bottle.'],
  ['der', 'Standmixer', 'Standmixer', 'blender', 'Home', 'Der Standmixer püriert die Suppe.', 'The blender purees the soup.'],
  ['die', 'Spüle', 'Spülen', 'sink', 'Home', 'Die Spüle ist aus Edelstahl.', 'The sink is made of stainless steel.'],
  ['der', 'Abfluss', 'Abflüsse', 'drain', 'Home', 'Der Abfluss ist verstopft.', 'The drain is clogged.'],
  ['das', 'Gefrierfach', 'Gefrierfächer', 'freezer compartment', 'Home', 'Das Gefrierfach voller Eis.', 'The freezer compartment is full of ice.'],
  ['der', 'Trockner', 'Trockner', 'dryer', 'Home', 'Der Trockner trocknet die Wäsche.', 'The dryer dries the laundry.'],
  ['der', 'Rauchmelder', 'Rauchmelder', 'smoke detector', 'Home', 'Der Rauchmelder hängt an der Decke.', 'The smoke detector hangs from the ceiling.'],
  ['der', 'Feuerlöscher', 'Feuerlöscher', 'fire extinguisher', 'Home', 'Der Feuerlöscher hängt im Flur.', 'The fire extinguisher hangs in the hallway.'],
  ['die', 'Hausapotheke', 'Hausapotheken', 'home medicine cabinet', 'Home', 'Die Hausapotheke ist vollständig.', 'The home medicine cabinet is complete.'],
  ['das', 'Treppenhaus', 'Treppenhäuser', 'stairwell', 'Home', 'Das Treppenhaus wird gereinigt.', 'The stairwell is being cleaned.'],
  ['die', 'Mülltrennung', null, 'waste separation', 'Home', 'Die Mülltrennung ist hier Pflicht.', 'Waste separation is mandatory here.'],
  ['das', 'Recycling', null, 'recycling', 'Home', 'Das Recycling spart Rohstoffe.', 'Recycling saves raw materials.'],
  ['der', 'Recyclinghof', 'Recyclinghöfe', 'recycling center', 'Home', 'Der Recyclinghof ist am Stadtrand.', 'The recycling center is on the edge of town.'],
  ['der', 'Flohmarkt', 'Flohmärkte', 'flea market', 'Home', 'Der Flohmarkt öffnet um acht.', 'The flea market opens at eight.'],
  ['das', 'Eigenheim', 'Eigenheime', 'own home', 'Home', 'Das Eigenheim ist abbezahlt.', 'The own home is paid off.'],
  ['der', 'Mitbewohner', 'Mitbewohner', 'roommate, flatmate', 'Home', 'Der Mitbewohner kocht heute.', 'The roommate is cooking today.'],
  [null, 'staubig', null, 'dusty', 'Home', 'Das Regal ist staubig.', 'The shelf is dusty.'],
  [null, 'zerbrechlich', null, 'fragile, breakable', 'Home', 'Das Glas ist zerbrechlich.', 'The glass is fragile.'],
  [null, 'unordentlich', null, 'messy, untidy', 'Home', 'Das Kinderzimmer ist unordentlich.', "The children's room is messy."],
  ['das', 'Buffet', 'Buffets', 'buffet', 'Food', 'Das Buffet ist reich gedeckt.', 'The buffet is lavishly laid out.'],
  ['die', 'Vorspeise', 'Vorspeisen', 'starter, appetizer', 'Food', 'Die Vorspeise ist kalt.', 'The starter is cold.'],
  ['das', 'Hauptgericht', 'Hauptgerichte', 'main course', 'Food', 'Das Hauptgericht kommt gleich.', 'The main course is coming soon.'],
  ['die', 'Bedienung', 'Bedienungen', 'server, waitstaff', 'Food', 'Die Bedienung ist sehr nett.', 'The server is very nice.'],
  ['die', 'Imbissbude', 'Imbissbuden', 'snack bar, kiosk', 'Food', 'Die Imbissbude hat mittags offen.', 'The snack bar is open at lunchtime.'],
  ['das', 'Besteck', 'Bestecke', 'cutlery', 'Food', 'Das Besteck liegt neben dem Teller.', 'The cutlery is next to the plate.'],
  ['die', 'Kanne', 'Kannen', 'pot, jug', 'Food', 'Die Kanne ist voller Kaffee.', 'The pot is full of coffee.'],
  ['die', 'Untertasse', 'Untertassen', 'saucer', 'Food', 'Die Untertasse passt zur Tasse.', 'The saucer matches the cup.'],
  ['die', 'Schüssel', 'Schüsseln', 'bowl', 'Food', 'Die Schüssel ist aus Keramik.', 'The bowl is made of ceramic.'],
  ['die', 'Reibe', 'Reiben', 'grater', 'Food', 'Die Reibe ist scharf.', 'The grater is sharp.'],
  ['die', 'Sahne', null, 'cream', 'Food', 'Die Sahne wird geschlagen.', 'The cream is being whipped.'],
  ['der', 'Quark', null, 'quark, curd cheese', 'Food', 'Der Quark schmeckt säuerlich.', 'The quark tastes sour.'],
  ['der', 'Pudding', 'Puddinge', 'pudding', 'Food', 'Der Pudding ist aus Schokolade.', 'The pudding is chocolate.'],
  ['die', 'Torte', 'Torten', 'gateau, torte', 'Food', 'Die Torte hat acht Stücke.', 'The torte has eight pieces.'],
  ['die', 'Beere', 'Beeren', 'berry', 'Food', 'Die Beere ist reif und süß.', 'The berry is ripe and sweet.'],
  ['der', 'Pfirsich', 'Pfirsiche', 'peach', 'Food', 'Der Pfirsich ist saftig.', 'The peach is juicy.'],
  ['die', 'Birne', 'Birnen', 'pear', 'Food', 'Die Birne ist noch hart.', 'The pear is still hard.'],
  ['die', 'Melone', 'Melonen', 'melon', 'Food', 'Die Melone ist schwer.', 'The melon is heavy.'],
  ['die', 'Traube', 'Trauben', 'grape', 'Food', 'Die Traube ist süß.', 'The grape is sweet.'],
  ['die', 'Brühe', 'Brühen', 'broth, stock', 'Food', 'Die Brühe ist salzig.', 'The broth is salty.'],
  ['der', 'Braten', 'Braten', 'roast', 'Food', 'Der Braten ist zart.', 'The roast is tender.'],
  ['das', 'Rührei', null, 'scrambled eggs', 'Food', 'Das Rührei ist fertig.', 'The scrambled eggs are ready.'],
  ['das', 'Spiegelei', 'Spiegeleier', 'fried egg', 'Food', 'Das Spiegelei ist zu salzig.', 'The fried egg is too salty.'],
  ['der', 'Lachs', 'Lachse', 'salmon', 'Food', 'Der Lachs ist geräuchert.', 'The salmon is smoked.'],
  ['das', 'Vollkornbrot', 'Vollkornbrote', 'whole-grain bread', 'Food', 'Das Vollkornbrot ist gesund.', 'The whole-grain bread is healthy.'],
  ['die', 'Bratwurst', 'Bratwürste', 'bratwurst', 'Food', 'Die Bratwurst kommt vom Grill.', 'The bratwurst comes from the grill.'],
  ['die', 'Currywurst', 'Currywürste', 'currywurst', 'Food', 'Die Currywurst ist eine Berliner Spezialität.', 'Currywurst is a Berlin specialty.'],
  ['die', 'Kantine', 'Kantinen', 'canteen', 'Food', 'Die Kantine öffnet um zwölf.', 'The canteen opens at twelve.'],
  ['die', 'Mensa', 'Mensen', 'university canteen', 'Food', 'Die Mensa ist um eins voll.', 'The university canteen is full at one.'],
  ['die', 'Lieferung', 'Lieferungen', 'delivery', 'Food', 'Die Lieferung kommt in zwanzig Minuten.', 'The delivery arrives in twenty minutes.'],
  [null, 'liefern', null, 'to deliver', 'Food', 'Der Bringdienst liefert das Essen.', 'The delivery service delivers the food.'],
  [null, 'einpacken', null, 'to wrap up, to pack', 'Food', 'Können Sie das einpacken?', 'Could you wrap that up?'],
  [null, 'aufwärmen', null, 'to reheat', 'Food', 'Ich wärme die Suppe auf.', 'I am reheating the soup.'],
  [null, 'schlucken', null, 'to swallow', 'Food', 'Das Kind schluckt die Tablette.', 'The child swallows the tablet.'],
  [null, 'kauen', null, 'to chew', 'Food', 'Kau den Apfel langsam!', 'Chew the apple slowly!'],
  [null, 'knusprig', null, 'crispy, crunchy', 'Food', 'Die Haut vom Braten ist knusprig.', 'The skin of the roast is crispy.'],
  [null, 'fett', null, 'fatty, greasy; fat', 'Food', 'Das Fleisch ist zu fett.', 'The meat is too fatty.'],
  [null, 'reif', null, 'ripe; mature', 'Food', 'Die Banane ist reif.', 'The banana is ripe.'],
  ['das', 'Haltbarkeitsdatum', 'Haltbarkeitsdaten', 'best-before date', 'Food', 'Das Haltbarkeitsdatum ist morgen.', 'The best-before date is tomorrow.'],
  ['die', 'Scheibe', 'Scheiben', 'slice', 'Food', 'Die Scheibe Brot ist dick.', 'The slice of bread is thick.'],
  ['der', 'Schluck', 'Schücke', 'swig, sip', 'Food', 'Er nimmt einen Schluck Wasser.', 'He takes a sip of water.'],
  ['der', 'Teig', 'Teige', 'dough, batter', 'Food', 'Der Teig muss noch ruhen.', 'The dough still has to rest.'],
  [null, 'umrühren', null, 'to stir', 'Food', 'Rühr die Soße um!', 'Stir the sauce!'],
  ['das', 'Tagesgericht', 'Tagesgerichte', 'dish of the day', 'Food', 'Das Tagesgericht kostet sechs Euro.', 'The dish of the day costs six euros.'],
  ['der', 'Notruf', 'Notrufe', 'emergency call', 'Health', 'Der Notruf geht an die 112.', 'The emergency call goes to 112.'],
  ['der', 'Rettungswagen', 'Rettungswagen', 'ambulance', 'Health', 'Der Rettungswagen kommt mit Blaulicht.', 'The ambulance comes with flashing lights.'],
  [null, 'pflegen', null, 'to care for, to nurse', 'Health', 'Sie pflegt ihre kranke Mutter.', 'She is caring for her sick mother.'],
  ['die', 'Erste Hilfe', null, 'first aid', 'Health', 'Die Erste Hilfe rettete sein Leben.', 'The first aid saved his life.'],
  ['der', 'Knochenbruch', 'Knochenbrüche', 'bone fracture', 'Health', 'Der Knochenbruch heilt in sechs Wochen.', 'The bone fracture heals in six weeks.'],
  ['der', 'Krampf', 'Krämpfe', 'cramp, spasm', 'Health', 'Der Krampf im Bein war schmerzhaft.', 'The cramp in the leg was painful.'],
  ['der', 'Schnupfen', null, 'head cold', 'Health', 'Der Schnupfen dauert drei Tage.', 'The head cold lasts three days.'],
  [null, 'allergisch', null, 'allergic', 'Health', 'Er ist allergisch gegen Katzen.', 'He is allergic to cats.'],
  ['der', 'Sonnenbrand', null, 'sunburn', 'Health', 'Der Sonnenbrand tut weh.', 'The sunburn hurts.'],
  ['die', 'Verbrennung', 'Verbrennungen', 'burn', 'Health', 'Die Verbrennung muss gekühlt werden.', 'The burn has to be cooled.'],
  ['der', 'Hausarzt', 'Hausärzte', 'family doctor', 'Health', 'Der Hausarzt kennt die Familie gut.', 'The family doctor knows the family well.'],
  ['das', 'Wartezimmer', 'Wartezimmer', 'waiting room', 'Health', 'Das Wartezimmer ist voll.', 'The waiting room is full.'],
  ['der', 'Arztbesuch', 'Arztbesuche', 'visit to the doctor', 'Health', 'Der Arztbesuch dauert eine Stunde.', 'The visit to the doctor takes an hour.'],
  [null, 'schwindlig', null, 'dizzy', 'Health', 'Mir ist schwindlig in der Höhe.', 'I feel dizzy up high.'],
  [null, 'atmen', null, 'to breathe', 'Health', 'Atme tief durch!', 'Breathe deeply!'],
  [null, 'niesen', null, 'to sneeze', 'Health', 'Er niest dreimal hintereinander.', 'He sneezes three times in a row.'],
  [null, 'sich erkälten', null, 'to catch a cold', 'Health', 'Ich erkälte mich jedes Jahr im Winter.', 'I catch a cold every year in winter.'],
  [null, 'schwitzen', null, 'to sweat', 'Health', 'Beim Sport schwitze ich viel.', 'I sweat a lot during sports.'],
  [null, 'hinfallen', null, 'to fall down', 'Health', 'Das Kind fällt im Sand hin.', 'The child falls down in the sand.'],
  [null, 'ausrutschen', null, 'to slip', 'Health', 'Er rutscht auf dem Eis aus.', 'He slips on the ice.'],
  ['der', 'Kreislauf', 'Kreisläufe', 'circulation', 'Health', 'Der Kreislauf ist wieder stabil.', 'The circulation is stable again.'],
  ['das', 'Vitamin', 'Vitamine', 'vitamin', 'Health', 'Das Vitamin C steckt in Orangen.', 'Vitamin C is in oranges.'],
  ['der', 'Hustensaft', 'Hustensäfte', 'cough syrup', 'Health', 'Der Hustensaft schmeckt süß.', 'The cough syrup tastes sweet.'],
  ['die', 'Sonnencreme', 'Sonnencremes', 'sunscreen', 'Health', 'Die Sonnencreme schützt die Haut.', 'The sunscreen protects the skin.'],
  [null, 'jucken', null, 'to itch', 'Health', 'Der Mückenstich juckt stark.', 'The mosquito bite itches badly.'],
  ['die', 'Blutgruppe', 'Blutgruppen', 'blood type', 'Health', 'Die Blutgruppe ist 0 negativ.', 'The blood type is O negative.'],
  ['der', 'Muskelkater', null, 'muscle soreness', 'Health', 'Der Muskelkater hält zwei Tage.', 'The muscle soreness lasts two days.'],
  ['der', 'Rollstuhl', 'Rollstühle', 'wheelchair', 'Health', 'Der Rollstuhl ist zusammenklappbar.', 'The wheelchair is foldable.'],
  ['das', 'Fieberthermometer', 'Fieberthermometer', 'fever thermometer', 'Health', 'Das Fieberthermometer zeigt 38 Grad.', 'The fever thermometer shows 38 degrees.'],
  ['das', 'Schmerzmittel', 'Schmerzmittel', 'painkiller', 'Health', 'Das Schmerzmittel wirkt schnell.', 'The painkiller works quickly.'],
  ['die', 'Diät', 'Diäten', 'diet', 'Health', 'Die Diät dauert einen Monat.', 'The diet lasts a month.'],
  ['die', 'Überstunde', 'Überstunden', 'overtime hour', 'Work', 'Die Überstunde wird bezahlt.', 'The overtime hour is paid.'],
  ['das', 'Homeoffice', 'Homeoffices', 'home office', 'Work', 'Das Homeoffice ist zweimal pro Woche.', 'The home office is twice a week.'],
  ['der', 'Aktenordner', 'Aktenordner', 'binder, file folder', 'Work', 'Der Aktenordner ist grau.', 'The binder is gray.'],
  ['die', 'Mappe', 'Mappen', 'folder, portfolio', 'Work', 'Die Mappe enthält die Unterlagen.', 'The folder contains the documents.'],
  ['der', 'Stempel', 'Stempel', 'stamp', 'Work', 'Der Stempel bestätigt den Antrag.', 'The stamp confirms the application.'],
  [null, 'vereinbaren', null, 'to arrange, to agree on', 'Work', 'Wir vereinbaren einen Termin.', 'We are arranging an appointment.'],
  [null, 'absagen', null, 'to cancel', 'Work', 'Er sagt das Meeting ab.', 'He is canceling the meeting.'],
  ['das', 'Praktikum', 'Praktika', 'internship', 'Work', 'Das Praktikum dauert drei Monate.', 'The internship lasts three months.'],
  ['der', 'Praktikant', 'Praktikanten', 'intern', 'Work', 'Der Praktikant lernt schnell.', 'The intern learns quickly.'],
  ['der', 'Dienst', 'Dienste', 'service, duty, shift', 'Work', 'Der Dienst beginnt um sieben.', 'The shift begins at seven.'],
  ['das', 'Seminar', 'Seminare', 'seminar', 'Work', 'Das Seminar findet online statt.', 'The seminar takes place online.'],
  ['die', 'Kopie', 'Kopien', 'copy', 'Work', 'Die Kopie ist unscharf.', 'The copy is blurry.'],
  [null, 'kopieren', null, 'to copy', 'Work', 'Er kopiert die Unterlagen.', 'He is copying the documents.'],
  ['das', 'Notizbuch', 'Notizbücher', 'notebook', 'Work', 'Das Notizbuch passt in jede Tasche.', 'The notebook fits in any bag.'],
  ['das', 'Arbeitsklima', null, 'work atmosphere', 'Work', 'Das Arbeitsklima ist entspannt.', 'The work atmosphere is relaxed.'],
  ['die', 'Teamarbeit', null, 'teamwork', 'Work', 'Die Teamarbeit macht Spaß.', 'The teamwork is fun.'],
  ['die', 'Anwesenheit', null, 'attendance, presence', 'Work', 'Die Anwesenheit wird notiert.', 'The attendance is being noted.'],
  [null, 'anwesend', null, 'present, in attendance', 'Work', 'Alle sind anwesend.', 'Everyone is present.'],
  ['die', 'Abwesenheit', 'Abwesenheiten', 'absence', 'Work', 'Die Abwesenheit ist genehmigt.', 'The absence is approved.'],
  ['das', 'Handout', 'Handouts', 'handout', 'Work', 'Das Handout fasst die Präsentation zusammen.', 'The handout summarizes the presentation.'],
  ['die', 'Wartezeit', 'Wartezeiten', 'waiting time', 'Work', 'Die Wartezeit betrug zehn Minuten.', 'The waiting time was ten minutes.'],
  ['der', 'Kalender', 'Kalender', 'calendar', 'Work', 'Der Kalender hängt im Büro.', 'The calendar hangs in the office.'],
  [null, 'gültig', null, 'valid', 'Work', 'Der Pass ist noch zwei Jahre gültig.', 'The passport is still valid for two years.'],
  ['der', 'Terminplan', 'Terminpläne', 'appointment schedule', 'Work', 'Der Terminplan ist voll.', 'The appointment schedule is full.'],
  ['der', 'Arbeitsplan', 'Arbeitspläne', 'work schedule', 'Work', 'Der Arbeitsplan hängt an der Wand.', 'The work schedule hangs on the wall.'],
  ['die', 'Frühschicht', 'Frühschichten', 'early shift', 'Work', 'Die Frühschicht beginnt um sechs.', 'The early shift starts at six.'],
  ['die', 'Spätschicht', 'Spätschichten', 'late shift', 'Work', 'Die Spätschicht endet um zweiundzwanzig Uhr.', 'The late shift ends at ten pm.'],
  ['die', 'Nachtschicht', 'Nachtschichten', 'night shift', 'Work', 'Die Nachtschicht ist anstrengend.', 'The night shift is exhausting.'],
  ['die', 'Anweisung', 'Anweisungen', 'instruction, directive', 'Work', 'Die Anweisung kommt vom Chef.', 'The instruction comes from the boss.'],
  ['der', 'Stundenzettel', 'Stundenzettel', 'time sheet', 'Work', 'Der Stundenzettel wird freitags abgegeben.', 'The time sheet is handed in on Fridays.'],
  ['die', 'Zeiterfassung', null, 'time tracking', 'Work', 'Die Zeiterfassung läuft digital.', 'The time tracking runs digitally.'],
  ['der', 'Handwerker', 'Handwerker', 'tradesman, craftsman', 'Work', 'Der Handwerker repariert die Heizung.', 'The tradesman is repairing the heating.'],
  ['die', 'Werkstatt', 'Werkstätten', 'workshop', 'Work', 'Die Werkstatt ist gut ausgestattet.', 'The workshop is well equipped.'],
  ['die', 'Maschine', 'Maschinen', 'machine', 'Work', 'Die Maschine läuft wieder.', 'The machine is running again.'],
  ['die', 'Fabrik', 'Fabriken', 'factory', 'Work', 'Die Fabrik stellt Autos her.', 'The factory produces cars.'],
  ['der', 'Bauarbeiter', 'Bauarbeiter', 'construction worker', 'Work', 'Der Bauarbeiter trägt einen Helm.', 'The construction worker wears a helmet.'],
  ['der', 'Architekt', 'Architekten', 'architect', 'Work', 'Der Architekt plant das neue Haus.', 'The architect is planning the new house.'],
  ['der', 'Ingenieur', 'Ingenieure', 'engineer', 'Work', 'Der Ingenieur prüft die Brücke.', 'The engineer is inspecting the bridge.'],
  ['das', 'Lager', 'Lager', 'warehouse, storage', 'Work', 'Das Lager ist vollständig inventarisiert.', 'The warehouse is fully inventoried.'],
  [null, 'verpacken', null, 'to package, to wrap', 'Work', 'Die Ware wird verpackt.', 'The goods are being packaged.'],
  ['das', 'Etikett', 'Etiketten', 'label', 'Work', 'Das Etikett zeigt den Preis.', 'The label shows the price.'],
  [null, 'kontrollieren', null, 'to check, to control', 'Work', 'Der Zoll kontrolliert die Pässe.', 'Customs is checking the passports.'],
  ['der', 'Firmenwagen', 'Firmenwagen', 'company car', 'Work', 'Der Firmenwagen ist neu.', 'The company car is new.'],
  [null, 'beauftragen', null, 'to commission, to entrust', 'Work', 'Die Firma beauftragt eine Agentur.', 'The company is commissioning an agency.'],
  ['der', 'Arbeitsplatz', 'Arbeitsplätze', 'job, workplace', 'Work', 'Der Arbeitsplatz ist sicher.', 'The job is secure.'],
  ['der', 'Arbeitsalltag', null, 'day-to-day work', 'Work', 'Der Arbeitsalltag beginnt um acht.', 'The day-to-day work begins at eight.'],
  ['der', 'Briefumschlag', 'Briefumschläge', 'envelope', 'Work', 'Der Briefumschlag ist frankiert.', 'The envelope is stamped.'],
  ['der', 'Blutdruck', null, 'blood pressure', 'Health', 'Der Blutdruck ist zu hoch.', 'The blood pressure is too high.'],
  ['die', 'Sitzung', 'Sitzungen', 'meeting, sitting', 'Work', 'Die Sitzung dauert zwei Stunden.', 'The meeting lasts two hours.'],
  ['der', 'Arbeitstag', 'Arbeitstage', 'working day', 'Work', 'Der Arbeitstag beginnt um acht.', 'The working day begins at eight.'],
  ['die', 'Schale', 'Schalen', 'peel, shell; bowl', 'Food', 'Die Schale der Zitrone ist dick.', 'The peel of the lemon is thick.'],
  ['das', 'Hackfleisch', null, 'minced meat', 'Food', 'Das Hackfleisch ist mager.', 'The minced meat is lean.'],
  ['die', 'Krankenschwester', 'Krankenschwestern', 'nurse', 'Health', 'Die Krankenschwester weckt den Patienten.', 'The nurse wakes the patient.'],
  ['die', 'Teilnahme', 'Teilnahmen', 'participation', 'Work', 'Die Teilnahme an der Schulung ist kostenlos.', 'Participation in the training is free.'],
  ['die', 'Gebrauchsanweisung', 'Gebrauchsanweisungen', 'instructions for use', 'Work', 'Die Gebrauchsanweisung erklärt jede Taste.', 'The instructions explain every button.'],
  [null, 'verlängern', null, 'to extend, to prolong', 'Work', 'Wir verlängern den Vertrag um ein Jahr.', 'We are extending the contract by a year.'],
  [null, 'ungültig', null, 'invalid, void', 'Work', 'Der Gutschein ist ungültig.', 'The voucher is invalid.'],
  ['das', 'Schlafmittel', 'Schlafmittel', 'sleeping pill', 'Health', 'Das Schlafmittel wirkt schnell.', 'The sleeping pill works quickly.'],
  ['das', 'Bargeld', null, 'cash', 'Work', 'Das Bargeld wird gezählt.', 'The cash is being counted.'],
  // M12.4 travel/transport/authorities batch (Reisen/Verkehr, Behörden/Ämter)
  ['der', 'Zugbegleiter', 'Zugbegleiter', 'train attendant', 'Transport', 'Der Zugbegleiter kontrolliert die Tickets.', 'The train attendant checks the tickets.'],
  ['der', 'Speisewagen', 'Speisewagen', 'dining car', 'Transport', 'Im Speisewagen gibt es Kaffee.', 'There is coffee in the dining car.'],
  ['die', 'Fahrgemeinschaft', 'Fahrgemeinschaften', 'carpool', 'Transport', 'Die Fahrgemeinschaft spart Benzin.', 'The carpool saves gasoline.'],
  ['die', 'Mitfahrgelegenheit', 'Mitfahrgelegenheiten', 'ride share', 'Transport', 'Die Mitfahrgelegenheit finde ich im Internet.', 'I find the ride share on the internet.'],
  [null, 'schwarzfahren', null, 'to ride without a ticket', 'Transport', 'Wer schwarzfährt, zahlt eine Strafe.', 'Anyone who rides without a ticket pays a fine.'],
  ['der', 'Kontrolleur', 'Kontrolleure', 'inspector, ticket checker', 'Transport', 'Der Kontrolleur prüft die Karten.', 'The inspector checks the tickets.'],
  ['der', 'Zuschlag', 'Zuschläge', 'supplement, surcharge', 'Transport', 'Für den Schnellzug zahlt man einen Zuschlag.', 'You pay a supplement for the express train.'],
  ['die', 'Parklücke', 'Parklücken', 'parking spot', 'City', 'Hier ist eine Parklücke frei.', 'There is a free parking spot here.'],
  ['die', 'Fahrradkette', 'Fahrradketten', 'bicycle chain', 'Transport', 'Die Fahrradkette braucht Öl.', 'The bicycle chain needs oil.'],
  ['der', 'Fahrradhelm', 'Fahrradhelme', 'bicycle helmet', 'Transport', 'Der Fahrradhelm schützt den Kopf.', 'The bicycle helmet protects the head.'],
  ['der', 'Fahrradverleih', 'Fahrradverleihe', 'bike rental', 'Travel', 'Am Bahnhof gibt es einen Fahrradverleih.', 'There is a bike rental at the station.'],
  ['der', 'Verleih', 'Verleihe', 'rental', 'Travel', 'Der Verleih ist erst ab zehn Uhr offen.', 'The rental only opens at ten.'],
  ['die', 'Radtour', 'Radtouren', 'bike tour', 'Travel', 'Die Radtour dauert den ganzen Tag.', 'The bike tour takes the whole day.'],
  ['der', 'Kreisverkehr', 'Kreisverkehre', 'roundabout', 'Transport', 'Der Kreisverkehr hat drei Ausfahrten.', 'The roundabout has three exits.'],
  ['die', 'Einfahrt', 'Einfahrten', 'entrance (for vehicles)', 'Transport', 'Die Einfahrt bitte freihalten.', 'Please keep the entrance clear.'],
  ['die', 'Kurve', 'Kurven', 'curve, bend', 'Transport', 'Nimm die nächste Kurve langsam.', 'Take the next curve slowly.'],
  ['der', 'Scheinwerfer', 'Scheinwerfer', 'headlight', 'Transport', 'Der linke Scheinwerfer ist kaputt.', 'The left headlight is broken.'],
  ['das', 'Rücklicht', 'Rücklichter', 'tail light', 'Transport', 'Das Rücklicht funktioniert nicht.', 'The tail light does not work.'],
  ['der', 'Blinker', 'Blinker', 'turn signal', 'Transport', 'Der Blinker zeigt nach rechts.', 'The turn signal points right.'],
  [null, 'blinken', null, 'to blink, flash', 'Transport', 'Das Licht am Auto blinkt.', 'The light on the car is blinking.'],
  ['die', 'Windschutzscheibe', 'Windschutzscheiben', 'windshield', 'Transport', 'Die Windschutzscheibe ist nass vom Regen.', 'The windshield is wet from the rain.'],
  ['der', 'Scheibenwischer', 'Scheibenwischer', 'windshield wiper', 'Transport', 'Der Scheibenwischer quietscht.', 'The windshield wiper squeaks.'],
  ['der', 'Rückspiegel', 'Rückspiegel', 'rearview mirror', 'Transport', 'Im Rückspiegel sehe ich ein Motorrad.', 'In the rearview mirror I see a motorcycle.'],
  ['das', 'Lenkrad', 'Lenkräder', 'steering wheel', 'Transport', 'Er hält das Lenkrad mit beiden Händen.', 'He holds the steering wheel with both hands.'],
  ['der', 'Tacho', 'Tachos', 'speedometer', 'Transport', 'Der Tacho zeigt hundert zwanzig.', 'The speedometer shows one twenty.'],
  ['der', 'Rücksitz', 'Rücksitze', 'back seat', 'Transport', 'Auf dem Rücksitz sitzen die Kinder.', 'The children sit on the back seat.'],
  ['der', 'Kindersitz', 'Kindersitze', 'child seat', 'Transport', 'Der Kindersitz muss hinten sein.', 'The child seat has to be in the back.'],
  ['das', 'Navi', 'Navis', 'GPS, navigation device', 'Transport', 'Das Navi führt uns zum Ziel.', 'The GPS leads us to the destination.'],
  ['die', 'Sperrung', 'Sperrungen', 'closure (road)', 'Transport', 'Die Sperrung gilt bis Freitag.', 'The closure applies until Friday.'],
  [null, 'sperren', null, 'to block, close off', 'Transport', 'Die Polizei sperrt die Straße.', 'The police block off the street.'],
  ['die', 'Warnweste', 'Warnwesten', 'safety vest', 'Transport', 'Die Warnweste muss im Auto liegen.', 'The safety vest has to be in the car.'],
  ['das', 'Warndreieck', 'Warndreiecke', 'warning triangle', 'Transport', 'Das Warndreieck steht hinter dem Auto.', 'The warning triangle stands behind the car.'],
  ['der', 'Verbandskasten', 'Verbandskästen', 'first-aid kit', 'Transport', 'Der Verbandskasten gehört in jedes Auto.', 'A first-aid kit belongs in every car.'],
  ['der', 'Ölwechsel', 'Ölwechsel', 'oil change', 'Transport', 'Der Ölwechsel dauert dreißig Minuten.', 'The oil change takes thirty minutes.'],
  ['die', 'Waschanlage', 'Waschanlagen', 'car wash', 'City', 'Die Waschanlage kostet acht Euro.', 'The car wash costs eight euros.'],
  ['die', 'Autovermietung', 'Autovermietungen', 'car rental', 'Travel', 'Die Autovermietung öffnet um sieben Uhr.', 'The car rental opens at seven.'],
  ['die', 'Rückgabe', 'Rückgaben', 'return (of something)', 'Travel', 'Die Rückgabe des Wagens erfolgt am Flughafen.', 'The return of the car takes place at the airport.'],
  [null, 'stornieren', null, 'to cancel (a booking)', 'Travel', 'Ich muss den Flug stornieren.', 'I have to cancel the flight.'],
  [null, 'umbuchen', null, 'to rebook', 'Travel', 'Können wir den Flug umbuchen?', 'Can we rebook the flight?'],
  [null, 'verreisen', null, 'to go away (on a trip)', 'Travel', 'Wir verreisen am Wochenende.', 'We are going away for the weekend.'],
  [null, 'übernachten', null, 'to stay overnight', 'Travel', 'Wir übernachten in einer kleinen Pension.', 'We stay overnight in a small guesthouse.'],
  [null, 'aufbrechen', null, 'to set off, depart', 'Travel', 'Wir brechen früh am Morgen auf.', 'We set off early in the morning.'],
  [null, 'besichtigen', null, 'to visit, tour (a sight)', 'Travel', 'Morgen besichtigen wir den Dom.', 'Tomorrow we tour the cathedral.'],
  [null, 'erkunden', null, 'to explore', 'Travel', 'Wir erkunden die Stadt zu Fuß.', 'We explore the city on foot.'],
  [null, 'landen', null, 'to land', 'Travel', 'Das Flugzeug landet pünktlich.', 'The plane lands on time.'],
  [null, 'abfliegen', null, 'to take off, fly out', 'Travel', 'Wir fliegen morgen früh ab.', 'We fly out tomorrow morning.'],
  [null, 'zwischenlanden', null, 'to make a stopover', 'Travel', 'Das Flugzeug zwischenlandet in Wien.', 'The plane makes a stopover in Vienna.'],
  [null, 'zurückkehren', null, 'to return', 'Travel', 'Nach dem Urlaub kehren wir zurück.', 'After the vacation we return.'],
  ['die', 'Halbpension', null, 'half board', 'Travel', 'Die Halbpension kostet vierzig Euro extra.', 'Half board costs forty euros extra.'],
  ['die', 'Vollpension', null, 'full board', 'Travel', 'Wir haben Vollpension gebucht.', 'We booked full board.'],
  ['die', 'Rezeption', 'Rezeptionen', 'reception (desk)', 'Travel', 'Die Rezeption ist rund um die Uhr besetzt.', 'The reception is staffed around the clock.'],
  ['der', 'Empfang', 'Empfänge', 'reception; signal reception', 'Travel', 'Der Empfang ist im Erdgeschoss.', 'The reception is on the ground floor.'],
  ['der', 'Safe', 'Safes', 'safe (lockbox)', 'Travel', 'Der Pass liegt im Safe.', 'The passport is in the safe.'],
  ['der', 'Zimmerservice', null, 'room service', 'Travel', 'Der Zimmerservice arbeitet bis Mitternacht.', 'Room service works until midnight.'],
  ['die', 'Rundreise', 'Rundreisen', 'round trip, tour', 'Travel', 'Die Rundreise führt durch fünf Länder.', 'The tour leads through five countries.'],
  ['die', 'Etappe', 'Etappen', 'stage (of a journey)', 'Travel', 'Die erste Etappe endet in Salzburg.', 'The first stage ends in Salzburg.'],
  ['die', 'Wegbeschreibung', 'Wegbeschreibungen', 'directions', 'Travel', 'Die Wegbeschreibung ist klar und einfach.', 'The directions are clear and simple.'],
  ['die', 'Stadtführung', 'Stadtführungen', 'city tour', 'Travel', 'Die Stadtführung beginnt am Marktplatz.', 'The city tour begins at the market square.'],
  ['der', 'Stadtrundgang', 'Stadtrundgänge', 'sightseeing walk', 'Travel', 'Der Stadtrundgang dauert zwei Stunden.', 'The sightseeing walk takes two hours.'],
  ['die', 'Seilbahn', 'Seilbahnen', 'cable car', 'Travel', 'Die Seilbahn fährt zum Gipfel.', 'The cable car goes to the summit.'],
  ['der', 'Sessellift', 'Sessellifte', 'chairlift', 'Travel', 'Der Sessellift ist nur im Winter offen.', 'The chairlift is only open in winter.'],
  ['der', 'Skilift', 'Skilifte', 'ski lift', 'Travel', 'Der Skilift fährt ab acht Uhr.', 'The ski lift runs from eight.'],
  ['der', 'Ski', 'Skier', 'ski', 'Travel', 'Der Ski ist zu lang für mich.', 'The ski is too long for me.'],
  ['das', 'Skigebiet', 'Skigebiete', 'ski resort', 'Travel', 'Das Skigebiet hat viele Pisten.', 'The ski resort has many slopes.'],
  ['die', 'Piste', 'Pisten', 'slope, piste', 'Travel', 'Die Piste ist frisch präpariert.', 'The slope is freshly groomed.'],
  ['die', 'Berghütte', 'Berghütten', 'mountain hut', 'Travel', 'Die Berghütte liegt auf tausend Metern.', 'The mountain hut is at one thousand meters.'],
  ['die', 'Lawine', 'Lawinen', 'avalanche', 'Travel', 'Die Lawine verschüttete den Weg.', 'The avalanche buried the path.'],
  ['der', 'Gipfel', 'Gipfel', 'summit, peak', 'Travel', 'Der Gipfel liegt auf zweitausend Metern.', 'The summit is at two thousand meters.'],
  [null, 'klettern', null, 'to climb', 'Travel', 'Wir klettern über die Felsen.', 'We climb over the rocks.'],
  ['das', 'Seil', 'Seile', 'rope', 'Travel', 'Das Seil ist zu kurz.', 'The rope is too short.'],
  ['der', 'Höhenweg', 'Höhenwege', 'high-altitude trail', 'Travel', 'Der Höhenweg ist nur bei gutem Wetter offen.', 'The high trail is only open in good weather.'],
  ['die', 'Gondel', 'Gondeln', 'gondola, cable car cabin', 'Travel', 'Die Gondel bietet Platz für acht Personen.', 'The gondola seats eight people.'],
  ['die', 'Talstation', 'Talstationen', 'valley station', 'Travel', 'Die Talstation ist unten im Dorf.', 'The valley station is down in the village.'],
  ['die', 'Bergstation', 'Bergstationen', 'mountain station', 'Travel', 'Die Bergstation liegt direkt am Gipfel.', 'The mountain station is right at the summit.'],
  ['die', 'Alpen', null, 'the Alps', 'Travel', 'Die Alpen sind ein beliebtes Reiseziel.', 'The Alps are a popular destination.'],
  ['die', 'Küste', 'Küsten', 'coast', 'Travel', 'Die Küste ist felsig und schön.', 'The coast is rocky and beautiful.'],
  ['das', 'Ufer', 'Ufer', 'shore, bank', 'Travel', 'Das Ufer ist voller Steine.', 'The shore is full of stones.'],
  ['die', 'Bucht', 'Buchten', 'bay', 'Travel', 'Die Bucht ist vor Wind geschützt.', 'The bay is sheltered from the wind.'],
  ['die', 'Halbinsel', 'Halbinseln', 'peninsula', 'Travel', 'Die Halbinsel ist per Fähre erreichbar.', 'The peninsula can be reached by ferry.'],
  ['die', 'Düne', 'Dünen', 'dune', 'Travel', 'Die Düne verschiebt sich mit dem Wind.', 'The dune shifts with the wind.'],
  ['der', 'Deich', 'Deiche', 'dike, levee', 'Travel', 'Der Deich schützt das Land vor dem Wasser.', 'The dike protects the land from the water.'],
  ['die', 'Ebbe', null, 'low tide', 'Travel', 'Bei Ebbe sieht man den Meeresboden.', 'At low tide you can see the seabed.'],
  ['die', 'Flut', 'Fluten', 'flood; high tide', 'Travel', 'Bei Flut ist das Wasser höher.', 'At high tide the water is higher.'],
  ['der', 'Kanal', 'Kanäle', 'canal; channel', 'Travel', 'Der Kanal verbindet zwei Flüsse.', 'The canal connects two rivers.'],
  ['das', 'Boot', 'Boote', 'boat', 'Travel', 'Das Boot schaukelt auf den Wellen.', 'The boat rocks on the waves.'],
  ['das', 'Kanu', 'Kanus', 'canoe', 'Travel', 'Das Kanu ist leicht zu tragen.', 'The canoe is easy to carry.'],
  ['das', 'Ruderboot', 'Ruderboote', 'rowboat', 'Travel', 'Das Ruderboot gehört zum Hotel.', 'The rowboat belongs to the hotel.'],
  ['der', 'Kompass', 'Kompasse', 'compass', 'Travel', 'Der Kompass zeigt nach Norden.', 'The compass points north.'],
  ['die', 'Himmelsrichtung', 'Himmelsrichtungen', 'cardinal direction', 'Travel', 'Die Himmelsrichtung steht auf dem Schild.', 'The cardinal direction is on the sign.'],
  ['der', 'Norden', null, 'the north', 'Travel', 'Der Norden ist kälter als der Süden.', 'The north is colder than the south.'],
  ['der', 'Süden', null, 'the south', 'Travel', 'Der Süden ist wärmer als der Norden.', 'The south is warmer than the north.'],
  ['der', 'Osten', null, 'the east', 'Travel', 'Die Sonne geht im Osten auf.', 'The sun rises in the east.'],
  ['der', 'Westen', null, 'the west', 'Travel', 'Der Wind kommt aus dem Westen.', 'The wind comes from the west.'],
  [null, 'nördlich', null, 'northern, to the north', 'Travel', 'Die Stadt liegt nördlich vom See.', 'The city lies north of the lake.'],
  [null, 'südlich', null, 'southern, to the south', 'Travel', 'Südlich der Grenze beginnt Österreich.', 'South of the border Austria begins.'],
  [null, 'westlich', null, 'western, to the west', 'Travel', 'Westlich des Flusses liegt ein Wald.', 'West of the river there is a forest.'],
  [null, 'östlich', null, 'eastern, to the east', 'Travel', 'Östlich der Stadt wächst Wein.', 'East of the city wine grows.'],
  ['das', 'Wahrzeichen', 'Wahrzeichen', 'landmark', 'Travel', 'Das Wahrzeichen der Stadt ist der Turm.', 'The landmark of the city is the tower.'],
  ['das', 'Kulturerbe', null, 'cultural heritage', 'Travel', 'Das Kulturerbe wird geschützt.', 'The cultural heritage is protected.'],
  ['die', 'Burg', 'Burgen', 'castle', 'Travel', 'Die Burg steht auf einem Hügel.', 'The castle stands on a hill.'],
  ['der', 'Palast', 'Paläste', 'palace', 'Travel', 'Der Palast ist jetzt ein Museum.', 'The palace is now a museum.'],
  ['der', 'Turm', 'Türme', 'tower', 'Travel', 'Der Turm bietet eine tolle Aussicht.', 'The tower offers a great view.'],
  ['die', 'Kathedrale', 'Kathedralen', 'cathedral', 'Travel', 'Die Kathedrale ist tausend Jahre alt.', 'The cathedral is a thousand years old.'],
  ['das', 'Kloster', 'Klöster', 'monastery', 'Travel', 'Das Kloster liegt abseits der Straße.', 'The monastery lies off the road.'],
  ['die', 'Kapelle', 'Kapellen', 'chapel', 'Travel', 'Die Kapelle ist immer offen.', 'The chapel is always open.'],
  ['das', 'Denkmal', 'Denkmäler', 'monument', 'Travel', 'Das Denkmal erinnert an den Dichter.', 'The monument commemorates the poet.'],
  ['die', 'Gedenkstätte', 'Gedenkstätten', 'memorial site', 'Travel', 'Wir besuchen die Gedenkstätte morgen.', 'We visit the memorial site tomorrow.'],
  ['der', 'Marktplatz', 'Marktplätze', 'market square', 'City', 'Der Marktplatz ist das Herz der Stadt.', 'The market square is the heart of the city.'],
  ['die', 'Markthalle', 'Markthallen', 'market hall', 'City', 'Die Markthalle hat frischen Fisch.', 'The market hall has fresh fish.'],
  ['die', 'Gasse', 'Gassen', 'alley', 'City', 'Die Gasse ist so eng, dass kein Auto passt.', 'The alley is so narrow that no car fits.'],
  ['die', 'Allee', 'Alleen', 'avenue, tree-lined street', 'City', 'Die Allee führt zum Schloss.', 'The avenue leads to the palace.'],
  ['die', 'Sackgasse', 'Sackgassen', 'dead end', 'City', 'Die Sackgasse endet an einer Mauer.', 'The dead end ends at a wall.'],
  ['das', 'Ausland', null, 'abroad', 'Travel', 'Er arbeitet im Ausland.', 'He works abroad.'],
  ['das', 'Inland', null, 'home country (domestic)', 'Travel', 'Das Inland hat auch schöne Ziele.', 'The home country also has beautiful destinations.'],
  ['das', 'Feuer', null, 'fire', 'Travel', 'Das Feuer wärmt die Hände.', 'The fire warms the hands.'],
  ['das', 'Lagerfeuer', 'Lagerfeuer', 'campfire', 'Travel', 'Das Lagerfeuer brennt bis spät in die Nacht.', 'The campfire burns late into the night.'],
  ['das', 'Dokument', 'Dokumente', 'document', 'Authorities', 'Das Dokument ist unterschrieben.', 'The document is signed.'],
  ['die', 'Bestätigung', 'Bestätigungen', 'confirmation', 'Authorities', 'Die Bestätigung kommt per Post.', 'The confirmation comes by mail.'],
  ['das', 'Siegel', 'Siegel', 'seal, stamp', 'Authorities', 'Der Brief trägt ein offizielles Siegel.', 'The letter bears an official seal.'],
  ['der', 'Reisepass', 'Reisepässe', 'passport', 'Authorities', 'Der Reisepass ist noch fünf Jahre gültig.', 'The passport is still valid for five years.'],
  ['der', 'Personalausweis', 'Personalausweise', 'ID card', 'Authorities', 'Der Personalausweis passt ins Portemonnaie.', 'The ID card fits in the wallet.'],
  ['der', 'Familienstand', null, 'marital status', 'Authorities', 'Der Familienstand steht im Formular.', 'The marital status is in the form.'],
  [null, 'ledig', null, 'single (unmarried)', 'Authorities', 'Er ist ledig und hat keine Kinder.', 'He is single and has no children.'],
  ['der', 'Geburtsort', 'Geburtsorte', 'birthplace', 'Authorities', 'Der Geburtsort steht im Pass.', 'The birthplace is in the passport.'],
  ['das', 'Geburtsdatum', 'Geburtsdaten', 'date of birth', 'Authorities', 'Das Geburtsdatum muss stimmen.', 'The date of birth must be correct.'],
  ['das', 'Geburtsland', 'Geburtsländer', 'country of birth', 'Authorities', 'Das Geburtsland ist für den Antrag wichtig.', 'The country of birth is important for the application.'],
  ['die', 'Auskunft', 'Auskünfte', 'information (desk)', 'Authorities', 'Die Auskunft am Telefon war freundlich.', 'The information on the phone was friendly.'],
  [null, 'behördlich', null, 'official, administrative', 'Authorities', 'Der behördliche Weg dauert oft lange.', 'The official route often takes a long time.'],
  ['der', 'Antragsteller', 'Antragsteller', 'applicant', 'Authorities', 'Der Antragsteller bekommt eine Nummer.', 'The applicant gets a number.'],
  ['die', 'Bearbeitung', 'Bearbeitungen', 'processing', 'Authorities', 'Die Bearbeitung dauert vier Wochen.', 'The processing takes four weeks.'],
  ['der', 'Bescheid', 'Bescheide', 'official decision, notice', 'Authorities', 'Der Bescheid kommt schriftlich.', 'The decision comes in writing.'],
  ['die', 'Geburtsurkunde', 'Geburtsurkunden', 'birth certificate', 'Authorities', 'Die Geburtsurkunde brauchen wir für die Anmeldung.', 'We need the birth certificate for the registration.'],
  ['die', 'Beglaubigung', 'Beglaubigungen', 'certification (of copies)', 'Authorities', 'Die Beglaubigung der Kopie kostet fünf Euro.', 'The certification of the copy costs five euros.'],
  ['das', 'Passbild', 'Passbilder', 'passport photo', 'Authorities', 'Das Passbild darf nicht älter als ein Jahr sein.', 'The passport photo must not be older than a year.'],
  ['die', 'Steuernummer', 'Steuernummern', 'tax number', 'Authorities', 'Die Steuernummer steht auf dem Brief.', 'The tax number is on the letter.'],
  ['das', 'Jobcenter', 'Jobcenter', 'job center', 'Authorities', 'Das Jobcenter hilft bei der Arbeitssuche.', 'The job center helps with the job search.'],
  ['die', 'Arbeitsagentur', 'Arbeitsagenturen', 'employment agency', 'Authorities', 'Die Arbeitsagentur vermittelt Stellen.', 'The employment agency places jobs.'],
  ['das', 'Sozialamt', 'Sozialämter', 'social welfare office', 'Authorities', 'Das Sozialamt unterstützt Bedürftige.', 'The social welfare office supports people in need.'],
  ['das', 'Gesundheitsamt', 'Gesundheitsämter', 'health office', 'Authorities', 'Das Gesundheitsamt berät kostenlos.', 'The health office advises free of charge.'],
  ['das', 'Ordnungsamt', 'Ordnungsämter', 'public order office', 'Authorities', 'Das Ordnungsamt ist für die Sauberkeit zuständig.', 'The public order office is responsible for cleanliness.'],
  ['das', 'Einwohnermeldeamt', 'Einwohnermeldeämter', 'residents registration office', 'Authorities', 'Nach dem Umzug gehst du zum Einwohnermeldeamt.', 'After moving you go to the registration office.'],
  ['die', 'Ausländerbehörde', 'Ausländerbehörden', 'immigration office', 'Authorities', 'Die Ausländerbehörde entscheidet über den Aufenthalt.', 'The immigration office decides about the stay.'],
  ['die', 'Abmeldung', 'Abmeldungen', 'deregistration', 'Authorities', 'Die Abmeldung erfolgt beim Umzug.', 'The deregistration happens when you move.'],
  ['die', 'Ummeldung', 'Ummeldungen', 're-registration', 'Authorities', 'Die Ummeldung ist nach dem Umzug Pflicht.', 'Re-registration is required after moving.'],
  ['der', 'Hauptwohnsitz', 'Hauptwohnsitze', 'primary residence', 'Authorities', 'Der Hauptwohnsitz ist in Berlin.', 'The primary residence is in Berlin.'],
  ['die', 'Einbürgerung', 'Einbürgerungen', 'naturalization', 'Authorities', 'Die Einbürgerung ist nach acht Jahren möglich.', 'Naturalization is possible after eight years.'],
  ['der', 'Aufenthaltstitel', 'Aufenthaltstitel', 'residence permit', 'Authorities', 'Der Aufenthaltstitel muss verlängert werden.', 'The residence permit has to be extended.'],
  ['die', 'Aufenthaltserlaubnis', 'Aufenthaltserlaubnisse', 'residence permit', 'Authorities', 'Die Aufenthaltserlaubnis gilt zwei Jahre.', 'The residence permit is valid for two years.'],
  ['der', 'Integrationskurs', 'Integrationskurse', 'integration course', 'Authorities', 'Der Integrationskurs endet mit einer Prüfung.', 'The integration course ends with an exam.'],
  [null, 'auswandern', null, 'to emigrate', 'Authorities', 'Viele wandern nach Kanada aus.', 'Many people emigrate to Canada.'],
  [null, 'einwandern', null, 'to immigrate', 'Authorities', 'Die Familie will nach Deutschland einwandern.', 'The family wants to immigrate to Germany.'],
  ['der', 'Einwanderer', 'Einwanderer', 'immigrant', 'Authorities', 'Der Einwanderer kommt aus Syrien.', 'The immigrant comes from Syria.'],
  ['die', 'Migration', null, 'migration', 'Authorities', 'Die Migration verändert die Städte.', 'Migration changes the cities.'],
  ['der', 'Migrant', 'Migranten', 'migrant', 'Authorities', 'Der Migrant arbeitet in einer Fabrik.', 'The migrant works in a factory.'],
  ['die', 'Erlaubnis', 'Erlaubnisse', 'permission', 'Authorities', 'Die Erlaubnis bekommt man schriftlich.', 'You get the permission in writing.'],
  ['der', 'Beamter', 'Beamten', 'civil servant', 'Authorities', 'Der Beamter prüft die Papiere.', 'The civil servant checks the papers.'],
  ['der', 'Zöllner', 'Zöllner', 'customs officer', 'Authorities', 'Der Zöllner schaut in den Koffer.', 'The customs officer looks into the suitcase.'],
  ['das', 'Postamt', 'Postämter', 'post office', 'Authorities', 'Das Postamt schließt um sechs.', 'The post office closes at six.'],
  ['der', 'Postbote', 'Postboten', 'mail carrier', 'Authorities', 'Der Postbote kommt gegen zehn.', 'The mail carrier comes around ten.'],
  ['der', 'Briefträger', 'Briefträger', 'mailman', 'Authorities', 'Der Briefträger kennt jede Adresse.', 'The mailman knows every address.'],
  ['die', 'Postleitzahl', 'Postleitzahlen', 'postal code', 'Authorities', 'Die Postleitzahl steht über dem Ort.', 'The postal code goes above the town.'],
  ['der', 'Absender', 'Absender', 'sender', 'Authorities', 'Der Absender steht oben links.', 'The sender is in the top left.'],
  ['der', 'Empfänger', 'Empfänger', 'recipient', 'Authorities', 'Der Empfänger muss unterschreiben.', 'The recipient has to sign.'],
  ['die', 'Anschrift', 'Anschriften', 'address (formal)', 'Authorities', 'Die Anschrift des Amtes finde ich online.', 'I find the office address online.'],
  ['das', 'Einschreiben', null, 'registered mail', 'Authorities', 'Ich schicke den Vertrag per Einschreiben.', 'I send the contract by registered mail.'],
  ['das', 'Porto', null, 'postage', 'Authorities', 'Das Porto für einen Brief beträgt achtzig Cent.', 'The postage for a letter is eighty cents.'],
  ['die', 'Paketstation', 'Paketstationen', 'parcel station', 'Authorities', 'Die Paketstation ist Tag und Nacht offen.', 'The parcel station is open day and night.'],
  ['der', 'Umschlag', 'Umschläge', 'envelope', 'Authorities', 'Der Umschlag ist zu klein für das Dokument.', 'The envelope is too small for the document.'],
  ['die', 'Nachnahme', null, 'cash on delivery', 'Authorities', 'Die Nachnahme zahlt der Empfänger.', 'The recipient pays cash on delivery.'],
  ['die', 'Zollgebühr', 'Zollgebühren', 'customs fee', 'Authorities', 'Die Zollgebühr beträgt zwanzig Euro.', 'The customs fee is twenty euros.'],
  [null, 'zollfrei', null, 'duty-free', 'Authorities', 'Zollfrei sind Geschenke bis fünfzig Euro.', 'Gifts up to fifty euros are duty-free.'],
  [null, 'verzollen', null, 'to declare (customs), pay duty on', 'Authorities', 'Muss ich diese Uhr verzollen?', 'Do I have to declare this watch?'],
  ['die', 'Einfuhr', 'Einfuhren', 'import (into a country)', 'Authorities', 'Die Einfuhr von Zigaretten ist begrenzt.', 'The import of cigarettes is limited.'],
  ['die', 'Ausfuhr', 'Ausfuhren', 'export (out of a country)', 'Authorities', 'Die Ausfuhr von Kunst ist verboten.', 'The export of art is forbidden.'],
  ['der', 'Grenzübergang', 'Grenzübergänge', 'border crossing', 'Authorities', 'Der Grenzübergang ist nachts geschlossen.', 'The border crossing is closed at night.'],
  ['die', 'Einreisebestimmung', 'Einreisebestimmungen', 'entry regulation', 'Authorities', 'Die Einreisebestimmung ändert sich oft.', 'The entry regulation changes often.'],
  ['die', 'Visumspflicht', null, 'visa requirement', 'Authorities', 'Die Visumspflicht gilt für viele Länder.', 'The visa requirement applies to many countries.'],
  ['das', 'Asyl', null, 'asylum', 'Authorities', 'Das Asyl ist ein Grundrecht.', 'Asylum is a basic right.'],
  ['der', 'Asylantrag', 'Asylanträge', 'asylum application', 'Authorities', 'Der Asylantrag wird bei der Behörde gestellt.', 'The asylum application is filed at the authority.'],
  ['die', 'Rückreise', 'Rückreisen', 'journey home', 'Travel', 'Die Rückreise traten wir am Montag an.', 'We started the journey home on Monday.'],
  ['die', 'Heimreise', 'Heimreisen', 'journey home', 'Travel', 'Die Heimreise dauert länger als geplant.', 'The journey home takes longer than planned.'],
  ['die', 'Weiterreise', 'Weiterreisen', 'onward journey', 'Travel', 'Die Weiterreise geht morgen früh los.', 'The onward journey starts tomorrow morning.'],
  ['der', 'Abschied', 'Abschiede', 'farewell', 'Travel', 'Der Abschied fiel uns schwer.', 'Saying goodbye was hard for us.'],
  [null, 'wiedersehen', null, 'to see again, reunite', 'Travel', 'Wir sehen uns nächstes Jahr wieder.', 'We will see each other again next year.'],
  ['das', 'Heimweh', null, 'homesickness', 'Travel', 'Das Heimweh wird nach einem Monat stärker.', 'Homesickness gets stronger after a month.'],
  [null, 'unterwegs', null, 'on the way, traveling', 'Travel', 'Wir sind morgen den ganzen Tag unterwegs.', 'We will be on the road all day tomorrow.'],
  ['der', 'Mitbringsel', 'Mitbringsel', 'small gift from a trip', 'Travel', 'Der Mitbringsel aus Italien ist Öl.', 'The gift from Italy is oil.'],
  ['das', 'Souvenir', 'Souvenirs', 'souvenir', 'Travel', 'Das Souvenir erinnert an den Urlaub.', 'The souvenir reminds us of the vacation.'],
  ['die', 'Vorbereitung', 'Vorbereitungen', 'preparation', 'Travel', 'Die Vorbereitung der Reise dauert Wochen.', 'Preparing the trip takes weeks.'],
  [null, 'abwesend', null, 'absent, away', 'Travel', 'Der Chef ist diese Woche abwesend.', 'The boss is away this week.'],
  ['der', 'Krankenwagen', 'Krankenwagen', 'ambulance', 'Law', 'Der Krankenwagen kommt mit Blaulicht.', 'The ambulance comes with flashing lights.'],
  ['der', 'Rettungsdienst', 'Rettungsdienste', 'emergency service', 'Law', 'Der Rettungsdienst ist in fünf Minuten da.', 'The emergency service arrives in five minutes.'],
  ['die', 'Feuerwehr', 'Feuerwehren', 'fire department', 'Law', 'Die Feuerwehr löscht das Feuer.', 'The fire department puts out the fire.'],
  ['der', 'Feuerwehrmann', 'Feuerwehrmänner', 'firefighter', 'Law', 'Der Feuerwehrmann steigt auf die Leiter.', 'The firefighter climbs the ladder.'],
  ['der', 'Feueralarm', 'Feueralarme', 'fire alarm', 'Law', 'Der Feueralarm ertönt plötzlich.', 'The fire alarm goes off suddenly.'],
  ['der', 'Brand', 'Brände', 'fire (blaze)', 'Law', 'Der Brand zerstörte die Scheune.', 'The blaze destroyed the barn.'],
  ['die', 'Sirene', 'Sirenen', 'siren', 'Law', 'Die Sirene heult jeden Monat.', 'The siren howls every month.'],
  ['der', 'Verkehrsunfall', 'Verkehrsunfälle', 'traffic accident', 'Law', 'Der Verkehrsunfall blockiert die Straße.', 'The traffic accident blocks the street.'],
  ['der', 'Erste-Hilfe-Kurs', 'Erste-Hilfe-Kurse', 'first aid course', 'Law', 'Der Erste-Hilfe-Kurs dauert einen Tag.', 'The first aid course takes one day.'],
  ['der', 'Ersthelfer', 'Ersthelfer', 'first responder', 'Law', 'Der Ersthelfer ruft den Notarzt.', 'The first responder calls the emergency doctor.'],
  ['die', 'Unfallstelle', 'Unfallstellen', 'accident scene', 'Law', 'Die Unfallstelle wird abgesichert.', 'The accident scene is secured.'],
  ['der', 'Polizist', 'Polizisten', 'police officer', 'Law', 'Der Polizist regelt den Verkehr.', 'The police officer directs the traffic.'],
  ['der', 'Passant', 'Passanten', 'passerby', 'City', 'Der Passant zeigt uns den Weg.', 'The passerby shows us the way.'],
  ['die', 'Anzeige', 'Anzeigen', 'police report; advertisement', 'Law', 'Die Anzeige erstattet man bei der Polizei.', 'You file the report at the police.'],
  [null, 'anzeigen', null, 'to report (to police); display', 'Law', 'Ich zeige den Diebstahl bei der Polizei an.', 'I report the theft to the police.'],
  ['der', 'Diebstahl', 'Diebstähle', 'theft', 'Law', 'Der Diebstahl geschah nachts.', 'The theft happened at night.'],
  [null, 'stehlen', null, 'to steal', 'Law', 'Wer stiehlt, wird bestraft.', 'Whoever steals will be punished.'],
  ['der', 'Dieb', 'Diebe', 'thief', 'Law', 'Der Dieb wurde gefasst.', 'The thief was caught.'],
  ['der', 'Betrug', null, 'fraud', 'Law', 'Der Betrug flog nach einem Jahr auf.', 'The fraud came to light after a year.'],
  [null, 'betrügen', null, 'to defraud, cheat', 'Law', 'Der Betrüger betrügt alte Leute.', 'The con man cheats old people.'],
  ['das', 'Opfer', 'Opfer', 'victim', 'Law', 'Das Opfer erinnert sich an das Gesicht.', 'The victim remembers the face.'],
  ['der', 'Täter', 'Täter', 'perpetrator', 'Law', 'Der Täter flüchtete zu Fuß.', 'The perpetrator fled on foot.'],
  [null, 'bestrafen', null, 'to punish', 'Law', 'Der Richter bestraft den Lügner.', 'The judge punishes the liar.'],
  ['der', 'Einbruch', 'Einbrüche', 'burglary; slump', 'Law', 'Der Einbruch geschah am Wochenende.', 'The burglary happened on the weekend.'],
  [null, 'einbrechen', null, 'to break in', 'Law', 'Die Diebe brechen nachts ein.', 'The thieves break in at night.'],
  ['der', 'Einbrecher', 'Einbrecher', 'burglar', 'Law', 'Der Einbrecher kam durch das Fenster.', 'The burglar came through the window.'],
  [null, 'überfallen', null, 'to attack, rob', 'Law', 'Die Bank wurde überfallen.', 'The bank was robbed.'],
  [null, 'beschädigen', null, 'to damage', 'Law', 'Der Vandal beschädigt das Auto.', 'The vandal damages the car.'],
  ['die', 'Beschädigung', 'Beschädigungen', 'damage', 'Law', 'Die Beschädigung ist versichert.', 'The damage is insured.'],
  [null, 'belästigen', null, 'to harass', 'Law', 'Niemand darf Fahrgäste belästigen.', 'Nobody may harass passengers.'],
  ['die', 'Warteschlange', 'Warteschlangen', 'queue, line', 'Authorities', 'Die Warteschlange reicht bis zur Tür.', 'The queue reaches to the door.'],
  ['die', 'Klage', 'Klagen', 'complaint, lawsuit', 'Law', 'Die Klage wurde abgewiesen.', 'The lawsuit was dismissed.'],
  ['die', 'Anwältin', 'Anwältinnen', 'lawyer (female)', 'Law', 'Die Anwältin studiert die Akten.', 'The lawyer studies the files.'],
  ['der', 'Kommissar', 'Kommissare', 'detective, commissioner', 'Law', 'Der Kommissar nimmt die Aussage auf.', 'The detective takes the statement.'],
  ['die', 'Kriminalpolizei', null, 'criminal police', 'Law', 'Die Kriminalpolizei ermittelt im Fall.', 'The criminal police investigate the case.'],
  ['das', 'Strafverfahren', 'Strafverfahren', 'criminal proceedings', 'Law', 'Das Strafverfahren dauert Monate.', 'The criminal proceedings take months.'],
]
