import type { SeedRow } from './types'

/** B1 seed corpus (~118 entries): work, society, opinions, abstract verbs. */
export const B1_ROWS: SeedRow[] = [
  ['die', 'Besprechung', 'Besprechungen', 'meeting', 'Work', 'Die Besprechung dauert eine Stunde.', 'The meeting lasts an hour.'],
  ['die', 'Firma', 'Firmen', 'company', 'Work', 'Die Firma ist international.', 'The company is international.'],
  ['der', 'Kollege', 'Kollegen', 'colleague', 'Work', 'Mein Kollege hilft mir.', 'My colleague helps me.'],
  ['die', 'Stelle', 'Stellen', 'job, position', 'Work', 'Ich suche eine neue Stelle.', 'I am looking for a new job.'],
  ['die', 'Bewerbung', 'Bewerbungen', 'job application', 'Work', 'Meine Bewerbung ist fertig.', 'My application is ready.'],
  ['der', 'Lebenslauf', 'Lebensläufe', 'resume, CV', 'Work', 'Ich schicke meinen Lebenslauf.', 'I am sending my resume.'],
  ['die', 'Erfahrung', 'Erfahrungen', 'experience', 'Work', 'Sie hat viel Erfahrung.', 'She has a lot of experience.'],
  ['die', 'Ausbildung', 'Ausbildungen', 'training, apprenticeship', 'Work', 'Die Ausbildung dauert drei Jahre.', 'The training takes three years.'],
  ['das', 'Gehalt', 'Gehälter', 'salary', 'Work', 'Das Gehalt ist gut.', 'The salary is good.'],
  ['die', 'Überstunden', null, 'overtime', 'Work', 'Heute mache ich Überstunden.', 'Today I am working overtime.'],
  ['die', 'Entscheidung', 'Entscheidungen', 'decision', 'Society', 'Das ist eine wichtige Entscheidung.', 'That is an important decision.'],
  ['die', 'Entwicklung', 'Entwicklungen', 'development', 'Society', 'Die Entwicklung ist positiv.', 'The development is positive.'],
  ['die', 'Umwelt', null, 'environment', 'Society', 'Wir schützen die Umwelt.', 'We protect the environment.'],
  ['die', 'Gesellschaft', 'Gesellschaften', 'society', 'Society', 'Die Gesellschaft verändert sich.', 'Society is changing.'],
  ['die', 'Wirtschaft', null, 'economy', 'Society', 'Die Wirtschaft wächst.', 'The economy is growing.'],
  ['die', 'Politik', null, 'politics', 'Society', 'Ich interessiere mich für Politik.', 'I am interested in politics.'],
  ['die', 'Regierung', 'Regierungen', 'government', 'Society', 'Die Regierung entscheidet.', 'The government decides.'],
  ['das', 'Gesetz', 'Gesetze', 'law', 'Society', 'Das Gesetz ist neu.', 'The law is new.'],
  ['das', 'Recht', 'Rechte', 'right, law', 'Society', 'Jeder Mensch hat Rechte.', 'Every person has rights.'],
  ['die', 'Verantwortung', null, 'responsibility', 'Society', 'Ich übernehme Verantwortung.', 'I am taking responsibility.'],
  ['der', 'Eindruck', 'Eindrücke', 'impression', 'Communication', 'Der erste Eindruck zählt.', 'The first impression counts.'],
  ['der', 'Streit', 'Streitereien', 'quarrel, dispute', 'Emotions', 'Der Streit ist vorbei.', 'The quarrel is over.'],
  ['der', 'Kompromiss', 'Kompromisse', 'compromise', 'Communication', 'Wir finden einen Kompromiss.', 'We will find a compromise.'],
  ['die', 'Diskussion', 'Diskussionen', 'discussion', 'Communication', 'Die Diskussion war spannend.', 'The discussion was exciting.'],
  ['die', 'Kritik', null, 'criticism', 'Communication', 'Ich nehme Kritik an.', 'I accept criticism.'],
  ['das', 'Argument', 'Argumente', 'argument', 'Communication', 'Das Argument ist überzeugend.', 'The argument is convincing.'],
  ['der', 'Vorteil', 'Vorteile', 'advantage', 'Society', 'Der Vorteil ist klar.', 'The advantage is clear.'],
  ['der', 'Nachteil', 'Nachteile', 'disadvantage', 'Society', 'Jeder Vorteil hat Nachteile.', 'Every advantage has disadvantages.'],
  ['die', 'Folge', 'Folgen', 'consequence', 'Society', 'Das hat Folgen.', 'That has consequences.'],
  ['die', 'Ursache', 'Ursachen', 'cause', 'Society', 'Die Ursache ist unbekannt.', 'The cause is unknown.'],
  ['der', 'Zweck', 'Zwecke', 'purpose', 'Society', 'Der Zweck der Reise ist klar.', 'The purpose of the trip is clear.'],
  ['der', 'Zusammenhang', 'Zusammenhänge', 'connection, context', 'Society', 'Ich verstehe den Zusammenhang.', 'I understand the connection.'],
  ['die', 'Beziehung', 'Beziehungen', 'relationship', 'People', 'Unsere Beziehung ist gut.', 'Our relationship is good.'],
  ['die', 'Ehe', 'Ehen', 'marriage', 'People', 'Die Ehe dauert zehn Jahre.', 'The marriage has lasted ten years.'],
  ['der', 'Partner', 'Partner', 'partner', 'People', 'Mein Partner arbeitet viel.', 'My partner works a lot.'],
  ['die', 'Gemeinschaft', 'Gemeinschaften', 'community', 'Society', 'Die Gemeinschaft hilft.', 'The community helps.'],
  ['die', 'Nachbarschaft', null, 'neighborhood', 'Society', 'Die Nachbarschaft ist freundlich.', 'The neighborhood is friendly.'],
  ['die', 'Sprache', 'Sprachen', 'language', 'Education', 'Deutsch ist eine schöne Sprache.', 'German is a beautiful language.'],
  ['der', 'Wortschatz', null, 'vocabulary', 'Education', 'Mein Wortschatz wächst.', 'My vocabulary is growing.'],
  ['der', 'Fehler', 'Fehler', 'mistake, error', 'Education', 'Aus Fehlern lernt man.', 'One learns from mistakes.'],
  ['der', 'Fortschritt', 'Fortschritte', 'progress', 'Education', 'Ich mache Fortschritte.', 'I am making progress.'],
  ['die', 'Kenntnis', 'Kenntnisse', 'knowledge', 'Education', 'Sie hat gute Kenntnisse.', 'She has good knowledge.'],
  ['die', 'Fähigkeit', 'Fähigkeiten', 'ability, skill', 'Education', 'Das ist eine wichtige Fähigkeit.', 'That is an important skill.'],
  ['das', 'Ziel', 'Ziele', 'goal', 'Education', 'Mein Ziel ist flüssiges Sprechen.', 'My goal is to speak fluently.'],
  ['der', 'Erfolg', 'Erfolge', 'success', 'Work', 'Der Erfolg kam schnell.', 'Success came quickly.'],
  ['das', 'Pech', null, 'bad luck', 'Emotions', 'Das war Pech!', 'That was bad luck!'],
  ['die', 'Geduld', null, 'patience', 'Emotions', 'Man braucht Geduld.', 'One needs patience.'],
  ['der', 'Mut', null, 'courage', 'Emotions', 'Sie hat viel Mut.', 'She has a lot of courage.'],
  ['die', 'Ruhe', null, 'peace, quiet', 'Emotions', 'Ich brauche Ruhe.', 'I need quiet.'],
  [null, 'beschreiben', null, 'to describe', 'Verbs', 'Beschreiben Sie das Bild.', 'Describe the picture.'],
  [null, 'empfehlen', null, 'to recommend', 'Verbs', 'Was empfehlen Sie?', 'What do you recommend?'],
  [null, 'entscheiden', null, 'to decide', 'Verbs', 'Ich muss schnell entscheiden.', 'I must decide quickly.'],
  [null, 'erlauben', null, 'to allow, to permit', 'Verbs', 'Rauchen ist nicht erlaubt.', 'Smoking is not allowed.'],
  [null, 'verbieten', null, 'to forbid', 'Verbs', 'Handys sind verboten.', 'Phones are forbidden.'],
  [null, 'verbessern', null, 'to improve', 'Verbs', 'Ich will mein Deutsch verbessern.', 'I want to improve my German.'],
  [null, 'verschlechtern', null, 'to worsen', 'Verbs', 'Das Wetter verschlechtert sich.', 'The weather is getting worse.'],
  [null, 'erledigen', null, 'to complete, to take care of', 'Verbs', 'Ich erledige die Aufgabe.', 'I will take care of the task.'],
  [null, 'organisieren', null, 'to organize', 'Verbs', 'Sie organisiert die Party.', 'She is organizing the party.'],
  [null, 'planen', null, 'to plan', 'Verbs', 'Wir planen die Reise.', 'We are planning the trip.'],
  [null, 'vorbereiten', null, 'to prepare', 'Verbs', 'Ich bereite die Prüfung vor.', 'I am preparing for the exam.'],
  [null, 'beenden', null, 'to end, to finish', 'Verbs', 'Ich beende die Arbeit.', 'I am finishing the work.'],
  [null, 'fortsetzen', null, 'to continue', 'Verbs', 'Setzen Sie den Text fort.', 'Continue the text.'],
  [null, 'unterbrechen', null, 'to interrupt', 'Verbs', 'Bitte unterbrich mich nicht.', 'Please do not interrupt me.'],
  [null, 'wiederholen', null, 'to repeat', 'Verbs', 'Können Sie das wiederholen?', 'Can you repeat that?'],
  [null, 'üben', null, 'to practice', 'Verbs', 'Ich übe jeden Tag.', 'I practice every day.'],
  [null, 'versuchen', null, 'to try, to attempt', 'Verbs', 'Ich versuche es noch einmal.', 'I will try again.'],
  [null, 'schaffen', null, 'to manage, to accomplish', 'Verbs', 'Ich schaffe das!', 'I can do it!'],
  [null, 'gelten', null, 'to be valid, to apply', 'Verbs', 'Das Angebot gilt nur heute.', 'The offer is only valid today.'],
  [null, 'betreffen', null, 'to concern, to affect', 'Verbs', 'Das betrifft mich nicht.', 'That does not concern me.'],
  [null, 'abhängen', null, 'to depend', 'Verbs', 'Das hängt vom Wetter ab.', 'That depends on the weather.'],
  [null, 'zweifeln', null, 'to doubt', 'Verbs', 'Ich zweifle daran.', 'I doubt it.'],
  [null, 'behaupten', null, 'to claim, to assert', 'Verbs', 'Sie behauptet, dass sie krank war.', 'She claimed that she was sick.'],
  [null, 'bemerken', null, 'to notice', 'Verbs', 'Ich habe den Fehler bemerkt.', 'I noticed the mistake.'],
  [null, 'beobachten', null, 'to observe, to watch', 'Verbs', 'Wir beobachten die Vögel.', 'We are watching the birds.'],
  [null, 'entwickeln', null, 'to develop', 'Verbs', 'Die Firma entwickelt neue Software.', 'The company is developing new software.'],
  [null, 'gründen', null, 'to found, to establish', 'Verbs', 'Er gründet eine Firma.', 'He is founding a company.'],
  [null, 'investieren', null, 'to invest', 'Verbs', 'Wir investieren in Bildung.', 'We are investing in education.'],
  [null, 'sparen', null, 'to save (money)', 'Verbs', 'Ich spare für den Urlaub.', 'I am saving for vacation.'],
  [null, 'ausgeben', null, 'to spend (money)', 'Verbs', 'Ich gebe zu viel aus.', 'I am spending too much.'],
  [null, 'verdienen', null, 'to earn', 'Verbs', 'Sie verdient gut.', 'She earns well.'],
  [null, 'wechseln', null, 'to change, to exchange', 'Verbs', 'Ich möchte Geld wechseln.', 'I would like to exchange money.'],
  [null, 'teilen', null, 'to share, to divide', 'Verbs', 'Wir teilen die Rechnung.', 'We are splitting the bill.'],
  [null, 'interessieren', null, 'to interest', 'Verbs', 'Ich interessiere mich für Kunst.', 'I am interested in art.'],
  [null, 'stören', null, 'to disturb, to bother', 'Verbs', 'Stört es dich?', 'Does it bother you?'],
  [null, 'aufpassen', null, 'to pay attention', 'Verbs', 'Pass gut auf!', 'Pay close attention!'],
  [null, 'nachdenken', null, 'to think about, to reflect', 'Verbs', 'Ich denke darüber nach.', 'I am thinking about it.'],
  [null, 'vorhaben', null, 'to plan, to intend', 'Verbs', 'Was hast du morgen vor?', 'What are you planning for tomorrow?'],
  [null, 'teilnehmen', null, 'to participate', 'Verbs', 'Ich nehme am Kurs teil.', 'I am taking part in the course.'],
  [null, 'beitragen', null, 'to contribute', 'Verbs', 'Jeder kann beitragen.', 'Everyone can contribute.'],
  [null, 'verlieren', null, 'to lose', 'Verbs', 'Ich habe meine Brille verloren.', 'I lost my glasses.'],
  [null, 'gewinnen', null, 'to win', 'Verbs', 'Wir haben das Spiel gewonnen.', 'We won the game.'],
  [null, 'erreichen', null, 'to reach, to achieve', 'Verbs', 'Wir erreichen das Ziel.', 'We are reaching the goal.'],
  [null, 'verpassen', null, 'to miss', 'Verbs', 'Ich habe den Zug verpasst.', 'I missed the train.'],
  [null, 'ausruhen', null, 'to rest', 'Verbs', 'Ich ruhe mich aus.', 'I am resting.'],
  [null, 'trennen', null, 'to separate, to split', 'Verbs', 'Wir trennen den Müll.', 'We separate the trash.'],
  [null, 'verbinden', null, 'to connect', 'Verbs', 'Das verbindet uns.', 'That connects us.'],
  [null, 'unterscheiden', null, 'to differ, to distinguish', 'Verbs', 'Die Zwillinge unterscheiden sich.', 'The twins are different.'],
  [null, 'übereinstimmen', null, 'to agree, to match', 'Verbs', 'Wir stimmen überein.', 'We agree.'],
  [null, 'zusammenarbeiten', null, 'to work together', 'Verbs', 'Wir arbeiten gern zusammen.', 'We like working together.'],
  [null, 'entschuldigen', null, 'to excuse, to forgive', 'Verbs', 'Entschuldigen Sie die Störung.', 'Excuse the interruption.'],
  [null, 'loben', null, 'to praise', 'Verbs', 'Der Chef lobt das Team.', 'The boss praises the team.'],
  ['die', 'Brille', 'Brillen', 'glasses', 'Health', 'Ich brauche eine Brille.', 'I need glasses.'],
  ['das', 'Rezept', 'Rezepte', 'recipe, prescription', 'Food', 'Das Rezept ist einfach.', 'The recipe is simple.'],
  ['die', 'Zutat', 'Zutaten', 'ingredient', 'Food', 'Alle Zutaten sind frisch.', 'All the ingredients are fresh.'],
  [null, 'lecker', null, 'tasty, delicious', 'Food', 'Die Suppe schmeckt lecker.', 'The soup tastes delicious.'],
  [null, 'vegetarisch', null, 'vegetarian', 'Food', 'Ich koche vegetarisch.', 'I cook vegetarian.'],
  ['die', 'Gewohnheit', 'Gewohnheiten', 'habit', 'Emotions', 'Das ist eine alte Gewohnheit.', 'That is an old habit.'],
  ['die', 'Entspannung', null, 'relaxation', 'Health', 'Yoga bringt Entspannung.', 'Yoga brings relaxation.'],
  ['das', 'Gleichgewicht', null, 'balance', 'Health', 'Ich suche das Gleichgewicht.', 'I am looking for balance.'],
  [null, 'eigentlich', null, 'actually', 'Basics', 'Eigentlich wollte ich schlafen.', 'Actually I wanted to sleep.'],
  [null, 'schließlich', null, 'finally, after all', 'Basics', 'Schließlich hat es geklappt.', 'In the end it worked out.'],
  [null, 'trotzdem', null, 'nevertheless', 'Basics', 'Es regnet, trotzdem gehen wir.', 'It is raining, nevertheless we are going.'],
  [null, 'deshalb', null, 'therefore', 'Basics', 'Ich bin müde, deshalb schlafe ich.', 'I am tired, therefore I am sleeping.'],
  [null, 'außerdem', null, 'besides, moreover', 'Basics', 'Außerdem ist es teuer.', 'Besides, it is expensive.'],
  [null, 'jedoch', null, 'however', 'Basics', 'Er ist klein, jedoch stark.', 'He is small, however strong.'],
  [null, 'bestimmt', null, 'certainly, definitely', 'Basics', 'Das schaffe ich bestimmt.', 'I will definitely manage that.'],
  [null, 'möglicherweise', null, 'possibly', 'Basics', 'Möglicherweise regnet es.', 'Possibly it will rain.'],
  [null, 'ziemlich', null, 'quite, fairly', 'Basics', 'Der Film war ziemlich gut.', 'The movie was quite good.'],
  [null, 'absolut', null, 'absolutely', 'Basics', 'Das ist absolut richtig.', 'That is absolutely right.'],
]
