import type { SeedRow } from './types'

/**
 * C1 seed corpus (232 rows): M12.3 batch (96, 2026-09-29) advanced health,
 * work/bureaucracy and household vocabulary + M12.4 batch (64) legal and
 * administrative register + M12.5 batch (72) emotions/character depth,
 * media critique and AI/technology register — the first C-level entries
 * in the vocab bank.
 */
export const C1_ROWS: SeedRow[] = [
  ['die', 'Vorerkrankung', 'Vorerkrankungen', 'pre-existing condition', 'Health', 'Die Vorerkrankung muss angegeben werden.', 'The pre-existing condition has to be declared.'],
  ['die', 'Dosierung', 'Dosierungen', 'dosage', 'Health', 'Die Dosierung steht auf dem Beipackzettel.', 'The dosage is on the package insert.'],
  ['die', 'Lebenserwartung', 'Lebenserwartungen', 'life expectancy', 'Health', 'Die Lebenserwartung steigt weiter.', 'Life expectancy keeps rising.'],
  ['das', 'Immunsystem', 'Immunsysteme', 'immune system', 'Health', 'Das Immunsystem kämpft gegen das Virus.', 'The immune system fights the virus.'],
  ['die', 'Prävention', 'Präventionen', 'prevention', 'Health', 'Die Prävention beginnt mit gesunder Ernährung.', 'Prevention starts with a healthy diet.'],
  ['die', 'Organspende', 'Organspenden', 'organ donation', 'Health', 'Die Organspende rettet Leben.', 'Organ donation saves lives.'],
  ['die', 'Blutspende', 'Blutspenden', 'blood donation', 'Health', 'Die Blutspende dauert nur zehn Minuten.', 'The blood donation takes only ten minutes.'],
  ['die', 'Intensivstation', 'Intensivstationen', 'intensive care unit', 'Health', 'Die Intensivstation ist ausgelastet.', 'The intensive care unit is at capacity.'],
  ['die', 'Überdosierung', 'Überdosierungen', 'overdose', 'Health', 'Die Überdosierung war ein Versehen.', 'The overdose was an accident.'],
  ['der', 'Erreger', 'Erreger', 'pathogen', 'Health', 'Der Erreger wird im Labor bestimmt.', 'The pathogen is identified in the lab.'],
  ['die', 'Beschwerde', 'Beschwerden', 'ailment; complaint', 'Health', 'Die Beschwerden des Patienten nehmen zu.', "The patient's ailments are increasing."],
  ['die', 'Atemnot', null, 'shortness of breath', 'Health', 'Die Atemnot trat plötzlich auf.', 'The shortness of breath occurred suddenly.'],
  ['die', 'Vene', 'Venen', 'vein', 'Health', 'Die Vene ist gut sichtbar.', 'The vein is clearly visible.'],
  ['die', 'Arterie', 'Arterien', 'artery', 'Health', 'Die Arterie ist verengt.', 'The artery is narrowed.'],
  ['das', 'Desinfektionsmittel', 'Desinfektionsmittel', 'disinfectant', 'Health', 'Das Desinfektionsmittel steht an der Tür.', 'The disinfectant is by the door.'],
  ['der', 'Impfstoff', 'Impfstoffe', 'vaccine', 'Health', 'Der Impfstoff muss gekühlt werden.', 'The vaccine has to be refrigerated.'],
  ['der', 'Antikörper', 'Antikörper', 'antibody', 'Health', 'Der Antikörper schützt vor einer Neuinfektion.', 'The antibody protects against reinfection.'],
  ['der', 'Sauerstoff', null, 'oxygen', 'Health', 'Der Sauerstoff im Blut wird gemessen.', 'The oxygen in the blood is measured.'],
  ['das', 'Pflegeheim', 'Pflegeheime', 'nursing home', 'Health', 'Das Pflegeheim liegt am Park.', 'The nursing home is by the park.'],
  ['die', 'Wiederbelebung', 'Wiederbelebungen', 'resuscitation', 'Health', 'Die Wiederbelebung dauerte zwanzig Minuten.', 'The resuscitation lasted twenty minutes.'],
  ['das', 'EKG', 'EKGs', 'EKG, electrocardiogram', 'Health', 'Das EKG zeigt einen ruhigen Rhythmus.', 'The EKG shows a steady rhythm.'],
  ['das', 'Beruhigungsmittel', 'Beruhigungsmittel', 'sedative', 'Health', 'Das Beruhigungsmittel wirkt nach zehn Minuten.', 'The sedative takes effect after ten minutes.'],
  ['die', 'Krücke', 'Krücken', 'crutch', 'Health', 'Die Krücke ist nach dem Unfall nötig.', 'The crutch is necessary after the accident.'],
  ['der', 'Juckreiz', null, 'itching', 'Health', 'Der Juckreiz hält den ganzen Tag an.', 'The itching lasts all day.'],
  ['der', 'Beipackzettel', 'Beipackzettel', 'package insert', 'Health', 'Der Beipackzettel listet die Nebenwirkungen auf.', 'The package insert lists the side effects.'],
  ['der', 'Hausbesuch', 'Hausbesuche', "(doctor's) house call", 'Health', 'Der Hausbesuch kostet extra.', 'The house call costs extra.'],
  ['die', 'Visite', 'Visiten', '(hospital) rounds', 'Health', 'Die Visite beginnt um acht Uhr.', 'The rounds begin at eight.'],
  ['der', 'Blinddarm', 'Blinddärme', 'appendix', 'Health', 'Der Blinddarm wird morgen entfernt.', 'The appendix is being removed tomorrow.'],
  ['das', 'Anschreiben', 'Anschreiben', 'cover letter', 'Work', 'Das Anschreiben überzeugt die Personalerin.', 'The cover letter convinces the recruiter.'],
  ['das', 'Arbeitszeugnis', 'Arbeitszeugnisse', 'employment reference', 'Work', 'Das Arbeitszeugnis ist qualifiziert ausgestellt.', 'The employment reference is fully detailed.'],
  ['das', 'Bewerbungsschreiben', 'Bewerbungsschreiben', 'letter of application', 'Work', 'Das Bewerbungsschreiben ist kurz und präzise.', 'The letter of application is short and precise.'],
  ['die', 'Bewerbungsunterlagen', null, 'application documents', 'Work', 'Die Bewerbungsunterlagen sind vollständig.', 'The application documents are complete.'],
  ['die', 'Gehaltsabrechnung', 'Gehaltsabrechnungen', 'payslip', 'Work', 'Die Gehaltsabrechnung kommt monatlich per Post.', 'The payslip comes monthly by mail.'],
  ['die', 'Gehaltsverhandlung', 'Gehaltsverhandlungen', 'salary negotiation', 'Work', 'Die Gehaltsverhandlung verlief erfolgreich.', 'The salary negotiation went well.'],
  ['die', 'Sozialversicherung', 'Sozialversicherungen', 'social insurance', 'Work', 'Die Sozialversicherung umfasst fünf Zweige.', 'Social insurance comprises five branches.'],
  ['die', 'Rentenversicherung', 'Rentenversicherungen', 'pension insurance', 'Work', 'Die Rentenversicherung sichert das Alter.', 'The pension insurance secures old age.'],
  ['die', 'Krankenversicherung', 'Krankenversicherungen', 'health insurance', 'Work', 'Die Krankenversicherung zahlt die Behandlung.', 'The health insurance pays for the treatment.'],
  ['die', 'Arbeitslosenversicherung', 'Arbeitslosenversicherungen', 'unemployment insurance', 'Work', 'Die Arbeitslosenversicherung greift nach einem Jahr.', 'Unemployment insurance kicks in after a year.'],
  ['der', 'Steuerberater', 'Steuerberater', 'tax advisor', 'Work', 'Der Steuerberater findet weitere Abzüge.', 'The tax advisor finds more deductions.'],
  ['die', 'Einarbeitung', 'Einarbeitungen', 'onboarding, induction', 'Work', 'Die Einarbeitung dauert vier Wochen.', 'The onboarding lasts four weeks.'],
  [null, 'sich einarbeiten', null, 'to get up to speed', 'Work', 'Er arbeitet sich schnell ein.', 'He is getting up to speed quickly.'],
  ['die', 'Laufbahn', 'Laufbahnen', 'career path', 'Work', 'Die Laufbahn begann mit einer Lehre.', 'The career path began with an apprenticeship.'],
  ['der', 'Nachfolger', 'Nachfolger', 'successor', 'Work', 'Der Nachfolger tritt im Mai an.', 'The successor takes over in May.'],
  ['der', 'Vorgänger', 'Vorgänger', 'predecessor', 'Work', 'Der Vorgänger hinterließ ein gut organisiertes Büro.', 'The predecessor left a well-organized office.'],
  ['die', 'Stellenausschreibung', 'Stellenausschreibungen', 'job posting', 'Work', 'Die Stellenausschreibung richtet sich an Quereinsteiger.', 'The job posting is aimed at career changers.'],
  ['der', 'Stellenabbau', null, 'job cuts', 'Work', 'Der Stellenabbau betrifft zwei Abteilungen.', 'The job cuts affect two departments.'],
  ['die', 'Kündigungsfrist', 'Kündigungsfristen', 'notice period', 'Work', 'Die Kündigungsfrist beträgt drei Monate.', 'The notice period is three months.'],
  [null, 'befördern', null, 'to promote', 'Work', 'Die Firma befördert ihn zum Teamleiter.', 'The company is promoting him to team leader.'],
  ['der', 'Quereinsteiger', 'Quereinsteiger', 'career changer', 'Work', 'Der Quereinsteiger bringt frische Ideen mit.', 'The career changer brings fresh ideas.'],
  ['der', 'Wiedereinstieg', 'Wiedereinstiege', 'return to work', 'Work', 'Der Wiedereinstieg nach der Elternzeit gelingt.', 'The return to work after parental leave succeeds.'],
  ['der', 'Personaler', 'Personaler', 'HR manager', 'Work', 'Der Personaler sichtet die Bewerbungen.', 'The HR manager is screening the applications.'],
  ['der', 'Inhaber', 'Inhaber', 'owner, holder', 'Work', 'Der Inhaber führt den Betrieb in dritter Generation.', 'The owner runs the business in the third generation.'],
  ['die', 'Elternzeit', null, 'parental leave', 'Work', 'Die Elternzeit endet im September.', 'The parental leave ends in September.'],
  ['die', 'Überlastung', 'Überlastungen', 'overload, burnout risk', 'Work', 'Die Überlastung führt zu Fehlern.', 'The overload leads to mistakes.'],
  ['das', 'Gewerbe', 'Gewerbe', 'trade, business', 'Work', 'Das Gewerbe muss angemeldet werden.', 'The business has to be registered.'],
  ['die', 'Herstellung', 'Herstellungen', 'production, manufacture', 'Work', 'Die Herstellung erfolgt in Deutschland.', 'The manufacture takes place in Germany.'],
  ['die', 'Verarbeitung', 'Verarbeitungen', 'processing', 'Work', 'Die Verarbeitung der Daten dauert Stunden.', 'The processing of the data takes hours.'],
  ['die', 'Logistik', null, 'logistics', 'Work', 'Die Logistik der Firma ist ausgefeilt.', 'The logistics of the company is sophisticated.'],
  ['die', 'Spedition', 'Speditionen', 'freight company', 'Work', 'Die Spedition liefert Möbel in ganz Europa.', 'The freight company delivers furniture across Europe.'],
  ['die', 'Fracht', 'Frachten', 'freight, cargo', 'Work', 'Die Fracht wiegt über zwanzig Tonnen.', 'The cargo weighs over twenty tons.'],
  ['die', 'Beanstandung', 'Beanstandungen', 'complaint (about defects)', 'Work', 'Die Beanstandung wurde schriftlich eingereicht.', 'The complaint was submitted in writing.'],
  [null, 'unterzeichnen', null, 'to sign (formally)', 'Work', 'Beide Parteien unterzeichnen den Vertrag.', 'Both parties are signing the contract.'],
  ['das', 'Nettogehalt', 'Nettogehälter', 'net salary', 'Work', 'Das Nettogehalt landet auf dem Konto.', 'The net salary lands in the account.'],
  ['das', 'Bruttogehalt', 'Bruttogehälter', 'gross salary', 'Work', 'Das Bruttogehalt steht im Arbeitsvertrag.', 'The gross salary is in the employment contract.'],
  ['der', 'Abzug', 'Abzüge', 'deduction', 'Work', 'Der Abzug für Steuern wächst mit dem Lohn.', 'The deduction for taxes grows with the pay.'],
  ['die', 'Sozialabgaben', null, 'social security contributions', 'Work', 'Die Sozialabgaben trägt Arbeit und Arbeitnehmer je zur Hälfte.', 'The social security contributions are shared equally by employer and employee.'],
  ['der', 'Steuerbescheid', 'Steuerbescheide', 'tax assessment notice', 'Work', 'Der Steuerbescheid kommt im Juni.', 'The tax assessment notice comes in June.'],
  ['die', 'Steuererstattung', 'Steuererstattungen', 'tax refund', 'Work', 'Die Steuererstattung fiel dieses Jahr hoch aus.', 'The tax refund turned out high this year.'],
  [null, 'erstatten', null, 'to reimburse', 'Work', 'Die Firma erstattet die Fahrtkosten.', 'The company reimburses the travel costs.'],
  ['der', 'Zinssatz', 'Zinssätze', 'interest rate', 'Work', 'Der Zinssatz bleibt dieses Jahr stabil.', 'The interest rate stays stable this year.'],
  ['die', 'Ratenzahlung', 'Ratenzahlungen', 'payment in installments', 'Work', 'Die Ratenzahlung verteilt den Preis auf zwölf Monate.', 'Payment in installments spreads the price over twelve months.'],
  [null, 'tilgen', null, 'to pay off, to amortize', 'Work', 'Das Darlehen wird in zehn Jahren getilgt.', 'The loan is paid off in ten years.'],
  [null, 'bargeldlos', null, 'cashless', 'Work', 'Bargeldlos zahlen ist hier üblich.', 'Paying cashlessly is common here.'],
  ['die', 'Zahlungsfrist', 'Zahlungsfristen', 'payment deadline', 'Work', 'Die Zahlungsfrist läuft Ende des Monats ab.', 'The payment deadline expires at the end of the month.'],
  ['die', 'Mahnung', 'Mahnungen', 'payment reminder', 'Work', 'Die Mahnung liegt heute im Briefkasten.', 'The payment reminder is in the mailbox today.'],
  [null, 'mahnen', null, 'to send a reminder', 'Work', 'Das Unternehmen mahnt nach vierzehn Tagen.', 'The company sends a reminder after fourteen days.'],
  ['die', 'Vorkasse', null, 'payment in advance', 'Work', 'Vorkasse ist bei diesem Shop Pflicht.', 'Payment in advance is mandatory at this shop.'],
  ['die', 'Betriebsausgabe', 'Betriebsausgaben', 'business expense', 'Work', 'Die Betriebsausgabe ist voll absetzbar.', 'The business expense is fully deductible.'],
  ['der', 'Freiberufler', 'Freiberufler', 'freelance professional', 'Work', 'Der Freiberufler schreibt Rechnungen ohne Umsatzsteuer.', 'The freelance professional writes invoices without VAT.'],
  ['die', 'Nebentätigkeit', 'Nebentätigkeiten', 'side job, secondary employment', 'Work', 'Die Nebentätigkeit ist beim Arbeitgeber gemeldet.', 'The side job is registered with the employer.'],
  ['die', 'Niederlassung', 'Niederlassungen', 'branch office', 'Work', 'Die Niederlassung in Wien öffnet im Herbst.', 'The branch office in Vienna opens in fall.'],
  ['der', 'Familienbetrieb', 'Familienbetriebe', 'family business', 'Work', 'Der Familienbetrieb besteht seit hundert Jahren.', 'The family business has existed for a hundred years.'],
  ['die', 'Ausschreibung', 'Ausschreibungen', 'tender, call for bids', 'Work', 'Die Ausschreibung richtet sich an kleine Firmen.', 'The tender is aimed at small companies.'],
  ['der', 'Kostenvoranschlag', 'Kostenvoranschläge', 'cost estimate', 'Work', 'Der Kostenvoranschlag liegt bei zweitausend Euro.', 'The cost estimate is two thousand euros.'],
  ['das', 'Aktenzeichen', 'Aktenzeichen', 'file number, reference number', 'Work', 'Das Aktenzeichen steht oben auf dem Brief.', 'The file number is at the top of the letter.'],
  ['die', 'Wartung', 'Wartungen', 'maintenance, servicing', 'Work', 'Die Wartung der Anlage erfolgt jährlich.', 'The maintenance of the system takes place annually.'],
  ['der', 'Fachbetrieb', 'Fachbetriebe', 'specialist company', 'Work', 'Der Fachbetrieb repariert die Heizung.', 'The specialist company repairs the heating.'],
  ['die', 'Montage', 'Montagen', 'assembly, installation', 'Work', 'Die Montage der Küche dauert zwei Tage.', 'The installation of the kitchen takes two days.'],
  ['der', 'Abstellraum', 'Abstellräume', 'storage room', 'Home', 'Der Abstellraum ist im Erdgeschoss.', 'The storage room is on the ground floor.'],
  [null, 'entkalken', null, 'to descale', 'Home', 'Die Maschine muss regelmäßig entkalkt werden.', 'The machine has to be descaled regularly.'],
  [null, 'bestreuen', null, 'to sprinkle', 'Food', 'Er bestreut den Kuchen mit Puderzucker.', 'He is sprinkling powdered sugar on the cake.'],
  [null, 'abschmecken', null, 'to adjust the seasoning', 'Food', 'Die Suppe muss noch abgeschmeckt werden.', 'The soup still needs its seasoning adjusted.'],
  [null, 'fade', null, 'bland, insipid', 'Food', 'Der Reis schmeckt fade.', 'The rice tastes bland.'],
  ['der', 'Bissen', 'Bissen', 'mouthful, bite', 'Food', 'Der erste Bissen war heiß.', 'The first bite was hot.'],
  ['die', 'Beschäftigung', 'Beschäftigungen', 'occupation, employment', 'Work', 'Die Beschäftigung mit dem Thema dauert Wochen.', 'Working on the topic takes weeks.'],
  ['die', 'Abrechnung', 'Abrechnungen', 'settlement, statement', 'Work', 'Die Abrechnung erfolgt am Monatsende.', 'The settlement takes place at the end of the month.'],
  // ── M12.4: Reisen/Verkehr + Behörden/Ämter — legal/administrative register ──
  ['das', 'Amtsgericht', 'Amtsgerichte', 'local (first-instance) court', 'Law', 'Der Prozess beginnt am Amtsgericht.', 'The trial begins at the local court.'],
  ['das', 'Landgericht', 'Landgerichte', 'regional court', 'Law', 'Das Landgericht verhandelt größere Strafsachen.', 'The regional court hears major criminal cases.'],
  ['das', 'Oberlandesgericht', 'Oberlandesgerichte', 'higher regional court', 'Law', 'Das Urteil wurde vom Oberlandesgericht bestätigt.', 'The verdict was confirmed by the higher regional court.'],
  ['der', 'Bundesgerichtshof', null, 'Federal Court of Justice', 'Law', 'Der Bundesgerichtshof entscheidet als letzte Instanz in Zivilsachen.', 'The Federal Court of Justice decides as the last instance in civil matters.'],
  ['das', 'Bundesverfassungsgericht', null, 'Federal Constitutional Court', 'Law', 'Das Bundesverfassungsgericht prüft Gesetze auf ihre Verfassungsmäßigkeit.', 'The Constitutional Court reviews laws for constitutionality.'],
  ['das', 'Schwurgericht', 'Schwurgerichte', 'jury court', 'Law', 'Mord verhandelt das Schwurgericht.', 'Murder is heard by the jury court.'],
  ['das', 'Verwaltungsgericht', 'Verwaltungsgerichte', 'administrative court', 'Law', 'Das Verwaltungsgericht prüft behördliche Entscheidungen.', 'The administrative court reviews administrative decisions.'],
  ['der', 'Gerichtssaal', 'Gerichtssäle', 'courtroom', 'Law', 'Der Gerichtssaal ist bis auf den letzten Platz gefüllt.', 'The courtroom is filled to the last seat.'],
  ['der', 'Staatsanwalt', 'Staatsanwälte', 'public prosecutor', 'Law', 'Der Staatsanwalt erhebt Anklage.', 'The prosecutor brings charges.'],
  ['die', 'Staatsanwaltschaft', 'Staatsanwaltschaften', "public prosecutor's office", 'Law', 'Die Staatsanwaltschaft leitet das Ermittlungsverfahren.', "The prosecutor's office directs the investigation."],
  ['der', 'Rechtsanwalt', 'Rechtsanwälte', 'attorney, lawyer', 'Law', 'Der Rechtsanwalt rät zu einem Vergleich.', 'The attorney advises a settlement.'],
  ['der', 'Verteidiger', 'Verteidiger', 'defence counsel', 'Law', 'Der Verteidiger beantragt die Freilassung.', 'The defence counsel requests release.'],
  [null, 'verteidigen', null, 'to defend', 'Law', 'Jeder Angeklagte darf sich selbst verteidigen.', 'Every defendant may defend himself.'],
  [null, 'verurteilen', null, 'to sentence, to convict', 'Law', 'Das Gericht verurteilt ihn zu zwei Jahren Bewährung.', 'The court sentences him to two years on probation.'],
  [null, 'ermitteln', null, 'to investigate', 'Law', 'Die Behörde ermittelt seit Monaten gegen die Firma.', 'The authority has been investigating the company for months.'],
  ['die', 'Ermittlung', 'Ermittlungen', 'investigation', 'Law', 'Die Ermittlung dauert ein Jahr.', 'The investigation takes a year.'],
  ['die', 'Festnahme', 'Festnahmen', 'arrest', 'Law', 'Die Festnahme verlief ohne Widerstand.', 'The arrest went without resistance.'],
  [null, 'festnehmen', null, 'to arrest', 'Law', 'Die Beamten nehmen den Tatverdächtigen fest.', 'The officers arrest the suspect.'],
  ['die', 'Vernehmung', 'Vernehmungen', 'interrogation', 'Law', 'Die Vernehmung des Zeugen dauerte drei Stunden.', 'The interrogation of the witness took three hours.'],
  ['die', 'Durchsuchung', 'Durchsuchungen', 'search (of premises)', 'Law', 'Die Durchsuchung der Wohnung brachte Beweise.', 'The search of the apartment produced evidence.'],
  ['die', 'Fahndung', null, 'manhunt', 'Law', 'Die Fahndung nach dem Täter läuft europaweit.', 'The manhunt for the perpetrator is underway across Europe.'],
  ['der', 'Haftbefehl', 'Haftbefehle', 'arrest warrant', 'Law', 'Der Richter unterschreibt den Haftbefehl.', 'The judge signs the arrest warrant.'],
  ['die', 'Untersuchungshaft', null, 'pretrial detention', 'Law', 'Der Verdächtige sitzt in Untersuchungshaft.', 'The suspect is in pretrial detention.'],
  ['die', 'Haft', null, 'detention, custody', 'Law', 'Die Haft dauerte drei Monate.', 'The detention lasted three months.'],
  ['der', 'Zwang', null, 'coercion, force', 'Law', 'Er handelte unter Zwang.', 'He acted under coercion.'],
  ['die', 'Strafverfolgung', null, 'criminal prosecution', 'Law', 'Die Strafverfolgung liegt beim Staat.', 'Criminal prosecution lies with the state.'],
  ['der', 'Verdächtiger', 'Verdächtigen', 'suspect', 'Law', 'Verdächtiger gesteht nach fünf Stunden.', 'Suspect confesses after five hours.'],
  ['die', 'Bewährung', null, 'probation', 'Law', 'Er kam mit Bewährung davon.', 'He got off with probation.'],
  ['die', 'Beweisaufnahme', null, 'taking of evidence', 'Law', 'Die Beweisaufnahme ergab ein klares Bild.', 'The taking of evidence produced a clear picture.'],
  ['die', 'Zeugenaussage', 'Zeugenaussagen', 'testimony', 'Law', 'Die Zeugenaussage entlastete den Angeklagten.', 'The testimony exonerated the defendant.'],
  ['die', 'Anhörung', 'Anhörungen', 'hearing', 'Law', 'Der Betroffene hat Anspruch auf eine Anhörung.', 'The person concerned is entitled to a hearing.'],
  ['die', 'Revision', 'Revisionen', 'revision (appeal on points of law)', 'Law', 'Die Revision blieb ohne Erfolg.', 'The revision was unsuccessful.'],
  ['die', 'Verfassung', 'Verfassungen', 'constitution', 'Law', 'Die Verfassung garantiert Grundrechte.', 'The constitution guarantees basic rights.'],
  ['das', 'Grundgesetz', null, 'Basic Law (German constitution)', 'Law', 'Das Grundgesetz trat 1949 in Kraft.', 'The Basic Law came into force in 1949.'],
  ['die', 'Rechtsprechung', null, 'jurisprudence, case law', 'Law', 'Die Rechtsprechung des Gerichts ist konstant.', "The court's jurisprudence is consistent."],
  ['die', 'Rechtslage', null, 'legal situation', 'Law', 'Die Rechtslage ist unklar und umstritten.', 'The legal situation is unclear and disputed.'],
  ['das', 'Gesetzbuch', 'Gesetzbücher', 'legal code', 'Law', 'Das bürgerliche Gesetzbuch regelt Verträge.', 'The civil code regulates contracts.'],
  ['das', 'Rechtssystem', 'Rechtssysteme', 'legal system', 'Law', 'Das Rechtssystem unterscheidet sich von Land zu Land.', 'Legal systems differ from country to country.'],
  ['die', 'Justiz', null, 'judiciary, justice system', 'Law', 'Die Justiz arbeitet langsam, aber gründlich.', 'The judiciary works slowly but thoroughly.'],
  ['der', 'Rechtsbruch', 'Rechtsbrüche', 'breach of law', 'Law', 'Der Rechtsbruch zieht Sanktionen nach sich.', 'A breach of law entails sanctions.'],
  ['die', 'Gesetzeslücke', 'Gesetzeslücken', 'loophole, gap in the law', 'Law', 'Die Gesetzeslücke wird bald geschlossen.', 'The loophole will soon be closed.'],
  ['die', 'Auslegung', 'Auslegungen', 'interpretation', 'Law', 'Die Auslegung des Gesetzes ist strittig.', 'The interpretation of the law is disputed.'],
  ['das', 'Rechtsmittel', 'Rechtsmittel', 'legal remedy, appeal', 'Law', 'Gegen das Urteil gibt es Rechtsmittel.', 'There are legal remedies against the verdict.'],
  ['die', 'Berufung', 'Berufungen', 'appeal', 'Law', 'Er legte Berufung gegen das Urteil ein.', 'He filed an appeal against the verdict.'],
  ['die', 'Klageerhebung', null, 'filing of a lawsuit', 'Law', 'Die Klageerhebung erfolgte fristgerecht.', 'The lawsuit was filed on time.'],
  ['der', 'Widerspruch', 'Widersprüche', 'objection; contradiction', 'Law', 'Gegen den Bescheid kannst du Widerspruch einlegen.', 'You can file an objection against the decision.'],
  ['die', 'Nachfrist', 'Nachfristen', 'grace period', 'Law', 'Die Nachfrist beträgt zwei Wochen.', 'The grace period is two weeks.'],
  [null, 'fristlos', null, 'with immediate effect, without notice', 'Law', 'Die Kündigung erfolgte fristlos.', 'The termination took effect immediately.'],
  ['die', 'Instanz', 'Instanzen', 'instance (court level)', 'Law', 'Die zweite Instanz hob das Urteil auf.', 'The second instance overturned the verdict.'],
  ['der', 'Instanzenzug', null, 'hierarchy of instances', 'Law', 'Der Instanzenzug umfasst bis zu drei Stufen.', 'The hierarchy of instances comprises up to three levels.'],
  ['die', 'Rechtskraft', null, 'finality, legal force', 'Law', 'Mit der Rechtskraft ist das Verfahren beendet.', 'Once final, the proceedings are closed.'],
  ['die', 'Vollstreckung', 'Vollstreckungen', 'enforcement', 'Law', 'Die Vollstreckung des Urteils dauert Monate.', 'Enforcement of the judgment takes months.'],
  ['die', 'Zwangsmaßnahme', 'Zwangsmaßnahmen', 'coercive measure', 'Law', 'Jede Zwangsmaßnahme braucht eine Rechtsgrundlage.', 'Every coercive measure needs a legal basis.'],
  ['die', 'Ordnungswidrigkeit', 'Ordnungswidrigkeiten', 'administrative offence', 'Law', 'Falschparken ist eine Ordnungswidrigkeit.', 'Illegal parking is an administrative offence.'],
  ['der', 'Schadensersatz', null, 'damages, compensation', 'Law', 'Sie klagt auf Schadensersatz.', 'She is suing for damages.'],
  ['das', 'Schmerzensgeld', null, 'compensation for pain and suffering', 'Law', 'Das Gericht sprach ihm Schmerzensgeld zu.', 'The court awarded him compensation for pain.'],
  ['die', 'Verjährung', null, 'statute of limitations', 'Law', 'Nach fünf Jahren tritt Verjährung ein.', 'After five years the statute of limitations applies.'],
  ['die', 'Wiedergutmachung', null, 'reparation, amends', 'Law', 'Er bot finanzielle Wiedergutmachung an.', 'He offered financial reparation.'],
  ['der', 'Gerichtsvollzieher', 'Gerichtsvollzieher', 'bailiff', 'Law', 'Der Gerichtsvollzieher pfändet das Auto.', 'The bailiff seizes the car.'],
  ['die', 'Fluchtgefahr', null, 'risk of flight', 'Law', 'Wegen Fluchtgefahr wurde er festgenommen.', 'He was arrested because of the risk of flight.'],
  ['der', 'Zeugenschutz', null, 'witness protection', 'Law', 'Der Zeuge lebt unter Zeugenschutz.', 'The witness lives under protection.'],
  ['der', 'Strafantrag', 'Strafanträge', 'criminal complaint', 'Law', 'Der Strafantrag muss rechtzeitig gestellt werden.', 'The criminal complaint must be filed in time.'],
  ['die', 'Begnadigung', 'Begnadigungen', 'pardon', 'Law', 'Die Begnadigung ist ein Akt der Gnade.', 'The pardon is an act of clemency.'],
  ['die', 'Amnestie', 'Amnestien', 'amnesty', 'Law', 'Die Amnestie gilt für Kleinkriminelle.', 'The amnesty applies to minor offenders.'],

  // ── M12.5: Gefühle/Charakter + Medien/Technik ──
  ['die', 'Empathie', null, 'empathy', 'Emotions', 'Empathie kann man lernen.', 'Empathy can be learned.'],
  ['das', 'Unterbewusstsein', null, 'subconscious', 'Emotions', 'Ängste sitzen oft im Unterbewusstsein.', 'Fears often sit in the subconscious.'],
  ['die', 'Gemütsverfassung', 'Gemütsverfassungen', 'state of mind', 'Emotions', 'Die Therapeutin fragt nach ihrer Gemütsverfassung.', 'The therapist asks about her state of mind.'],
  ['die', 'Seelenruhe', null, 'inner calm, serenity', 'Emotions', 'Mit Seelenruhe erträgt sie die Kritik.', 'With serenity she endures the criticism.'],
  ['die', 'Wehmut', null, 'wistfulness, melancholy', 'Emotions', 'Beim Anblick der alten Fotos spürte er Wehmut.', 'At the sight of the old photos he felt wistfulness.'],
  ['der', 'Übermut', null, 'overconfidence, high spirits', 'Emotions', 'Aus Übermut kletterte er auf das Dach.', 'Out of high spirits he climbed onto the roof.'],
  ['die', 'Genugtuung', null, 'satisfaction, vindication', 'Emotions', 'Nach dem Sieg fühlte er tiefe Genugtuung.', 'After the victory he felt deep vindication.'],
  ['die', 'Betroffenheit', null, 'consternation, distress', 'Emotions', 'Die Nachricht löste landesweite Betroffenheit aus.', 'The news caused nationwide consternation.'],
  ['das', 'Unbehagen', null, 'discomfort, unease', 'Emotions', 'Das Thema löst bei ihr Unbehagen aus.', 'The topic triggers unease in her.'],
  ['das', 'Entsetzen', null, 'horror, shock', 'Emotions', 'Ein Schrei des Entsetzens ging durch den Saal.', 'A cry of horror went through the hall.'],
  ['die', 'Entrüstung', null, 'indignation, outrage', 'Emotions', 'Seine Bemerkung löste Entrüstung aus.', 'His remark caused indignation.'],
  ['die', 'Hingabe', null, 'dedication, devotion', 'Emotions', 'Sie unterrichtet mit großer Hingabe.', 'She teaches with great dedication.'],
  ['die', 'Verachtung', null, 'contempt', 'Emotions', 'Er spricht mit Verachtung über den Verrat.', 'He speaks about the betrayal with contempt.'],
  ['die', 'Nostalgie', 'Nostalgien', 'nostalgia', 'Emotions', 'Alte Fotos wecken bei ihr Nostalgie.', 'Old photos awaken nostalgia in her.'],
  ['der', 'Ekel', null, 'disgust', 'Emotions', 'Der Anblick erfüllte sie mit Ekel.', 'The sight filled her with disgust.'],
  ['die', 'Abscheu', null, 'abhorrence, repugnance', 'Emotions', 'Gewalt erfüllt ihn mit Abscheu.', 'Violence fills him with abhorrence.'],
  ['die', 'Verlegenheit', null, 'embarrassment', 'Emotions', 'Aus Verlegenheit wurde sie still.', 'Out of embarrassment she went quiet.'],
  ['die', 'Begierde', null, 'desire, craving', 'Emotions', 'Seine Begierde nach Anerkennung trieb ihn an.', 'His craving for recognition drove him on.'],
  ['die', 'Leidenschaft', 'Leidenschaften', 'passion', 'Emotions', 'Sie spielt mit großer Leidenschaft Klavier.', 'She plays the piano with great passion.'],
  [null, 'teilnahmslos', null, 'apathetic, indifferent', 'Emotions', 'Sie hörte teilnahmslos zu.', 'She listened apathetically.'],
  ['die', 'Schadenfreude', null, 'schadenfreude, gloating', 'Emotions', 'Schadenfreude ist keine schöne Eigenschaft.', 'Schadenfreude is not a nice trait.'],
  ['die', 'Zuneigung', null, 'affection', 'Emotions', 'Zwischen den beiden entwickelte sich Zuneigung.', 'Affection developed between the two of them.'],
  ['die', 'Lebensfreude', null, 'joie de vivre, love of life', 'Emotions', 'Trotz allem bewahrt sie ihre Lebensfreude.', 'Despite everything she keeps her love of life.'],
  ['die', 'Selbstliebe', null, 'self-love, self-care', 'Emotions', 'Gesunde Selbstliebe stärkt die Psyche.', 'Healthy self-love strengthens the psyche.'],
  ['die', 'Schwärmerei', null, 'gushing, infatuation', 'Emotions', 'Seine Schwärmerei für den Sänger geht den Freunden auf die Nerven.', 'His gushing about the singer gets on the nerves of his friends.'],
  ['die', 'Bewunderung', null, 'admiration', 'Emotions', 'Sie spricht mit Bewunderung über ihre Lehrerin.', 'She speaks about her teacher with admiration.'],
  ['die', 'Heuchelei', null, 'hypocrisy', 'Character', 'Seine Heuchelei flog beim zweiten Gespräch auf.', 'His hypocrisy was exposed in the second conversation.'],
  ['der', 'Heuchler', 'Heuchler', 'hypocrite', 'Character', 'Der Heuchler spielt Empfindungen nur vor.', 'The hypocrite only feigns feelings.'],
  ['die', 'Aufrichtigkeit', null, 'sincerity, candor', 'Character', 'Ihre Aufrichtigkeit gewinnt das Vertrauen der Gruppe.', 'Her sincerity wins the trust of the group.'],
  ['die', 'Selbstdisziplin', null, 'self-discipline', 'Character', 'Ohne Selbstdisziplin scheitert jedes Vorhaben.', 'Without self-discipline every project fails.'],
  ['die', 'Weisheit', null, 'wisdom', 'Character', 'In ihren Worten liegt viel Weisheit.', 'There is a lot of wisdom in her words.'],
  ['das', 'Laster', 'Laster', 'vice', 'Character', 'Das Rauchen ist ein ungesundes Laster.', 'Smoking is an unhealthy vice.'],
  ['das', 'Gemüt', 'Gemüter', 'mind, disposition', 'Character', 'Die Nachricht beruhigte die erregten Gemüter.', 'The news calmed the excited minds.'],
  ['die', 'Selbstgefälligkeit', null, 'complacency, smugness', 'Character', 'Aus Selbstgefälligkeit übersieht er seine Fehler.', 'Out of complacency he overlooks his mistakes.'],
  ['die', 'Besonnenheit', null, 'composure, level-headedness', 'Character', 'Mit Besonnenheit schlichtete er den Streit.', 'With composure he settled the dispute.'],
  ['die', 'Gewissenhaftigkeit', null, 'conscientiousness', 'Character', 'Gewissenhaftigkeit zeichnet ihre Arbeit aus.', 'Conscientiousness characterizes her work.'],
  ['die', 'Verschwiegenheit', null, 'discretion', 'Character', 'Als Anwalt ist Verschwiegenheit Pflicht.', 'As a lawyer discretion is a duty.'],
  ['die', 'Arglosigkeit', null, 'gullibility, artlessness', 'Character', 'Ihre Arglosigkeit wurde ausgenutzt.', 'Her gullibility was taken advantage of.'],
  ['die', 'Hinterhältigkeit', null, 'deviousness', 'Character', 'Die Hinterhältigkeit des Plans schockierte alle.', 'The deviousness of the plan shocked everyone.'],
  ['die', 'Skrupellosigkeit', null, 'unscrupulousness', 'Character', 'Seine Skrupellosigkeit kostete ihn den Respekt der Kollegen.', 'His unscrupulousness cost him the respect of his colleagues.'],
  ['die', 'Skrupel', null, 'scruples', 'Character', 'Der Betrüger kennt keine Skrupel.', 'The fraudster knows no scruples.'],
  ['die', 'Integrität', null, 'integrity', 'Character', 'Seine Integrität ist über jeden Zweifel erhaben.', 'His integrity is beyond any doubt.'],
  ['die', 'Authentizität', null, 'authenticity', 'Character', 'Ihre Authentizität überzeugt das Publikum.', 'Her authenticity convinces the audience.'],
  ['das', 'Einfühlungsvermögen', null, 'empathy, capacity for empathy', 'Character', 'Einfühlungsvermögen zeichnet gute Führungskräfte aus.', 'Empathy characterizes good leaders.'],
  ['das', 'Pflichtgefühl', null, 'sense of duty', 'Character', 'Aus starkem Pflichtgefühl kam er trotz Fieber.', 'Out of a strong sense of duty he came despite a fever.'],
  ['der', 'Starrsinn', null, 'obstinacy', 'Character', 'Sein Starrsinn blockiert jede Einigung.', 'His obstinacy blocks any agreement.'],
  ['die', 'Güte', null, 'goodness, kindness', 'Character', 'Sie begegnet allen Menschen mit Güte.', 'She meets all people with kindness.'],
  ['die', 'Gesinnung', null, 'conviction, mindset', 'Character', 'Seine politische Gesinnung spielt hier keine Rolle.', 'His political conviction plays no role here.'],
  ['die', 'Weltanschauung', 'Weltanschauungen', 'worldview', 'Character', 'Reisen erweitern die eigene Weltanschauung.', 'Travel broadens your own worldview.'],
  ['das', 'Selbstwertgefühl', null, 'self-esteem', 'Character', 'Ein stabiles Selbstwertgefühl schützt vor Kränkungen.', 'A stable self-esteem protects against affronts.'],
  ['die', 'Meinungsbildung', null, 'opinion formation', 'Media', 'Soziale Medien beeinflussen die Meinungsbildung stark.', 'Social media strongly influence opinion formation.'],
  ['der', 'Boulevardjournalismus', null, 'tabloid journalism', 'Media', 'Boulevardjournalismus lebt von Skandalen.', 'Tabloid journalism lives off scandals.'],
  ['die', 'Auflagenhöhe', 'Auflagenhöhen', 'circulation figure', 'Media', 'Die Auflagenhöhe der Zeitung sinkt seit Jahren.', 'The circulation figure of the newspaper has been falling for years.'],
  ['die', 'Medienkritik', null, 'media criticism', 'Media', 'Medienkritik gehört zur Demokratie.', 'Media criticism is part of democracy.'],
  ['der', 'Aufmacher', 'Aufmacher', 'front-page story', 'Media', 'Der Aufmacher widmet sich der Klimakrise.', 'The front-page story is devoted to the climate crisis.'],
  ['die', 'Glosse', 'Glossen', 'gloss (satirical column)', 'Media', 'Ihre Glosse trifft den Nerv der Leser.', 'Her gloss hits a nerve with readers.'],
  ['das', 'Feuilleton', 'Feuilletons', 'arts and culture section', 'Media', 'Die Rezension erschien im Feuilleton.', 'The review appeared in the arts section.'],
  ['das', 'Dossier', 'Dossiers', 'dossier, file', 'Media', 'Die Redaktion erstellte ein Dossier zu dem Fall.', 'The editorial office compiled a dossier on the case.'],
  ['die', 'Recherche', 'Recherchen', 'research, investigation (journalism)', 'Media', 'Die Recherche ergab Überraschendes.', 'The research produced surprising findings.'],
  ['der', 'Redakteur', 'Redakteure', 'editor', 'Media', 'Der Redakteur kürzt meinen Artikel für die morgige Ausgabe.', 'The editor shortens my article for the edition tomorrow.'],
  ['der', 'Verleger', 'Verleger', 'publisher', 'Media', 'Der Verleger entscheidet über jedes neue Buch.', 'The publisher decides about every new book.'],
  ['die', 'künstliche Intelligenz', null, 'artificial intelligence', 'Technology', 'Künstliche Intelligenz verändert viele Berufe.', 'Artificial intelligence is changing many professions.'],
  ['das', 'maschinelle Lernen', null, 'machine learning', 'Technology', 'Viele Anwendungen nutzen das maschinelle Lernen.', 'Many applications use machine learning.'],
  ['die', 'Datenanalyse', 'Datenanalysen', 'data analysis', 'Technology', 'Die Datenanalyse deckt überraschende Muster auf.', 'The data analysis reveals surprising patterns.'],
  ['die', 'Cybersicherheit', null, 'cybersecurity', 'Technology', 'Cybersicherheit hat für Banken höchste Priorität.', 'Cybersecurity has the highest priority for banks.'],
  ['die', 'Vernetzung', null, 'interconnection, networking', 'Technology', 'Die zunehmende Vernetzung schafft neue Risiken.', 'The increasing interconnection creates new risks.'],
  ['die', 'Überwachung', 'Überwachungen', 'surveillance, monitoring', 'Technology', 'Die Überwachung öffentlicher Plätze nimmt zu.', 'The surveillance of public places is increasing.'],
  ['die', 'Manipulation', 'Manipulationen', 'manipulation', 'Technology', 'Die Manipulation von Daten ist strafbar.', 'The manipulation of data is a criminal offense.'],
  ['die', 'Datenflut', null, 'flood of data', 'Technology', 'Die tägliche Datenflut überfordert viele Teams.', 'The daily flood of data overwhelms many teams.'],
  ['die', 'Informationsflut', null, 'information overload', 'Technology', 'Die Informationsflut erschwert den Überblick.', 'The flood of information makes it hard to keep an overview.'],
  ['die', 'Benutzeroberfläche', 'Benutzeroberflächen', 'user interface', 'Technology', 'Die Benutzeroberfläche der App wurde neu gestaltet.', 'The user interface of the app was redesigned.'],
  ['der', 'Quellcode', 'Quellcodes', 'source code', 'Technology', 'Der Quellcode des Programms ist öffentlich einsehbar.', 'The source code of the program is publicly viewable.'],
]
