import type { SeedRow } from './types'

/**
 * C1 seed corpus (M12.3 batch, 2026-09-29): advanced health, work/bureaucracy
 * and household vocabulary — the first C-level entries in the vocab bank.
 */
export const C1_ROWS: SeedRow[] = [
  ['die', 'Vorerkrankung', 'Vorerkrankungen', 'pre-existing condition', 'Health', 'Die Vorerkrankung muss angegeben werden.', 'The pre-existing condition has to be declared.'],
  ['die', 'Dosierung', 'Dosierungen', 'dosage', 'Health', 'Die Dosierung steht auf dem Beipackzettel.', 'The dosage is on the package insert.'],
  ['die', 'Lebenserwartung', 'Lebenserwartungen', 'life expectancy', 'Health', 'Die Lebenserwartung steigt weiter.', 'Life expectancy keeps rising.'],
  ['das', 'Immunsystem', 'Immunsysteme', 'immune system', 'Health', 'Das Immunsystem kämpft gegen das Virus.', 'The immune system fights the virus.'],
  ['die', 'Prävention', 'Präventionen', 'prevention', 'Health', 'Die Prävention beginnt mit gesunder Ernährung.', 'Prevention starts with a healthy diet.'],
  ['die', 'Organspende', 'Organspenden', 'organ donation', 'Health', 'Die Organspende rettet Leben.', 'Organ donation saves lives.'],
  ['die', 'Blutspende', 'Blutspenden', 'blood donation', 'Health', 'Die Blutspende dauert nur zehn Minuten.', 'The blood donation takes only ten minutes.'],
  ['die', 'Intensivstation', 'Intensivstationen', 'intensive care unit', 'Health', 'Die Intensivstation ist ausgelastet.', 'The intensive care unit is at capacity.'],
  ['die', 'Überdosierung', 'Überdosierungen', 'overdose', 'Health', 'Die Überdosierung war ein Versehen.', 'The overdose was an accident.'],
  ['der', 'Erreger', 'Erreger', 'pathogen', 'Health', 'Der Erreger wird im Labor bestimmt.', 'The pathogen is identified in the lab.'],
  ['die', 'Beschwerde', 'Beschwerden', 'ailment; complaint', 'Health', 'Die Beschwerden des Patienten nehmen zu.', "The patient's ailments are increasing."],
  ['die', 'Atemnot', null, 'shortness of breath', 'Health', 'Die Atemnot trat plötzlich auf.', 'The shortness of breath occurred suddenly.'],
  ['die', 'Vene', 'Venen', 'vein', 'Health', 'Die Vene ist gut sichtbar.', 'The vein is clearly visible.'],
  ['die', 'Arterie', 'Arterien', 'artery', 'Health', 'Die Arterie ist verengt.', 'The artery is narrowed.'],
  ['das', 'Desinfektionsmittel', 'Desinfektionsmittel', 'disinfectant', 'Health', 'Das Desinfektionsmittel steht an der Tür.', 'The disinfectant is by the door.'],
  ['der', 'Impfstoff', 'Impfstoffe', 'vaccine', 'Health', 'Der Impfstoff muss gekühlt werden.', 'The vaccine has to be refrigerated.'],
  ['der', 'Antikörper', 'Antikörper', 'antibody', 'Health', 'Der Antikörper schützt vor einer Neuinfektion.', 'The antibody protects against reinfection.'],
  ['der', 'Sauerstoff', null, 'oxygen', 'Health', 'Der Sauerstoff im Blut wird gemessen.', 'The oxygen in the blood is measured.'],
  ['das', 'Pflegeheim', 'Pflegeheime', 'nursing home', 'Health', 'Das Pflegeheim liegt am Park.', 'The nursing home is by the park.'],
  ['die', 'Wiederbelebung', 'Wiederbelebungen', 'resuscitation', 'Health', 'Die Wiederbelebung dauerte zwanzig Minuten.', 'The resuscitation lasted twenty minutes.'],
  ['das', 'EKG', 'EKGs', 'EKG, electrocardiogram', 'Health', 'Das EKG zeigt einen ruhigen Rhythmus.', 'The EKG shows a steady rhythm.'],
  ['das', 'Beruhigungsmittel', 'Beruhigungsmittel', 'sedative', 'Health', 'Das Beruhigungsmittel wirkt nach zehn Minuten.', 'The sedative takes effect after ten minutes.'],
  ['die', 'Krücke', 'Krücken', 'crutch', 'Health', 'Die Krücke ist nach dem Unfall nötig.', 'The crutch is necessary after the accident.'],
  ['der', 'Juckreiz', null, 'itching', 'Health', 'Der Juckreiz hält den ganzen Tag an.', 'The itching lasts all day.'],
  ['der', 'Beipackzettel', 'Beipackzettel', 'package insert', 'Health', 'Der Beipackzettel listet die Nebenwirkungen auf.', 'The package insert lists the side effects.'],
  ['der', 'Hausbesuch', 'Hausbesuche', "(doctor's) house call", 'Health', 'Der Hausbesuch kostet extra.', 'The house call costs extra.'],
  ['die', 'Visite', 'Visiten', '(hospital) rounds', 'Health', 'Die Visite beginnt um acht Uhr.', 'The rounds begin at eight.'],
  ['der', 'Blinddarm', 'Blinddärme', 'appendix', 'Health', 'Der Blinddarm wird morgen entfernt.', 'The appendix is being removed tomorrow.'],
  ['das', 'Anschreiben', 'Anschreiben', 'cover letter', 'Work', 'Das Anschreiben überzeugt die Personalerin.', 'The cover letter convinces the recruiter.'],
  ['das', 'Arbeitszeugnis', 'Arbeitszeugnisse', 'employment reference', 'Work', 'Das Arbeitszeugnis ist qualifiziert ausgestellt.', 'The employment reference is fully detailed.'],
  ['das', 'Bewerbungsschreiben', 'Bewerbungsschreiben', 'letter of application', 'Work', 'Das Bewerbungsschreiben ist kurz und präzise.', 'The letter of application is short and precise.'],
  ['die', 'Bewerbungsunterlagen', null, 'application documents', 'Work', 'Die Bewerbungsunterlagen sind vollständig.', 'The application documents are complete.'],
  ['die', 'Gehaltsabrechnung', 'Gehaltsabrechnungen', 'payslip', 'Work', 'Die Gehaltsabrechnung kommt monatlich per Post.', 'The payslip comes monthly by mail.'],
  ['die', 'Gehaltsverhandlung', 'Gehaltsverhandlungen', 'salary negotiation', 'Work', 'Die Gehaltsverhandlung verlief erfolgreich.', 'The salary negotiation went well.'],
  ['die', 'Sozialversicherung', 'Sozialversicherungen', 'social insurance', 'Work', 'Die Sozialversicherung umfasst fünf Zweige.', 'Social insurance comprises five branches.'],
  ['die', 'Rentenversicherung', 'Rentenversicherungen', 'pension insurance', 'Work', 'Die Rentenversicherung sichert das Alter.', 'The pension insurance secures old age.'],
  ['die', 'Krankenversicherung', 'Krankenversicherungen', 'health insurance', 'Work', 'Die Krankenversicherung zahlt die Behandlung.', 'The health insurance pays for the treatment.'],
  ['die', 'Arbeitslosenversicherung', 'Arbeitslosenversicherungen', 'unemployment insurance', 'Work', 'Die Arbeitslosenversicherung greift nach einem Jahr.', 'Unemployment insurance kicks in after a year.'],
  ['der', 'Steuerberater', 'Steuerberater', 'tax advisor', 'Work', 'Der Steuerberater findet weitere Abzüge.', 'The tax advisor finds more deductions.'],
  ['die', 'Einarbeitung', 'Einarbeitungen', 'onboarding, induction', 'Work', 'Die Einarbeitung dauert vier Wochen.', 'The onboarding lasts four weeks.'],
  [null, 'sich einarbeiten', null, 'to get up to speed', 'Work', 'Er arbeitet sich schnell ein.', 'He is getting up to speed quickly.'],
  ['die', 'Laufbahn', 'Laufbahnen', 'career path', 'Work', 'Die Laufbahn begann mit einer Lehre.', 'The career path began with an apprenticeship.'],
  ['der', 'Nachfolger', 'Nachfolger', 'successor', 'Work', 'Der Nachfolger tritt im Mai an.', 'The successor takes over in May.'],
  ['der', 'Vorgänger', 'Vorgänger', 'predecessor', 'Work', 'Der Vorgänger hinterließ ein gut organisiertes Büro.', 'The predecessor left a well-organized office.'],
  ['die', 'Stellenausschreibung', 'Stellenausschreibungen', 'job posting', 'Work', 'Die Stellenausschreibung richtet sich an Quereinsteiger.', 'The job posting is aimed at career changers.'],
  ['der', 'Stellenabbau', null, 'job cuts', 'Work', 'Der Stellenabbau betrifft zwei Abteilungen.', 'The job cuts affect two departments.'],
  ['die', 'Kündigungsfrist', 'Kündigungsfristen', 'notice period', 'Work', 'Die Kündigungsfrist beträgt drei Monate.', 'The notice period is three months.'],
  [null, 'befördern', null, 'to promote', 'Work', 'Die Firma befördert ihn zum Teamleiter.', 'The company is promoting him to team leader.'],
  ['der', 'Quereinsteiger', 'Quereinsteiger', 'career changer', 'Work', 'Der Quereinsteiger bringt frische Ideen mit.', 'The career changer brings fresh ideas.'],
  ['der', 'Wiedereinstieg', 'Wiedereinstiege', 'return to work', 'Work', 'Der Wiedereinstieg nach der Elternzeit gelingt.', 'The return to work after parental leave succeeds.'],
  ['der', 'Personaler', 'Personaler', 'HR manager', 'Work', 'Der Personaler sichtet die Bewerbungen.', 'The HR manager is screening the applications.'],
  ['der', 'Inhaber', 'Inhaber', 'owner, holder', 'Work', 'Der Inhaber führt den Betrieb in dritter Generation.', 'The owner runs the business in the third generation.'],
  ['die', 'Elternzeit', null, 'parental leave', 'Work', 'Die Elternzeit endet im September.', 'The parental leave ends in September.'],
  ['die', 'Überlastung', 'Überlastungen', 'overload, burnout risk', 'Work', 'Die Überlastung führt zu Fehlern.', 'The overload leads to mistakes.'],
  ['das', 'Gewerbe', 'Gewerbe', 'trade, business', 'Work', 'Das Gewerbe muss angemeldet werden.', 'The business has to be registered.'],
  ['die', 'Herstellung', 'Herstellungen', 'production, manufacture', 'Work', 'Die Herstellung erfolgt in Deutschland.', 'The manufacture takes place in Germany.'],
  ['die', 'Verarbeitung', 'Verarbeitungen', 'processing', 'Work', 'Die Verarbeitung der Daten dauert Stunden.', 'The processing of the data takes hours.'],
  ['die', 'Logistik', null, 'logistics', 'Work', 'Die Logistik der Firma ist ausgefeilt.', 'The logistics of the company is sophisticated.'],
  ['die', 'Spedition', 'Speditionen', 'freight company', 'Work', 'Die Spedition liefert Möbel in ganz Europa.', 'The freight company delivers furniture across Europe.'],
  ['die', 'Fracht', 'Frachten', 'freight, cargo', 'Work', 'Die Fracht wiegt über zwanzig Tonnen.', 'The cargo weighs over twenty tons.'],
  ['die', 'Beanstandung', 'Beanstandungen', 'complaint (about defects)', 'Work', 'Die Beanstandung wurde schriftlich eingereicht.', 'The complaint was submitted in writing.'],
  [null, 'unterzeichnen', null, 'to sign (formally)', 'Work', 'Beide Parteien unterzeichnen den Vertrag.', 'Both parties are signing the contract.'],
  ['das', 'Nettogehalt', 'Nettogehälter', 'net salary', 'Work', 'Das Nettogehalt landet auf dem Konto.', 'The net salary lands in the account.'],
  ['das', 'Bruttogehalt', 'Bruttogehälter', 'gross salary', 'Work', 'Das Bruttogehalt steht im Arbeitsvertrag.', 'The gross salary is in the employment contract.'],
  ['der', 'Abzug', 'Abzüge', 'deduction', 'Work', 'Der Abzug für Steuern wächst mit dem Lohn.', 'The deduction for taxes grows with the pay.'],
  ['die', 'Sozialabgaben', null, 'social security contributions', 'Work', 'Die Sozialabgaben trägt Arbeit und Arbeitnehmer je zur Hälfte.', 'The social security contributions are shared equally by employer and employee.'],
  ['der', 'Steuerbescheid', 'Steuerbescheide', 'tax assessment notice', 'Work', 'Der Steuerbescheid kommt im Juni.', 'The tax assessment notice comes in June.'],
  ['die', 'Steuererstattung', 'Steuererstattungen', 'tax refund', 'Work', 'Die Steuererstattung fiel dieses Jahr hoch aus.', 'The tax refund turned out high this year.'],
  [null, 'erstatten', null, 'to reimburse', 'Work', 'Die Firma erstattet die Fahrtkosten.', 'The company reimburses the travel costs.'],
  ['der', 'Zinssatz', 'Zinssätze', 'interest rate', 'Work', 'Der Zinssatz bleibt dieses Jahr stabil.', 'The interest rate stays stable this year.'],
  ['die', 'Ratenzahlung', 'Ratenzahlungen', 'payment in installments', 'Work', 'Die Ratenzahlung verteilt den Preis auf zwölf Monate.', 'Payment in installments spreads the price over twelve months.'],
  [null, 'tilgen', null, 'to pay off, to amortize', 'Work', 'Das Darlehen wird in zehn Jahren getilgt.', 'The loan is paid off in ten years.'],
  [null, 'bargeldlos', null, 'cashless', 'Work', 'Bargeldlos zahlen ist hier üblich.', 'Paying cashlessly is common here.'],
  ['die', 'Zahlungsfrist', 'Zahlungsfristen', 'payment deadline', 'Work', 'Die Zahlungsfrist läuft Ende des Monats ab.', 'The payment deadline expires at the end of the month.'],
  ['die', 'Mahnung', 'Mahnungen', 'payment reminder', 'Work', 'Die Mahnung liegt heute im Briefkasten.', 'The payment reminder is in the mailbox today.'],
  [null, 'mahnen', null, 'to send a reminder', 'Work', 'Das Unternehmen mahnt nach vierzehn Tagen.', 'The company sends a reminder after fourteen days.'],
  ['die', 'Vorkasse', null, 'payment in advance', 'Work', 'Vorkasse ist bei diesem Shop Pflicht.', 'Payment in advance is mandatory at this shop.'],
  ['die', 'Betriebsausgabe', 'Betriebsausgaben', 'business expense', 'Work', 'Die Betriebsausgabe ist voll absetzbar.', 'The business expense is fully deductible.'],
  ['der', 'Freiberufler', 'Freiberufler', 'freelance professional', 'Work', 'Der Freiberufler schreibt Rechnungen ohne Umsatzsteuer.', 'The freelance professional writes invoices without VAT.'],
  ['die', 'Nebentätigkeit', 'Nebentätigkeiten', 'side job, secondary employment', 'Work', 'Die Nebentätigkeit ist beim Arbeitgeber gemeldet.', 'The side job is registered with the employer.'],
  ['die', 'Niederlassung', 'Niederlassungen', 'branch office', 'Work', 'Die Niederlassung in Wien öffnet im Herbst.', 'The branch office in Vienna opens in fall.'],
  ['der', 'Familienbetrieb', 'Familienbetriebe', 'family business', 'Work', 'Der Familienbetrieb besteht seit hundert Jahren.', 'The family business has existed for a hundred years.'],
  ['die', 'Ausschreibung', 'Ausschreibungen', 'tender, call for bids', 'Work', 'Die Ausschreibung richtet sich an kleine Firmen.', 'The tender is aimed at small companies.'],
  ['der', 'Kostenvoranschlag', 'Kostenvoranschläge', 'cost estimate', 'Work', 'Der Kostenvoranschlag liegt bei zweitausend Euro.', 'The cost estimate is two thousand euros.'],
  ['das', 'Aktenzeichen', 'Aktenzeichen', 'file number, reference number', 'Work', 'Das Aktenzeichen steht oben auf dem Brief.', 'The file number is at the top of the letter.'],
  ['die', 'Wartung', 'Wartungen', 'maintenance, servicing', 'Work', 'Die Wartung der Anlage erfolgt jährlich.', 'The maintenance of the system takes place annually.'],
  ['der', 'Fachbetrieb', 'Fachbetriebe', 'specialist company', 'Work', 'Der Fachbetrieb repariert die Heizung.', 'The specialist company repairs the heating.'],
  ['die', 'Montage', 'Montagen', 'assembly, installation', 'Work', 'Die Montage der Küche dauert zwei Tage.', 'The installation of the kitchen takes two days.'],
  ['der', 'Abstellraum', 'Abstellräume', 'storage room', 'Home', 'Der Abstellraum ist im Erdgeschoss.', 'The storage room is on the ground floor.'],
  [null, 'entkalken', null, 'to descale', 'Home', 'Die Maschine muss regelmäßig entkalkt werden.', 'The machine has to be descaled regularly.'],
  [null, 'bestreuen', null, 'to sprinkle', 'Food', 'Er bestreut den Kuchen mit Puderzucker.', 'He is sprinkling powdered sugar on the cake.'],
  [null, 'abschmecken', null, 'to adjust the seasoning', 'Food', 'Die Suppe muss noch abgeschmeckt werden.', 'The soup still needs its seasoning adjusted.'],
  [null, 'fade', null, 'bland, insipid', 'Food', 'Der Reis schmeckt fade.', 'The rice tastes bland.'],
  ['der', 'Bissen', 'Bissen', 'mouthful, bite', 'Food', 'Der erste Bissen war heiß.', 'The first bite was hot.'],
  ['die', 'Beschäftigung', 'Beschäftigungen', 'occupation, employment', 'Work', 'Die Beschäftigung mit dem Thema dauert Wochen.', 'Working on the topic takes weeks.'],
  ['die', 'Abrechnung', 'Abrechnungen', 'settlement, statement', 'Work', 'Die Abrechnung erfolgt am Monatsende.', 'The settlement takes place at the end of the month.'],
]
