import type { SeedRow } from './types'

/**
 * C1 seed corpus (232 rows): M12.3 batch (96, 2026-09-29) advanced health,
 * work/bureaucracy and household vocabulary + M12.4 batch (64) legal and
 * administrative register + M12.5 batch (72) emotions/character depth,
 * media critique and AI/technology register — the first C-level entries
 * in the vocab bank.
 */
export const C1_ROWS: SeedRow[] = [
  ['die', 'Vorerkrankung', 'Vorerkrankungen', 'pre-existing condition', 'Health', 'Die Vorerkrankung muss angegeben werden.', 'The pre-existing condition has to be declared.'],
  ['die', 'Dosierung', 'Dosierungen', 'dosage', 'Health', 'Die Dosierung steht auf dem Beipackzettel.', 'The dosage is on the package insert.'],
  ['die', 'Lebenserwartung', 'Lebenserwartungen', 'life expectancy', 'Health', 'Die Lebenserwartung steigt weiter.', 'Life expectancy keeps rising.'],
  ['das', 'Immunsystem', 'Immunsysteme', 'immune system', 'Health', 'Das Immunsystem kämpft gegen das Virus.', 'The immune system fights the virus.'],
  ['die', 'Prävention', 'Präventionen', 'prevention', 'Health', 'Die Prävention beginnt mit gesunder Ernährung.', 'Prevention starts with a healthy diet.'],
  ['die', 'Organspende', 'Organspenden', 'organ donation', 'Health', 'Die Organspende rettet Leben.', 'Organ donation saves lives.'],
  ['die', 'Blutspende', 'Blutspenden', 'blood donation', 'Health', 'Die Blutspende dauert nur zehn Minuten.', 'The blood donation takes only ten minutes.'],
  ['die', 'Intensivstation', 'Intensivstationen', 'intensive care unit', 'Health', 'Die Intensivstation ist ausgelastet.', 'The intensive care unit is at capacity.'],
  ['die', 'Überdosierung', 'Überdosierungen', 'overdose', 'Health', 'Die Überdosierung war ein Versehen.', 'The overdose was an accident.'],
  ['der', 'Erreger', 'Erreger', 'pathogen', 'Health', 'Der Erreger wird im Labor bestimmt.', 'The pathogen is identified in the lab.'],
  ['die', 'Beschwerde', 'Beschwerden', 'ailment; complaint', 'Health', 'Die Beschwerden des Patienten nehmen zu.', "The patient's ailments are increasing."],
  ['die', 'Atemnot', null, 'shortness of breath', 'Health', 'Die Atemnot trat plötzlich auf.', 'The shortness of breath occurred suddenly.'],
  ['die', 'Vene', 'Venen', 'vein', 'Health', 'Die Vene ist gut sichtbar.', 'The vein is clearly visible.'],
  ['die', 'Arterie', 'Arterien', 'artery', 'Health', 'Die Arterie ist verengt.', 'The artery is narrowed.'],
  ['das', 'Desinfektionsmittel', 'Desinfektionsmittel', 'disinfectant', 'Health', 'Das Desinfektionsmittel steht an der Tür.', 'The disinfectant is by the door.'],
  ['der', 'Impfstoff', 'Impfstoffe', 'vaccine', 'Health', 'Der Impfstoff muss gekühlt werden.', 'The vaccine has to be refrigerated.'],
  ['der', 'Antikörper', 'Antikörper', 'antibody', 'Health', 'Der Antikörper schützt vor einer Neuinfektion.', 'The antibody protects against reinfection.'],
  ['der', 'Sauerstoff', null, 'oxygen', 'Health', 'Der Sauerstoff im Blut wird gemessen.', 'The oxygen in the blood is measured.'],
  ['das', 'Pflegeheim', 'Pflegeheime', 'nursing home', 'Health', 'Das Pflegeheim liegt am Park.', 'The nursing home is by the park.'],
  ['die', 'Wiederbelebung', 'Wiederbelebungen', 'resuscitation', 'Health', 'Die Wiederbelebung dauerte zwanzig Minuten.', 'The resuscitation lasted twenty minutes.'],
  ['das', 'EKG', 'EKGs', 'EKG, electrocardiogram', 'Health', 'Das EKG zeigt einen ruhigen Rhythmus.', 'The EKG shows a steady rhythm.'],
  ['das', 'Beruhigungsmittel', 'Beruhigungsmittel', 'sedative', 'Health', 'Das Beruhigungsmittel wirkt nach zehn Minuten.', 'The sedative takes effect after ten minutes.'],
  ['die', 'Krücke', 'Krücken', 'crutch', 'Health', 'Die Krücke ist nach dem Unfall nötig.', 'The crutch is necessary after the accident.'],
  ['der', 'Juckreiz', null, 'itching', 'Health', 'Der Juckreiz hält den ganzen Tag an.', 'The itching lasts all day.'],
  ['der', 'Beipackzettel', 'Beipackzettel', 'package insert', 'Health', 'Der Beipackzettel listet die Nebenwirkungen auf.', 'The package insert lists the side effects.'],
  ['der', 'Hausbesuch', 'Hausbesuche', "(doctor's) house call", 'Health', 'Der Hausbesuch kostet extra.', 'The house call costs extra.'],
  ['die', 'Visite', 'Visiten', '(hospital) rounds', 'Health', 'Die Visite beginnt um acht Uhr.', 'The rounds begin at eight.'],
  ['der', 'Blinddarm', 'Blinddärme', 'appendix', 'Health', 'Der Blinddarm wird morgen entfernt.', 'The appendix is being removed tomorrow.'],
  ['das', 'Anschreiben', 'Anschreiben', 'cover letter', 'Work', 'Das Anschreiben überzeugt die Personalerin.', 'The cover letter convinces the recruiter.'],
  ['das', 'Arbeitszeugnis', 'Arbeitszeugnisse', 'employment reference', 'Work', 'Das Arbeitszeugnis ist qualifiziert ausgestellt.', 'The employment reference is fully detailed.'],
  ['das', 'Bewerbungsschreiben', 'Bewerbungsschreiben', 'letter of application', 'Work', 'Das Bewerbungsschreiben ist kurz und präzise.', 'The letter of application is short and precise.'],
  ['die', 'Bewerbungsunterlagen', null, 'application documents', 'Work', 'Die Bewerbungsunterlagen sind vollständig.', 'The application documents are complete.'],
  ['die', 'Gehaltsabrechnung', 'Gehaltsabrechnungen', 'payslip', 'Work', 'Die Gehaltsabrechnung kommt monatlich per Post.', 'The payslip comes monthly by mail.'],
  ['die', 'Gehaltsverhandlung', 'Gehaltsverhandlungen', 'salary negotiation', 'Work', 'Die Gehaltsverhandlung verlief erfolgreich.', 'The salary negotiation went well.'],
  ['die', 'Sozialversicherung', 'Sozialversicherungen', 'social insurance', 'Work', 'Die Sozialversicherung umfasst fünf Zweige.', 'Social insurance comprises five branches.'],
  ['die', 'Rentenversicherung', 'Rentenversicherungen', 'pension insurance', 'Work', 'Die Rentenversicherung sichert das Alter.', 'The pension insurance secures old age.'],
  ['die', 'Krankenversicherung', 'Krankenversicherungen', 'health insurance', 'Work', 'Die Krankenversicherung zahlt die Behandlung.', 'The health insurance pays for the treatment.'],
  ['die', 'Arbeitslosenversicherung', 'Arbeitslosenversicherungen', 'unemployment insurance', 'Work', 'Die Arbeitslosenversicherung greift nach einem Jahr.', 'Unemployment insurance kicks in after a year.'],
  ['der', 'Steuerberater', 'Steuerberater', 'tax advisor', 'Work', 'Der Steuerberater findet weitere Abzüge.', 'The tax advisor finds more deductions.'],
  ['die', 'Einarbeitung', 'Einarbeitungen', 'onboarding, induction', 'Work', 'Die Einarbeitung dauert vier Wochen.', 'The onboarding lasts four weeks.'],
  [null, 'sich einarbeiten', null, 'to get up to speed', 'Work', 'Er arbeitet sich schnell ein.', 'He is getting up to speed quickly.'],
  ['die', 'Laufbahn', 'Laufbahnen', 'career path', 'Work', 'Die Laufbahn begann mit einer Lehre.', 'The career path began with an apprenticeship.'],
  ['der', 'Nachfolger', 'Nachfolger', 'successor', 'Work', 'Der Nachfolger tritt im Mai an.', 'The successor takes over in May.'],
  ['der', 'Vorgänger', 'Vorgänger', 'predecessor', 'Work', 'Der Vorgänger hinterließ ein gut organisiertes Büro.', 'The predecessor left a well-organized office.'],
  ['die', 'Stellenausschreibung', 'Stellenausschreibungen', 'job posting', 'Work', 'Die Stellenausschreibung richtet sich an Quereinsteiger.', 'The job posting is aimed at career changers.'],
  ['der', 'Stellenabbau', null, 'job cuts', 'Work', 'Der Stellenabbau betrifft zwei Abteilungen.', 'The job cuts affect two departments.'],
  ['die', 'Kündigungsfrist', 'Kündigungsfristen', 'notice period', 'Work', 'Die Kündigungsfrist beträgt drei Monate.', 'The notice period is three months.'],
  [null, 'befördern', null, 'to promote', 'Work', 'Die Firma befördert ihn zum Teamleiter.', 'The company is promoting him to team leader.'],
  ['der', 'Quereinsteiger', 'Quereinsteiger', 'career changer', 'Work', 'Der Quereinsteiger bringt frische Ideen mit.', 'The career changer brings fresh ideas.'],
  ['der', 'Wiedereinstieg', 'Wiedereinstiege', 'return to work', 'Work', 'Der Wiedereinstieg nach der Elternzeit gelingt.', 'The return to work after parental leave succeeds.'],
  ['der', 'Personaler', 'Personaler', 'HR manager', 'Work', 'Der Personaler sichtet die Bewerbungen.', 'The HR manager is screening the applications.'],
  ['der', 'Inhaber', 'Inhaber', 'owner, holder', 'Work', 'Der Inhaber führt den Betrieb in dritter Generation.', 'The owner runs the business in the third generation.'],
  ['die', 'Elternzeit', null, 'parental leave', 'Work', 'Die Elternzeit endet im September.', 'The parental leave ends in September.'],
  ['die', 'Überlastung', 'Überlastungen', 'overload, burnout risk', 'Work', 'Die Überlastung führt zu Fehlern.', 'The overload leads to mistakes.'],
  ['das', 'Gewerbe', 'Gewerbe', 'trade, business', 'Work', 'Das Gewerbe muss angemeldet werden.', 'The business has to be registered.'],
  ['die', 'Herstellung', 'Herstellungen', 'production, manufacture', 'Work', 'Die Herstellung erfolgt in Deutschland.', 'The manufacture takes place in Germany.'],
  ['die', 'Verarbeitung', 'Verarbeitungen', 'processing', 'Work', 'Die Verarbeitung der Daten dauert Stunden.', 'The processing of the data takes hours.'],
  ['die', 'Logistik', null, 'logistics', 'Work', 'Die Logistik der Firma ist ausgefeilt.', 'The logistics of the company is sophisticated.'],
  ['die', 'Spedition', 'Speditionen', 'freight company', 'Work', 'Die Spedition liefert Möbel in ganz Europa.', 'The freight company delivers furniture across Europe.'],
  ['die', 'Fracht', 'Frachten', 'freight, cargo', 'Work', 'Die Fracht wiegt über zwanzig Tonnen.', 'The cargo weighs over twenty tons.'],
  ['die', 'Beanstandung', 'Beanstandungen', 'complaint (about defects)', 'Work', 'Die Beanstandung wurde schriftlich eingereicht.', 'The complaint was submitted in writing.'],
  [null, 'unterzeichnen', null, 'to sign (formally)', 'Work', 'Beide Parteien unterzeichnen den Vertrag.', 'Both parties are signing the contract.'],
  ['das', 'Nettogehalt', 'Nettogehälter', 'net salary', 'Work', 'Das Nettogehalt landet auf dem Konto.', 'The net salary lands in the account.'],
  ['das', 'Bruttogehalt', 'Bruttogehälter', 'gross salary', 'Work', 'Das Bruttogehalt steht im Arbeitsvertrag.', 'The gross salary is in the employment contract.'],
  ['der', 'Abzug', 'Abzüge', 'deduction', 'Work', 'Der Abzug für Steuern wächst mit dem Lohn.', 'The deduction for taxes grows with the pay.'],
  ['die', 'Sozialabgaben', null, 'social security contributions', 'Work', 'Die Sozialabgaben trägt Arbeit und Arbeitnehmer je zur Hälfte.', 'The social security contributions are shared equally by employer and employee.'],
  ['der', 'Steuerbescheid', 'Steuerbescheide', 'tax assessment notice', 'Work', 'Der Steuerbescheid kommt im Juni.', 'The tax assessment notice comes in June.'],
  ['die', 'Steuererstattung', 'Steuererstattungen', 'tax refund', 'Work', 'Die Steuererstattung fiel dieses Jahr hoch aus.', 'The tax refund turned out high this year.'],
  [null, 'erstatten', null, 'to reimburse', 'Work', 'Die Firma erstattet die Fahrtkosten.', 'The company reimburses the travel costs.'],
  ['der', 'Zinssatz', 'Zinssätze', 'interest rate', 'Work', 'Der Zinssatz bleibt dieses Jahr stabil.', 'The interest rate stays stable this year.'],
  ['die', 'Ratenzahlung', 'Ratenzahlungen', 'payment in installments', 'Work', 'Die Ratenzahlung verteilt den Preis auf zwölf Monate.', 'Payment in installments spreads the price over twelve months.'],
  [null, 'tilgen', null, 'to pay off, to amortize', 'Work', 'Das Darlehen wird in zehn Jahren getilgt.', 'The loan is paid off in ten years.'],
  [null, 'bargeldlos', null, 'cashless', 'Work', 'Bargeldlos zahlen ist hier üblich.', 'Paying cashlessly is common here.'],
  ['die', 'Zahlungsfrist', 'Zahlungsfristen', 'payment deadline', 'Work', 'Die Zahlungsfrist läuft Ende des Monats ab.', 'The payment deadline expires at the end of the month.'],
  ['die', 'Mahnung', 'Mahnungen', 'payment reminder', 'Work', 'Die Mahnung liegt heute im Briefkasten.', 'The payment reminder is in the mailbox today.'],
  [null, 'mahnen', null, 'to send a reminder', 'Work', 'Das Unternehmen mahnt nach vierzehn Tagen.', 'The company sends a reminder after fourteen days.'],
  ['die', 'Vorkasse', null, 'payment in advance', 'Work', 'Vorkasse ist bei diesem Shop Pflicht.', 'Payment in advance is mandatory at this shop.'],
  ['die', 'Betriebsausgabe', 'Betriebsausgaben', 'business expense', 'Work', 'Die Betriebsausgabe ist voll absetzbar.', 'The business expense is fully deductible.'],
  ['der', 'Freiberufler', 'Freiberufler', 'freelance professional', 'Work', 'Der Freiberufler schreibt Rechnungen ohne Umsatzsteuer.', 'The freelance professional writes invoices without VAT.'],
  ['die', 'Nebentätigkeit', 'Nebentätigkeiten', 'side job, secondary employment', 'Work', 'Die Nebentätigkeit ist beim Arbeitgeber gemeldet.', 'The side job is registered with the employer.'],
  ['die', 'Niederlassung', 'Niederlassungen', 'branch office', 'Work', 'Die Niederlassung in Wien öffnet im Herbst.', 'The branch office in Vienna opens in fall.'],
  ['der', 'Familienbetrieb', 'Familienbetriebe', 'family business', 'Work', 'Der Familienbetrieb besteht seit hundert Jahren.', 'The family business has existed for a hundred years.'],
  ['die', 'Ausschreibung', 'Ausschreibungen', 'tender, call for bids', 'Work', 'Die Ausschreibung richtet sich an kleine Firmen.', 'The tender is aimed at small companies.'],
  ['der', 'Kostenvoranschlag', 'Kostenvoranschläge', 'cost estimate', 'Work', 'Der Kostenvoranschlag liegt bei zweitausend Euro.', 'The cost estimate is two thousand euros.'],
  ['das', 'Aktenzeichen', 'Aktenzeichen', 'file number, reference number', 'Work', 'Das Aktenzeichen steht oben auf dem Brief.', 'The file number is at the top of the letter.'],
  ['die', 'Wartung', 'Wartungen', 'maintenance, servicing', 'Work', 'Die Wartung der Anlage erfolgt jährlich.', 'The maintenance of the system takes place annually.'],
  ['der', 'Fachbetrieb', 'Fachbetriebe', 'specialist company', 'Work', 'Der Fachbetrieb repariert die Heizung.', 'The specialist company repairs the heating.'],
  ['die', 'Montage', 'Montagen', 'assembly, installation', 'Work', 'Die Montage der Küche dauert zwei Tage.', 'The installation of the kitchen takes two days.'],
  ['der', 'Abstellraum', 'Abstellräume', 'storage room', 'Home', 'Der Abstellraum ist im Erdgeschoss.', 'The storage room is on the ground floor.'],
  [null, 'entkalken', null, 'to descale', 'Home', 'Die Maschine muss regelmäßig entkalkt werden.', 'The machine has to be descaled regularly.'],
  [null, 'bestreuen', null, 'to sprinkle', 'Food', 'Er bestreut den Kuchen mit Puderzucker.', 'He is sprinkling powdered sugar on the cake.'],
  [null, 'abschmecken', null, 'to adjust the seasoning', 'Food', 'Die Suppe muss noch abgeschmeckt werden.', 'The soup still needs its seasoning adjusted.'],
  [null, 'fade', null, 'bland, insipid', 'Food', 'Der Reis schmeckt fade.', 'The rice tastes bland.'],
  ['der', 'Bissen', 'Bissen', 'mouthful, bite', 'Food', 'Der erste Bissen war heiß.', 'The first bite was hot.'],
  ['die', 'Beschäftigung', 'Beschäftigungen', 'occupation, employment', 'Work', 'Die Beschäftigung mit dem Thema dauert Wochen.', 'Working on the topic takes weeks.'],
  ['die', 'Abrechnung', 'Abrechnungen', 'settlement, statement', 'Work', 'Die Abrechnung erfolgt am Monatsende.', 'The settlement takes place at the end of the month.'],
  // ── M12.4: Reisen/Verkehr + Behörden/Ämter — legal/administrative register ──
  ['das', 'Amtsgericht', 'Amtsgerichte', 'local (first-instance) court', 'Law', 'Der Prozess beginnt am Amtsgericht.', 'The trial begins at the local court.'],
  ['das', 'Landgericht', 'Landgerichte', 'regional court', 'Law', 'Das Landgericht verhandelt größere Strafsachen.', 'The regional court hears major criminal cases.'],
  ['das', 'Oberlandesgericht', 'Oberlandesgerichte', 'higher regional court', 'Law', 'Das Urteil wurde vom Oberlandesgericht bestätigt.', 'The verdict was confirmed by the higher regional court.'],
  ['der', 'Bundesgerichtshof', null, 'Federal Court of Justice', 'Law', 'Der Bundesgerichtshof entscheidet als letzte Instanz in Zivilsachen.', 'The Federal Court of Justice decides as the last instance in civil matters.'],
  ['das', 'Bundesverfassungsgericht', null, 'Federal Constitutional Court', 'Law', 'Das Bundesverfassungsgericht prüft Gesetze auf ihre Verfassungsmäßigkeit.', 'The Constitutional Court reviews laws for constitutionality.'],
  ['das', 'Schwurgericht', 'Schwurgerichte', 'jury court', 'Law', 'Mord verhandelt das Schwurgericht.', 'Murder is heard by the jury court.'],
  ['das', 'Verwaltungsgericht', 'Verwaltungsgerichte', 'administrative court', 'Law', 'Das Verwaltungsgericht prüft behördliche Entscheidungen.', 'The administrative court reviews administrative decisions.'],
  ['der', 'Gerichtssaal', 'Gerichtssäle', 'courtroom', 'Law', 'Der Gerichtssaal ist bis auf den letzten Platz gefüllt.', 'The courtroom is filled to the last seat.'],
  ['der', 'Staatsanwalt', 'Staatsanwälte', 'public prosecutor', 'Law', 'Der Staatsanwalt erhebt Anklage.', 'The prosecutor brings charges.'],
  ['die', 'Staatsanwaltschaft', 'Staatsanwaltschaften', "public prosecutor's office", 'Law', 'Die Staatsanwaltschaft leitet das Ermittlungsverfahren.', "The prosecutor's office directs the investigation."],
  ['der', 'Rechtsanwalt', 'Rechtsanwälte', 'attorney, lawyer', 'Law', 'Der Rechtsanwalt rät zu einem Vergleich.', 'The attorney advises a settlement.'],
  ['der', 'Verteidiger', 'Verteidiger', 'defence counsel', 'Law', 'Der Verteidiger beantragt die Freilassung.', 'The defence counsel requests release.'],
  [null, 'verteidigen', null, 'to defend', 'Law', 'Jeder Angeklagte darf sich selbst verteidigen.', 'Every defendant may defend himself.'],
  [null, 'verurteilen', null, 'to sentence, to convict', 'Law', 'Das Gericht verurteilt ihn zu zwei Jahren Bewährung.', 'The court sentences him to two years on probation.'],
  [null, 'ermitteln', null, 'to investigate', 'Law', 'Die Behörde ermittelt seit Monaten gegen die Firma.', 'The authority has been investigating the company for months.'],
  ['die', 'Ermittlung', 'Ermittlungen', 'investigation', 'Law', 'Die Ermittlung dauert ein Jahr.', 'The investigation takes a year.'],
  ['die', 'Festnahme', 'Festnahmen', 'arrest', 'Law', 'Die Festnahme verlief ohne Widerstand.', 'The arrest went without resistance.'],
  [null, 'festnehmen', null, 'to arrest', 'Law', 'Die Beamten nehmen den Tatverdächtigen fest.', 'The officers arrest the suspect.'],
  ['die', 'Vernehmung', 'Vernehmungen', 'interrogation', 'Law', 'Die Vernehmung des Zeugen dauerte drei Stunden.', 'The interrogation of the witness took three hours.'],
  ['die', 'Durchsuchung', 'Durchsuchungen', 'search (of premises)', 'Law', 'Die Durchsuchung der Wohnung brachte Beweise.', 'The search of the apartment produced evidence.'],
  ['die', 'Fahndung', null, 'manhunt', 'Law', 'Die Fahndung nach dem Täter läuft europaweit.', 'The manhunt for the perpetrator is underway across Europe.'],
  ['der', 'Haftbefehl', 'Haftbefehle', 'arrest warrant', 'Law', 'Der Richter unterschreibt den Haftbefehl.', 'The judge signs the arrest warrant.'],
  ['die', 'Untersuchungshaft', null, 'pretrial detention', 'Law', 'Der Verdächtige sitzt in Untersuchungshaft.', 'The suspect is in pretrial detention.'],
  ['die', 'Haft', null, 'detention, custody', 'Law', 'Die Haft dauerte drei Monate.', 'The detention lasted three months.'],
  ['der', 'Zwang', null, 'coercion, force', 'Law', 'Er handelte unter Zwang.', 'He acted under coercion.'],
  ['die', 'Strafverfolgung', null, 'criminal prosecution', 'Law', 'Die Strafverfolgung liegt beim Staat.', 'Criminal prosecution lies with the state.'],
  ['der', 'Verdächtiger', 'Verdächtigen', 'suspect', 'Law', 'Verdächtiger gesteht nach fünf Stunden.', 'Suspect confesses after five hours.'],
  ['die', 'Bewährung', null, 'probation', 'Law', 'Er kam mit Bewährung davon.', 'He got off with probation.'],
  ['die', 'Beweisaufnahme', null, 'taking of evidence', 'Law', 'Die Beweisaufnahme ergab ein klares Bild.', 'The taking of evidence produced a clear picture.'],
  ['die', 'Zeugenaussage', 'Zeugenaussagen', 'testimony', 'Law', 'Die Zeugenaussage entlastete den Angeklagten.', 'The testimony exonerated the defendant.'],
  ['die', 'Anhörung', 'Anhörungen', 'hearing', 'Law', 'Der Betroffene hat Anspruch auf eine Anhörung.', 'The person concerned is entitled to a hearing.'],
  ['die', 'Revision', 'Revisionen', 'revision (appeal on points of law)', 'Law', 'Die Revision blieb ohne Erfolg.', 'The revision was unsuccessful.'],
  ['die', 'Verfassung', 'Verfassungen', 'constitution', 'Law', 'Die Verfassung garantiert Grundrechte.', 'The constitution guarantees basic rights.'],
  ['das', 'Grundgesetz', null, 'Basic Law (German constitution)', 'Law', 'Das Grundgesetz trat 1949 in Kraft.', 'The Basic Law came into force in 1949.'],
  ['die', 'Rechtsprechung', null, 'jurisprudence, case law', 'Law', 'Die Rechtsprechung des Gerichts ist konstant.', "The court's jurisprudence is consistent."],
  ['die', 'Rechtslage', null, 'legal situation', 'Law', 'Die Rechtslage ist unklar und umstritten.', 'The legal situation is unclear and disputed.'],
  ['das', 'Gesetzbuch', 'Gesetzbücher', 'legal code', 'Law', 'Das bürgerliche Gesetzbuch regelt Verträge.', 'The civil code regulates contracts.'],
  ['das', 'Rechtssystem', 'Rechtssysteme', 'legal system', 'Law', 'Das Rechtssystem unterscheidet sich von Land zu Land.', 'Legal systems differ from country to country.'],
  ['die', 'Justiz', null, 'judiciary, justice system', 'Law', 'Die Justiz arbeitet langsam, aber gründlich.', 'The judiciary works slowly but thoroughly.'],
  ['der', 'Rechtsbruch', 'Rechtsbrüche', 'breach of law', 'Law', 'Der Rechtsbruch zieht Sanktionen nach sich.', 'A breach of law entails sanctions.'],
  ['die', 'Gesetzeslücke', 'Gesetzeslücken', 'loophole, gap in the law', 'Law', 'Die Gesetzeslücke wird bald geschlossen.', 'The loophole will soon be closed.'],
  ['die', 'Auslegung', 'Auslegungen', 'interpretation', 'Law', 'Die Auslegung des Gesetzes ist strittig.', 'The interpretation of the law is disputed.'],
  ['das', 'Rechtsmittel', 'Rechtsmittel', 'legal remedy, appeal', 'Law', 'Gegen das Urteil gibt es Rechtsmittel.', 'There are legal remedies against the verdict.'],
  ['die', 'Berufung', 'Berufungen', 'appeal', 'Law', 'Er legte Berufung gegen das Urteil ein.', 'He filed an appeal against the verdict.'],
  ['die', 'Klageerhebung', null, 'filing of a lawsuit', 'Law', 'Die Klageerhebung erfolgte fristgerecht.', 'The lawsuit was filed on time.'],
  ['der', 'Widerspruch', 'Widersprüche', 'objection; contradiction', 'Law', 'Gegen den Bescheid kannst du Widerspruch einlegen.', 'You can file an objection against the decision.'],
  ['die', 'Nachfrist', 'Nachfristen', 'grace period', 'Law', 'Die Nachfrist beträgt zwei Wochen.', 'The grace period is two weeks.'],
  [null, 'fristlos', null, 'with immediate effect, without notice', 'Law', 'Die Kündigung erfolgte fristlos.', 'The termination took effect immediately.'],
  ['die', 'Instanz', 'Instanzen', 'instance (court level)', 'Law', 'Die zweite Instanz hob das Urteil auf.', 'The second instance overturned the verdict.'],
  ['der', 'Instanzenzug', null, 'hierarchy of instances', 'Law', 'Der Instanzenzug umfasst bis zu drei Stufen.', 'The hierarchy of instances comprises up to three levels.'],
  ['die', 'Rechtskraft', null, 'finality, legal force', 'Law', 'Mit der Rechtskraft ist das Verfahren beendet.', 'Once final, the proceedings are closed.'],
  ['die', 'Vollstreckung', 'Vollstreckungen', 'enforcement', 'Law', 'Die Vollstreckung des Urteils dauert Monate.', 'Enforcement of the judgment takes months.'],
  ['die', 'Zwangsmaßnahme', 'Zwangsmaßnahmen', 'coercive measure', 'Law', 'Jede Zwangsmaßnahme braucht eine Rechtsgrundlage.', 'Every coercive measure needs a legal basis.'],
  ['die', 'Ordnungswidrigkeit', 'Ordnungswidrigkeiten', 'administrative offence', 'Law', 'Falschparken ist eine Ordnungswidrigkeit.', 'Illegal parking is an administrative offence.'],
  ['der', 'Schadensersatz', null, 'damages, compensation', 'Law', 'Sie klagt auf Schadensersatz.', 'She is suing for damages.'],
  ['das', 'Schmerzensgeld', null, 'compensation for pain and suffering', 'Law', 'Das Gericht sprach ihm Schmerzensgeld zu.', 'The court awarded him compensation for pain.'],
  ['die', 'Verjährung', null, 'statute of limitations', 'Law', 'Nach fünf Jahren tritt Verjährung ein.', 'After five years the statute of limitations applies.'],
  ['die', 'Wiedergutmachung', null, 'reparation, amends', 'Law', 'Er bot finanzielle Wiedergutmachung an.', 'He offered financial reparation.'],
  ['der', 'Gerichtsvollzieher', 'Gerichtsvollzieher', 'bailiff', 'Law', 'Der Gerichtsvollzieher pfändet das Auto.', 'The bailiff seizes the car.'],
  ['die', 'Fluchtgefahr', null, 'risk of flight', 'Law', 'Wegen Fluchtgefahr wurde er festgenommen.', 'He was arrested because of the risk of flight.'],
  ['der', 'Zeugenschutz', null, 'witness protection', 'Law', 'Der Zeuge lebt unter Zeugenschutz.', 'The witness lives under protection.'],
  ['der', 'Strafantrag', 'Strafanträge', 'criminal complaint', 'Law', 'Der Strafantrag muss rechtzeitig gestellt werden.', 'The criminal complaint must be filed in time.'],
  ['die', 'Begnadigung', 'Begnadigungen', 'pardon', 'Law', 'Die Begnadigung ist ein Akt der Gnade.', 'The pardon is an act of clemency.'],
  ['die', 'Amnestie', 'Amnestien', 'amnesty', 'Law', 'Die Amnestie gilt für Kleinkriminelle.', 'The amnesty applies to minor offenders.'],

  // ── M12.5: Gefühle/Charakter + Medien/Technik ──
  ['die', 'Empathie', null, 'empathy', 'Emotions', 'Empathie kann man lernen.', 'Empathy can be learned.'],
  ['das', 'Unterbewusstsein', null, 'subconscious', 'Emotions', 'Ängste sitzen oft im Unterbewusstsein.', 'Fears often sit in the subconscious.'],
  ['die', 'Gemütsverfassung', 'Gemütsverfassungen', 'state of mind', 'Emotions', 'Die Therapeutin fragt nach ihrer Gemütsverfassung.', 'The therapist asks about her state of mind.'],
  ['die', 'Seelenruhe', null, 'inner calm, serenity', 'Emotions', 'Mit Seelenruhe erträgt sie die Kritik.', 'With serenity she endures the criticism.'],
  ['die', 'Wehmut', null, 'wistfulness, melancholy', 'Emotions', 'Beim Anblick der alten Fotos spürte er Wehmut.', 'At the sight of the old photos he felt wistfulness.'],
  ['der', 'Übermut', null, 'overconfidence, high spirits', 'Emotions', 'Aus Übermut kletterte er auf das Dach.', 'Out of high spirits he climbed onto the roof.'],
  ['die', 'Genugtuung', null, 'satisfaction, vindication', 'Emotions', 'Nach dem Sieg fühlte er tiefe Genugtuung.', 'After the victory he felt deep vindication.'],
  ['die', 'Betroffenheit', null, 'consternation, distress', 'Emotions', 'Die Nachricht löste landesweite Betroffenheit aus.', 'The news caused nationwide consternation.'],
  ['das', 'Unbehagen', null, 'discomfort, unease', 'Emotions', 'Das Thema löst bei ihr Unbehagen aus.', 'The topic triggers unease in her.'],
  ['das', 'Entsetzen', null, 'horror, shock', 'Emotions', 'Ein Schrei des Entsetzens ging durch den Saal.', 'A cry of horror went through the hall.'],
  ['die', 'Entrüstung', null, 'indignation, outrage', 'Emotions', 'Seine Bemerkung löste Entrüstung aus.', 'His remark caused indignation.'],
  ['die', 'Hingabe', null, 'dedication, devotion', 'Emotions', 'Sie unterrichtet mit großer Hingabe.', 'She teaches with great dedication.'],
  ['die', 'Verachtung', null, 'contempt', 'Emotions', 'Er spricht mit Verachtung über den Verrat.', 'He speaks about the betrayal with contempt.'],
  ['die', 'Nostalgie', 'Nostalgien', 'nostalgia', 'Emotions', 'Alte Fotos wecken bei ihr Nostalgie.', 'Old photos awaken nostalgia in her.'],
  ['der', 'Ekel', null, 'disgust', 'Emotions', 'Der Anblick erfüllte sie mit Ekel.', 'The sight filled her with disgust.'],
  ['die', 'Abscheu', null, 'abhorrence, repugnance', 'Emotions', 'Gewalt erfüllt ihn mit Abscheu.', 'Violence fills him with abhorrence.'],
  ['die', 'Verlegenheit', null, 'embarrassment', 'Emotions', 'Aus Verlegenheit wurde sie still.', 'Out of embarrassment she went quiet.'],
  ['die', 'Begierde', null, 'desire, craving', 'Emotions', 'Seine Begierde nach Anerkennung trieb ihn an.', 'His craving for recognition drove him on.'],
  ['die', 'Leidenschaft', 'Leidenschaften', 'passion', 'Emotions', 'Sie spielt mit großer Leidenschaft Klavier.', 'She plays the piano with great passion.'],
  [null, 'teilnahmslos', null, 'apathetic, indifferent', 'Emotions', 'Sie hörte teilnahmslos zu.', 'She listened apathetically.'],
  ['die', 'Schadenfreude', null, 'schadenfreude, gloating', 'Emotions', 'Schadenfreude ist keine schöne Eigenschaft.', 'Schadenfreude is not a nice trait.'],
  ['die', 'Zuneigung', null, 'affection', 'Emotions', 'Zwischen den beiden entwickelte sich Zuneigung.', 'Affection developed between the two of them.'],
  ['die', 'Lebensfreude', null, 'joie de vivre, love of life', 'Emotions', 'Trotz allem bewahrt sie ihre Lebensfreude.', 'Despite everything she keeps her love of life.'],
  ['die', 'Selbstliebe', null, 'self-love, self-care', 'Emotions', 'Gesunde Selbstliebe stärkt die Psyche.', 'Healthy self-love strengthens the psyche.'],
  ['die', 'Schwärmerei', null, 'gushing, infatuation', 'Emotions', 'Seine Schwärmerei für den Sänger geht den Freunden auf die Nerven.', 'His gushing about the singer gets on the nerves of his friends.'],
  ['die', 'Bewunderung', null, 'admiration', 'Emotions', 'Sie spricht mit Bewunderung über ihre Lehrerin.', 'She speaks about her teacher with admiration.'],
  ['die', 'Heuchelei', null, 'hypocrisy', 'Character', 'Seine Heuchelei flog beim zweiten Gespräch auf.', 'His hypocrisy was exposed in the second conversation.'],
  ['der', 'Heuchler', 'Heuchler', 'hypocrite', 'Character', 'Der Heuchler spielt Empfindungen nur vor.', 'The hypocrite only feigns feelings.'],
  ['die', 'Aufrichtigkeit', null, 'sincerity, candor', 'Character', 'Ihre Aufrichtigkeit gewinnt das Vertrauen der Gruppe.', 'Her sincerity wins the trust of the group.'],
  ['die', 'Selbstdisziplin', null, 'self-discipline', 'Character', 'Ohne Selbstdisziplin scheitert jedes Vorhaben.', 'Without self-discipline every project fails.'],
  ['die', 'Weisheit', null, 'wisdom', 'Character', 'In ihren Worten liegt viel Weisheit.', 'There is a lot of wisdom in her words.'],
  ['das', 'Laster', 'Laster', 'vice', 'Character', 'Das Rauchen ist ein ungesundes Laster.', 'Smoking is an unhealthy vice.'],
  ['das', 'Gemüt', 'Gemüter', 'mind, disposition', 'Character', 'Die Nachricht beruhigte die erregten Gemüter.', 'The news calmed the excited minds.'],
  ['die', 'Selbstgefälligkeit', null, 'complacency, smugness', 'Character', 'Aus Selbstgefälligkeit übersieht er seine Fehler.', 'Out of complacency he overlooks his mistakes.'],
  ['die', 'Besonnenheit', null, 'composure, level-headedness', 'Character', 'Mit Besonnenheit schlichtete er den Streit.', 'With composure he settled the dispute.'],
  ['die', 'Gewissenhaftigkeit', null, 'conscientiousness', 'Character', 'Gewissenhaftigkeit zeichnet ihre Arbeit aus.', 'Conscientiousness characterizes her work.'],
  ['die', 'Verschwiegenheit', null, 'discretion', 'Character', 'Als Anwalt ist Verschwiegenheit Pflicht.', 'As a lawyer discretion is a duty.'],
  ['die', 'Arglosigkeit', null, 'gullibility, artlessness', 'Character', 'Ihre Arglosigkeit wurde ausgenutzt.', 'Her gullibility was taken advantage of.'],
  ['die', 'Hinterhältigkeit', null, 'deviousness', 'Character', 'Die Hinterhältigkeit des Plans schockierte alle.', 'The deviousness of the plan shocked everyone.'],
  ['die', 'Skrupellosigkeit', null, 'unscrupulousness', 'Character', 'Seine Skrupellosigkeit kostete ihn den Respekt der Kollegen.', 'His unscrupulousness cost him the respect of his colleagues.'],
  ['die', 'Skrupel', null, 'scruples', 'Character', 'Der Betrüger kennt keine Skrupel.', 'The fraudster knows no scruples.'],
  ['die', 'Integrität', null, 'integrity', 'Character', 'Seine Integrität ist über jeden Zweifel erhaben.', 'His integrity is beyond any doubt.'],
  ['die', 'Authentizität', null, 'authenticity', 'Character', 'Ihre Authentizität überzeugt das Publikum.', 'Her authenticity convinces the audience.'],
  ['das', 'Einfühlungsvermögen', null, 'empathy, capacity for empathy', 'Character', 'Einfühlungsvermögen zeichnet gute Führungskräfte aus.', 'Empathy characterizes good leaders.'],
  ['das', 'Pflichtgefühl', null, 'sense of duty', 'Character', 'Aus starkem Pflichtgefühl kam er trotz Fieber.', 'Out of a strong sense of duty he came despite a fever.'],
  ['der', 'Starrsinn', null, 'obstinacy', 'Character', 'Sein Starrsinn blockiert jede Einigung.', 'His obstinacy blocks any agreement.'],
  ['die', 'Güte', null, 'goodness, kindness', 'Character', 'Sie begegnet allen Menschen mit Güte.', 'She meets all people with kindness.'],
  ['die', 'Gesinnung', null, 'conviction, mindset', 'Character', 'Seine politische Gesinnung spielt hier keine Rolle.', 'His political conviction plays no role here.'],
  ['die', 'Weltanschauung', 'Weltanschauungen', 'worldview', 'Character', 'Reisen erweitern die eigene Weltanschauung.', 'Travel broadens your own worldview.'],
  ['das', 'Selbstwertgefühl', null, 'self-esteem', 'Character', 'Ein stabiles Selbstwertgefühl schützt vor Kränkungen.', 'A stable self-esteem protects against affronts.'],
  ['die', 'Meinungsbildung', null, 'opinion formation', 'Media', 'Soziale Medien beeinflussen die Meinungsbildung stark.', 'Social media strongly influence opinion formation.'],
  ['der', 'Boulevardjournalismus', null, 'tabloid journalism', 'Media', 'Boulevardjournalismus lebt von Skandalen.', 'Tabloid journalism lives off scandals.'],
  ['die', 'Auflagenhöhe', 'Auflagenhöhen', 'circulation figure', 'Media', 'Die Auflagenhöhe der Zeitung sinkt seit Jahren.', 'The circulation figure of the newspaper has been falling for years.'],
  ['die', 'Medienkritik', null, 'media criticism', 'Media', 'Medienkritik gehört zur Demokratie.', 'Media criticism is part of democracy.'],
  ['der', 'Aufmacher', 'Aufmacher', 'front-page story', 'Media', 'Der Aufmacher widmet sich der Klimakrise.', 'The front-page story is devoted to the climate crisis.'],
  ['die', 'Glosse', 'Glossen', 'gloss (satirical column)', 'Media', 'Ihre Glosse trifft den Nerv der Leser.', 'Her gloss hits a nerve with readers.'],
  ['das', 'Feuilleton', 'Feuilletons', 'arts and culture section', 'Media', 'Die Rezension erschien im Feuilleton.', 'The review appeared in the arts section.'],
  ['das', 'Dossier', 'Dossiers', 'dossier, file', 'Media', 'Die Redaktion erstellte ein Dossier zu dem Fall.', 'The editorial office compiled a dossier on the case.'],
  ['die', 'Recherche', 'Recherchen', 'research, investigation (journalism)', 'Media', 'Die Recherche ergab Überraschendes.', 'The research produced surprising findings.'],
  ['der', 'Redakteur', 'Redakteure', 'editor', 'Media', 'Der Redakteur kürzt meinen Artikel für die morgige Ausgabe.', 'The editor shortens my article for the edition tomorrow.'],
  ['der', 'Verleger', 'Verleger', 'publisher', 'Media', 'Der Verleger entscheidet über jedes neue Buch.', 'The publisher decides about every new book.'],
  ['die', 'künstliche Intelligenz', null, 'artificial intelligence', 'Technology', 'Künstliche Intelligenz verändert viele Berufe.', 'Artificial intelligence is changing many professions.'],
  ['das', 'maschinelle Lernen', null, 'machine learning', 'Technology', 'Viele Anwendungen nutzen das maschinelle Lernen.', 'Many applications use machine learning.'],
  ['die', 'Datenanalyse', 'Datenanalysen', 'data analysis', 'Technology', 'Die Datenanalyse deckt überraschende Muster auf.', 'The data analysis reveals surprising patterns.'],
  ['die', 'Cybersicherheit', null, 'cybersecurity', 'Technology', 'Cybersicherheit hat für Banken höchste Priorität.', 'Cybersecurity has the highest priority for banks.'],
  ['die', 'Vernetzung', null, 'interconnection, networking', 'Technology', 'Die zunehmende Vernetzung schafft neue Risiken.', 'The increasing interconnection creates new risks.'],
  ['die', 'Überwachung', 'Überwachungen', 'surveillance, monitoring', 'Technology', 'Die Überwachung öffentlicher Plätze nimmt zu.', 'The surveillance of public places is increasing.'],
  ['die', 'Manipulation', 'Manipulationen', 'manipulation', 'Technology', 'Die Manipulation von Daten ist strafbar.', 'The manipulation of data is a criminal offense.'],
  ['die', 'Datenflut', null, 'flood of data', 'Technology', 'Die tägliche Datenflut überfordert viele Teams.', 'The daily flood of data overwhelms many teams.'],
  ['die', 'Informationsflut', null, 'information overload', 'Technology', 'Die Informationsflut erschwert den Überblick.', 'The flood of information makes it hard to keep an overview.'],
  ['die', 'Benutzeroberfläche', 'Benutzeroberflächen', 'user interface', 'Technology', 'Die Benutzeroberfläche der App wurde neu gestaltet.', 'The user interface of the app was redesigned.'],
  ['der', 'Quellcode', 'Quellcodes', 'source code', 'Technology', 'Der Quellcode des Programms ist öffentlich einsehbar.', 'The source code of the program is publicly viewable.'],
  // ── M12.6: Natur und Umwelt (abstrakt) ──
  ['der', 'Kipppunkt', 'Kipppunkte', 'tipping point', 'Environment', 'Wissenschaftler warnen vor dem Kipppunkt im Klimasystem.', 'Scientists warn of the tipping point in the climate system.'],
  ['das', 'Artensterben', null, 'species extinction', 'Environment', 'Das Artensterben schreitet schneller voran als befürchtet.', 'Species extinction is progressing faster than feared.'],
  ['der', 'Artenschwund', null, 'loss of species', 'Environment', 'Der Artenschwund betrifft auch Insekten.', 'The loss of species also affects insects.'],
  ['die', 'Biodiversität', null, 'biodiversity', 'Environment', 'Die Biodiversität der Tropen ist einzigartig.', 'The biodiversity of the tropics is unique.'],
  ['die', 'Renaturierung', null, 'renaturation, restoration', 'Environment', 'Die Renaturierung des Flusses dauert Jahrzehnte.', 'The restoration of the river takes decades.'],
  ['die', 'Aufforstung', null, 'reforestation', 'Environment', 'Die Aufforstung beginnt im Frühjahr.', 'The reforestation begins in spring.'],
  ['die', 'Wiedervernässung', null, 'rewetting (of moors)', 'Environment', 'Die Wiedervernässung der Moore bindet CO2.', 'The rewetting of moors binds CO2.'],
  ['der', 'Flächenverbrauch', null, 'land consumption', 'Environment', 'Der Flächenverbrauch zerstört Lebensräume.', 'Land consumption destroys habitats.'],
  ['die', 'Versiegelung', null, 'sealing (of soil)', 'Environment', 'Die Versiegelung der Böden erhöht die Hochwassergefahr.', 'The sealing of soils increases the risk of flooding.'],
  ['die', 'Zersiedelung', null, 'urban sprawl', 'Environment', 'Die Zersiedelung des Ulands frisst Ackerland.', 'Urban sprawl devours farmland.'],
  ['das', 'Anthropozän', null, 'Anthropocene', 'Environment', 'Manche Forscher nennen unser Zeitalter das Anthropozän.', 'Some researchers call our era the Anthropocene.'],
  ['die', 'Desertifikation', null, 'desertification', 'Environment', 'Die Desertifikation bedroht die Sahelzone.', 'Desertification threatens the Sahel zone.'],
  ['das', 'Mikroplastik', null, 'microplastics', 'Environment', 'Mikroplastik wurde sogar in der Arktis gefunden.', 'Microplastics have even been found in the Arctic.'],
  ['der', 'Emissionshandel', null, 'emissions trading', 'Environment', 'Der Emissionshandel verteuert CO2.', 'Emissions trading makes CO2 more expensive.'],
  ['die', 'Klimagerechtigkeit', null, 'climate justice', 'Environment', 'Klimagerechtigkeit verbindet Nord und Süd.', 'Climate justice connects North and South.'],
  ['die', 'Klimaneutralität', null, 'climate neutrality', 'Environment', 'Die Stadt will bis 2035 Klimaneutralität erreichen.', 'The city wants to achieve climate neutrality by 2035.'],
  ['die', 'Dekarbonisierung', null, 'decarbonization', 'Environment', 'Die Dekarbonisierung der Industrie ist teuer.', 'The decarbonization of industry is expensive.'],
  ['die', 'Resilienz', null, 'resilience', 'Environment', 'Ökosysteme brauchen Resilienz gegen Krisen.', 'Ecosystems need resilience against crises.'],
  ['die', 'Verwundbarkeit', null, 'vulnerability', 'Environment', 'Die Verwundbarkeit der Küstenregionen wächst.', 'The vulnerability of coastal regions is growing.'],
  ['die', 'Überweidung', null, 'overgrazing', 'Environment', 'Überweidung verwüstet die Steppen.', 'Overgrazing devastates the steppes.'],
  ['die', 'Wegwerfgesellschaft', null, 'throwaway society', 'Environment', 'Die Wegwerfgesellschaft produziert Berge von Müll.', 'The throwaway society produces mountains of waste.'],
  ['die', 'Konsumkritik', null, 'criticism of consumption', 'Environment', 'Konsumkritik prägt die junge Generation.', 'Criticism of consumption shapes the young generation.'],
  ['der', 'Verzicht', 'Verzichte', 'renunciation, doing without', 'Environment', 'Verzicht ist ein Teil des Klimaschutzes.', 'Renunciation is a part of climate protection.'],
  ['die', 'Genügsamkeit', null, 'frugality, contentment with little', 'Environment', 'Genügsamkeit gilt als alte Tugend.', 'Frugality is considered an old virtue.'],
  ['die', 'Entschleunigung', null, 'slowing down (of life)', 'Environment', 'Entschleunigung beginnt mit weniger Konsum.', 'Slowing down begins with less consumption.'],
  [null, 'verwüsten', null, 'to devastate, lay waste', 'Environment', 'Der Krieg verwüstete ganze Landstriche.', 'The war devastated entire regions.'],
  [null, 'aufforsten', null, 'to reforest', 'Environment', 'Die Stadt will die Kahlschläge aufforsten.', 'The city wants to reforest the clear-cuts.'],
  [null, 'renaturieren', null, 'to restore (nature)', 'Environment', 'Man will den Kanal renaturieren.', 'The canal is to be restored to its natural state.'],
  [null, 'entschleunigen', null, 'to slow down', 'Environment', 'Der Urlaub hilft uns, den Alltag zu entschleunigen.', 'The vacation helps us slow down everyday life.'],
  [null, 'ausrotten', null, 'to exterminate, wipe out', 'Environment', 'Der Mensch hat viele Arten ausgerottet.', 'Humans have exterminated many species.'],
  [null, 'züchten', null, 'to breed', 'Environment', 'Bauern züchten robuste Getreidesorten.', 'Farmers breed robust varieties of grain.'],
  [null, 'hegen', null, 'to nurture, care for', 'Environment', 'Der Förster hegt den jungen Baumbestand.', 'The forester nurtures the young tree population.'],
  [null, 'bewirtschaften', null, 'to farm, cultivate', 'Environment', 'Die Familie bewirtschaftet den Hof seit 1800.', 'The family has farmed the estate since 1800.'],
  [null, 'brachliegen', null, 'to lie fallow', 'Environment', 'Das Feld soll ein Jahr brachliegen.', 'The field is to lie fallow for a year.'],
  ['die', 'Ursprünglichkeit', null, 'pristine quality, unspoiledness', 'Nature', 'Die Ursprünglichkeit des Tals zieht Besucher an.', 'The unspoiled nature of the valley attracts visitors.'],
  ['das', 'Idyll', 'Idylle', 'idyll', 'Nature', 'Das Dorf ist ein echtes Idyll.', 'The village is a real idyll.'],
  ['die', 'Abgeschiedenheit', null, 'seclusion, remoteness', 'Nature', 'Die Abgeschiedenheit der Berge tut der Seele gut.', 'The seclusion of the mountains is good for the soul.'],
  ['die', 'Erhabenheit', null, 'sublimity, majesty', 'Nature', 'Die Erhabenheit der Gipfel überwältigt jeden.', 'The majesty of the peaks overwhelms everyone.'],
  ['die', 'Weite', null, 'vastness, expanse', 'Nature', 'Die Weite der Landschaft raubt einem den Atem.', 'The vastness of the landscape takes your breath away.'],
  ['der', 'Rückzugsort', 'Rückzugsorte', 'place of retreat', 'Nature', 'Der Wald ist sein Rückzugsort.', 'The forest is his place of retreat.'],
  ['das', 'Refugium', 'Refugien', 'refuge, sanctuary', 'Nature', 'Die Berge wurden ihnen zum Refugium.', 'The mountains became a refuge for them.'],
  ['die', 'Symbiose', 'Symbiosen', 'symbiosis', 'Nature', 'Pilz und Baum leben in Symbiose.', 'Fungus and tree live in symbiosis.'],
  ['die', 'Bestäubung', null, 'pollination', 'Nature', 'Ohne Bestäubung gäbe es keine Früchte.', 'Without pollination there would be no fruit.'],
  ['der', 'Bestäuber', 'Bestäuber', 'pollinator', 'Nature', 'Die Biene ist der wichtigste Bestäuber.', 'The bee is the most important pollinator.'],
  ['die', 'Photosynthese', null, 'photosynthesis', 'Nature', 'Bei der Photosynthese entstehen Sauerstoff und Zucker.', 'Oxygen and sugar are produced during photosynthesis.'],
  ['die', 'Wetterfühligkeit', null, 'weather sensitivity', 'Nature', 'Ihre Wetterfühligkeit macht Wandern schwer.', 'Her weather sensitivity makes hiking difficult.'],
  ['der', 'Lebenszyklus', 'Lebenszyklen', 'life cycle', 'Nature', 'Der Lebenszyklus der Libelle dauert ein Jahr.', 'The life cycle of the dragonfly lasts one year.'],
  // ── M12.6: Gesellschaft (abstrakt) ──
  ['das', 'Narrativ', 'Narrative', 'narrative', 'Society', 'Jede Partei erzählt ihr eigenes Narrativ.', 'Each party tells its own narrative.'],
  ['die', 'Polarisierung', null, 'polarization', 'Society', 'Die Polarisierung der Gesellschaft schreitet voran.', 'The polarization of society is advancing.'],
  ['der', 'Populismus', null, 'populism', 'Society', 'Der Populismus vereinfacht komplexe Themen.', 'Populism simplifies complex issues.'],
  ['die', 'Radikalisierung', null, 'radicalization', 'Society', 'Der Verein will der Radikalisierung junger Menschen vorbeugen.', 'The association wants to prevent the radicalization of young people.'],
  ['die', 'Verschwörungstheorie', 'Verschwörungstheorien', 'conspiracy theory', 'Society', 'Die Verschwörungstheorie verbreitet sich rasend schnell.', 'The conspiracy theory is spreading rapidly.'],
  ['die', 'Filterblase', 'Filterblasen', 'filter bubble', 'Society', 'In der Filterblase hört man nur noch die eigene Meinung.', 'In the filter bubble you only hear your own opinion.'],
  ['die', 'Echokammer', 'Echokammern', 'echo chamber', 'Society', 'Soziale Medien sind oft eine Echokammer.', 'Social media are often an echo chamber.'],
  ['die', 'Transparenz', null, 'transparency', 'Society', 'Transparenz schafft Vertrauen in die Behörden.', 'Transparency creates trust in authorities.'],
  ['die', 'Rechenschaft', null, 'accountability', 'Society', 'Der Minister schuldet dem Parlament Rechenschaft.', 'The minister owes accountability to parliament.'],
  ['die', 'Legitimität', null, 'legitimacy', 'Society', 'Die Legitimität der Wahl war unbestritten.', 'The legitimacy of the election was undisputed.'],
  ['die', 'Souveränität', null, 'sovereignty', 'Society', 'Die Souveränität des Staates ist verfassungsrechtlich geschützt.', 'The sovereignty of the state is protected by the constitution.'],
  ['der', 'Föderalismus', null, 'federalism', 'Society', 'Der Föderalismus verteilt Macht auf Länder und Bund.', 'Federalism distributes power between states and the federation.'],
  ['das', 'Gemeinwohl', null, 'common good', 'Society', 'Der Staat muss das Gemeinwohl im Blick behalten.', 'The state must keep the common good in mind.'],
  ['die', 'Umverteilung', null, 'redistribution', 'Society', 'Steuern dienen der Umverteilung von Reichtum.', 'Taxes serve the redistribution of wealth.'],
  ['der', 'Lobbyismus', null, 'lobbying', 'Society', 'Kritiker bemängeln den Einfluss des Lobbyismus.', 'Critics complain about the influence of lobbying.'],
  ['die', 'Geschichtsaufarbeitung', null, 'coming to terms with history', 'Society', 'Die Geschichtsaufarbeitung dauert Generationen.', 'Coming to terms with history takes generations.'],
  ['die', 'Vergangenheitsbewältigung', null, 'coming to terms with the past', 'Society', 'Vergangenheitsbewältigung ist ein langer Prozess.', 'Coming to terms with the past is a long process.'],
  ['die', 'Erinnerungskultur', null, 'culture of remembrance', 'Society', 'Die Erinnerungskultur prägt den 8. Mai.', 'The culture of remembrance shapes May 8th.'],
  ['das', 'Mahnmal', 'Mahnmale', 'memorial, warning monument', 'Society', 'Das Mahnmal erinnert an die Opfer.', 'The memorial commemorates the victims.'],
  ['der', 'Zeitzeuge', 'Zeitzeugen', 'contemporary witness', 'Society', 'Der Zeitzeuge erzählt Schülern vom Krieg.', 'The contemporary witness tells students about the war.'],
  ['der', 'Völkermord', 'Völkermorde', 'genocide', 'Society', 'Der Völkermord wird bis heute geleugnet.', 'The genocide is still denied today.'],
  ['das', 'Kriegsverbrechen', 'Kriegsverbrechen', 'war crime', 'Society', 'Kriegsverbrechen gehören vor internationale Gerichte.', 'War crimes belong before international courts.'],
  ['die', 'Zivilcourage', null, 'moral courage', 'Society', 'Zivilcourage zeigt sich im Alltag.', 'Moral courage shows itself in everyday life.'],
  ['die', 'Zivilgesellschaft', null, 'civil society', 'Society', 'Die Zivilgesellschaft organisiert Hilfe für Geflüchtete.', 'Civil society organizes help for refugees.'],
  ['die', 'Selbstverwaltung', null, 'self-administration', 'Society', 'Die Unis genießen akademische Selbstverwaltung.', 'Universities enjoy academic self-administration.'],
  ['die', 'Staatsverschuldung', null, 'national debt', 'Society', 'Die Staatsverschuldung erreicht einen Rekordwert.', 'The national debt reaches a record level.'],
  ['die', 'Schuldenbremse', null, 'debt brake', 'Society', 'Die Schuldenbremse begrenzt neue Kredite.', 'The debt brake limits new loans.'],
  ['das', 'Bleiberecht', null, 'right to remain', 'Society', 'Nach zehn Jahren erhält sie das Bleiberecht.', 'After ten years she receives the right to remain.'],
  ['der', 'Familiennachzug', null, 'family reunification', 'Society', 'Der Familiennachzug wurde neu geregelt.', 'Family reunification was newly regulated.'],
  ['die', 'Willkommenskultur', null, 'culture of welcome', 'Society', 'Die Willkommenskultur prägte das Jahr 2015.', 'The culture of welcome shaped the year 2015.'],
  ['die', 'Mehrsprachigkeit', null, 'multilingualism', 'Society', 'Mehrsprachigkeit gilt als Schlüsselkompetenz.', 'Multilingualism is considered a key skill.'],
  ['die', 'Demografie', null, 'demographics', 'Society', 'Die Demografie verändert das Land tiefgreifend.', 'Demographics are changing the country profoundly.'],
  ['die', 'Landflucht', null, 'rural exodus', 'Society', 'Die Landflucht entvölkert ganze Regionen.', 'The rural exodus depopulates entire regions.'],
  ['die', 'Verstädterung', null, 'urbanization', 'Society', 'Die Verstädterung schreitet weltweit voran.', 'Urbanization is progressing worldwide.'],
  ['das', 'Renteneintrittsalter', null, 'retirement age', 'Society', 'Das Renteneintrittsalter soll schrittweise steigen.', 'The retirement age is to rise gradually.'],
  ['das', 'Grundeinkommen', 'Grundeinkommen', 'basic income', 'Society', 'Ein Grundeinkommen wurde in Pilotprojekten getestet.', 'A basic income was tested in pilot projects.'],
  ['die', 'Altersvorsorge', null, 'retirement provision', 'Society', 'Die private Altersvorsorge wird staatlich gefördert.', 'Private retirement provision is supported by the state.'],
  ['der', 'Niedriglohnsektor', null, 'low-wage sector', 'Society', 'Der Niedriglohnsektor ist in den letzten Jahren gewachsen.', 'The low-wage sector has grown in recent years.'],
  ['die', 'Leiharbeit', null, 'temporary agency work', 'Society', 'Leiharbeit bietet Flexibilität, aber wenig Sicherheit.', 'Temporary work offers flexibility but little security.'],
  ['der', 'Wertewandel', null, 'change in values', 'Society', 'Der Wertewandel begann in den 1960er-Jahren.', 'The change in values began in the 1960s.'],
  ['die', 'Zeitenwende', 'Zeitenwenden', 'turn of era, watershed', 'Society', 'Die Rede von der Zeitenwende prägt die Debatte.', 'The talk of a turning point shapes the debate.'],
  ['das', 'Misstrauensvotum', 'Misstrauensvoten', 'vote of no confidence', 'Society', 'Das Misstrauensvotum gegen den Kanzler scheiterte knapp.', 'The vote of no confidence against the chancellor failed narrowly.'],
  ['die', 'Vertrauensfrage', 'Vertrauensfragen', 'vote of confidence', 'Society', 'Der Kanzler stellte die Vertrauensfrage im Parlament.', 'The chancellor posed the vote of confidence in parliament.'],
  ['die', 'Regierungserklärung', 'Regierungserklärungen', 'government policy statement', 'Society', 'Die Regierungserklärung dauerte über eine Stunde.', 'The government policy statement lasted over an hour.'],
  ['der', 'Koalitionsvertrag', 'Koalitionsverträge', 'coalition agreement', 'Society', 'Der Koalitionsvertrag umfasst 140 Seiten.', 'The coalition agreement comprises 140 pages.'],
  ['die', 'Sachverständige', 'Sachverständigen', 'expert (female); experts', 'Society', 'Die Sachverständige warnte vor falschen Zahlen.', 'The expert warned against false numbers.'],
  ['das', 'Verfassungsgericht', 'Verfassungsgerichte', 'constitutional court', 'Society', 'Das Verfassungsgericht prüft das neue Gesetz.', 'The constitutional court reviews the new law.'],
  ['die', 'Diplomatie', null, 'diplomacy', 'Society', 'Diplomatie hat den Krieg verhindert.', 'Diplomacy prevented the war.'],
  [null, 'diplomatisch', null, 'diplomatic(ally)', 'Society', 'Sie formuliert ihre Kritik stets diplomatisch.', 'She always phrases her criticism diplomatically.'],
  ['die', 'Sanktion', 'Sanktionen', 'sanction', 'Society', 'Die Sanktion trifft die Wirtschaft des Landes.', 'The sanction hits the economy of the country.'],
  ['der', 'Kapitalismus', null, 'capitalism', 'Society', 'Der Kapitalismus wird von Kritikern und Befürwortern diskutiert.', 'Capitalism is discussed by critics and supporters alike.'],
  ['der', 'Sozialismus', null, 'socialism', 'Society', 'Der Sozialismus war Staatsdoktrin in der DDR.', 'Socialism was state doctrine in the GDR.'],
  ['die', 'Marktwirtschaft', 'Marktwirtschaften', 'market economy', 'Society', 'Die soziale Marktwirtschaft ist das deutsche Modell.', 'The social market economy is the German model.'],
  ['die', 'Planwirtschaft', 'Planwirtschaften', 'planned economy', 'Society', 'Die Planwirtschaft scheiterte an ihrer Ineffizienz.', 'The planned economy failed due to its inefficiency.'],
  // ── M12.7: Wissenschaft (abstraktes Register) ──
  ['die', 'Reproduzierbarkeit', null, 'reproducibility', 'Science', 'Reproduzierbarkeit ist das Herz guter Forschung.', 'Reproducibility is the heart of good research.'],
  ['die', 'Falsifizierbarkeit', null, 'falsifiability', 'Science', 'Falsifizierbarkeit trennt Wissenschaft von Glauben.', 'Falsifiability separates science from belief.'],
  ['das', 'Paradigma', 'Paradigmen', 'paradigm', 'Science', 'Das alte Paradigma geriet ins Wanken.', 'The old paradigm began to falter.'],
  ['der', 'Paradigmenwechsel', null, 'paradigm shift', 'Science', 'Der Paradigmenwechsel dauerte ein Jahrzehnt.', 'The paradigm shift took a decade.'],
  ['die', 'Interdisziplinarität', null, 'interdisciplinarity', 'Science', 'Interdisziplinarität öffnet neue Perspektiven.', 'Interdisciplinarity opens new perspectives.'],
  ['die', 'Replikation', 'Replikationen', 'replication (of a study)', 'Science', 'Die Replikation bestätigte den Befund nicht.', 'The replication did not confirm the finding.'],
  ['die', 'Replikationskrise', null, 'replication crisis', 'Science', 'Die Replikationskrise erschütterte die Psychologie.', 'The replication crisis shook psychology.'],
  ['das', 'Peer-Review', 'Peer-Reviews', 'peer review', 'Science', 'Das Peer-Review dauert oft Monate.', 'Peer review often takes months.'],
  ['die', 'Aussagekraft', null, 'significance, explanatory power', 'Science', 'Die Aussagekraft der Studie ist begrenzt.', 'The explanatory power of the study is limited.'],
  ['die', 'Signifikanz', null, 'statistical significance', 'Science', 'Das Ergebnis verfehlt die Signifikanz knapp.', 'The result narrowly misses significance.'],
  ['die', 'Korrelation', 'Korrelationen', 'correlation', 'Science', 'Die Korrelation ist stark, aber nicht beweiskräftig.', 'The correlation is strong but not conclusive.'],
  ['die', 'Kausalität', null, 'causality', 'Science', 'Kausalität ist schwer nachzuweisen.', 'Causality is hard to prove.'],
  ['die', 'Varianz', 'Varianzen', 'variance', 'Science', 'Die Varianz der Messwerte ist hoch.', 'The variance of the measurements is high.'],
  ['die', 'Datenlage', 'Datenlagen', 'data situation, state of evidence', 'Science', 'Die Datenlage ist noch unklar.', 'The state of the evidence is still unclear.'],
  ['die', 'Evidenz', 'Evidenzen', 'evidence', 'Science', 'Die Evidenz spricht für die neue Theorie.', 'The evidence speaks for the new theory.'],
  ['die', 'Plausibilität', null, 'plausibility', 'Science', 'Die Plausibilität der These überzeugt.', 'The plausibility of the thesis is convincing.'],
  ['die', 'Stringenz', null, 'stringency, rigor', 'Science', 'Die Stringenz der Argumentation beeindruckt.', 'The rigor of the argument is impressive.'],
  ['die', 'Erkenntnistheorie', null, 'epistemology', 'Science', 'Erkenntnistheorie fragt, wie Wissen entsteht.', 'Epistemology asks how knowledge arises.'],
  ['die', 'Empirie', null, 'empirical research, empiricism', 'Science', 'Die Empirie prüft, was die Theorie behauptet.', 'Empirical research tests what the theory claims.'],
  ['die', 'Versuchsanordnung', 'Versuchsanordnungen', 'experimental setup', 'Science', 'Die Versuchsanordnung folgt einem Standard.', 'The experimental setup follows a standard.'],
  ['die', 'Messgenauigkeit', null, 'measurement accuracy', 'Science', 'Die Messgenauigkeit entscheidet über den Beweis.', 'Measurement accuracy decides about the proof.'],
  ['die', 'Messunsicherheit', 'Messunsicherheiten', 'measurement uncertainty', 'Science', 'Jede Messunsicherheit muss angegeben werden.', 'Every measurement uncertainty must be stated.'],
  ['die', 'Kalibrierung', 'Kalibrierungen', 'calibration', 'Science', 'Die Kalibrierung des Geräts erfolgt wöchentlich.', 'Calibration of the device happens weekly.'],
  ['die', 'Skala', 'Skalen', 'scale', 'Science', 'Die Skala reicht von eins bis zehn.', 'The scale ranges from one to ten.'],
  ['die', 'Gravitationswelle', 'Gravitationswellen', 'gravitational wave', 'Science', 'Die Gravitationswelle wurde 2015 gemessen.', 'The gravitational wave was measured in 2015.'],
  ['die', 'Quantenphysik', null, 'quantum physics', 'Science', 'Quantenphysik widerspricht der Intuition.', 'Quantum physics contradicts intuition.'],
  ['die', 'Relativitätstheorie', null, 'theory of relativity', 'Science', 'Die Relativitätstheorie veränderte die Physik.', 'The theory of relativity changed physics.'],
  ['die', 'Thermodynamik', null, 'thermodynamics', 'Science', 'Thermodynamik beschreibt Wärme und Energie.', 'Thermodynamics describes heat and energy.'],
  ['die', 'Entropie', 'Entropien', 'entropy', 'Science', 'Die Entropie eines Systems nimmt zu.', 'The entropy of a system increases.'],
  // ── M12.7: Wirtschaft (abstraktes Register) ──
  ['die', 'Amortisation', null, 'amortization', 'Economy', 'Die Amortisation der Anlage dauert fünf Jahre.', 'Amortization of the plant takes five years.'],
  ['die', 'Wertsteigerung', 'Wertsteigerungen', 'increase in value', 'Economy', 'Die Wertsteigerung der Immobilie überrascht.', 'The increase in the value of the property is surprising.'],
  ['die', 'Vermögensbildung', null, 'building wealth', 'Economy', 'Vermögensbildung beginnt mit Sparen.', 'Building wealth starts with saving.'],
  ['die', 'Anlagestrategie', 'Anlagestrategien', 'investment strategy', 'Economy', 'Ihre Anlagestrategie ist vorsichtig.', 'Her investment strategy is cautious.'],
  ['die', 'Volatilität', null, 'volatility', 'Economy', 'Die Volatilität der Märkte nimmt zu.', 'The volatility of the markets is increasing.'],
  ['der', 'Hebel', 'Hebel', 'leverage; lever', 'Economy', 'Der Hebel wirkt bei jedem Kauf.', 'The leverage works with every purchase.'],
  ['das', 'Derivat', 'Derivate', 'derivative (finance)', 'Economy', 'Das Derivat ist schwer zu bewerten.', 'The derivative is hard to value.'],
  ['der', 'Leerverkauf', 'Leerverkäufe', 'short sale', 'Economy', 'Der Leerverkauf setzt auf fallende Kurse.', 'The short sale bets on falling prices.'],
  ['der', 'Wohlfahrtsstaat', 'Wohlfahrtsstaaten', 'welfare state', 'Economy', 'Der Wohlfahrtsstaat steht unter Druck.', 'The welfare state is under pressure.'],
  ['die', 'Deregulierung', null, 'deregulation', 'Economy', 'Die Deregulierung öffnete die Märkte.', 'Deregulation opened the markets.'],
  ['die', 'Regulierung', 'Regulierungen', 'regulation', 'Economy', 'Die Regulierung der Banken wurde verschärft.', 'The regulation of banks was tightened.'],
  ['die', 'Kartellbehörde', 'Kartellbehörden', 'antitrust authority', 'Economy', 'Die Kartellbehörde prüft die Fusion.', 'The antitrust authority examines the merger.'],
  ['der', 'Binnenmarkt', 'Binnenmärkte', 'single market, domestic market', 'Economy', 'Der Binnenmarkt umfasst 450 Millionen Menschen.', 'The single market comprises 450 million people.'],
  ['die', 'Zollunion', 'Zollunionen', 'customs union', 'Economy', 'Die Zollunion beseitigt Grenzkontrollen.', 'The customs union removes border controls.'],
  ['die', 'Kapitalflucht', null, 'capital flight', 'Economy', 'Die Kapitalflucht schwächt die Währung.', 'Capital flight weakens the currency.'],
  ['die', 'Erbschaftsteuer', 'Erbschaftsteuern', 'inheritance tax', 'Economy', 'Die Erbschaftsteuer trifft große Vermögen.', 'The inheritance tax hits large estates.'],
  ['die', 'Steuergerechtigkeit', null, 'tax fairness', 'Economy', 'Steuergerechtigkeit bleibt umstritten.', 'Tax fairness remains controversial.'],
  ['die', 'Einkommensschere', 'Einkommensscheren', 'income gap', 'Economy', 'Die Einkommensschere öffnet sich weiter.', 'The income gap keeps widening.'],
  ['die', 'Abwrackprämie', 'Abwrackprämien', 'scrappage bonus', 'Economy', 'Die Abwrackprämie rettete den Autobau.', 'The scrappage bonus saved car manufacturing.'],
  ['die', 'Subventionspolitik', null, 'subsidy policy', 'Economy', 'Die Subventionspolitik wird neu bewertet.', 'Subsidy policy is being reassessed.'],
  ['die', 'Haushaltskonsolidierung', null, 'budget consolidation', 'Economy', 'Die Haushaltskonsolidierung dauert Jahre.', 'Budget consolidation takes years.'],
  ['der', 'Sparhaushalt', 'Sparhaushalte', 'austerity budget', 'Economy', 'Der Sparhaushalt kürzt überall.', 'The austerity budget cuts everywhere.'],
  ['der', 'Nachtragshaushalt', 'Nachtragshaushalte', 'supplementary budget', 'Economy', 'Der Nachtragshaushalt kommt im Sommer.', 'The supplementary budget comes in summer.'],
  ['die', 'Schwarzarbeit', null, 'illegal work', 'Economy', 'Schwarzarbeit schadet der ganzen Wirtschaft.', 'Illegal work harms the whole economy.'],
  ['der', 'Gutachter', 'Gutachter', 'expert, appraiser', 'Economy', 'Der Gutachter bewertet das Haus.', 'The appraiser values the house.'],
  ['der', 'Wirtschaftsprüfer', 'Wirtschaftsprüfer', 'auditor', 'Economy', 'Der Wirtschaftsprüfer prüft die Bilanz.', 'The auditor checks the balance sheet.'],
  ['der', 'Jahresabschluss', 'Jahresabschlüsse', 'annual financial statement', 'Economy', 'Der Jahresabschluss erscheint im April.', 'The annual financial statement appears in April.'],
  ['die', 'Inflationsrate', 'Inflationsraten', 'inflation rate', 'Economy', 'Die Inflationsrate erreicht sieben Prozent.', 'The inflation rate reaches seven percent.'],
  ['die', 'Währungsreform', 'Währungsreformen', 'currency reform', 'Economy', 'Die Währungsreform von 1948 brachte die D-Mark.', 'The 1948 currency reform brought the Deutsche Mark.'],
  ['der', 'Rettungsfonds', 'Rettungsfonds', 'rescue fund', 'Economy', 'Der Rettungsfonds stützt Banken und Länder.', 'The rescue fund supports banks and countries.'],
  ['die', 'Bankenunion', null, 'banking union', 'Economy', 'Die Bankenunion vereinheitlicht die Aufsicht.', 'The banking union standardizes supervision.'],
  ['die', 'Einlagensicherung', null, 'deposit insurance', 'Economy', 'Die Einlagensicherung schützt Sparer.', 'Deposit insurance protects savers.'],
  ['die', 'Immobilienblase', 'Immobilienblasen', 'real estate bubble', 'Economy', 'Die Immobilienblase droht zu platzen.', 'The real estate bubble threatens to burst.'],
  ['die', 'Geldwäsche', null, 'money laundering', 'Economy', 'Die Bank meldet Verdacht auf Geldwäsche.', 'The bank reports suspicion of money laundering.'],
  ['der', 'Fiskus', null, 'the treasury, tax authorities', 'Economy', 'Der Fiskus verlangt Nachzahlungen.', 'The treasury demands back payments.'],
  ['der', 'Etat', 'Etats', 'budget', 'Economy', 'Der Etat des Vereins ist knapp.', 'The budget of the association is tight.'],
  ['die', 'Kreditaufnahme', 'Kreditaufnahmen', 'taking out a loan', 'Economy', 'Die Kreditaufnahme verteuert sich.', 'Taking out a loan is becoming more expensive.'],
  ['die', 'Refinanzierung', 'Refinanzierungen', 'refinancing', 'Economy', 'Die Refinanzierung der Bank läuft über Anleihen.', 'The refinancing of the bank runs via bonds.'],
  ['die', 'Verschuldungsgrenze', 'Verschuldungsgrenzen', 'debt ceiling', 'Economy', 'Die Verschuldungsgrenze steht im Gesetz.', 'The debt ceiling is in the law.'],
  ['der', 'Schuldenschnitt', 'Schuldenschnitte', 'debt haircut', 'Economy', 'Der Schuldenschnitt entlastete den Staat.', 'The debt haircut relieved the state.'],
  ['der', 'Schuldenerlass', null, 'debt relief', 'Economy', 'Der Schuldenerlass hilft den ärmsten Ländern.', 'Debt relief helps the poorest countries.'],
  // ── M12.7: Wissenschaft (moderne Forschung) ──
  ['die', 'Molekularbiologie', null, 'molecular biology', 'Science', 'Molekularbiologie entschlüsselt das Erbgut.', 'Molecular biology decodes the genome.'],
  ['die', 'Neurowissenschaft', 'Neurowissenschaften', 'neuroscience', 'Science', 'Die Neurowissenschaft erforscht das Gehirn.', 'Neuroscience researches the brain.'],
  ['die', 'Verhaltensforschung', null, 'behavioral research', 'Science', 'Die Verhaltensforschung beobachtet Tiere im Freien.', 'Behavioral research observes animals in the wild.'],
  ['die', 'Hirnforschung', null, 'brain research', 'Science', 'Die Hirnforschung macht schnelle Fortschritte.', 'Brain research is making rapid progress.'],
  ['die', 'Stammzelle', 'Stammzellen', 'stem cell', 'Science', 'Die Stammzelle kann sich in alles verwandeln.', 'The stem cell can turn into anything.'],
  ['die', 'Stammzellforschung', null, 'stem cell research', 'Science', 'Stammzellforschung ist ethisch umstritten.', 'Stem cell research is ethically controversial.'],
  ['die', 'Gentherapie', 'Gentherapien', 'gene therapy', 'Science', 'Die Gentherapie heilt erbliche Krankheiten.', 'Gene therapy heals hereditary diseases.'],
  ['die', 'Biotechnologie', null, 'biotechnology', 'Science', 'Biotechnologie nutzt Zellen als Fabriken.', 'Biotechnology uses cells as factories.'],
  ['die', 'Nanotechnologie', null, 'nanotechnology', 'Science', 'Nanotechnologie arbeitet mit kleinsten Teilchen.', 'Nanotechnology works with the smallest particles.'],
  ['die', 'Materialforschung', null, 'materials research', 'Science', 'Die Materialforschung sucht bessere Batterien.', 'Materials research looks for better batteries.'],
  ['der', 'Modellversuch', 'Modellversuche', 'pilot experiment', 'Science', 'Der Modellversuch läuft in drei Städten.', 'The pilot experiment runs in three cities.'],
  ['die', 'Modellrechnung', 'Modellrechnungen', 'model calculation', 'Science', 'Die Modellrechnung bestätigt den Trend.', 'The model calculation confirms the trend.'],
  ['die', 'Vorhersagekraft', null, 'predictive power', 'Science', 'Die Vorhersagekraft des Modells ist hoch.', 'The predictive power of the model is high.'],
  ['die', 'Klimaforschung', null, 'climate research', 'Science', 'Die Klimaforschung warnt seit Jahrzehnten.', 'Climate research has been warning for decades.'],
  ['die', 'Meeresforschung', null, 'marine research', 'Science', 'Die Meeresforschung kartiert den Tiefseeboden.', 'Marine research maps the deep sea floor.'],
  ['die', 'Mondlandung', 'Mondlandungen', 'moon landing', 'Science', 'Die Mondlandung von 1969 veränderte die Welt.', 'The 1969 moon landing changed the world.'],
  ['die', 'Astrophysik', null, 'astrophysics', 'Science', 'Astrophysik erklärt Sterne und Galaxien.', 'Astrophysics explains stars and galaxies.'],
  ['der', 'Teilchenbeschleuniger', null, 'particle accelerator', 'Science', 'Der Teilchenbeschleuniger liegt unter der Erde.', 'The particle accelerator lies underground.'],
  ['der', 'Quantencomputer', 'Quantencomputer', 'quantum computer', 'Science', 'Der Quantencomputer rechnet anders als jeder Chip.', 'The quantum computer calculates differently than any chip.'],
  ['die', 'Kryptowährung', 'Kryptowährungen', 'cryptocurrency', 'Science', 'Die Kryptowährung schwankt stark.', 'The cryptocurrency fluctuates strongly.'],
  ['die', 'Blockchain', 'Blockchains', 'blockchain', 'Science', 'Die Blockchain speichert Transaktionen unveränderbar.', 'The blockchain stores transactions immutably.'],
  // ── M12.7: Abstrakte Verben (gehobenes Register) ──
  [null, 'gewähren', null, 'to grant, allow', 'Abstract', 'Die Behörde gewährt einen Zuschuss.', 'The authority grants a subsidy.'],
  [null, 'gestatten', null, 'to permit', 'Abstract', 'Der Trainer gestattet eine Pause.', 'The coach permits a break.'],
  [null, 'innehaben', null, 'to hold (an office)', 'Abstract', 'Er hat das Amt zehn Jahre inne.', 'He has held the office for ten years.'],
  [null, 'anstreben', null, 'to strive for', 'Abstract', 'Das Team strebt Platz eins an.', 'The team strives for first place.'],
  [null, 'anvisieren', null, 'to set ones sights on', 'Abstract', 'Die Firma visiert den Herbst an.', 'The company sets its sights on autumn.'],
  [null, 'aufschieben', null, 'to postpone', 'Abstract', 'Sie schiebt den Termin auf.', 'She postpones the appointment.'],
  [null, 'ausräumen', null, 'to clear away; to dispel', 'Abstract', 'Das Gespräch räumt alle Zweifel aus.', 'The conversation dispels all doubts.'],
  [null, 'entkräften', null, 'to refute, invalidate', 'Abstract', 'Neue Daten entkräften den Einwand.', 'New data invalidate the objection.'],
  [null, 'entlarven', null, 'to expose, unmask', 'Abstract', 'Die Recherche entlarvt den Betrug.', 'The investigation exposes the fraud.'],
  [null, 'überführen', null, 'to convict, prove guilty', 'Abstract', 'Zeugen überführen den Täter.', 'Witnesses convict the perpetrator.'],
  [null, 'belegen', null, 'to substantiate, document', 'Abstract', 'Studien belegen den Effekt.', 'Studies substantiate the effect.'],
  [null, 'untermauern', null, 'to underpin, bolster', 'Abstract', 'Zahlen untermauern die These.', 'Figures underpin the thesis.'],
  [null, 'stützen', null, 'to support, sustain', 'Abstract', 'Zwei Argumente stützen den Vorschlag.', 'Two arguments support the proposal.'],
  [null, 'fundieren', null, 'to found, ground thoroughly', 'Abstract', 'Erfahrung fundiert sein Urteil.', 'Experience grounds his judgment.'],
  [null, 'konterkarieren', null, 'to thwart, run counter to', 'Abstract', 'Die Sparpolitik konterkariert das Ziel.', 'The austerity policy runs counter to the goal.'],
  [null, 'torpedieren', null, 'to torpedo, sabotage', 'Abstract', 'Ein Veto torpediert den Plan.', 'A veto torpedoes the plan.'],
  [null, 'unterminieren', null, 'to undermine', 'Abstract', 'Gerüchte unterminieren das Vertrauen.', 'Rumors undermine trust.'],
  [null, 'verabschieden', null, 'to pass (a law); to see off', 'Abstract', 'Das Parlament verabschiedet das Gesetz.', 'Parliament passes the law.'],
  [null, 'verkünden', null, 'to proclaim, announce', 'Abstract', 'Das Gericht verkündet das Urteil.', 'The court proclaims the verdict.'],
  [null, 'präzisieren', null, 'to make precise', 'Abstract', 'Die Sprecherin präzisiert ihre Aussage.', 'The spokesperson makes her statement precise.'],
  [null, 'spezifizieren', null, 'to specify', 'Abstract', 'Der Kunde spezifiziert seine Wünsche.', 'The customer specifies his wishes.'],
  [null, 'quantifizieren', null, 'to quantify', 'Abstract', 'Der Schaden lässt sich beziffern und quantifizieren.', 'The damage can be quantified.'],
  [null, 'diskreditieren', null, 'to discredit', 'Abstract', 'Die Kampagne diskreditiert die Wissenschaft.', 'The campaign discredits science.'],
  [null, 'delegitimieren', null, 'to delegitimize', 'Abstract', 'Die Wahl delegitimiert die alte Führung.', 'The election delegitimizes the old leadership.'],
  [null, 'legitimieren', null, 'to legitimize', 'Abstract', 'Der Beschluss legitimiert das Vorgehen.', 'The decision legitimizes the procedure.'],
  [null, 'kategorisieren', null, 'to categorize', 'Abstract', 'Die Daten werden neu kategorisiert.', 'The data are being re-categorized.'],
  [null, 'systematisieren', null, 'to systematize', 'Abstract', 'Er systematisiert seine Notizen.', 'He systematizes his notes.'],
  [null, 'einordnen', null, 'to classify, place in context', 'Abstract', 'Historiker ordnen den Fund ins 4. Jahrhundert ein.', 'Historians place the find in the 4th century.'],
  [null, 'ausklammern', null, 'to leave out, bracket off', 'Abstract', 'Die Debatte klammert die Kostenfrage aus.', 'The debate leaves out the cost question.'],
  [null, 'problematisieren', null, 'to problematize', 'Abstract', 'Der Artikel problematisiert die Sammelwut.', 'The article problematizes the collecting mania.'],
  [null, 'verharmlosen', null, 'to play down', 'Abstract', 'Der Sprecher spielt die Vorwürfe nicht weg, er verharmlost sie.', 'The spokesperson plays down the accusations.'],
  [null, 'schönreden', null, 'to gloss over', 'Abstract', 'Man darf die Lage nicht schönreden.', 'You must not gloss over the situation.'],
  [null, 'verschleiern', null, 'to obscure, veil', 'Abstract', 'Komplexe Formulare verschleiern die wahren Kosten.', 'Complex forms obscure the true costs.'],
  [null, 'enttarnen', null, 'to unmask', 'Abstract', 'Die Kellnerin enttarnt den Trickbetrüger.', 'The waitress unmasks the con man.'],
  [null, 'offenlegen', null, 'to disclose', 'Abstract', 'Der Konzern legt seine Steuern offen.', 'The corporation discloses its taxes.'],
  [null, 'vereiteln', null, 'to foil, thwart', 'Abstract', 'Die Polizei vereitelt den Überfall.', 'The police foil the robbery.'],
  [null, 'durchkreuzen', null, 'to cross, frustrate', 'Abstract', 'Ein Ausfall durchkreuzt die Planung.', 'An absence frustrates the planning.'],
  [null, 'abwenden', null, 'to avert', 'Abstract', 'Schnelle Hilfe wendet den Kollaps ab.', 'Quick aid averts the collapse.'],
  [null, 'administrieren', null, 'to administer', 'Abstract', 'Eine Stiftung administriert die Gelder.', 'A foundation administers the funds.'],
  [null, 'verwalten', null, 'to manage, administer', 'Abstract', 'Die Stadt verwaltet die Wohnungen.', 'The city manages the apartments.'],
  [null, 'haushalten', null, 'to budget, economize', 'Abstract', 'Mit wenig Geld muss man haushalten.', 'With little money you have to budget.'],
  // ── M12.7: Abstrakte Substantive (Wirtschaft und Denken) ──
  ['das', 'Konjunkturprogramm', 'Konjunkturprogramme', 'stimulus program', 'Economy', 'Das Konjunkturprogramm kommt im Herbst.', 'The stimulus program comes in autumn.'],
  ['die', 'Wirtschaftsleistung', null, 'economic output', 'Economy', 'Die Wirtschaftsleistung sank im Winter.', 'Economic output fell in winter.'],
  ['die', 'Rentabilität', null, 'profitability', 'Economy', 'Die Rentabilität der Anlage ist gesichert.', 'The profitability of the investment is secured.'],
  ['die', 'Größenordnung', 'Größenordnungen', 'order of magnitude', 'Abstract', 'Die Summe liegt in einer anderen Größenordnung.', 'The sum is in a different order of magnitude.'],
  ['der', 'Imperativ', 'Imperative', 'imperative; command', 'Abstract', 'Der Imperativ der Stunde heißt sparen.', 'The imperative of the hour is called saving.'],
  ['die', 'Prämisse', 'Prämissen', 'premise', 'Abstract', 'Die ganze Argumentation ruht auf einer Prämisse.', 'The whole argument rests on one premise.'],
  ['das', 'Postulat', 'Postulate', 'postulate, demand', 'Abstract', 'Das Postulat der Forschung heißt Transparenz.', 'The postulate of research is called transparency.'],
  ['die', 'Heuristik', 'Heuristiken', 'heuristics', 'Abstract', 'Eine einfache Heuristik spart Zeit.', 'A simple heuristic saves time.'],
  ['die', 'Dogmatik', null, 'dogmatics, dogmatism', 'Abstract', 'Dogmatik erstickt jede Neugier.', 'Dogmatism stifles all curiosity.'],
  ['der', 'Kanon', 'Kanons', 'canon', 'Abstract', 'Der Kanon der Literatur umfasst hundert Werke.', 'The literary canon comprises one hundred works.'],
  ['die', 'Hermeneutik', null, 'hermeneutics', 'Abstract', 'Hermeneutik lehrt das Verstehen von Texten.', 'Hermeneutics teaches the understanding of texts.'],
  ['die', 'Gretchenfrage', 'Gretchenfragen', 'the pointed question', 'Abstract', 'Die Gehaltsfrage ist beim Autokauf die Gretchenfrage.', 'The price question is the pointed one when buying a car.'],
  ['die', 'Kernfrage', 'Kernfragen', 'key question', 'Abstract', 'Die Kernfrage der Debatte bleibt offen.', 'The key question of the debate remains open.'],
  ['der', 'Knackpunkt', 'Knackpunkte', 'crux, sticking point', 'Abstract', 'Der Knackpunkt ist die Finanzierung.', 'The crux is the financing.'],
  ['der', 'Streitpunkt', 'Streitpunkte', 'point of contention', 'Abstract', 'Der Streitpunkt ist klein, aber hartnäckig.', 'The point of contention is small but stubborn.'],
  ['der', 'Ansatzpunkt', 'Ansatzpunkte', 'point of departure', 'Abstract', 'Der Ansatzpunkt der Reform ist die Schule.', 'The point of departure of the reform is the school.'],
  ['der', 'Ausgangspunkt', 'Ausgangspunkte', 'starting point', 'Abstract', 'Der Bahnhof ist unser Ausgangspunkt.', 'The train station is our starting point.'],
  ['der', 'Tiefpunkt', 'Tiefpunkte', 'low point', 'Abstract', 'Das Jahr 2009 war der Tiefpunkt.', 'The year 2009 was the low point.'],
  ['die', 'Markteinführung', 'Markteinführungen', 'market launch', 'Economy', 'Die Markteinführung ist für März geplant.', 'The market launch is planned for March.'],
  ['die', 'Produktpalette', 'Produktpaletten', 'product range', 'Economy', 'Die Produktpalette wächst jedes Jahr.', 'The product range grows every year.'],
  ['der', 'Zielmarkt', 'Zielmärkte', 'target market', 'Economy', 'Frankreich ist der wichtigste Zielmarkt.', 'France is the most important target market.'],
  ['die', 'Entscheidungsbefugnis', 'Entscheidungsbefugnisse', 'decision-making authority', 'Abstract', 'Die Entscheidungsbefugnis liegt beim Rat.', 'The decision-making authority lies with the council.'],
]
