import type { CefrLevel, KeyPhrase, Scenario } from '../../db/types'

/** Deterministic build stamp for seed rows (never changes per release). */
const SEED_TS = Date.UTC(2026, 8, 20, 12, 0, 0)

interface SeedScenario {
  id: string
  title: string
  cefr: CefrLevel
  emoji: string
  description: string
  goal: string
  keyPhrases: KeyPhrase[]
}

const SEED: SeedScenario[] = [
  {
    id: 's-cafe',
    title: 'Café bestellen',
    cefr: 'A1',
    emoji: '☕',
    description: 'Order a coffee and a piece of cake at a German café and pay at the end.',
    goal: 'Order a drink and something to eat, ask one question about the offer, and ask for the bill.',
    keyPhrases: [
      { de: 'Ich hätte gern einen Kaffee, bitte.', en: 'I would like a coffee, please.' },
      { de: 'Was empfehlen Sie?', en: 'What do you recommend?' },
      { de: 'Für hier oder zum Mitnehmen?', en: 'For here or to take away?' },
      { de: 'Könnte ich die Rechnung haben, bitte?', en: 'Could I have the bill, please?' },
      { de: 'Das war lecker, danke!', en: 'That was delicious, thank you!' },
    ],
  },
  {
    id: 's-baeckerei',
    title: 'In der Bäckerei',
    cefr: 'A1',
    emoji: '🥨',
    description: 'Buy bread and rolls at the bakery in the morning.',
    goal: 'Buy two items, ask what something costs, and pay by card.',
    keyPhrases: [
      { de: 'Ich möchte zwei Brötchen, bitte.', en: "I'd like two rolls, please." },
      { de: 'Was gibt es heute Frisches?', en: 'What fresh things are there today?' },
      { de: 'Wie viel kostet das Brot?', en: 'How much does the bread cost?' },
      { de: 'Nein danke, das ist alles.', en: 'No thank you, that is everything.' },
      { de: 'Kann ich mit Karte bezahlen?', en: 'Can I pay by card?' },
    ],
  },
  {
    id: 's-supermarkt',
    title: 'Im Supermarkt',
    cefr: 'A1',
    emoji: '🛒',
    description: 'Find products in the supermarket and go through the checkout.',
    goal: 'Ask where two products are, and handle a short exchange at the checkout.',
    keyPhrases: [
      { de: 'Entschuldigung, wo finde ich die Milch?', en: 'Excuse me, where do I find the milk?' },
      { de: 'Haben Sie auch laktosefreie Milch?', en: 'Do you also have lactose-free milk?' },
      { de: 'Ich suche die Kasse.', en: "I'm looking for the checkout." },
      { de: 'Ich hätte gern eine Tüte, bitte.', en: "I'd like a bag, please." },
      { de: 'Was kostet ein Kilo Äpfel?', en: 'What does a kilo of apples cost?' },
    ],
  },
  {
    id: 's-ticket',
    title: 'Ticket kaufen (Öffentliche Verkehrsmittel)',
    cefr: 'A1',
    emoji: '🚋',
    description: 'Buy a ticket for bus, tram or train and find your connection.',
    goal: 'Buy a ticket, ask when the next connection leaves, and find the platform or stop.',
    keyPhrases: [
      { de: 'Eine Fahrkarte nach Berlin, bitte.', en: 'One ticket to Berlin, please.' },
      { de: 'Wann fährt der nächste Zug?', en: 'When does the next train leave?' },
      { de: 'Muss ich umsteigen?', en: 'Do I have to change trains?' },
      { de: 'Wo ist der Bahnsteig?', en: 'Where is the platform?' },
      { de: 'Ist diese Karte auch für die Tram gültig?', en: 'Is this ticket also valid for the tram?' },
    ],
  },
  {
    id: 's-arzt',
    title: 'Arzttermin',
    cefr: 'A2',
    emoji: '🩺',
    description: 'Make a doctor’s appointment and describe your symptoms.',
    goal: 'Book an appointment, describe two symptoms and say how long you have had them, and ask about medication.',
    keyPhrases: [
      { de: 'Ich möchte einen Termin vereinbaren.', en: "I'd like to make an appointment." },
      { de: 'Ich habe seit drei Tagen Halsschmerzen.', en: "I've had a sore throat for three days." },
      { de: 'Haben Sie diese Woche noch einen freien Termin?', en: 'Do you still have a free appointment this week?' },
      { de: 'Brauche ich eine Überweisung?', en: 'Do I need a referral?' },
      { de: 'Wie oft soll ich die Tabletten nehmen?', en: 'How often should I take the tablets?' },
    ],
  },
  {
    id: 's-buergeramt',
    title: 'Bürgeramt: Anmeldung',
    cefr: 'B1',
    emoji: '🏛️',
    description: 'Register your new address at the Bürgeramt.',
    goal: 'Register your address, hand over your documents, and ask what happens next.',
    keyPhrases: [
      { de: 'Ich möchte mich anmelden.', en: 'I would like to register my address.' },
      { de: 'Hier sind mein Pass und die Wohnungsgeberbestätigung.', en: "Here are my passport and the landlord's confirmation." },
      { de: 'Brauche ich noch weitere Unterlagen?', en: 'Do I need any further documents?' },
      { de: 'Wann bekomme ich die Steueridentifikationsnummer?', en: 'When will I receive my tax ID?' },
      { de: 'Können Sie das bitte langsamer wiederholen?', en: 'Could you please repeat that more slowly?' },
    ],
  },
  {
    id: 's-nachbar',
    title: 'Nachbar small talk',
    cefr: 'A2',
    emoji: '🏠',
    description: 'Chat with your neighbour in the stairwell.',
    goal: 'Introduce yourself, ask one practical question about the building, and end the chat politely.',
    keyPhrases: [
      { de: 'Guten Tag! Wir sind die neuen Nachbarn.', en: 'Hello! We are the new neighbours.' },
      { de: 'Kann ich Sie kurz etwas fragen?', en: 'May I quickly ask you something?' },
      { de: 'Wann wird denn der Müll abgeholt?', en: 'When is the rubbish collected?' },
      { de: 'Entschuldigen Sie die Störung gestern.', en: 'Sorry about the disturbance yesterday.' },
      { de: 'Möchten Sie mal auf einen Kaffee vorbeikommen?', en: 'Would you like to come by for a coffee sometime?' },
    ],
  },
  {
    id: 's-wohnung',
    title: 'Wohnungssuche',
    cefr: 'B1',
    emoji: '🏡',
    description: 'Call about a flat advert and arrange a viewing.',
    goal: 'Ask if the flat is still available, ask about rent and conditions, and arrange a viewing.',
    keyPhrases: [
      { de: 'Ich habe Ihre Anzeige gelesen. Ist die Wohnung noch frei?', en: 'I read your ad. Is the flat still available?' },
      { de: 'Wie hoch ist die Miete ohne Nebenkosten?', en: 'What is the rent without utilities?' },
      { de: 'Wann wäre eine Besichtigung möglich?', en: 'When would a viewing be possible?' },
      { de: 'Sind Haustiere erlaubt?', en: 'Are pets allowed?' },
      { de: 'Ab wann ist die Wohnung bezugsfrei?', en: 'From when is the flat available?' },
    ],
  },
  {
    id: 's-telefon',
    title: 'Telefonieren',
    cefr: 'B1',
    emoji: '📞',
    description: 'Make a phone call and leave a message with a colleague’s office.',
    goal: 'Ask for a person, explain why you are calling, and leave a callback message.',
    keyPhrases: [
      { de: 'Guten Tag, kann ich bitte Herrn Weber sprechen?', en: 'Hello, may I speak to Mr Weber, please?' },
      { de: 'Es geht um unseren Termin am Freitag.', en: "It's about our appointment on Friday." },
      { de: 'Kann ich eine Nachricht hinterlassen?', en: 'Can I leave a message?' },
      { de: 'Er kann mich gerne morgen zurückrufen.', en: 'He is welcome to call me back tomorrow.' },
      { de: 'Ich rufe später noch einmal an.', en: "I'll call again later." },
    ],
  },
  {
    id: 's-arbeit',
    title: 'Arbeit / Besprechung',
    cefr: 'B2',
    emoji: '💼',
    description: 'Take part in a team meeting and talk about project status.',
    goal: 'Give a short project update, respond to a critical question, and agree on next steps.',
    keyPhrases: [
      { de: 'Können wir den Termin auf nächste Woche verschieben?', en: 'Can we move the meeting to next week?' },
      { de: 'Ich schicke Ihnen das Protokoll nach dem Meeting.', en: "I'll send you the minutes after the meeting." },
      { de: 'Wie ist der Stand bei dem Projekt?', en: 'What is the status of the project?' },
      { de: 'Da sehe ich noch Handlungsbedarf.', en: 'I still see a need for action there.' },
      { de: 'Fassen wir zusammen: Wer macht was bis wann?', en: 'Let us summarise: who does what by when?' },
    ],
  },
  {
    id: 's-fitness',
    title: 'Im Fitnessstudio',
    cefr: 'A2',
    emoji: '🏋️',
    description:
      'Small talk and practical questions at the gym (A2/B1): machines, duration, weights, reps and sets, training with a partner.',
    goal: 'Ask how a machine works, talk about how long you have been training, discuss sets/reps/weight, and find a training partner.',
    keyPhrases: [
      { de: 'Wie funktioniert dieses Gerät?', en: 'How does this machine work?' },
      { de: 'Kannst du mir zeigen, wie die Beinpresse funktioniert?', en: 'Can you show me how the leg press works?' },
      { de: 'Wie viel Gewicht soll ich nehmen?', en: 'How much weight should I use?' },
      { de: 'Ich mache 3 Sätze mit 12 Wiederholungen.', en: 'I do 3 sets of 12 reps.' },
      { de: 'Wie lange trainierst du schon?', en: 'How long have you been training?' },
      { de: 'Welche Muskeln trainiert dieses Gerät?', en: 'Which muscles does this machine train?' },
      { de: 'Trainierst du lieber allein oder mit einem Partner?', en: 'Do you prefer training alone or with a partner?' },
    ],
  },
  {
    id: 's-bewerbung',
    title: 'Bewerbungsgespräch',
    cefr: 'B1',
    emoji: '🤝',
    description: 'A job interview: talk about your experience, strengths and motivation.',
    goal: 'Introduce your background, describe a strength and a weakness, and ask two questions about the role.',
    keyPhrases: [
      { de: 'Vielen Dank für die Einladung zu diesem Gespräch.', en: 'Thank you for the invitation to this interview.' },
      { de: 'Ich habe drei Jahre Erfahrung im Kundenservice.', en: 'I have three years of experience in customer service.' },
      { de: 'Zu meinen Stärken gehört, dass ich sehr zuverlässig bin.', en: 'One of my strengths is that I am very reliable.' },
      { de: 'Ich bin jemand, der gerne im Team arbeitet.', en: 'I am someone who enjoys working in a team.' },
      { de: 'Wie sieht ein typischer Arbeitstag in dieser Position aus?', en: 'What does a typical working day look like in this position?' },
      { de: 'Wann kann ich mit Ihrer Entscheidung rechnen?', en: 'When can I expect your decision?' },
    ],
  },
  {
    id: 's-reklamation',
    title: 'Reklamation im Geschäft',
    cefr: 'B1',
    emoji: '🧾',
    description: 'Return a defective online order and ask for a refund or replacement.',
    goal: 'Explain what is wrong with the product, say when you bought it, and ask for a refund or exchange.',
    keyPhrases: [
      { de: 'Ich möchte diesen Artikel umtauschen, er ist defekt.', en: 'I would like to exchange this item, it is defective.' },
      { de: 'Ich habe ihn vor zwei Wochen online bestellt.', en: 'I ordered it online two weeks ago.' },
      { de: 'Der Reißverschluss funktioniert schon nach einem Tag nicht mehr.', en: 'The zip stopped working after just one day.' },
      { de: 'Ich habe hier den Kassenzettel und die Bestellbestätigung.', en: 'I have the receipt and the order confirmation here.' },
      { de: 'Wäre es möglich, den Betrag zurückzubekommen?', en: 'Would it be possible to get the money back?' },
      { de: 'Wie lange dauert die Rückerstattung in der Regel?', en: 'How long does the refund usually take?' },
    ],
  },
  {
    id: 's-verspaetung',
    title: 'Verspätung im Zug',
    cefr: 'B1',
    emoji: '🚆',
    description: 'Your train is cancelled — rebook your connection and ask about your rights.',
    goal: 'Report the cancelled connection, ask for the next option, and find out about compensation.',
    keyPhrases: [
      { de: 'Mein Zug nach München fällt gerade aus. Was kann ich tun?', en: 'My train to Munich has just been cancelled. What can I do?' },
      { de: 'Wann fährt die nächste Verbindung mit Umstieg in Fulda?', en: 'When does the next connection with a change in Fulda leave?' },
      { de: 'Gilt mein Ticket auch im Regionalzug?', en: 'Is my ticket also valid on the regional train?' },
      { de: 'Ich muss um drei Uhr am Flughafen sein.', en: 'I have to be at the airport by three o’clock.' },
      { de: 'Bekomme ich eine Entschädigung für die Verspätung?', en: 'Do I get compensation for the delay?' },
      { de: 'Können Sie mir das bitte schriftlich bestätigen?', en: 'Can you please confirm that in writing?' },
    ],
  },
  {
    id: 's-freunde',
    title: 'Pläne mit Freunden',
    cefr: 'B1',
    emoji: '🎬',
    description: 'Plan a cinema evening with a friend — suggest, discuss and agree.',
    goal: 'Suggest an activity, react to your friend’s idea, agree on time and place, and cancel one plan politely.',
    keyPhrases: [
      { de: 'Hast du am Freitag schon etwas vor?', en: 'Do you already have plans on Friday?' },
      { de: 'Ich hätte Lust, ins Kino zu gehen. Was hältst du davon?', en: "I'd like to go to the cinema. What do you think?" },
      { de: 'Ich könnte dich gegen sieben Uhr abholen.', en: 'I could pick you up at around seven.' },
      { de: 'Das passt mir leider nicht. Geht es auch am Samstag?', en: "Unfortunately that doesn't suit me. Would Saturday work too?" },
      { de: 'Lass uns vor dem Kino noch einen Kaffee trinken.', en: "Let's have a coffee before the film." },
      { de: 'Ich muss leider absagen — können wir das verschieben?', en: 'I unfortunately have to cancel — can we postpone it?' },
    ],
  },
  {
    id: 's-behoerde',
    title: 'Beim Amt: Bescheid anfragen',
    cefr: 'B2',
    emoji: '📄',
    description: 'Call the authority about an official notice you do not fully understand.',
    goal: 'Explain why you are calling, ask two questions about the letter, and clarify what has to be done by when.',
    keyPhrases: [
      { de: 'Ich rufe wegen des Bescheids an, den ich diese Woche erhalten habe.', en: 'I am calling about the official notice I received this week.' },
      { de: 'Könnten Sie mir sagen, was genau in Punkt drei gemeint ist?', en: 'Could you tell me what exactly point three means?' },
      { de: 'Bis wann muss ich Widerspruch einlegen?', en: 'By when do I have to file an objection?' },
      { de: 'Welche Unterlagen muss ich einreichen?', en: 'Which documents do I have to submit?' },
      { de: 'Könnten Sie mir das noch einmal per E-Mail bestätigen?', en: 'Could you confirm that once more by email?' },
      { de: 'Ich hätte gern einen Termin für eine persönliche Beratung.', en: 'I would like an appointment for a personal consultation.' },
    ],
  },
  {
    id: 's-konflikt',
    title: 'Konflikt im Team',
    cefr: 'B2',
    emoji: '🗣️',
    description: 'A conflict with a colleague: criticise constructively and find a compromise.',
    goal: 'Describe the problem without blaming, respond to criticism, and agree on a concrete solution.',
    keyPhrases: [
      { de: 'Ich möchte offen mit dir über die Situation in unserem Projekt sprechen.', en: 'I would like to talk openly with you about the situation in our project.' },
      { de: 'Mir ist aufgefallen, dass die Ergebnisse oft erst sehr spät kommen.', en: 'I have noticed that the results often arrive very late.' },
      { de: 'Ich verstehe deinen Punkt, sehe das aber etwas anders.', en: 'I understand your point, but I see it a little differently.' },
      { de: 'Wie können wir es so organisieren, dass es für beide Seiten passt?', en: 'How can we organise it so that it works for both sides?' },
      { de: 'Ich schlage vor, dass wir die Aufgaben neu aufteilen.', en: 'I suggest that we redistribute the tasks.' },
      { de: 'Einverstanden — halten wir also fest, wer bis wann was liefert.', en: 'Agreed — so let us note down who delivers what by when.' },
    ],
  },
  {
    id: 's-diskussion',
    title: 'Nachrichten diskutieren',
    cefr: 'B2',
    emoji: '📰',
    description: 'Discuss a current news topic with a friend: opinions, arguments, counter-arguments.',
    goal: 'Give your opinion with reasons, react to an opposing view, and end with common ground.',
    keyPhrases: [
      { de: 'Hast du den Artikel über das neue Verkehrskonzept gelesen?', en: 'Did you read the article about the new transport concept?' },
      { de: 'Ich bin der Meinung, dass die Maßnahme mehr Nachteile als Vorteile hat.', en: 'In my opinion, the measure has more disadvantages than advantages.' },
      { de: 'Das mag sein, aber man darf die Kosten nicht außer Acht lassen.', en: 'That may be so, but the costs must not be ignored.' },
      { de: 'Da bin ich nicht ganz deiner Meinung.', en: "I don't quite agree with you there." },
      { de: 'Studien zufolge hat sich die Luftqualität deutlich verbessert.', en: 'According to studies, air quality has improved significantly.' },
      { de: 'Einig sind wir uns also, dass man die Wirkung weiter beobachten muss.', en: 'So we agree that the effects must be monitored further.' },
    ],
  },
  {
    id: 's-vermieter',
    title: 'Mit dem Vermieter verhandeln',
    cefr: 'B2',
    emoji: '🧑‍⚖️',
    description: 'Your landlord wants to raise the rent — negotiate and push for overdue repairs.',
    goal: 'Respond to the rent increase, question one point, and get a commitment for an overdue repair.',
    keyPhrases: [
      { de: 'Ich habe Ihr Schreiben zur Mieterhöhung erhalten und möchte es besprechen.', en: 'I have received your letter about the rent increase and would like to discuss it.' },
      { de: 'Darf ich fragen, worauf sich diese Berechnung stützt?', en: 'May I ask what this calculation is based on?' },
      { de: 'Ich müsste das erst prüfen, bevor ich zustimme.', en: 'I would have to look into that first before agreeing.' },
      { de: 'Außerdem ist die Heizung seit einem Monat defekt.', en: 'Besides, the heating has been defective for a month.' },
      { de: 'Ich bitte Sie, den Mangel bis Ende des Monats zu beheben.', en: 'I ask you to fix the defect by the end of the month.' },
      { de: 'Können wir das schriftlich festhalten?', en: 'Can we put that in writing?' },
    ],
  },
  {
    id: 's-praesentation',
    title: 'Präsentation halten',
    cefr: 'B2',
    emoji: '🎤',
    description: 'Present project results at work or university and handle critical questions.',
    goal: 'Outline your results, answer a critical question diplomatically, and agree on next steps.',
    keyPhrases: [
      { de: 'Ich möchte Ihnen heute die wichtigsten Ergebnisse unseres Projekts vorstellen.', en: 'Today I would like to present the key results of our project.' },
      { de: 'Zunächst ein kurzer Überblick über den Stand der Dinge.', en: 'First, a brief overview of the current state of affairs.' },
      { de: 'Wie Sie der Grafik entnehmen können, sind die Kosten gesunken.', en: 'As you can see from the chart, costs have fallen.' },
      { de: 'Das ist ein berechtigter Einwand, dem ich nachgehen werde.', en: 'That is a valid objection, which I will look into.' },
      { de: 'Daraus ergibt sich für uns folgender Handlungsbedarf.', en: 'From this, the following need for action arises for us.' },
      { de: 'Vielen Dank für Ihre Aufmerksamkeit — gibt es noch Fragen?', en: 'Thank you for your attention — are there any questions?' },
    ],
  },
]

export const SEED_SCENARIOS: Scenario[] = SEED.map((s) => ({ ...s, updatedAt: SEED_TS, custom: false }))

